### ISSUE TITLE
same token generated with two Permissions

### ISSUE THREAD

**Issue by ragulan77** [vert-x3/issues#100]
Hi,

I am doing some junit test for my application. When I try to generate consecutively two tokens with two different permissions they are both identical for some reason. Here is a sample:

``` java
JsonObject config = new JsonObject().put("keyStore", new JsonObject()
                                            .put("path", "src/main/java/com/myproject/user/keystore.jceks")
                                            .put("type", "jceks")
                                            .put("password", "secret"));
JWTAuth authProvider = JWTAuth.create(vertx, config);
JsonObject tokenContent = new JsonObject().put("login", "dupond");
userToken = authProvider.generateToken(tokenContent, new     JWTOptions().addPermission("user"));
adminToken = authProvider.generateToken(tokenContent, new   JWTOptions().addPermission("admin"));
        
System.out.println(userToken);
System.out.println(adminToken);
```

I have the following print for both:
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbiI6ImR1cG9uZCIsInBlcm1pc3Npb25zIjpbInVzZXIiXSwiaWF0IjoxNDU1NDU1MTk1fQ==.Rj7s-hgx1wVbE6yqIaBhJaTbLgD35EN8jOTF6dwSVVU=

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbiI6ImR1cG9uZCIsInBlcm1pc3Npb25zIjpbInVzZXIiXSwiaWF0IjoxNDU1NDU1MTk1fQ==.Rj7s-hgx1wVbE6yqIaBhJaTbLgD35EN8jOTF6dwSVVU=

Why do I get the same token ? Am I doing it wrongly ?

Thanks

**Comment by pmlopes** [comment]
The permissions you want on the token or claims should be on the first argument, since you use the same json both tokens are the same

**Comment by ragulan77** [comment]
I don't understand, it should work because it works fine inside my login function. Here is a piece of code:

```java
JsonObject tokenContent = new JsonObject().put("login", user.getString("login"));
String token = authProvider.generateToken(tokenContent, new JWTOptions().addPermission("user"));
JsonObject jsToken = new JsonObject().put("token", token);
 
 //Test
JsonObject authInfo = new JsonObject().put("jwt", token);
authProvider.authenticate(authInfo, res -> {
    if(res.succeeded())
    {
        System.out.println(res.result().principal().toString());
        System.out.println(res.result().isAuthorised("user", hasRole -> {
            System.out.println(hasRole.result().booleanValue());
         }));
     }
});
//endTest
                        
context.response().end(jsToken.encode());
```

And my output is: 

> INFO: Query execution succeeded
{"login":"charles","permissions":["user"],"iat":1455471699}
true


So according to the output, the addPermission on JWTOptions should add inside the claim (token) ?

**Comment by pmlopes** [comment]
after looking at your code i see that you assume that the claims are immutable, which probably should be.

In order to work around this issue for now, do not re-use the claims object and you will get the desired result, for example:

```java
userToken = authProvider.generateToken(ew JsonObject().put("login", "dupond"), new     JWTOptions().addPermission("user"));
adminToken = authProvider.generateToken(ew JsonObject().put("login", "dupond"), new   JWTOptions().addPermission("admin"));
```

it should give the desired result. I'll update the code to not modify the original claims object.
