### ISSUE TITLE
Launcher - Classpath env var must contain vert.x core

### ISSUE THREAD

**Issue by ekirin** [vert-x3/issues#104]
Following by instuction

> IntelliJ - create a Run configuration (Application), set the Main class to io.vertx.core.Launcher. In the Program arguments write: run your-verticle-fully-qualified-name --redeploy=**/*.class --launcher-class=io.vertx.core.Launcher. To trigger the redeployment, you need to make the project or the module explicitly (Build menu → Make project).

Always get error
```
25.02.2016 12:21:25.833 [main] INFO  io.vertx.core.impl.launcher.commands.Watcher - Starting the vert.x application in redeploy mode
Starting vert.x application...
ef5985cd-6a55-4506-948c-3ee655ea6997-redeploy
Error: Could not find or load main class io.vertx.core.Launcher
```
It's because there is no `vertx-core-3.2.1.jar` in the classpath. The error arises because of in my system has been defined CLASSPATH var. After reset CLASSPATH the problem has gone.

I think it's good idea to mention about this in the documentation.

**Comment by cescoffier** [comment]
Definitely ! 

Yes the "CLASSPATH" needs to contain vert.x. I will add a "warning" in the documentation.

**Comment by cescoffier** [comment]
Fixed in https://github.com/eclipse/vert.x/pull/1352.

**Comment by cescoffier** [comment]
PR merged
