### ISSUE TITLE
Integrate the Apache Ignite cluster manager in the stack

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/issues#105]

**Comment by cescoffier** [comment]
CC @agura

**Comment by cescoffier** [comment]
CI: https://vertx.ci.cloudbees.com/view/vert.x-3/job/vert.x3-ignite/

**Comment by cescoffier** [comment]
Everything done, ready for the 3.3.0 release.

**Comment by agura** [comment]
@cescoffier 

Clement, build fails on CI: https://vertx.ci.cloudbees.com/view/vert.x-3/job/vert.x3-ignite/4/console

Can I do something in order to fix it?

**Comment by cescoffier** [comment]
I guess it's because of "[00:41:05] Attempting to start more nodes than physical RAM available on current host (this can cause significant slowdown)"

**Comment by agura** [comment]
It's just performance hint and doesn't affect logic.

Builds are failed after different number of test passed. Is there any info about test boxes (RAM, OS)?

**Comment by cescoffier** [comment]
The JVM was killed because it ran out of memory. I've configure the build to use a "bigger" EC2 instance, so it passes now. I'm surprise it needs that much memory. Maybe we should open in issue in vertx-ignite and check if there is a leak somewhere.

**Comment by agura** [comment]
I've ran tests with `-Xmx1200m` and all tests passed without OOM. How many RAM available on one EC2 instance?

**Comment by agura** [comment]
Required heap size was decreased.
