### ISSUE TITLE
Is possible add more distribution strategy for eventBus ?

### ISSUE THREAD

**Issue by stream-iori** [vert-x3/issues#110]
Hi.
As nginx provide ip_hash / custom weight strategy for upstream, does make sense that make a interface that abstract message distribution strategy instead of default impl Round-Robin?

**Comment by purplefox** [comment]
What's the use case for this?

**Comment by stream1984** [comment]
Hi Tim 

1: we wanna select target by weight, as our hardware is not same.

2: I think that would be great if we can select target by eventbus's reply time, the shorter reply time means target have better throughout. 

3: maybe we can also decide which target should be selected by count target's backlog?


 



发自我的 iPhone

**Comment by tsegismont** [comment]
For the record, this is possible since Vert.x 4.0 (using a custom delivery strategy).
