### ISSUE TITLE
Server stops when printing PDF 

### ISSUE THREAD

**Issue by zackzulg** [vert-x3/issues#111]
Hi guys,
I was able to generate PDF using Vertx java and Jasper Report but my problem is when I click on close button of my PDF my server stops. So how to make server keep running even when I close my PDF.
Here is my java code : 

>> public void start(Future<Void> startFuture){
               String fileJSON = "{nom : 'Stackoverflow', dateDebut : '15-06-2014', dateFin : '02-09-2018'}";
               String file =  "/Test1";
               Router router = Router.router(vertx);
               router.route(file).handler(routingContext -> {
               HttpServerResponse response = routingContext.response();
            response.setChunked(true);            
            InputStream iostream = new ByteArrayInputStream(fileJSON.getBytes(StandardCharsets.UTF_8));
                    try{                                  
                        JsonDataSource ds = new JsonDataSource(iostream);
                        Map parametersMap = new HashMap();  
                        String report = "C:\\Users\\Path\\To\\My\\report2.jrxml";
                        JasperReport Jasp = JasperCompileManager.compileReport(report);
                        JasperPrint JASP_PRINT = JasperFillManager.fillReport(Jasp,parametersMap,ds);
                        JasperViewer.viewReport(JASP_PRINT);
                        JasperExportManager.exportReportToPdfFile(JASP_PRINT,            "C:\\\\Path\\To\\My\\report4.pdf");                             
                        }
                    catch(Exception e){ System.out.println(e);}
             routingContext.vertx().setTimer(1000, tid ->  routingContext.response().end());
          });
 vertx.createHttpServer()
                .requestHandler(router::accept)
                .listen(8089, "localhost", res -> {
 if (res.succeeded()){
                        startFuture.complete();    
                    }
                    else
                        startFuture.fail(res.cause());
                });
 }

**Comment by zackzulg** [comment]
Solved, I had to add second param to JasperViewer.viewReport(JASP_PRINT,false);

**Comment by cescoffier** [comment]
Reported as fixed by the user.
