### ISSUE TITLE
Can't read from json config

### ISSUE THREAD

**Issue by zackzulg** [vert-x3/issues#112]
Hi guys,
I want to read port and host from json file, I followed steps in http://vertx.io/blog/vert-x-application-configuration/  but when I use response.write(config().toString()); it returns an empty json ( only { } ).

**Comment by cescoffier** [comment]
At that point in the blog post series you have a single verticle. `config()` is passed to the first / main verticle, other (children) verticle don't have access to it.

To have access to is, configure the `DeploymentOption`.

If you are using a single verticle, I would need more detail about:

* what's the content of the json file
* how do you pass it to the application

**Comment by zackzulg** [comment]
Good morning Clement,
Yes sure, here is my class : 
 public void start(Future<Void> startFuture){
        
        String file =  "/TestConfig";
        //int port = config().getInteger("http.port", 8080);
        Router router = Router.router(vertx);
           router.route(file).handler(routingContext -> {
            HttpServerResponse response = routingContext.response();
            response.setChunked(true); 

            response.write(config().toString());
            response.end();
            routingContext.vertx().setTimer(1000, tid ->  routingContext.response().end());
            });
           vertx.createHttpServer()
                .requestHandler(router::accept)
                .listen(config().getInteger("port", 8087), "localhost", res -> {                    
                    if (res.succeeded()){

                        startFuture.complete();    
                    }
                    else
                        startFuture.fail(res.cause());
                });
    }


And for my main class : 
               public class Application {
                 public static void main(String[] args) {
                  Vertx vertx = Vertx.vertx();
                    TestConfig verticle = new TestConfig();
                
                       vertx.deployVerticle(verticle, res -> {
                         if (res.failed())
                          res.cause().printStackTrace();
                });
                  } 
                  }

And my json file (src/main/conf/NameOfApplication-config.json) : 
{
    "host"  : "localhost",
    "port"  : 8087,
}

**Comment by cescoffier** [comment]
So, the `-conf` and configuration passing works only if you are using the `io.vertx.core.Launcher` class as _main_ class. In your case you have your own main class. So you need either:

* replace is using the `Launcher` class
* read the json configuration from the file in your main class and pass it to the `DeploymentOption` of the `vertx.deployVerticle` method:

````
vertx.deployVerticle(verticle, new DeploymentOption().setConfig(config), res -> { .... });
````

**Comment by zackzulg** [comment]
I tried to add new DeploymentOption().setConfig(config) but it is unrecognized(both DeploymentOption and config). 
I was mistaken to use main method, because the main class is Launcher class, correct me if I'm wrong but i think the whole work should be in start (in this case)
Regards.

**Comment by cescoffier** [comment]
```
JsonObject config = <- read the file and build the JsonObject
vertx.deployVerticle(verticle, new DeploymentOptions().setConfig(config));
```

**Comment by cescoffier** [comment]
Closing this issue, please reopen if needed.
