### ISSUE TITLE
Could not load driverClass org.hsqldb.jdbcDriver

### ISSUE THREAD

**Issue by zackzulg** [vert-x3/issues#113]
Good morning, 
I try to use Vertx Jdbc to get infos from database, but when i run my code it gives me : AVERTISSEMENT: Could not load driverClass org.hsqldb.jdbcDriver
java.lang.ClassNotFoundException: org.hsqldb.jdbcDriver

Here is my code : 

> public class JasperJdbc extends AbstractVerticle{
     @Override
    public void start(Future<Void> startFuture){
        String file="/Test1";
        Router router = Router.router(vertx);
           router.route(file).handler(routingContext -> {
            HttpServerResponse response = routingContext.response();
            response.setChunked(true);            
            JDBCClient client = JDBCClient.createShared(vertx, new JsonObject()
            		  .put("url", "jdbc:hsqldb:mem:OdbcName")
            		  .put("driver_class", "org.hsqldb.jdbcDriver")
                    .put("max_pool_size", 2));
            client.getConnection(res -> {
                          if (res.succeeded()) {
                        	  	System.out.println("oki done");
                          } else {
                            System.out.println("No data");
                          }
                        });
                        response.end();
            routingContext.vertx().setTimer(1000, tid ->  routingContext.response().end());
        });
        vertx.createHttpServer()
                .requestHandler(router::accept)
                .listen(8089, "localhost", res -> {                    
                    if (res.succeeded()){
          startFuture.complete();    
                    }
                    else
                        startFuture.fail(res.cause());
                });
    }

**Comment by pmlopes** [comment]
do you have the driver in your class path? e.g.: part of your dependencies in your pom file if you're using maven.

**Comment by zackzulg** [comment]
Hi Paulo, actually I don't use maven or gradle, I add jars from build path of eclipse.

**Comment by pmlopes** [comment]
still the same principle applies, do you have the driver jar in your project?

**Comment by zackzulg** [comment]
Yeap I added it from Hsql web site ( I tried to get it from vertx but I couldn't find it), it works for my SOPrintln, but when I want to fetch some data from my database it gives me this instead of my data : 

> avr. 11, 2016 11:53:04 AM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
INFOS: Succeeded in deploying verticle
MLog initialization issue: slf4j found no binding or threatened to use its (dangerously silent) NOPLogger. We consider the slf4j library not found.
avr. 11, 2016 11:53:20 AM com.mchange.v2.log.MLog 
INFOS: MLog clients using java 1.4+ standard logging.
avr. 11, 2016 11:53:22 AM com.mchange.v2.c3p0.C3P0Registry 
INFOS: Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
avr. 11, 2016 11:53:22 AM io.vertx.core.impl.BlockedThreadChecker
AVERTISSEMENT: Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2244 ms, time limit is 2000
avr. 11, 2016 11:53:23 AM io.vertx.core.impl.BlockedThreadChecker
AVERTISSEMENT: Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 3244 ms, time limit is 2000
avr. 11, 2016 11:53:24 AM io.vertx.core.impl.BlockedThreadChecker
AVERTISSEMENT: Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 4245 ms, time limit is 2000
avr. 11, 2016 11:53:25 AM com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource 
INFOS: Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hge14j9g1dhk3gajtf7f|9c8e73, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.hsqldb.jdbcDriver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1hge14j9g1dhk3gajtf7f|9c8e73, idleConnectionTestPeriod -> 0, initialPoolSize -> 3, jdbcUrl -> jdbc:hsqldb:mem:zakaria, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 30, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
avr. 11, 2016 11:53:25 AM io.vertx.core.impl.ContextImpl
GRAVE: Unhandled exception
java.lang.IllegalStateException: Response has already been written
	at io.vertx.core.http.impl.HttpServerResponseImpl.checkWritten(HttpServerResponseImpl.java:561)
	at io.vertx.core.http.impl.HttpServerResponseImpl.end0(HttpServerResponseImpl.java:389)
	at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:328)
	at SendData.JasperJdbc.lambda$3(JasperJdbc.java:44)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:738)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:709)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Unknown Source)


Here is my statement : 

> if (res.succeeded()) {
                            SQLConnection connection = res.result();
                            connection.query("SELECT * FROM dbo.Achat", res2 -> {
                              if (res2.succeeded()) {
                                ResultSet rs = res2.result();
                                System.out.println(rs);
                              }
                            });
                          } else {
                            System.out.println("No data");
                          }
                        });
                        response.end();

**Comment by pmlopes** [comment]
but now you have another issue. The driver is loader properly but your flow control seems to be wrong.

From the exception it seems that you end the http response before the database response arrives so you cannot write anymore since the response is ended.

Can you share the http code too?

**Comment by zackzulg** [comment]
Yes sure, 

> public class JasperJdbc extends AbstractVerticle{
     @Override
    public void start(Future<Void> startFuture){
        String file="/Test1";
        Router router = Router.router(vertx);
           router.route(file).handler(routingContext -> {
            HttpServerResponse response = routingContext.response();
            response.setChunked(true);            
            JDBCClient client = JDBCClient.createShared(vertx, new JsonObject()
            		  .put("url", "jdbc:hsqldb:mem:OdbcName")
            		  .put("driver_class", "org.hsqldb.jdbcDriver")	
                      .put("max_pool_size", 30));
            client.getConnection(res -> {
                          if (res.succeeded()) {
                            SQLConnection connection = res.result();
                            connection.query("SELECT * FROM dbo.Achat", res2 -> {
                              if (res2.succeeded()) {
                            	  res2.toString();
//                                ResultSet rs = res2.result();
//                                System.out.println(rs.getResults().toString());
                              }
                              else { System.out.println(res2.cause().toString()); }
                            });
                          } else {
                            System.out.println("No data");
                          }
                        });
            routingContext.vertx().setTimer(8000, tid ->  routingContext.response().end());
        });
/* ***** HTTP Side  ***** * /
        vertx.createHttpServer()
                .requestHandler(router::accept)
                .listen(8085, "localhost", res -> {                    
                    if (res.succeeded()){
                        startFuture.complete();    
                    }
                    else
                        startFuture.fail(res.cause());
                });
    }
}

It seems it doesn't go through the second condition because it gives as message now : "user lacks privilege or object not found: ACHAT"

**Comment by zackzulg** [comment]
I edit code to : 
`                 connection.query("SELECT TABLE_NAME FROM information_schema.tables", res2 -> {
                              if (res2.succeeded()) {
                            	  System.out.println(res2.result().getResults().toString());`

which list my tables from database but instead of fetching tables name it gives something else : 
[["ADMINISTRABLE_ROLE_AUTHORIZATIONS"], ["APPLICABLE_ROLES"], ["ASSERTIONS"], ["AUTHORIZATIONS"], ["CHARACTER_SETS"], ["CHECK_CONSTRAINTS"], ["CHECK_CONSTRAINT_ROUTINE_USAGE"], ["COLLATIONS"], ["COLUMNS"], ["COLUMN_COLUMN_USAGE"], ["COLUMN_DOMAIN_USAGE"], ["COLUMN_PRIVILEGES"], ["COLUMN_UDT_USAGE"], ["CONSTRAINT_COLUMN_USAGE"], ["CONSTRAINT_TABLE_USAGE"], ["DATA_TYPE_PRIVILEGES"], ["DOMAINS"], ["DOMAIN_CONSTRAINTS"], ["ELEMENT_TYPES"], ["ENABLED_ROLES"], ["INFORMATION_SCHEMA_CATALOG_NAME"], ["JARS"], ["JAR_JAR_USAGE"], ["KEY_COLUMN_USAGE"], ["PARAMETERS"], ["REFERENTIAL_CONSTRAINTS"], ["ROLE_AUTHORIZATION_DESCRIPTORS"], ["ROLE_COLUMN_GRANTS"], ["ROLE_ROUTINE_GRANTS"], ["ROLE_TABLE_GRANTS"], ["ROLE_UDT_GRANTS"], ["ROLE_USAGE_GRANTS"], ["ROUTINES"], ["ROUTINE_COLUMN_USAGE"], ["ROUTINE_JAR_USAGE"], ["ROUTINE_PRIVILEGES"], ["ROUTINE_ROUTINE_USAGE"], ["ROUTINE_SEQUENCE_USAGE"], ["ROUTINE_TABLE_USAGE"], ["SCHEMATA"], ["SEQUENCES"], ["SQL_FEATURES"], ["SQL_IMPLEMENTATION_INFO"], ["SQL_PACKAGES"], ["SQL_PARTS"], ["SQL_SIZING"], ["SQL_SIZING_PROFILES"], ["SYSTEM_BESTROWIDENTIFIER"], ["SYSTEM_CACHEINFO"], ["SYSTEM_COLUMNS"], ["SYSTEM_COLUMN_SEQUENCE_USAGE"], ["SYSTEM_COMMENTS"], ["SYSTEM_CONNECTION_PROPERTIES"], ["SYSTEM_CROSSREFERENCE"], ["SYSTEM_INDEXINFO"], ["SYSTEM_INDEXSTATS"], ["SYSTEM_PRIMARYKEYS"], ["SYSTEM_PROCEDURECOLUMNS"], ["SYSTEM_PROCEDURES"], ["SYSTEM_PROPERTIES"], ["SYSTEM_SCHEMAS"], ["SYSTEM_SEQUENCES"], ["SYSTEM_SESSIONINFO"], ["SYSTEM_SESSIONS"], ["SYSTEM_TABLES"], ["SYSTEM_TABLESTATS"], ["SYSTEM_TABLETYPES"], ["SYSTEM_TEXTTABLES"], ["SYSTEM_TYPEINFO"], ["SYSTEM_UDTS"], ["SYSTEM_USERS"], ["SYSTEM_VERSIONCOLUMNS"], ["TABLES"], ["TABLE_CONSTRAINTS"], ["TABLE_PRIVILEGES"], ["TRANSLATIONS"], ["TRIGGERED_UPDATE_COLUMNS"], ["TRIGGERS"], ["TRIGGER_COLUMN_USAGE"], ["TRIGGER_ROUTINE_USAGE"], ["TRIGGER_SEQUENCE_USAGE"], ["TRIGGER_TABLE_USAGE"], ["UDT_PRIVILEGES"], ["USAGE_PRIVILEGES"], ["USER_DEFINED_TYPES"], ["VIEWS"], ["VIEW_COLUMN_USAGE"], ["VIEW_ROUTINE_USAGE"], ["VIEW_TABLE_USAGE"], ["BLOCKS"], ["LOBS"], ["LOB_IDS"], ["PARTS"]]

**Comment by pmlopes** [comment]
Those are hsqldb standard views:

http://www.hsqldb.org/doc/2.0/guide/databaseobjects-chapt.html

**Comment by ORESoftware** [comment]
Can someone just cite the pom dependency for `org.hsqldb.jdbcDriver`?

ok here
https://mvnrepository.com/artifact/org.hsqldb/hsqldb/2.3.2
