### ISSUE TITLE
HttpClientRequest buffer issue with setChunked(true)

### ISSUE THREAD

**Issue by pfisher346** [vert-x3/issues#117]
The request sometimes looses single chunks probably due to an buffer handling issue:
Independent from the max chunk size provided the request sometimes seems to (re-)use some buffer with an arbitrary size for the first chunks. The chunks from this buffer are always received on the server side.
This first buffer is often sufficient for the complete request and everything works. 

But as soon as this first big buffer is full and the request has not ended yet, the request seems to switch to buffers with the correct max chunk size. The next chunk after the first (big) buffer is not sent out (in the test run below the chunk with identifier : 3). 
All further chunks work again as expected:

112
{"identifier" : "0", "type_of_item" : "hardcover_book", "title_of_item" : "test record 0"}, {"identifier" : "1", "type_of_item" : "hardcover_book", "title_of_item" : "test record 1"}, {"identifier" : "2", "type_of_item" : "hardcover_book", "title_of_item" : "test record 2"}
5c
, {"identifier" : "4", "type_of_item" : "hardcover_book", "title_of_item" : "test record 4"}
5c
, {"identifier" : "5", "type_of_item" : "hardcover_book", "title_of_item" : "test record 5"}
5c
, {"identifier" : "6", "type_of_item" : "hardcover_book", "title_of_item" : "test record 6"}
5c
, {"identifier" : "7", "type_of_item" : "hardcover_book", "title_of_item" : "test record 7"}
5c
, {"identifier" : "8", "type_of_item" : "hardcover_book", "title_of_item" : "test record 8"}
5c
, {"identifier" : "9", "type_of_item" : "hardcover_book", "title_of_item" : "test record 9"}
3
...
0
 
HTTP/1.1 500 Internal Server Error
Content-Length: 14
 
missing doc: 3

The test code code can be found here - might have to be run several times till the problem occurs...
[dx.test.http.zip](https://github.com/vert-x3/issues/files/244574/dx.test.http.zip)

**Comment by purplefox** [comment]
I have reproduced this and it appears to be a race condition.

I notice you are interacting with the request from outside an event loop. This should work, but is not the recommended/optimal way of using Vert.x.

You're using Vert.x 3.2.1 and I also notice that @vietj has made various threading related changes/fixes in the http client since then. Can you try with 3.3.0-SNAPSHOT and see if the problem continues?

**Comment by purplefox** [comment]
I've tested the test program with Vert.x 3.3.0-SNAPSHOT and I can't replicate the issue, so I will assume Julien has already fixed this.

**Comment by pfisher346** [comment]
Hi Tim,

thanks for checking - will try v3.3.0 first thing tomorrow German time (today is a public holiday)...

Thanks, Peter

**Comment by pfisher346** [comment]
3.3.0-SNAPSHOT works!

Thanks for your quick help!!!
