### ISSUE TITLE
MongoDBClient - Unable to perform query filters with ISODate fields

### ISSUE THREAD

**Issue by filipedelgado** [vert-x3/issues#118]
It's not possible to perform queries involving MongoDB ISODate fields, as reported in topic: https://groups.google.com/forum/#!topic/vertx/W6bcFkTfPmY

To perform these types of queries with the original MongoDB Client, it should built with this approach:
```
DBCollection coll = ...
coll.insert(new BasicDBObject("ts", new Date()));
```

However, since VertxMongoClient only supports queries as JsonObject, we should do something like:
`"creation_date": {
				"$gte": ISODate("2016-05-09T06:48:11.526+01:00")
			}`

The problem:
The above query is not a valid JsonObject, I'm unable to build it.

Other approaches tried:
`"creation_date": {
				"$gte": "ISODate(2016-05-09T09:48:11.526+01:00)"
			}`

Valid JsonObject but the query doesn't work.

**Comment by pmlopes** [comment]
You are mixing JSON and mongo query language, for a ISODate (a mongo query language type) in JSON you should use:

```
{ "$date": "<date>" }
```

So it reads:

```
"creation_date": { "$gte": { "$date": "2016-05-09T09:48:11.526+01" } }
```

For more info see: https://docs.mongodb.com/manual/reference/mongodb-extended-json/

**Comment by filipedelgado** [comment]
Hi Paulo,  I'veI've also  tried your approach but It seemed that it only works with equals,  not with operators like $gte. I'll try again tomorrow,  thanks.

**Comment by filipedelgado** [comment]
@pmlopes I've tried again and it works. So, what was the problem: when we build queries with extended json, they will not work in MongoDB shell and I was doing this to test the queries. May I suggest that you add an example like this in the official documentation? I'm sure it will save lots of time to a lot of people :)

**Comment by pmlopes** [comment]
it was there i think: http://vertx.io/docs/vertx-mongo-client/java/#_mongodb_extended_json_support
