### ISSUE TITLE
Vertx : insert array of objects into my database without without for loop.

### ISSUE THREAD

**Issue by zackzulg** [vert-x3/issues#119]
Hi guys,

I have an array of json object which i want to insert into my database, and instead of using a loop 'for' I'd like to use stored procedure, my question is how to do it without using the add method of jsonArray because as i see it takes one by one my records.

For example I have an array like this : [{'website': 'github.com', 'description': 'very useful'}, {'website' : 'google.com', 'description' : 'huge informations'}] and I don't want to use it like this :

    for(i=0;i<ja.size();i++){
       JsonArray params = new JsonArray();
       params.add('website',ja.getJsonObject(i).getValue("website")).add('website',ja.getJsonObject(i).getValue("description"));
    }

Regards.

**Comment by pmlopes** [comment]
This is not a bug, you should be asking this in the development forum: https://groups.google.com/forum/#!forum/vertx where the community will help you.
