### ISSUE TITLE
make use of EditorConfig to ensure consistent code style

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/issues#122]
In the wiki we specify that code should be indented with 2 spaces instead of tabs or long 4 spaces. If we add the `.editorconfig` to the root of the repos, all code editions directly on github, intellij and many other editors will be automatically set to the style we want.

Most IDEs will work without even a plugin.

see: http://editorconfig.org/

a example would be:

```
root = true

[*]
end_of_line = lf
insert_final_newline = true
charset = utf-8
indent_style = space
indent_size = 2

# For exotic formats we can do specific tuning
# e.g.: Makefiles need Tab indentation
[Makefile]
indent_style = tab
```

This would solve comments on PR where indentation is broken for example...

**Comment by Pahan-Madusha** [comment]
I think the example `.editorconfig` file you mentioned can be used as it is for all repos. Are there any other file types like `Makefile` which need tab indentation?

**Comment by vietj** [comment]
should be mentioned here and contain the config : https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines
