### ISSUE TITLE
RX Js not working

### ISSUE THREAD

**Issue by chethan-K** [vert-x3/issues#124]
Hi,

I include RXJS with this pom.xml
<groupId>io.vertx</groupId>
<artifactId>vertx-rx-js</artifactId> 

Trying load rx js module with

**Comment by pmlopes** [comment]
duplicate of #125

**Comment by chethan-K** [comment]
Hi Paulo(@pmlopes)

Thanks for the very quick response.
It worked after installing RX  npm module.

I have few question here:

1. If i istall npm package, I can work with node version of rx module invoking its observable methods.
Is it right ..? I should be making use of vertx.rx library right ..?

2. My assumption is that, I should not be using npm modules as I will be having equivalent API's written in vertx.     If I use npm version of JS module, this manual(http://vertx.io/docs/vertx-rx/js/) does not make much sense. 

I am new to vertex js, coming from nodejs . Any help is appreciated. 

Thanks in advance
Chethan K
