### ISSUE TITLE
RXJS not working.

### ISSUE THREAD

**Issue by chethan-K** [vert-x3/issues#125]
Hi,
I am getting this ERROR : 
javax.script.ScriptException: Error: Cannot find module ./rx in <eval> at line number 141 at column number 6
 - When trying load rx js  with require("rx.vertx")

Included dependency in pom.xml like this,
      <groupId>io.vertx</groupId>
      <artifactId>vertx-rx-js</artifactId>

Please help. I followed API documentation.

**Comment by pmlopes** [comment]
You need to include the npm rx module.

https://www.npmjs.com/package/rx

```
npm install rx
```

**Comment by chethan-K** [comment]
Hi Paulo(@pmlopes)

Thanks for the very quick response.
It worked after installing RX npm module.

I have few question here:

If i istall npm package, I can work with node version of rx module invoking its observable methods.
Is it right ..? I should be making use of vertx.rx library right ..?

My assumption is that, I should not be using npm modules as I will be having equivalent API's written in vertx. If I use npm version of JS module, this manual(http://vertx.io/docs/vertx-rx/js/) does not make much sense.

I am new to vertex js, coming from nodejs . Any help is appreciated.

Thanks in advance
Chethan K

**Comment by pmlopes** [comment]
The vertx library is build on top of the RxJS api, when you get an observable from vert.x in fact you're getting a Observable from RxJS so the RX api you need to know to use the the official one.

**Comment by dsetton** [comment]
Hi Paulo (@pmlopes),

I have a similar issue, with a maven project with several modules. Where should I run the npm command? I've tried a few possibilities, but none fixed the problem.

Thanks

**Comment by pmlopes** [comment]
assuming you're using maven and your source lives under `src/main/resouces` that's where you should install any npm related dependencies.

**Comment by dsetton** [comment]
It was my first assumption. But it didn't work. I managed to get it working under `src/main`
