### ISSUE TITLE
programmatic logging configuration

### ISSUE THREAD

**Issue by ukr15** [vert-x3/issues#127]
We would like to use only one configuration file for our verticles which includes logging configuration too.
it would be fine, if there is a chance to access the logger delegate object in order to do the programmatic configuration, like removing console logger, add dedicated formatter etc. 

To be more detailed, we need the following functionality:
1. get an  handle to the underlying logging framework
2. use this handle, e.g. to deactivate console logging. to attach file logger and an formatter

io.vertx.core.logging.Logger logger = LoggingFactory.getLogger(a.class);

java.util.logging.Logger delegate (java.util.logging.Logger) logger.getDelegate();

FileHandler fileHandler;

try{ 

// define file handler

   fileHandler = new FileHandler(config.getString(Constants.KEY_PATH, "log.log"), 1000*1024),10);

// deactivate consoleLogger

   delegate.setUseParentHandlers(false);

// set log level

   delegate.setLevel(getLogLevel(Level.INFO));

   fileHandler.setFormatter(new SimpleFormatter());

// add file handler to delegate

```
 delegate.addHandler(fileHandler); 
```

}....

In the following, the default vertx logging interface will be used

**Comment by pmlopes** [comment]
Logging is no longer a concern of vertx-core. Users are advised to use own logger.
