### ISSUE TITLE
one client's packet is splited to three packets by server

### ISSUE THREAD

**Issue by boyhooda** [vert-x3/issues#128]
client code 
```java
public class ClientTest {
	public static void main(String[] args) {
		Vertx vertx = Vertx.vertx();
		vertx.createNetClient().connect(1234, "localhost", res -> {
			NetSocket socket = res.result();
        	Random random = new Random();
			byte[] data = new byte[2200];
			random.nextBytes(data);
			socket.write(Buffer.buffer().appendBytes(data));
		});
	}
}
```

server code
```java
public class ServerTest {
    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        NetServerOptions options = new NetServerOptions();
        //options.setReceiveBufferSize(2000);
        //options.setSendBufferSize(2000);
        NetServer server = vertx.createNetServer(options);
        server.connectHandler(socket -> {
            socket.handler(buffer -> {
                System.out.println("I received some bytes: " + buffer.length());
            });
        }).listen(1234);
    }
}
```

I konw vertx use AdaptiveRecvByteBufAllocator for default allocator, it can automatically increases and decreases buffer size, but it not work for the first large packet.
I also used NetServerOptions to set BufferSize, vertx will use FixedRecvByteBufAllocator, it work well  at the beginning, but this connection's tcp window is decreasing, the result is the  tcp window can't hold one packet.
How should I do, if I want to receive a whole packet.

**Comment by vietj** [comment]
hi, you should not ask questions in this issue tracker and instead use the Vert.x forum where someone will answer you https://groups.google.com/forum/#!forum/vertx
