### ISSUE TITLE
Enhance Vert.x Web Router Support

### ISSUE THREAD

**Issue by Jotschi** [vert-x3/issues#138]
I propose adding a router management system for vert.x web which allows you to write verticles which can hook into existing sub routers.

I can break down my usecase this way:

I have a central router (/) which mounts one subrouter for my REST API (/api/v1).
I can now dynamically add and remove verticles which hook into either the subrouter (/api/v1) in order to extend the REST API and I can add and remove verticles which mount their own routers in order to for example create routes which serve static content.

I wrote my own specific router management system which is only 300 LOC but I always felt that this should be a part of vert.x web in some way. My own implementation is just a class which contains a bunch of Maps to keep track of the created routers.

Please correct me if i'm wrong but I think it is also not very easy to share routes between Java and Javascript verticles for example.

**Update**

I assume the main reason why I initially wrote my management class is that i was unable to access mounted routers from within my initial router which i added to my webserver. I guess if the routing system would allow to list _mountpoints_ that would solve a lot of troubles I came across. As far as I know that is currently not possible.

**Comment by pmlopes** [comment]
When you're saying `router management system` are you thinking of `JMX` in order to enable/disable routes? or you want to see more fine grained control?

**Comment by Jotschi** [comment]
@pmlopes I would like to be able to list mounted routers. That way I would be able to traverse the router tree. This would basically eliminate the need for a central router management system since the routers them self keep track of mounted routers.

**Comment by kastork** [comment]
Others have tried to articulate this use-case, or at least similar use-cases.

https://github.com/vert-x3/vertx-web/issues/140

In this demo, the Router reference is exposed as a service in OSGI and subrouters are added at runtime.
https://github.com/paulbakker/osgi-vertx-demo

I've seen a Guice example where the router is made injectable and discoverable but I can't seem to find it right now.

**Comment by Jotschi** [comment]
Another related issue may be https://github.com/vert-x3/vertx-web/issues/378. 
Tim stated:

> If you find yourself sharing Routers between verticle instances that's an anti-pattern. They were never designed to be used this way.

I'm currently sharing routers in between verticles. I use verticles to add or remove endpoints from my REST API and this can (afaik) only be done by sharing a common router. I don't see why this should be seen as an anti-pattern.

Summary:
- Add a way to access a router's sub routers (router mounts)
- Allow sharing of routers in between verticles in a vert.x supported way

**Comment by kastork** [comment]
@Jotschi , I'm speculating, but I suspect Tim's opinion may have to do with the integrity of the verticle's guarantee that anything in the verticle will be run on the same thread.  Verticles sharing object references, like the router,  does seem antithetical to that principle.

I think it (meaning your proposal) is a valid use-case, but there could be some very non-trivial work to do to get there.

**Comment by vietj** [comment]
@kastork indeed the technical issue is that verticles have different contexts and thus not the same thread.

My personal opinion when it comes to modularize routing, is that the user should have a way to discover routers and load them in the same verticle. If there is a need of multiple verticles, then routing can remain in the same verticle but the functional parts is isolated in verticles and communication happens using event bus.

**Comment by kastork** [comment]
Your description of modularization of routing makes sense to me.

My main desire would be to have the ability to create an app that has, say, vertx shell with commands  (perhaps my own, perhaps provided) that would allow me to deploy and undeploy endpoints of any type (including the possibility of additional static handlers who have their content in their jar file) without restarting or rebuilding the verticle that's providing the web server.

That idea leads naturally to the notion that the thing being deployed and undeployed would be a verticle, since that's the natural unit of deployment/packaging in Vertx.   Or maybe there's a case here for something that deploys like a verticle, but isn't one.

**Comment by aesteve** [comment]
Maybe that's silly and doesn't address the use case, but what if the `Router` had a "service-proxified" interface ?

I think this addresses the use case, when you start your, say, `PetsRestService` which has all your business logic, you'd write something like : 

``` java
Router router = Router.remote(vertx, "some-address-youve-defined-in-the-webserver"); // maybe Router is not accurate here since it won't be the same signature at all, RemoteRouter ?
router.get("/api/v1/pets", this::listPets); // OK this one should be changed to an asynchronous invokation... Maybe router.remoteEndpoint("/api/v1/pets", this::listPets, registrationAsyncResult -> {});
```

And within the main "webserver" verticle 

``` java
Router router = Router.router(vertx, "some-address-youve-defined-in-the-webserver"); // by specifying a String we're telling vertx to "bridge" the router over the event-bus
server.requestHandler(router::accept);
```

That'd register the eventBus consumers / producers on the specified address. 

The only problem I see would be the marshalling / unmarshalling (serialization) of the RoutingContext over the event-bus.  Is this even possible ? Which overhead would that introduce ?

Regarding design. I'm not sure I like it. But I kinda understand the use case "I'm deploying a new micro service and want to attach it's REST primitives to an existing API server".

At least I think that this approach can be easily tested as a standalone (week-end) project, no ?

**Comment by pmlopes** [comment]
For basic requests this should be doable i guess but how would you handle request bodies, say that you want to handle a POST/PUT of image/json/blob this would probably generate huge json messages that would consume some CPU plus put stress on the internal network to push the request to right node and handle back the response...

**Comment by aesteve** [comment]
Yeah right. Request/response chunking would be a total mess :\ didn't think about that, sorry.

**Comment by pmlopes** [comment]
No need to be sorry, we're brainstorming here :)

**Comment by vietj** [comment]
@aesteve your suggestion seems a bit related to this experiment : https://github.com/vietj/vertx-reverse-proxy except it would not use HTTP (as reverse proxy) but the event bus service proxies

**Comment by kastork** [comment]
@vietj  (since we're brainstorming) So like now when you deploy n verticles who have a web server configured you still only get one public endpoint (only consume one port) and Vertx handles the internal load balancing.  If the (let's call them) dynamic sub-routers were actually http servers, but maybe specialized to be aware of all this, then maybe could add internal reverse proxy capability to the existing load balancing system?

**Comment by Jotschi** [comment]
I assume this discussion is also related to this issue:

https://groups.google.com/forum/#!topic/vertx/dd4ciH_AzwM

A best practice example which showcases a good solution for this usecase would be really great.

**Comment by vitalif** [comment]
Hi, +1 to the issue / feature request.
The idea is in fact very simple - everyone wants modular webapps. I.e. everyone wants to just deploy 10 independent verticles and get a single web-server dispatching requests to all of them, with all verticles still having access to all vert.x-web features like cookies, sessions, file uploads and so on.
I.e. webserver (and router, and so on) should not be a part of any specific verticle, or at least it should be shared between verticles.
This is the behaviour you get with the event bus: there is a single event bus for an instance of vertx and you plug handlers into it. Everyone wants to do the same with HTTP.
You can of course try to workaround it by moving your real HTTP request handlers into event bus handlers and make a single "router" verticle dispatch requests to event bus handlers. BUT this stops you from using ALL vert.x-web features! All of them are implemented via router and thus are inaccessible from event bus handlers.

**Comment by manish-panwar** [comment]
@vitalif  I may be off the topic but if you are okay with using Spring with Vertx then I would recommend you to take a look at Vertx-Beans - https://github.com/rworsnop/vertx-beans It's a very sleek implementation allowing you to integrate with Spring and move away from Verticles (basically using Vertx as API along with Spring). 

I know that's not what you are looking for but I want to make people aware about the benefits we are having with using Vertx and Spring. We found it so easy to use Vertx as API than platform. In our app we have around 10 different webapps(nothing but handlers - aka Spring managed beans). And we are able to split app in different routers, be able to use all features of Vertx Web and so on...

I can provide some real world end-to-end examples if you are interested.

+1 on your suggestion.

**Comment by manish-panwar** [comment]
BTW, we use Vertx app as a proxy serving terabytes of data, and also the REST API part of same app. Only thing you will miss is, be able to use Vertx-Test API to test verticles/eventbus etc, but we are still able to test our app effortlessly.

**Comment by pmlopes** [comment]
@vitalif if you are looking for deploying many verticles and have them as a single API server I guess you are looking for an API gateway. @manish-panwar true that you can use spring to glue everything but once you do that you end up with a monolith which is not a synonym of modularity per se. True for most users that is fine but for cases where scalability and high availability are paramount then you would be better with an API gateway.

**Comment by vitalif** [comment]
What do you mean by an api gateway? Do you mean a separate "proxy" that receives http requests and forwards them to the event bus? Ok, but in that case you have no access to vert.x web features inside your services. You can't use templating, sessions, cookies, file uploads, response headers and so on - unless you implement it yourself in your API gateway and pass it over your event bus.
Another common issue with API gateway is the registration of routes/endpoints. How should it be solved? If you hardcode your routes into your API gateway you again lose modularity.
Shared router is the simplest solution, although maybe it's not the best one - the idea is Vert.x needs some kind of "integrated" router and event bus logic. Or you can think about it like that vertx should have a builtin "api gateway" with all these issues solved out of the box :-)

**Comment by manish-panwar** [comment]
@pmlopes - Maybe I didn't explain our usage clearly OR are you trying to say that using "Vertx as API" is monolith v/s using Vertx as platform? We use everything out of Vertx, that includes HTTP server, eventbus, almost everything...

**Comment by vitalif** [comment]
Tried using vert.x sessions with REST handlers distributed over the event bus - it's a real pain in the ass... Session is SO MUCH tied to the RoutingContext...

**Comment by orre** [comment]
For what it's worth (and maybe somewhat out of context) I've been attempting to do modularization by "passing in" a Router to my verticle from the "main" program that creates the singular Router & HTTP server. My intention was to share the router between possibly several verticles. My conclusion: THIS LEADS TO GLOBAL MADNESS. DON'T DO IT. The guarantee that all handlers that you see in a verticle will execute on the same event-loop thread no longer holds. Which means that your verticle is no longer "single-threaded". The program below illustrates this malpractice, and it will in fact fail miserably immediately if sent any request, e.g.

> curl -X PUT -H "Content-Type: application/json" -d '{"name":"arne"}' http://localhost:8080/hello

---------

package foo;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Future;
import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.core.http.HttpServerOptions;
import io.vertx.core.http.HttpServerRequest;
import io.vertx.ext.web.Router;

public class FooBar extends AbstractVerticle {

    private long myThreadId;
    private Router router;

    public FooBar(Router router) { this.router = router; }

    @Override
    public void start(Future<Void> startFuture) throws Exception {
        myThreadId = Thread.currentThread().getId();
        System.out.println(String.format("My initial thread ID: %d", myThreadId));
        router.route().handler(rc -> {
            HttpServerRequest request = rc.request();
            request.handler(buffer -> {
                checkThread();
            }).endHandler(aVoid -> {
                request.response().end();
            });
        });
        startFuture.complete();
    }

    private void checkThread() {
        if (myThreadId != Thread.currentThread().getId()) {
            System.err.println("Gotcha!! You are on the wrong thread!!");
            System.exit(0);
        }
    }

    public static void main(final String[] args) {
        final Vertx vertx = Vertx.vertx(new VertxOptions());
        final Router router = Router.router(vertx);
        vertx.deployVerticle(new FooBar(router), new DeploymentOptions());
        vertx.createHttpServer(new HttpServerOptions().setHost("0.0.0.0")).requestHandler(router::accept).listen(8080);
    }
}

**Comment by Jotschi** [comment]
I created a small example which shows how I'm now handling my routers across multiple verticles. 
https://github.com/Jotschi/vertx-router-example

I create a router for each verticle and use a dedicated class to make it possible to synchronize changes to the routers. (e.g.: rename a subrouter mount)

**Comment by pmlopes** [comment]
Router can properly handle sub routers now and has a `getRoutes()` which allows traversing the router routes. This makes this issue irrelevant. Please reopen if needed.
