### ISSUE TITLE
OSGI integration wishlist

### ISSUE THREAD

**Issue by david-t-daniel** [vert-x3/issues#139]
I love that Vertx can be hosted in an osgi environement now.  It would great to see some plugins that have tighter integration with the spec.  Some examples.
- An OSGI compliant httpservice in vertx web
- A Service discovery plugin that works with the OSGI resolver and Remote Service spec
- An OSGI compatible auth provider

Now that I have both vertx and osgi I find myself having to choose which one I use for components that really do the same thing.

**Comment by dixiesraj** [comment]
How about making dropwizard metrices extensions to be OSGi compliant.
With 3.3.2 most of them are OSGi complaint.

> **It would also be great to keep us (OSGi fans) in mind whilst adding new features.**

**Comment by cescoffier** [comment]
Dropwizard is going to be OSGi compliant in the 3.3.3 version. Check https://github.com/vert-x3/vertx-dropwizard-metrics

**Comment by pmlopes** [comment]
Due to lack maintainers and proper testing OSGi metadata is removed from all modules on master.
Which makes this issue not fixable.
