### ISSUE TITLE
Add package information to documentation

### ISSUE THREAD

**Issue by HugoCrd** [vert-x3/issues#14]
Reading the docs, user can't easily find what to add to it's dependency manager.
It would be great to add this information in each documentation's header :

> Just add this dependency to your package manager :
> Gradle : ```compile io.vertx:vertx-whatever:3.0.0```
> Maven :
```
<dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-whatever</artifactId>
    <version>3.0.0</version>
    <scope>compile</scope>
</dependency> 
```

Issue from discussion: https://groups.google.com/forum/#!topic/vertx/H_X3afrAuNU

**Comment by cescoffier** [comment]
We are going to add such information.
The first step was to provide a way to inject the required coordinates in our docs:
https://github.com/vert-x3/vertx-ext-parent/issues/4

**Comment by cescoffier** [comment]
Dependencies have been added to all projects from the stack.

**Comment by HugoCrd** [comment]
:+1:
