### ISSUE TITLE
Basic Spring support

### ISSUE THREAD

**Issue by draxly** [vert-x3/issues#142]
Hi!

I ported my existing code base from Spring Boot to Vertx and am very happy about that. To make the transition smoother I started using the Vertx Spring module found here: https://github.com/amoAHCP/spring-vertx-ext

I am using Spring for dependency injection with bean definitions, Spring profiles and Spring support for unit testing. It is working quite nicely but I would be more confident using an official Vertx way to solve this (where the code base will be updated and patched for new Vertx released).
It would also be nice to be able to use both the functionality of SpringJUnit4ClassRunner and VertxUnitRunner when running unit tests.

Cheers,
Tim

**Comment by Jotschi** [comment]
The spring-vertx-ext is basically just a simple verticle factory. I have used it from vert.x 2 to 3.3.2 and did not need to touch it much (except migrating it from vert.x 2 to 3 ). JacpFX is also reacting very fast if you open a PR.

I have also shortly investigated how to merge the VertxUnitRunner and SpringJUnit4ClassRunner but decided it was not really worth the effort since I already had a working test setup.

**Comment by vietj** [comment]
Junit 5 should solve this testing aspect as they cared about mixing runners.

**Comment by draxly** [comment]
I read through some of the source code for spring-vertx-ext and came to the same understanding. It's working nicely for me but I would still prefer to have it as part of the official product if possible. =) But it's good to hear that JacpFX is reacting quickly to PRs.

Will look into Junit 5, sounds promising even though they will reach GA late this year according to their homepage.

**Comment by vietj** [comment]
@draxly you could contribute vertx-unit to spring-vertx-ext and later we retrofit it in vertx-unit with junit 5

**Comment by draxly** [comment]
If I get some spare time I will give it a go or perhaps start testing a bit with junit 5 to see what it will provide.

**Comment by Sergey80** [comment]
i guess it is time

**Comment by vietj** [comment]
@Sergey80 wdym ?

**Comment by Sergey80** [comment]
I mean to provide official vertex support fir spring and junit 5. Say to be able to run unit/integration tests with @ExtendWith to use TestContext.

**Comment by vietj** [comment]
@Sergey80 @jponge is currently investigating junit 5 support for Vert.x, I believe that running with Spring should be one of the requirements

**Comment by jponge** [comment]
Indeed. I'm doing experiments, but I should be soon able to share a prototype.

**Comment by pmlopes** [comment]
junit5 is already supported.
