### ISSUE TITLE
Allow worker threads to wait for event bus replies

### ISSUE THREAD

**Issue by beders** [vert-x3/issues#143]
Worker threads are not able to send/receive event bus messages while they run.
While they can register as a consumer for messages, they can't interact with any other verticle running as receiving replies is asynchronous.

CompletableFuture does not work in this scenario, thus a new blocking runOnEventBus function is proposed.

```
JsonObject result = vertx.runOnEventLoop(future -> { 
    vertx.eventBus().send("thop", cmd, reply -> {
        System.out.println(reply);
        if (reply.succeeded()) {
            JsonObject value = (JsonObject) reply.result().body();
            future.complete(value);
        } else {
            future.completeExceptionally(reply.cause());
        }
    });
});
```

More discussion:
https://github.com/eclipse/vert.x/issues/1386

**Comment by vietj** [comment]
I gave some thoughts at this point, this is actually forbidden because worker concurrency model mandates that at most one thread can execute the worker at the same time.

Multithreaded worker model works with such a case, for instance this works:

```
  @Test
  public void testWorkerWaitForReply(TestContext tc) {
    vertx.eventBus().consumer("the-address", msg -> {
      msg.reply(msg.body());
    });
    Async async = tc.async();
    vertx.deployVerticle(new AbstractVerticle() {
      @Override
      public void start() throws Exception {
        CountDownLatch latch = new CountDownLatch(1);
        vertx.eventBus().send("the-address", "hello", reply -> {
          latch.countDown();
        });
        latch.await(10, TimeUnit.SECONDS);
        async.complete();
      }
    }, new DeploymentOptions().
      setWorker(true).
      setMultiThreaded(true));
  }
```
