### ISSUE TITLE
Improvements to JDBC client

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/issues#145]
- Return all result sets form a statement, currently it only returns the 1st result set
- Add a streaming result set mode, currently the whole RS is converted to JSON in memory (for big amounts of data this can be a performance bottleneck)

**Comment by javadevmtl** [comment]
+1

**Comment by cescoffier** [comment]
@javadevmtl : you you use the thumb up icon in the issue description. It would make gathering the votes way easier. Thanks !

**Comment by pmlopes** [comment]
This has been fixed on sql-common and jdbc-client modules
