### ISSUE TITLE
A vert.x can communicate with multi cluster.

### ISSUE THREAD

**Issue by stream-iori** [vert-x3/issues#146]
Hi
There is a scene in our case, that we have two separate cluster, and themselves do not know each other, but both of them dependency a service which we call it as ServiceC, so C should join the two clusters, this mean that **a Vert.x have to load two cluster.xml** , and startup two verticles for each ClusterManager.

I know that startup two ServiceC for each cluster can solve this problem, but that will spent two times resources, we don't want to do that.

I think that would be good if provide such command in vertx.
 _vertx run MyVerticle --cluster --multi-cluster clusterA.xml clusterB.xml_ 

![image](https://cloud.githubusercontent.com/assets/273171/16871306/c8f69cae-4ab8-11e6-9507-5aeef7350842.png)

**Comment by pmlopes** [comment]
that is the purpose of the tcp bridge:

https://github.com/vert-x3/vertx-tcp-eventbus-bridge

or is thst not enough for your use case?

**Comment by stream-iori** [comment]
We want to full features of cluster not just eventbus, and tcp-eventbus-bridge do not provide load balance, so we hope can use native eventbus :)

**Comment by stream-iori** [comment]
OK, I found i can implements it by embed two vert.x to one Main method
