### ISSUE TITLE
TCP bridge raw event handler, ability to extract SSL client information per message

### ISSUE THREAD

**Issue by cinterloper** [vert-x3/issues#147]
Hello
I think an important security feature with the TCP bridge would be the ability to extract the SSL client connection information (CN etc) from the message at the bridge, and attach it as a header on the message. 

This would facilitate identification of clients, and allow client certificates to be individually treated with different application behavior/privileges/ or revoked when using SSL/TLS client certificate enforcement/auth. 

as a user of the javascript/websocket bridge, i can could see this being accomplished similar to:
http://vertx.io/docs/vertx-web/java/#_handling_event_bus_bridge_events

```
You can also amend the raw message, e.g. change the body. For messages that are flowing in from the client you can also add headers to the message, here’s an example:
```

**Comment by vietj** [comment]
@cinterloper it seems like a fairly straightforward to implement, would you mind to contribute it ?

**Comment by cinterloper** [comment]
looks like it landed, please let me know if any issues arise.

**Comment by pmlopes** [comment]
:+1:
