### ISSUE TITLE
vertx 3.2 multipart form-data client

### ISSUE THREAD

**Issue by rtv2222** [vert-x3/issues#148]
Here is an enhancement request for a vertx-web api for creating a multipart form-data POST http request.

**Comment by pconway11** [comment]
Also interested in this enhancement..
also the ability to use Pump to supply the data

e.g. usecase is a google drive multipart file upload

https://developers.google.com/drive/v3/web/manage-uploads#multipart

Is it feasible to write() the metadata part...then pump data from a client request to a vertx http client?

**Comment by alexlehm** [comment]
Pumping files would require either a input stream that can give its size in advance or support for chunked encoding in the google drive server, both might be possible

**Comment by pmlopes** [comment]
Webclient can handle multi part data:

https://vertx.io/docs/vertx-web-client/java/#_writing_request_bodies
