### ISSUE TITLE
create an Apache Camel bridge

### ISSUE THREAD

**Issue by jstrachan** [vert-x3/issues#15]
thats kinda like the [AMQP bridge](https://github.com/vert-x3/vertx-amqp-service/blob/master/src/main/asciidoc/java/index.adoc) but reuses Apache Camel's 150+ connectors so that vertx folks can use the event bus to talk to any network protocol, back end system, API, database, messaging system or data format etc

Any chance someone from the vertx team can create an empty git repo then we can try submit a PR for it?

**Comment by jstrachan** [comment]
e.g. it looks like we could just trivially map vertx event bus names to camel endpoints like the AMQP bridge:
https://github.com/vert-x3/vertx-amqp-service/blob/master/src/examples/request-reply/request-reply.json#L11

**Comment by davsclaus** [comment]
This is a great idea. I would like to help with this.

**Comment by davsclaus** [comment]
I will be on vacation from mid next week until mid/end august. Will get started on this after the vacation.

**Comment by hekonsek** [comment]
Looking forward to seeing this!

**Comment by vietj** [comment]
@davsclaus any progress on this ?

**Comment by davsclaus** [comment]
I am on PTO till mid next week

**Comment by cescoffier** [comment]
As discussed, postponed this to 3.2.0.

**Comment by cescoffier** [comment]
There is an exiting support here: http://camel.apache.org/vertx.html.

**Comment by jstrachan** [comment]
@cescoffier yeah; I created the first cut of that stuff & grok what it does ;) 

I think the camel bridge inside Vertx is a little different. Rather than using Vertx from inside a Camel route (which is what this does http://camel.apache.org/vertx.html) I raised this issue to be able to reuse camel endpoints from inside Vertx; by using the Vertx event bus. i.e. so Camel appears to Vertx users as just another set of event bus endpoints - like the AMQP bridge

**Comment by cescoffier** [comment]
Oh I see, so definitely something different. Will have a look in 3.3.

**Comment by cescoffier** [comment]
First stab: https://github.com/vert-x3/vertx-camel-bridge/tree/initial-work

**Comment by davsclaus** [comment]
@cescoffier great you got started on this. We can touch base early next week.

**Comment by cescoffier** [comment]
PR merged. Integration in the vert.x stack in progress...

**Comment by cescoffier** [comment]
Everything done. Ready to be part of 3.3.0.

**Comment by vietj** [comment]
:+1:

**Comment by jstrachan** [comment]
Awesome!
