### ISSUE TITLE
Checking Json type feature

### ISSUE THREAD

**Issue by EmadAlblueshi** [vert-x3/issues#155]
I think it would be nice to have a checking **boolean** function for **JSON** type either in **io.vertx.ext.web.RoutingContext** or in **io.vertx.core.json.Json** here you are an example 

``` javascript

RoutingContext.isBodyAsJsonObject()
RoutingContext.isBodyAsJsonArray()

//or

Json.isObject(String body)
Json.isArray(String body)

```

Thanks

**Comment by pmlopes** [comment]
I guess this could be extended to a utility class like javascript has:

``` js
JSON.parse(string);
JSON.stringify(map); /* or */ JSON.stringify(list);
```

**Comment by EmadAlblueshi** [comment]
@pmlopes Maybe in `io.vertx.core.json.Json` as a static method

**Comment by EmadAlblueshi** [comment]
Vert.x now supports this feature by simply using `Object json = Json.decodeValue("{}");`
