### ISSUE TITLE
Add ability to add a retries header variable at send options

### ISSUE THREAD

**Issue by guidomedina** [vert-x3/issues#161]
There isn't a retry mechanism and the only possible solution right now is to recursively make a method with a counter, if the reply times out for example, you would call the same method just like in the following post:

https://groups.google.com/forum/#!topic/vertx/xOQAJeul05k

I wonder if there is a way to automatically have Vert.x retry if a header parameter was set to do so when a message was not replied _-only in the case a reply handler is set-_, such `retries` variable could be a message header variable.

Not sure if adding a default `retries` to be something like 3 would be any wise.

**Comment by guidomedina** [comment]
It adds a complexity aspect as now if a message fails you would want to do something like:

`message.retryIfRetriesLeft()`

which will basically retry only if such message has retries left.

**Comment by guidomedina** [comment]
Maybe there is no need to call nothing explicitly because you could easily mark the message as done within the fail block, otherwise retry if you didn't.

**Comment by vietj** [comment]
@guidomedina can we close this issue ?

**Comment by guidomedina** [comment]
Ah, sure though it would be a nice to have in the future.
