### ISSUE TITLE
Vert.x Commons module

### ISSUE THREAD

**Issue by aschrijver** [vert-x3/issues#164]
There are so many small, but great code snippets and utility classes around in the existing standard modules, and out 'in the wild' in various community projects.
A lot of this is really useful, and reusable functionality (or could easily be made reusable), but will never be included in `vertx-core` (understandably, to keep it lean and mean). Also in `vertx-core` there is probably code that is now internal, but would be useful to the broader public.

For this reason I propose having a `vertx-commons` standard module. In other words "_the `Guava` library, but then for Vert.x_".

Because many people in the community already have candidate stuff to include, there would be (I think) a very low barrier to contribute to the project (copy + paste + PR + refine + approve + release).

Note this project, which has a similar goal: https://github.com/jtruelove/vertx-util
And the example of people creating duplicate classes for the same functionality (see referenced issue on `Action<T>`).

**Comment by aschrijver** [comment]
And even better would be not to have one `vertx-common` with loads of transitive dependencies but a separate section in the modules pages for multiple smaller modules, like:
- `common-async`
- `common-eventbus`
- `common-json`
- `common-clustering`
- ...

**Comment by aschrijver** [comment]
Also be great would be if some of these modules had no dependency on core (see also discussion on `io.vertx.common.json.JsonObject` in https://github.com/vert-x3/issues/issues/166).

As mentioned this can be a great marketing opportunity for Vert.x. Many non-Vert.x projects could benefit e.g. the `vertx-async` library or `vertx-streams` or what have you.

Developers at the coffee machine would say: "Man, are you really still using Guava for that. That's some heavy sh*t you've got going on there. Why don't you take something light, like Vert.x commons?" :wink: )

**Comment by vietj** [comment]
@aschrijver there is an existing vertx-async libarry existing in the ecosystem I find quite good (yet not polyglot but the author said he's working on it), have you looked at it ?

**Comment by aschrijver** [comment]
Yes I've seen it but not yet tried. Thanks. The library names are more examples. Can be anything. Its more about the concept of collecting the real useful stuff in comprehensive modules within the toolkit rather than having them hang around (unnoticed by others) in the codebase of larger projects.

**Comment by gchauvet** [comment]
@vietj I was busy with my new job. I will publish vertx-async polyglot support ASAP.

**Comment by vietj** [comment]
@gchauvet with Vert.x 3.3.3 that was just released :-)

**Comment by pmlopes** [comment]
vertx projects can either be listed in the awesome project or proposed to the reactiverse.io org.
