### ISSUE TITLE
Move JsonObject from vertx-core to its own library

### ISSUE THREAD

**Issue by aschrijver** [vert-x3/issues#166]
I like `JsonObject`. It is simple, intuitive, very light-weight and is widely used by the entire Vert.x community. I have seen examples of Vert.x projects that only depend `JsonObject` and therefore require the one dependency on `vertx-core`.

While these projects could potentially be valuable to a much broader audience this vertx-core dependency adds way too much overhead for it to be interesting to them.
It would be great having a separate small `vertx-json` library, that is used by core, but also stands on its own.

I also have 2 of these kinds of projects coming up (near future): [vertx-graphql-json-marshaller](https://github.com/engagingspaces) (to marshal/unmarshal GraphQL schema's to JSON) and [vertx-jwt-codec](https://github.com/engagingspaces) (a more versatile and less opinionated JWT module).

From a marketing perspective: JSON is so widely used these days, that `vertx-json` could have many users as well. A good way to attract new users to the rest of toolkit!

**Comment by pmlopes** [comment]
In order to do this first we need to transform jsonobject/jsonarray into interfaces so we can replace implementations at runtime first.

**Comment by aschrijver** [comment]
Can't it just be pulled in by default in `vertx-core` as a 'system' dependency, so nothing effectively changes on that end? Like codegen and docgen, but not optional.

**Comment by pmlopes** [comment]
how would you define a contract for different implementations?

**Comment by aschrijver** [comment]
Ah, you meant its needed for polyglot support reasons.

**Comment by pmlopes** [comment]
no, i mean, say that we have:

io.vertx.json.JsonObject is provided by `vertx-json.jar` we then reference the class form `vertx-core.jar` if now you want to replace `vertx-json.jar` with `myown-json.jar` you can't break the contact otherwise the JVM will fail to run with `ClassNotFound`, `LinkageException`, etc...

We need to have a base contract usually in java it is a interface. So if we have a `JsonObject` interface then we can replace jars and as long the implementations are correct they should not affect the runtime.

**Comment by vietj** [comment]
Java 9 modules don't allow the same package name to span on two modules, the `io.vertx.core` package would span on 2 difference modules, how do you solve that ?

Concerning @pmlopes suggestion about making JsonObject an interface, `new JsonObject()` would not compile.

**Comment by pmlopes** [comment]
I'd even say that the default/fallback impl should remain on core since it is a runtime requirement to have always 1 impl present unlike the cluster managers which are not really required to be present to run an application.

**Comment by aschrijver** [comment]
So there would be 2 libraries. One with the api which is also referenced by core impl. classes and one lib with the separated implementation classes.

**Comment by vietj** [comment]
@pmlopes doesn't this imply to replace all occurences of `io.vertx.core.json.JsonObject` by `io.vertx.json.JsonObject` in method signatures ?

**Comment by pmlopes** [comment]
i was typing out of my head, the signature should remain the same but as you pointed out this would be a breaking change since one cannot instantiate a interface the `new JsonObject()` will break

**Comment by aschrijver** [comment]
Changing the package location is a cleaner solution, but also a much bigger break than just replacing some instantiation lines on a 3.4.0 migration. The first would be more of a 4.x kind of thing, I could imagine, and timely `@deprecated` markings in upcoming release, etc.

BTW in 4.x the package would better be `io.vertx.common.json.JsonObject` according to idea explained in https://github.com/vert-x3/issues/issues/164

**Comment by aschrijver** [comment]
For my understanding: If `JsonObject` was moved as-is to its own library with codegen support, with package name unchanged, and pulled in as dependency in core, then there would be no issue, right (other than having small part of core package live in its own jar)? Or are there more things at play?

**Comment by pmlopes** [comment]
the constructor would break all the things. Even if we would rename the class to an interface and keep it on the same package, all code like:

``` java
new JsonObject()
```

Would break since you can't instantiate an interface. You would need something like:

``` java
JavaObject.create()
```

**Comment by aschrijver** [comment]
Yes sure, that's what I described, but that is not as big a break as changing the package name. It should be easy to migrate to.

**Comment by pmlopes** [comment]
Regarding #164 we should be careful since this would become a circular dependency:

`core` > **depends on** > `common` > **depends on** > `core`

**Comment by aschrijver** [comment]
But it would be an either / or thing: either not using core, and core may include you, or depend on core and that's it.

**Comment by pmlopes** [comment]
This would be a big break imo since i can expect that all existing modules would break. Just grep for `new JsonObject` in any vert.x related project and if there is 1 occurrence it means that it won't work out of the box on the "next" release.

**Comment by aschrijver** [comment]
And my other suggestion of ripping it out as-is, and with separate codegen/docgen support? No package renaming.

Regarding circular dependency: I added suggestion to break into separate topic-specific common modules. Some may use core, others may not. Having as single commons module would mean it would get a lot of transitive dependencies and less attractive to include.

**Comment by vietj** [comment]
@aschrijver it would cause problem with Java 9 modules because you cannot have the same package name spanning over two different modules (`io.vertx.core`).

**Comment by aschrijver** [comment]
Ah. That's a pity. So it would be either a breaking change or leave as it is now..

**Comment by aschrijver** [comment]
Looking through new Java 9 features I see it will also have a light-weight JSON API in `java.util`. So seems a better idea to investigate its usability as a replacement. That will also be breaking, but makes a lot more sense.

**Comment by pmlopes** [comment]
@aschrijver i think it got dropped from JDK9:

http://mail.openjdk.java.net/pipermail/jdk9-dev/2014-December/001670.html

I haven't followed up it latelly.

**Comment by aschrijver** [comment]
Yes it seems so. I found this: https://jaxenter.com/json-api-dropped-java-9-113028.html
Many recent feature lists still have it as a bullet point (maybe because don't want to make it even less attractive).

**Comment by aschrijver** [comment]
When traversing back the discussion up to https://github.com/vert-x3/issues/issues/166#issuecomment-236557128 if you have:
- a `io.vertx:vertx-common-json:3.4.0` module with
  - separate API `vertx-common-json-api` with interfaces
    - `io.vertx.common.json.api.JsonObject`
    - `io.vertx.common.json.api.JsonArray`
  - an implementation of the interfaces is provided in `vertx-common-json-impl`
    - dependency on `jackson` (can be removed from core 4.x onwards. unopinionated +=1!)
    - PS a nice, maybe more fitting alternative to jackson for Vert.x would be [`jackson-jr`](https://github.com/FasterXML/jackson-jr)
- in `vertx-core` 3.4:
  - take a dependency on `vertx-common-json-api`
  - `JsonObject` and `JsonArray` remain as is, but implement the new interfaces
  - All standard modules use interface method signature, but still use default implementation in core so `new JsonObject()` keeps working

In a Vert.x 4.0 release there can be a switch to the new module entirely.
But the barrier to accept the breaking changes this causes can be very much lowered, I think, if the replacement json library has been allowed to evolve on the 3.x line with some attractive new features to make it a more reactive stream-based json that fits even better with Vert.x concepts 

(Not really reactive, but an example of such extension I proposed in https://github.com/vert-x3/issues/issues/167).

**Comment by EmadAlblueshi** [comment]
@aschrijver @pmlopes @vietj 

Kindly take a look at [json-b.net](http://json-b.net)

**Comment by aschrijver** [comment]
@EmadAlblueshi it looks nice on first glance, but what is your proposal with regards to vert.x and your project?

**Comment by EmadAlblueshi** [comment]
@aschrijver I'm thinking out loud if we can utilize it in the future. It looks simpler than jackson.

**Comment by pmlopes** [comment]
just a note: i just looked at the json-b pom and it seems to pull a couple of packages from javaee and CDI which will be big and brings lots of unnecessary code i guess (i did not try it, so i could be totally wrong here).

**Comment by EmadAlblueshi** [comment]
@pmlopes true

**Comment by pmlopes** [comment]
This could be revived for 4.x but for now we can do it since it would break pretty much all existing code.

**Comment by cescoffier** [comment]
Marked it as `wontfix` - understand `won't fix for now`
