### ISSUE TITLE
Consider switch to lightweight jackson-jr for JsonObject implementation

### ISSUE THREAD

**Issue by aschrijver** [vert-x3/issues#169]
Given Vert.x focus to being lean and mean a switch from jackson-databind to [jackson-jr](https://github.com/FasterXML/jackson-jr) also from FasterXML might be worthwhile to consider.

Maybe in combination with #166 and #167

**Comment by pmlopes** [comment]
How would this work with something like: https://github.com/eclipse/vert.x/pull/1274

**Comment by aschrijver** [comment]
There is no module support in jackson-jr. It is explicitly a feature minus version of jackson-databind.
So while it can fit current JsonObject implementation, it doesn't fit this PR.

The `registerModule` addition would be quite valuable. You can handle advanced serialization cases with it, like serializing bi-directional relationships, recursion, etc.

So a switch now does not seem the best choice. If going for #166 Vert.x could have the lean Jr. implementation by default and a full Jackson plug-in alternative.

BTW, if honoring this PR that would also not be possible, as you'll have forever bound vert.x core to jackson-databind by exposing it on the API of core. Maybe it is best to first decide on a strategy for #166 and #164 before deciding to merge this.

Note that an alternative to this would be having a jackson module for Vert.x that serializes to `JsonObject`. Such a thing already exists in [jackson-datatype-vertx](https://github.com/Crunc/jackson-datatype-vertx) (haven't checked it, not fully up-to-date). This separate module approach might be better than exposing jackson objects on vertx-core API.

**Comment by apatrida** [comment]
This would be trouble for things like Kotlin which require a module.  Jackson-jr support for Kotlin is possible, but was a fair amount of work when I last looked at starting it, involving a PR to jr and then the ability to plugin something to take over metadata management and creating objects.

**Comment by aschrijver** [comment]
Yes, I agree. The jr thing is not a good idea. It might be a separate json implementation, together with https://github.com/vert-x3/issues/issues/166#issuecomment-236839646

**Comment by vietj** [comment]
`io.vertx.core.json.Json` exposes the Jackson API:

```
  public static <T> T decodeValue(String str, Class<T> clazz) throws DecodeException {
    try {
      return mapper.readValue(str, clazz);
    }
    catch (Exception e) {
      throw new DecodeException("Failed to decode:" + e.getMessage());
    }
  }
```

**Comment by pmlopes** [comment]
the `decode` API calls are also supported by jackson-jr from the documentation the only thing I haven't saw yet was if we could register custom encoders that we need for `JsonObject`/`JsonArray`

**Comment by pmlopes** [comment]
I've looked at the API and this would be possible to implement keeping the existing API **but** it would require that `JsonObject` would implement a `Map` interface and `JsonArray` a `List` interface since jackson-jr does not have the concept of custom serializers.

Also it would introduce a small functional change by not allowing `C` style comments in JSON (which by the way are not supposed to be allowed but we do have enabled by default.

So if we would like to reduce the jar footprint and simplify the interop of JsonObject/JsonArray with say groovy/js this could be a interesting feature otherwise I'm not sure if it is worth the work without breaking what we already have.

**Comment by vietj** [comment]
in short it can be resumed as : "is it worth to break the API for 1mb" ?

**Comment by pmlopes** [comment]
yes that and _maybe_ simplify the usage of JsonObject/JsonArray across languages

**Comment by pmlopes** [comment]
Since this would be a big breaking change (we would remove the jackson mapper (which is public at the moment) this feature will not be implemented. It could be revived for a 4.x cycle.
