### ISSUE TITLE
Creating MongoClient using CreateShared(..) is time/performance issue...

### ISSUE THREAD

**Issue by shaunak-kastar** [vert-x3/issues#170]
When I deploy verticle at that point of time I create MongoClient using CreateShared(...) method and on a REST call I have first app life cycle call to mongo db... At this moment of time It is really taking a very lot of time compared to the mongo calls made after 1st call...
Is this a bug or there is some reason behind it?

Another thing is that CreateShared() method returns async way a MongoClient object wihtout setting up a complete mongo connection...
So in that case at least a handler parameter should be provided to get success or failure acknowledgement of mongo connection.

As vert.x provides abstraction layers over many things so I dont wanna use the native implementation coz vert.x provides a proper implementation with its own context management.

So should I go with Vert.x Mongo or Mongo Java Async API ?????
I am not preferable to use JDBC client for mongo atleast.

So please do help me out with this ASAP....

Thank you!!!!!

**Comment by pmlopes** [comment]
This has been asked in the forum:

https://groups.google.com/forum/#!topic/vertx/7rAqhCf704Y
