### ISSUE TITLE
Make mysql/postgresql async client official module

### ISSUE THREAD

**Issue by beatdigit** [vert-x3/issues#171]
Currently http://vertx.io/docs/vertx-mysql-postgresql-client/java/ is still under technical preview, it would be great to make it official module as JDBC client.

Also on https://www.techempower.com/benchmarks/, the benchmark code is still using JDBC client, which is slow. Better to update it with async client.

I think DB operation is very common and by showing vertx's performance in this cases, it would benefit lots of people.

Thanks!

**Comment by vietj** [comment]
+1 for making it an official module, we need to define the missing features in this module because I believe it is missing some

Instead of having this issue here, could you instead create an issue in https://github.com/vert-x3/issues/issues/ with a whishlist tag ?

**Comment by pmlopes** [comment]
@beatdigit just for reference, the latest techempower git code is built on the async driver.

**Comment by AdamMcM** [comment]
+1 I think this is important
