### ISSUE TITLE
Javaslang integration?

### ISSUE THREAD

**Issue by aschrijver** [vert-x3/issues#173]
This is not directly a wish-list item for Vert.x, but an idea to consider.

Vert.x core and other modules contains ever more nice classes and code snippets to help create powerful, yet still easy to understand, reactive and asynchronous logic.
There are suggestions on this list to add more common modules with helpers, utilities, etc. in future versions.

But this code builds mostly on 'plain' Java 8. There will be 'reinvention of the wheel' to create the basic language constructs that Java 8 should have, but is still missing.
Especially to get the most out of lambda's and functional programming there are some very clean, lightweight libraries around, that could be of great benefit as a core dependency.

One example (but there may be other good candidates as well) is Javaslang:
- [javaslang.io](http://www.javaslang.io/) ([docs](http://www.javaslang.io/javaslang-docs/))
- https://github.com/javaslang/javaslang

It uses plain Java 8, no other dependencies and offers a wide range of functional code constructs.

**Comment by pmlopes** [comment]
@aschrijver shouldn't this be then asked on javaslang project instead? Alternatively I'd say create small projects and list them on the awesome list.

A simple jar with a couple of classes without 3rd party dependencies should be ok, If you look for example at npmjs, many libraries there are just that. Utilities.

**Comment by aschrijver** [comment]
Yes. That will do fine. Thanks, I'll close this one.
