### ISSUE TITLE
dynamically sized worker pool - wish of new feature

### ISSUE THREAD

**Issue by AdamMcM** [vert-x3/issues#174]
We can set the number of worker threads, but it would also be nice to set a start/max number of threads.  Perhaps specifying a start size for the pool and a max size.  If all workers are busy, create a new worker thread and add to the pool, up to a max size.

One could also imagine pool that could decrease in size, but I am not sure if that is necessary.

**Comment by leolux** [comment]
I think to remember that the default pool size is the number of CPU cores times 2 which seems to be reasonable for unblocking code. But for worker threads the dynamically sized worker pool makes sense to me, especially if you have more long running tasks to be executed than the number of worker threads. So I like the idea.

:+1:

**Comment by vietj** [comment]
It is possible to set the size of the worker pool size using VertxOptions (or the CLI).

How is that different ?

**Comment by leolux** [comment]
Btw, what happens at the moment when all worker threads are busy and another blocking code gets triggered?

**Comment by leolux** [comment]
The current API for setWorkserPoolSize says: "Set the maximum number of worker threads to be used by the Vert.x instance". So the worker thread pool seems to be dynamic already^^

**Comment by vietj** [comment]
@leolux there will always be a max size whatsoever.

If all worker threads are busy, it means you have a problem that is either you have a wrong initial max size or what triggers the worker execution happens too often (i.e if it's an http server, then it means you handle more requests than you can).

**Comment by leolux** [comment]
I agree. Physical resource limits cannot be outrun by a high number of threads. So the question every software architect has to consider is how to handle high traffic load without wasting too many resources. I think this discussion would lead to the art of modern software design :)

**Comment by AdamMcM** [comment]
Yes, you can set the limit of max threads already.  But, vertx does something that  bit unexpected.  The first time you call executeBlocking it creates/uses thread: vert.x-worker-thread-1.  Then the next time it creates (or uses) another thread: vert.x-worker-thread-2.  I would expect that vert.x-worker-thread-1 would be reused, and vert.x-worker-thread-2 would only be created if vert.x-worker-thread-1 were in use. 

 This way it only creates threads as necessary.  Currently, it seems to create/use threads in a round robin fashion (up until the max) regardless if any of the threads are busy.

I don't think this is a ig deal, but it seems that one of the major goals of vertx is to limit the number of OS threads.  This seems like a sensible place to do just that.

**Comment by vietj** [comment]
@AdamMcM there is this open issue https://github.com/eclipse/vert.x/issues/1539 that would allow to provide an SPI for executor service for worker threads, this sound more like what you want to achieve ?

**Comment by AdamMcM** [comment]
an allowing to pass an executor service might work fine.  Thanks for pointing out this option

**Comment by mhstnsc** [comment]
I backup @AdamMcM .
I currently had a performance issue with our app which had too many threads configured and then java took too much overhead to do the youngen collection. 

It would be good to pass a max but vertx should create a new thread only if were actually needed. This way i don't have to keep testing and optimizing.
