### ISSUE TITLE
Cluster manager based on Apache Ignite

### ISSUE THREAD

**Issue by agura** [vert-x3/issues#18]
I want to implement cluster manager based on Apache Ignite. As I can see, Hazelcast-based cluster manager has separate repository. So I have questions: Where I have to start my work? Can anybody create new repository (vertx-ignite)?

**Comment by pmlopes** [comment]
Hello @agura I would suggest you first to create it on your local account and once you have it complete then share it with the community.

I would suggest that you look at hazelcast and the other implementation for the project structure.

Once you're ready follow the standard procedure: https://github.com/vert-x3/wiki/wiki/How-to-contribute-to-Vert.x

**Comment by purplefox** [comment]
Hi Agura!

An apache ignite cluster manager looks like a great idea.

The projects under the vert-x3 organisation are usually projects that are in the official stack or ones we are working so they get in the official stack soon.

As Paulo says, I'd recommend you work on your implementation in your own repository and share with the community.

Also, don't forget to add a link to it in vertx-awesome :)

https://github.com/vert-x3/vertx-awesome

**Comment by agura** [comment]
@pmlopes, @purplefox,

thanks for answers and advices.

I created repository on my account: [vertx-ignite](https://github.com/agura/vertx-ignite)
