### ISSUE TITLE
Add Future method to interface of Vertx

### ISSUE THREAD

**Issue by stream-iori** [vert-x3/issues#180]
Shall we add some future method to Vertx's interface?

eg: 

``` java

void deployVerticle(Verticle verticle);

void deployVerticle(Verticle verticle, Handler<AsyncResult<String>> completionHandler);

//we can make a new API
Future<Void> deployVerticleByFuture(Verticle verticle);

```

**Comment by tsegismont** [comment]
Just in case you didn't know, this can get you a future for deployment:

Future deployFuture = Future.future();
vertx.deployVerticle(verticle, deployFuture.completer());
// now compose or do whatever you want with the future

2016-08-25 10:21 GMT+02:00 Stream notifications@github.com:

**Comment by stream-iori** [comment]
Wow, it can work, i am not look into the Future :)

**Comment by vietj** [comment]
Vert.x uses callback style and not promise style as design for async.

As shown @tsegismont it can be easy to turn an async callback style into a future style.
