### ISSUE TITLE
Message codec for NetServer

### ISSUE THREAD

**Issue by martin-robo** [vert-x3/issues#183]
Codec support for NetServer to handle more than Buffer directly. MessageCodec<S,R> of event bus could be set to an instance of NetServer to easily support arbitrary network protocols.

**Comment by pmlopes** [comment]
Could you give some examples of such codec?

**Comment by vietj** [comment]
@ppatierno maybe it could fit the needs of MQTT server to simplify it a bit ? WDYT ?

**Comment by martin-robo** [comment]
Well, I am the developer of a Java server that has to support a lot of binary network communication protocols. One example is IEC 60870-5-104, but there are a lot more. I need to read and write network bytes at a low level with high comfort. Netty codecs were/are just perfect here. If I could get this with vert-x I would be really happy.

**Comment by vietj** [comment]
I agree the use case is interesting and related to MQTT server case we have at the moment.
Being able to customize a `NetServer` means that it would benefit from the `NetServer` features (TLS, Proxy, TLS upgrade, scaling) and reuse existing Netty handlers like mqtt-codec.

Again the benefit is in _reuse_, otherwise Vert.x could be used fine for building it from scratch.

**Comment by vietj** [comment]
@martin-robo are there existing Netty handlers you are considering reusing or will you write yours ?

**Comment by martin-robo** [comment]
I have written multiple own handlers using Netty's ReplayingDecoder for example.

**Comment by ppatierno** [comment]
Yes I agree with that. Today the MQTT server creates the pipeline in its own ServerBootstrap adding the MQTT encoder/decoder from Netty. Having that from the NetServer could be useful for simplifying the code.

**Comment by tsegismont** [comment]
Please consider adding this feature to Datagram servers as well.

**Comment by vietj** [comment]
@tsegismont which UDP based protocols do you have in mind ?

**Comment by ppatierno** [comment]
@vietj  @tsegismont  I have CoAP in mind :-)

**Comment by vietj** [comment]
makes sense

**Comment by martin-robo** [comment]
I'd also need UDP support but again for a rather special channel encoding standard. FYI: German security standard [BSI TR-03109](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03109/TR03109-1.pdf?__blob=publicationFile&v=1). This is also where I would need it as UDP client. 

@pmlopes  @vietj Maybe general support of codecs throughout all vert.x servers and clients would be perfect.

**Comment by vietj** [comment]
@martin-robo you mean TCP/UDP right ?

so these servers could not expose the NetSocket API but instead provide their own API that expose the protocol to the application ?

I'm still trying to figure out a simple way to do that.

**Comment by martin-robo** [comment]
@vietj Yes, I mean TCP/UDP.

**Comment by tsegismont** [comment]
@vietj what I'm not sure about is if using MessageCodec on Vert.x
Net/Datagram servers is better than integrating deeper with Netty like here
https://github.com/vietj/vertx-materials/blob/master/src/main/asciidoc/output/Integrating_Netty.adoc

2016-10-23 11:31 GMT+02:00 Julien Viet notifications@github.com:

**Comment by tsegismont** [comment]
collectd's network protocol

2016-10-21 14:01 GMT+02:00 Julien Viet notifications@github.com:

**Comment by vietj** [comment]
both are I think interesting.

with extending, you gain a few features for free:
- SSL support
- SSL upgrade
- proxy support for client
- scalability model

if you think about it, the Net server/client provide just that with no other protocols, then it's just about plugging protocols with a dispatch API.

**Comment by vietj** [comment]
I think also we do not have to do everything at once, but starting little with mqttserver from NetServer is a good start to see how it goes.

I believe acutally this integration should rather remain internal to vertx because harder to support. And the content of the "integrating netty" doc still applies and is very valid in this case.

**Comment by tsegismont** [comment]
Got you

2016-10-25 21:38 GMT+02:00 Julien Viet notifications@github.com:

**Comment by EmadAlblueshi** [comment]
+1

**Comment by vietj** [comment]
Actually now we support to reuse the NetServer stuff with the NetServerBase, it's a bit internal but it works. So we support it enough to enable building on it, it will improve over the time hopefully.
