### ISSUE TITLE
Include the vertx-configuration-service in Vert.x

### ISSUE THREAD

**Issue by asmirnov77** [vert-x3/issues#185]
Hi,

We are using https://github.com/cescoffier/vertx-configuration-service and it works like a charm. It simplifies the configuration process, it's flexible and support very well with our configuration process. 

Can this project be included in Vert.x 3.3.3 or Vert.x 3.4.0 ? I believe, it would be useful for many users.

**Comment by cescoffier** [comment]
A discussion has been started here: https://groups.google.com/forum/#!topic/vertx-dev/PAi1c5U_b-0

**Comment by pmlopes** [comment]
This has been merged: https://github.com/vert-x3/vertx-configuration
