### ISSUE TITLE
Add optional argument to Router.blockingHandler to call setEnableMultipart(true)

### ISSUE THREAD

**Issue by InfoSec812** [vert-x3/issues#186]
Currently, to use multipart POST submissions with blockingHandler(), you have to do something like:

```
router.post("/post/path").handler(ctx -> ctx.setEnableMultipart(true).next()).blockingHandler(this::blockingHandler)
```

It would be great if we could have an optional parameter like:

```
router.post("/post/path").blockingHandler(this::blockingHandler, false, true);
```

Such that we continue to disable parallel processing of blocking handlers, but allow the option to handle multipart form data. There is already a overloaded instance of Router.blockingHandler() for enabling parallel processing. This proposal would add a new overloaded method to enable multipart form data capabilities.

**Comment by pmlopes** [comment]
Issue moved to [vert-x3/vertx-web #586](https://github.com/vert-x3/vertx-web/issues/586) via [**ZenHub**](https://www.zenhub.com/)
