### ISSUE TITLE
Support UNIX Domain Sockets in HttpClient/HttpServer/NetSocketClient/NetSocketServer

### ISSUE THREAD

**Issue by InfoSec812** [vert-x3/issues#188]
Netty already supports DomainSockets/DomainChannels, so I was hoping it might be possible to implement support (via HttpOptions/SocketOptions) to support UNIX Domain sockets (AF_UNIX)??? We do this quite often for secured APIs across docker containers. We mount the socket file as a volume in the container and then the different applications communicate via the UNIX Domain socket. We have also taken to communicating with the Docker daemon itself in this manner instead of exposing the Docker HTTP API.

**Comment by vietj** [comment]
please open an issue in Vert.x Core for this.

**Comment by pmlopes** [comment]
Fixed in core.
