### ISSUE TITLE
Enhance io.vertx.core.CompositeFuture

### ISSUE THREAD

**Issue by cazacugmihai** [vert-x3/issues#192]
Hi,

Can you extract [Chain.java](https://github.com/cescoffier/vertx-microservices-workshop/blob/0f34db195d55082fe27582dcf04aeaebb9b916a0/vertx-workshop-common/src/main/java/io/vertx/workshop/common/Chain.java)'s methods into io.vertx.core.CompositeFuture? It is a very common way to run sequential features and I think that many of us use a kind of the same utility class (instead of writing something like [Sequential composition](http://vertx.io/docs/vertx-core/java/#_sequential_composition)).

Thanks,
Mihai

P. S. It is related to https://github.com/cescoffier/vertx-microservices-workshop/issues/9

**Comment by cazacugmihai** [comment]
+1

**Comment by lu-ko** [comment]
+1

**Comment by cazacugmihai** [comment]
Is there some activity on this?

**Comment by vietj** [comment]
we might revisit the attempt to have CompletableFuture or CompletionStage in Vert.x after 3.5.1 so we would rather focus on this instead
