### ISSUE TITLE
Vert.x Doesn't Support Chinese Routing Path

### ISSUE THREAD

**Issue by WangyuHello** [vert-x3/issues#195]
I simply set router.route("/哈哈"),  and I tested it,it didn't work. Also I let Server response a string like "你好",I got a clobber.

**Comment by pmlopes** [comment]
The route match is done using regular expressions and intl support is not on by default. Regarding the response are you returning the content-encoding? by default everything should be UTF-8 if you're using something else you might need to adjust it.

**Comment by WangyuHello** [comment]
How could I turn on intl support?
After setting response encoding, it works fine(๑>؂<๑）

On Sep 17, 2016 6:45 PM, Paulo Lopes notifications@github.com wrote:

The route match is done using regular expressions and intl support is not on by default. Regarding the response are you returning the content-encoding? by default everything should be UTF-8 if you're using something else you might need to adjust it.

**Comment by pmlopes** [comment]
The regex into support needs to be changed on code but it brings a performance penalty so we need to investigate how to do it correctly.

**Comment by WangyuHello** [comment]
I have solved the problem by URLEncoding my path string.
Thanks a lot!٩( 'ω' )و

**Comment by pmlopes** [comment]
According to the RFC http://www.ietf.org/rfc/rfc2396.txt the protocol does not allow non ASCII characters in the request and they should be url encoded if you do not want to loose their correct value. So the current behaviour is correct.
