### ISSUE TITLE
Support time-based scheduler

### ISSUE THREAD

**Issue by EmadAlblueshi** [vert-x3/issues#196]
I wish that vert.x ecosystem has a time-based scheduler for complicated tasks because one-shot timers and periodic timers are very limited.

Thanks

**Comment by tsegismont** [comment]
Can you elaborate on the minimal features you would need?

**Comment by EmadAlblueshi** [comment]
@tsegismont Hi, something like [Cron](https://en.wikipedia.org/wiki/Cron) but in vert.x way of course.

**Comment by tsegismont** [comment]
As a workaround, if you're programming in Java, you could use [cron4j](http://www.sauronsoftware.it/projects/cron4j/). Just beware of the thread executing the task (use either _runOnContext_ or the event bus to go back to Vert.x world).

**Comment by vietj** [comment]
there is https://github.com/diabolicallabs/vertx-cron

**Comment by EmadAlblueshi** [comment]
@tsegismont @vietj Thanks for immediate response. I'm going to see your recommendations and such a feature would be great :+1:

**Comment by vietj** [comment]
@EmadAlblueshi have you checked the vertx-cron project ?

**Comment by EmadAlblueshi** [comment]
@vietj yes, It does the job but I'm not sure if it's polyglot

**Comment by vietj** [comment]
@EmadAlblueshi it could be contributed to the project instead - you should get in touch with the project owner

**Comment by EmadAlblueshi** [comment]
@vietj ok thanks
