### ISSUE TITLE
Problem with trailing slashes in http routes containing a parameter

### ISSUE THREAD

**Issue by jbreich** [vert-x3/issues#198]
It seems that using a parameter in a route path prevents from using trailing slashes on the network

You can reproduce with the following code

``` java
public void handle(RoutingContext context) {
    context.response().setStatusCode(200).end("ok");
}

public void start() {
    Vertx vertx = Vertx.vertx();
    Router router = Router.router(vertx);
    router.route(HttpMethod.GET, "/test1")
              .handler(this::handle);
    router.route(HttpMethod.GET, "/test1/:id")
              .handler(this::handle);
    router.route(HttpMethod.GET, "/test1/:id/test2")
              .handler(this::handle);

    vertx.createHttpServer()
             .requestHandler(router::accept)
             .listen(8080);
}
```

I get the following results when accessing the server with a GET request:
- /test1 ==> OK
- /test1/ ==> OK
- /test1// ==> OK
- /test1/id ==> OK
- /test1/id/ ==> **Failed**
- /test1/id// ==> **Failed**
- /test1/id/test2 ==> OK
- /test1/id/test2/ ==> **Failed**
- /test1/id/test2// ==> **Failed**

**Comment by pmlopes** [comment]
once you add a trailing slash you're referring to a different HTTP resource so the results you're having are correct. To better understand the behaviour you could see the spec or maybe something more understandable as this google webmaster platform blog post: https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html

**Comment by jbreich** [comment]
From what I understand it is normal to accept trailing slashes which is exactly my point. I would like to be consistent and accept trailing slashes everytime. My problem is that they are accepted when registering an exact path ("/test1") but not when using a parameter ("/test1/:id"). I just want to have a consistent behavior between the two cases. From what I understand from the Vert.X documentation trailing slashes should be accepted:
http://vertx.io/docs/vertx-web/js/#_routing_by_exact_path

**Comment by pmlopes** [comment]
Issue moved to [vert-x3/vertx-web #498](https://github.com/vert-x3/vertx-web/issues/498) via [**ZenHub**](https://www.zenhub.com/)

**Comment by cescoffier** [comment]
Issue marked as invalid because it has been moved to the right project
