### ISSUE TITLE
FR:  response.sendFilePartial

### ISSUE THREAD

**Issue by omidp** [vert-x3/issues#200]
it would be great if vert.x supports partial file streaming. there is an implementation here as an example 

[MultipartFileSender](https://gist.github.com/omidp/eef5d2907e0d5f8733cf8bbec0cf62be)

**Comment by tsegismont** [comment]
You can send part of the file. See
http://vertx.io/docs/apidocs/io/vertx/core/http/HttpServerResponse.html#sendFile-java.lang.String-long-long-io.vertx.core.Handler-

You have to manually manage the headers for content range though. Vert.x
Web does that for you with static resources.

2016-10-03 14:51 GMT+02:00 Omid Pourhadi notifications@github.com:

**Comment by omidp** [comment]
Thank you for your answer. 

actually I tried it and get 

`
    java.lang.IllegalStateException: Head already written
        at io.vertx.core.http.impl.HttpServerResponseImpl.doSendFile(HttpServerResponseImpl.java:436)`

 [here](https://groups.google.com/forum/#!topic/vertx/eLPHyTRU0UQ) I explained in more detail

**Comment by pmlopes** [comment]
This is a question not an issue. As Thomas wrote vertx-web does implement partial content streaming with the static handler. Follow the question on the forum.

**Comment by omidp** [comment]
@pmlopes based on [this topic](https://groups.google.com/forum/#!topic/vertx/duFVIcSR0zg) on the forum

> If you have an idea/feature/fix you would like to see in Vert.x add it to https://github.com/vert-x3/issues/issues

I opened this issue.

**Comment by pmlopes** [comment]
Ok, i'll reopen but you need to explain what you wish, since we already support partical file send :)

**Comment by pmlopes** [comment]
Since there's no feedback I'll close this question.
