### ISSUE TITLE
HttpClient : ConnectTimeoutException not catch by exceptionHandler

### ISSUE THREAD

**Issue by kjeremi** [vert-x3/issues#202]
When I try to do a request on a server which is slow to respond or which doesn't respond at all (like app.applynwork.com) a ConnectTimeoutException is thrown but I can't see it in the ExceptionHandler. How could I intercept this exception to do a fallback action ? 

Here is a test to reproduce the problem:

``` java
@RunWith(VertxUnitRunner.class)
public class TimeoutTest {

    @org.junit.Rule
    final public RunTestOnContext r = new RunTestOnContext();

    @Test
    public void testTimeOut(TestContext context) {

        Async async = context.async();
        HttpClientOptions options = new HttpClientOptions();
        options.setConnectTimeout(500);
        final HttpClient client = r.vertx().createHttpClient(options);
        try {
            HttpClientRequest request = client.get(80,"app.applynwork.com","/", ctx -> {
                ctx.exceptionHandler(ex -> {
                    context.fail(ex);
                });

                ctx.endHandler(v -> {
                    System.out.println("End handler");
                    async.complete();
                });
            });
            request.end();
        } catch (Throwable t) {
            context.fail(t);
        }
    }
}
```

> oct. 09, 2016 1:56:54 PM io.vertx.core.http.impl.HttpClientRequestImpl
> GRAVE: io.netty.channel.ConnectTimeoutException: connection timed out: app.applynwork.com/107.191.46.174:80

**Comment by alexlehm** [comment]
The exception handler that is set in the get handler is never set when the connection times out, you have to send an exception handler on the request before the .end() call

**Comment by kjeremi** [comment]
Understood, Thanks a lot !
