### ISSUE TITLE
Add HTTP2 Support

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/issues#21]
Add support for HTTP2 server and client

Github Project: https://github.com/eclipse/vert.x

**Comment by pmlopes** [comment]
this will require bumping netty to 4.1, 4.0 does support spdy which is not the official http2, http2 seems to be available from 4.1 see: http://search.maven.org/#search|gav|1|g%3A%22io.netty%22%20AND%20a%3A%22netty-codec-http2%22

**Comment by cescoffier** [comment]
Postponed to 3.3.0 as it requires a new version of Netty.

**Comment by vietj** [comment]
DONE!
