### ISSUE TITLE
Create a RoutingContext#destroyCookie method to actually remove browser cookies

### ISSUE THREAD

**Issue by kshep92** [vert-x3/issues#210]
Currently RoutingContext#removeCookie simply removes the cookie from the list of cookies in the current routing context. To remove a cookie from the browser, one would have to do `routingContext.getCookie("my-cookie").setMaxAge(0)`

I think a convenience method that would execute this logic in addition to null checks would be appreciated:

```
public RoutingContext destroyCookie(String cookieName) {
     Cookie cookie;
     if((cookie = getCookie(cookieName)) != null) {
         cookie.setMaxAge(0);
     }
     return this;
}
```

**Comment by pmlopes** [comment]
`delete` and `setMaxAge` are semantically 2 different things, i'm not sure they should be merged

**Comment by kshep92** [comment]
True... But the code block I posted seems to be a procedure that'll be pretty common in web dev. A convenience method would definitely be handy. Maybe rename it to expireCookie() or something?

**Comment by pmlopes** [comment]
Issue moved to [vert-x3/vertx-web #497](https://github.com/vert-x3/vertx-web/issues/497) via [**ZenHub**](https://www.zenhub.com/)

**Comment by cescoffier** [comment]
Issue marked as invalid because it has been moved to another project.
