### ISSUE TITLE
Events from vertx event bus to camel are not processed asynchronously

### ISSUE THREAD

**Issue by tleveque** [vert-x3/issues#213]
When a Camel processor execute blocking code, the event loop is blocked.
The root cause is that camel processor process is not async but synchronous even if you use AsyncProcessorConverterHelper to convert the processor to async one as described by Javadoc of the AsyncProcessorConverterHelper class:

A simple converter that can convert any {@link Processor} to an {@link AsyncProcessor}.
Processing will still occur synchronously but it will provide the required
notifications that the caller expects.

The solution would be to ask vertx to execute producer.process call as blocking code into FromVertxToCamelProducer class line 58.
// It's an async producer so won't block.
producer.process(exchange, new CamelProducerCallback(exchange, vertxMessage));

**Comment by pmlopes** [comment]
@tleveque would you mind to move this issue to: https://github.com/vert-x3/vertx-camel-bridge

**Comment by tleveque** [comment]
@pmlopes sure, it is done.

**Comment by cescoffier** [comment]
Issue opened there: https://github.com/vert-x3/vertx-camel-bridge/issues/18

**Comment by cescoffier** [comment]
Issue moved to its project (that's why I set the invalid flag on it).
