### ISSUE TITLE
how to intercept the RouteContext.response().end() method 

### ISSUE THREAD

**Issue by kevinmonster911** [vert-x3/issues#215]

**Comment by kevinmonster911** [comment]
I just want to do something before the response has been sent

**Comment by pmlopes** [comment]
If you're looking for support you should use the project forum:

https://groups.google.com/forum/#!forum/vertx

You're probably looking for this:

http://vertx.io/docs/apidocs/io/vertx/ext/web/RoutingContext.html#addHeadersEndHandler-io.vertx.core.Handler-

http://vertx.io/docs/apidocs/io/vertx/ext/web/RoutingContext.html#addBodyEndHandler-io.vertx.core.Handler-

**Comment by kevinmonster911** [comment]
tks @pmlopes
