### ISSUE TITLE
Problem while deploying mutiple verticles with VerticleFactory using Launcher

### ISSUE THREAD

**Issue by MicSpring** [vert-x3/issues#218]
I am trying to deploy multiple verticles using VerticleFactory.
But everytime only one verticle is getting deployed.

I found all my verticle factories are present in verticleFactories concurrenthashMap through verticleFactories() method of DeploymentManager.java.

Upon checking the source code I found that the doDeployVerticle() method in DeploymentManager.java have a "return" statement without any condition after the doDeploy() method, within the while loop which iterates the registered verticle factories.

I think this might be the probable cause provided I am following the right track.
Can I get any help in this regard?

**Comment by cescoffier** [comment]
The launcher deploys only the 'main verticle', this verticle has to deploys the other verticles. A verticle matches a single verticle factory, meaning that when a matching factory is found it is deployed using this factory.

Maybe I miss something, can you provide a reproducer or give more details ?

**Comment by MicSpring** [comment]
Thanks a lot for your response.

I was under the impression that doDeployVerticle() method in DeploymentManager.java will iterate though the Colection and deploy each verticle correspnding to its factory.

So I have one question here If the launcher deploys only the 'main verticle', and the main verticle has to deploy the other verticles then why we can register multiple verticle factories and hold them in a Collection?

In my case:
I have used two Verticle Factories for deployment of two separate Verticles and registered those factories using vertx.registerVerticleFactory() method. Within this method, the DeploymentManager class calls its registerVerticleFactory() method which adds those factories to a ConcurrentHashMap. Now when we deploy using Launcher the doDeployVerticle() method iterates through ConcurrentHashMap containing verticle factories but registers the verticle pertaining to the first factory that it finds and then returns without iterating through the other verticles. I am bit confused at this standpoint.

I will share my code at the GITHUB by tonight and may be it will help me to explain myself more elaborately the approach that I want to implement.

Thanks again.

**Comment by cescoffier** [comment]
The service factories let you support different type of verticle: java, groovy, js, RX…. A verticle can be deployed by only one factory.

**Comment by MicSpring** [comment]
Thanks again for your comments. 

Following your suggestion I tried to deploy multiple Verticles using a Single Verticle (i.e. the master). The single master verticle is deployed using VerticleFactory and other verticles are deployed using master verticle. My intention is to use Google Guice for DI in Vertx app.

To achieve this I was following a project hosted in GitHub, but there has been only a single Verticle and I want to implement DI when there will be deployments of more than 1 verticles.

So if you can please refer to the following two files and let me know if I am following the correct approach and suggestions if any it will be really great help:
https://github.com/MicSpring/explore-vertx/blob/master/src/main/groovy/com/subha/vertx/VertxGuiceMain.groovy 

and 

https://github.com/MicSpring/explore-vertx/blob/master/src/main/groovy/com/subha/vertx/verticles/MasterVerticle.groovy

**Comment by cescoffier** [comment]
Looks good to me.

**Comment by MicSpring** [comment]
Thanks a lot.
