### ISSUE TITLE
Async ReadStream implementation based on the database query resultset.

### ISSUE THREAD

**Issue by luolong** [vert-x3/issues#219]
Currently, the JDBCClient has an ability to perform asynchronous queries and I can use query callback to parse the list of results returned from the database, but there are use cases where ReadStream is more natural way to process results from the database query.

For example, when polling database for additional data and sending it off to an EventBus for further processing (i.e. generating update notifications, progressive indexing, stream processing, etc).

**Comment by pmlopes** [comment]
This has just landed: https://github.com/vert-x3/vertx-sql-common/pull/31 I think it covers your issue.

**Comment by pmlopes** [comment]
@luolong Can we close this issue then?

**Comment by luolong** [comment]
yes

**Comment by cescoffier** [comment]
Set the invalid flag because the issue moved to another project.
