### ISSUE TITLE
ServerWebSocket::reject cannot be invoked in handlers set by HttpServer::websocketHandler

### ISSUE THREAD

**Issue by yayj** [vert-x3/issues#220]
In my scenario, HTTP handshake comes in to trigger HttpServer::websocketHandler, and it's necessary to start some asynchronized operations to decide whether handshake should be rejected or not. The code might look like:

```
vertx.createHttpServer().websocketHandler(socket -> {
  Future<String> future = Future.future();
  redis.get(SOME_KEY, future.completer());
  future.setHandler(ar -> {
    if (ar.success() && isOK(ar.result())) {
      socket.handler(this::onMessage);       // Normal case
    } else {
      socket.reject();                    // Exceptional case to reject HTTP handshake
    }
  });
}).listen(80);
```

Unfortunately, `ServerWebSocket::reject` will be always failed because of handshake established immediately after `HttpServer::websocketHandler` returned.

**Comment by pmlopes** [comment]
You can solve this by running the reject in the next iteration of the event loop:

```java
future.setHandler(ar -> {
    if (ar.success() && isOK(ar.result())) {
      socket.handler(this::onMessage); // Normal case
    } else {
      vertx.runOnContext(v -> socket.reject()); // Exceptional case to reject HTTP handshake
    }
  });
```

**Comment by yayj** [comment]
It seems not working. Vertx still reports `java.lang.IllegalStateException: Cannot reject websocket, it has already been written to` and HTTP handshake has been already succeeded. I guess the implementation might be located in line 759-769 of `HttpServerImpl.java`:

```
wsConn.handleWebsocketConnect(ws);   // Invoking handler set by HttpServer::websocketHandler
if (!ws.isRejected()) {  // Checking whether connection should be reject or not immediately
  // do something else
  ws.connectNow();   // Establishing connection
} else {
  ch.writeAndFlush(new DefaultFullHttpResponse(HTTP_1_1, BAD_GATEWAY));
}
```

**Comment by zella** [comment]
Same problem (3.4.1). Can't reject in async manner, eg:

```
scalaFuture.onSuccess {
    vertx.runOnContext(new Handler[Void] {
                        override def handle(event: Void) = ws.reject()
                      })
}
```

**Comment by vietj** [comment]
one solution would be to use pause() / resume() and not accept immediately the websocket when the ws has been paused during the handler(ws) callback.

**Comment by yayj** [comment]
@vietj like this snippet?

```
server.websocketHandler(s -> {
  s.pause();
  vertx.setTimer(10000, id -> s.reject());
});
```

I don't think it make sense, because `ServerWebSocket::pause` just prevents to read from `Channel` automatically.

And anyway, according to the code snippet in my last comment, Vertx will determine whether the HTTP handshake is succeeded or not right after the connection handler returns. It means the programmers cannot determine the HTTP handshake status in some callbacks.

**Comment by vietj** [comment]
yes, and if it shall be used, the websocket would be resumed first

**Comment by vietj** [comment]
another way (that breaks compat) is to use a `Future` I think.

**Comment by yayj** [comment]
@vietj I don't think any workaround can make it, because the source code of Vertx has already proved that HTTP handshake must be determined right after connection handler returns.

**Comment by vietj** [comment]
@yayj I mean also that we would modify the source code to defer the handshake if he socket is paused

**Comment by vietj** [comment]
perhaps using something with a future is cleaner though. an override with `reject(Future<Boolean>)`

**Comment by endeavour** [comment]
Is there any update on this?

**Comment by vietj** [comment]
not yet

**Comment by vietj** [comment]
I'll close this issue as there is one issue tracking this in vertx-core https://github.com/eclipse-vertx/vert.x/issues/2585
