### ISSUE TITLE
vertx-web StaticHandler: add `setDefaultContentEncoding` method

### ISSUE THREAD

**Issue by timove** [vert-x3/issues#221]
It's not unusual to have static text web resources (esp. html, css) encoded in UTF-8 regardless of the production system's settings. My local machine e.g. yields `windows-1252` for `Charset.defaultCharset().name()` but I prefer to have my html files UTF-8 encoded, so they don't rely on the environment. To have german umlauts and other characters render correctly, I need to change the `defaultContentEncoding` field of the StaticHandler and need an appropriate setter, `setDefaultContentEncoding`. Currently (as of vert.x 3.3.3) the relevant field is defined as `private static final String defaultContentEncoding = Charset.defaultCharset().name();`.

**Comment by pmlopes** [comment]
Issue moved to [vert-x3/vertx-web #500](https://github.com/vert-x3/vertx-web/issues/500) via [**ZenHub**](https://www.zenhub.com/)

**Comment by cescoffier** [comment]
I've set the `invalid` flag as it's tracked somewhere else.
