### ISSUE TITLE
Vertx-web getWithRegex with named capture groups

### ISSUE THREAD

**Issue by andrewwh** [vert-x3/issues#222]
It would be nice to use getWithRegex with named capture groups such as `/(?<section>[^/]+)/?`. Such that you can use context.request().getParam("section") rather than context.request().getParam("param0").

**Comment by pmlopes** [comment]
Issue moved to [vert-x3/vertx-web #585](https://github.com/vert-x3/vertx-web/issues/585) via [**ZenHub**](https://www.zenhub.com/)
