### ISSUE TITLE
Compose Future In Vertx Differently

### ISSUE THREAD

**Issue by awaisraad** [vert-x3/issues#223]
I don't like the way we compose Future, and AsyncHandler result in Vertx. If we could associate directly the callback to the operations success or failure, that will be much better. It should be similar to how they do ajax calls in Jquery, or Angular1.x.

`Future<String> future =`
       `new FutureBuilder<String>()`
          `.success(System.out::println)`
          `.failure(err -> {`
            `System.out.println(err.getMessage());`
          `})`
          `.build();`

I am using this approach myself, so could be better if we get built in support for it.
You can look at example of it here: https://github.com/awaisraad/VertFutureBuilder/blob/master/src/main/java/raad/vertx/custom/DemoVerticle.java

**Comment by vietj** [comment]
@awaisraad why don't you make this a library and share it in Vert.x Awesome ?

**Comment by awaisraad** [comment]
Glad to hear from you.

Sure. But, could you take a look at the code again, all it has is just one class. The same can be achieved, up to some extent, with Future.compose(...). That's why I closed this issue.

**Comment by manish-panwar** [comment]
@awaisraad It would be great if we have it part of Verx or Vertx-awesome! Thanks @awaisraad for the implementation/suggestion!!!

**Comment by awaisraad** [comment]
Will do it soon. Thanks to you both.
