### ISSUE TITLE
Cleaner OSGi support

### ISSUE THREAD

**Issue by gadieichhorn** [vert-x3/issues#227]
Would like to see better/cleaner support for OSGi.

* separation of API and implementation bundles

Thanks.

@vietj for your group post request for suggestions. 
[https://groups.google.com/forum/#!topic/vertx/duFVIcSR0zg](url)

**Comment by pmlopes** [comment]
Seperation of API and implementation is a topic that has popped up a few times, one thing to be careful is that this could break the semver API. This requires good thinking on how to do it with minimal impact if applicable to 3.x code base.

**Comment by gadieichhorn** [comment]
@pmlopes I agree, it is not an easy task.
it's a good practice for non OSGi projects too, I found it useful practice on other platforms and languages.

**Comment by pmlopes** [comment]
Related to #139

**Comment by pmlopes** [comment]
Due to lack maintainers and proper testing OSGi metadata is removed from all modules on master.
Which makes this issue not fixable.
