### ISSUE TITLE
Website vertx.io per HTTPS access able

### ISSUE THREAD

**Issue by genofire** [vert-x3/issues#228]

**Comment by pmlopes** [comment]
This is a limitation of our hosting (github.com) and we can't do anything about it for the moment.

**Comment by genofire** [comment]
Why did not use the vert-x3.github.io domain or host it on his own.

**Comment by alexlehm** [comment]
Because its not portable (github.io) and because it costs money for hosting.

**Comment by genofire** [comment]
https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

Or should i host it? ^^

**Comment by vietj** [comment]
Above everything, GitHub hosting is handy because you can interact with the web server files with git.

**Comment by alexlehm** [comment]
Cloudflare would actually work, but I fail to see why this is even relevant, everything that is downloaded is hosted elsewhere, either on maven or on bintray.

**Comment by alexlehm** [comment]
Cloudflare would actually work, but I fail to see why this is even relevant, everything that is downloaded is hosted elsewhere, either on maven or on bintray.

**Comment by genofire** [comment]
@vietj there are webserver which could handle files with git -> https://caddyserver.com/docs/git

@alexlehm 
"Privacy by default" ^^ that disregard - bye
