### ISSUE TITLE
bug: HttpClient.getNow() does not handle exceptions or timeouts

### ISSUE THREAD

**Issue by elad-yosifon** [vert-x3/issues#231]
Vert.x version: v3.3.3

### how to reproduce:
```java
   try {
      HttpClient httpClient = vertx.createHttpClient(new HttpClientOptions().setConnectTimeout(1000));
      httpClient.getNow(80, "169.254.169.254", "/", response -> {
        // never gets here...
        response.exceptionHandler(event -> {
          callback.handle(null); // never gets here...
        });
        response.bodyHandler(body -> {
          callback.handle(null); // never gets here...
        });
      });
    } catch (Throwable e) {
      callback.handle(null); // never gets here...
    }
```
### Expected:
response handler triggers the exceptionHandler.

### Actual:
vert.x throws an internal exception `SEVERE: io.netty.channel.ConnectTimeoutException: connection timed out: /169.254.169.254:80` which cannot be caught or handled.

**Comment by alexlehm** [comment]
Yes, that is correct, please use get() if you want to register an exception handler.
Since the error happens during establishing of the connection, the handler for response is not called, so the handlers are not registered.

**Comment by cescoffier** [comment]
When using `get`, don't forget to call `end` to emit the request.

**Comment by vietj** [comment]
and soon use the web-client instead :-)

**Comment by vietj** [comment]
can we close this issue ?
