### ISSUE TITLE
NPE in vertx-consul-client

### ISSUE THREAD

**Issue by kjeremi** [vert-x3/issues#233]
consulClient.getValues fails with a Null Pointer Exception if one the values returned by consul is empty (to reproduce create an empty key withconsulUI) 

Here is what is returned by consul: 
>{"LockIndex":0,"Key":"System/uploadWS/","Flags":0,"Value":null,"CreateIndex":3574,"ModifyIndex":3574}

The NPE is thrown in the decode method: io.vertx.ext.consul.impl.KVParser:
line 25 : 
>        return (new KeyValue()).setKey(json.getString("Key")).setValue(new String(Base64.getDecoder().decode(json.getString("Value")))).setSession(json.getString("Session")).setFlags(json.getLong("Flags", Long.valueOf(0L)).longValue()).setCreateIndex(json.getLong("CreateIndex", Long.valueOf(0L)).longValue()).setModifyIndex(json.getLong("ModifyIndex", Long.valueOf(0L)).longValue()).setLockIndex(json.getLong("LockIndex", Long.valueOf(0L)).longValue());

May I suggest to check the return of json.getString("Value") before passing it to the decoder ? 

Thanks 

Consul version :  v0.7.2
vertx-consul-client : 3.4.0-SNAPSHOT

**Comment by ruslansennov** [comment]
thank you

**Comment by ruslansennov** [comment]
@kjeremi please update your snapshot

**Comment by kjeremi** [comment]
I confirm this is fixed. Thanks a lot for your reactivity !
