### ISSUE TITLE
vertx-eventbus.js single location

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/issues#234]
Currently the source code for the sockjs bus bridge client is maintained here:

https://github.com/vert-x3/vertx-web/tree/master/vertx-web/src/client

And then replicated here:

https://github.com/vert-x3/vertx-bus-bower

And copied here:

https://github.com/vert-x3/vertx-stack/tree/master/stack-npm/src/main/npm/client

We should align it to just one place

**Comment by cescoffier** [comment]
Actually, it's maintained on in https://github.com/vert-x3/vertx-web/tree/master/vertx-web/src/client.

In https://github.com/vert-x3/vertx-bus-bower, the file is copied during the release process but not maintained. (I should have a big warning in the README to say to user to not use the issue tracker).

In https://github.com/vert-x3/vertx-stack/tree/master/stack-npm/src/main/npm/client, it needs to be fixed as it can be copied in "target" and so not be in the (SCM) source tree.
