### ISSUE TITLE
Misspelling in documentation 

### ISSUE THREAD

**Issue by BobbyBakes** [vert-x3/issues#235]
￼http://vertx.io/docs/vertx-service-proxy/java/

The second method takes an instance of DeliveryOptions where you **con** configure the message delivery (such as the timeout).

**Comment by tsegismont** [comment]
Thanks for the pointer. Would you like to contribute the fix?

2017-02-01 22:01 GMT+01:00 BobbyBakes <notifications@github.com>:

**Comment by BobbyBakes** [comment]
Sure thing

**Comment by BobbyBakes** [comment]
Where can i pull from?

**Comment by cescoffier** [comment]
From there: https://github.com/vert-x3/vertx-service-proxy/blob/master/src/main/java/io/vertx/serviceproxy/package-info.java#L271

**Comment by cescoffier** [comment]
It has been fixed in the service proxy project.
