### ISSUE TITLE
Service discovery custom service type implementation instructions wrong on web site

### ISSUE THREAD

**Issue by MrLoNee** [vert-x3/issues#238]
Hi, 

In the page about service discovery 
http://vertx.io/docs/vertx-service-discovery/java/

section 

> "Implementing your own service type"

the documentation instruction is to create a file to define a specific ServiceType

> META-INF/services/io.vertx.**ext.discovery**.spi.ServiceType

The service type has been refactored and the package is now 

META-INF/services/io.vertx.**servicediscovery**.spi.ServiceType

**Comment by cescoffier** [comment]
This will be fixed when we push the documentation alongside the next G.A. release. For now you can refer to http://vertx.io/docs/3.4.0.Beta1/vertx-service-discovery/java/
