### ISSUE TITLE
Calling pause/resume in an AsyncFile's endHandler will cause a new call to the endHandler.

### ISSUE THREAD

**Issue by bckfnn** [vert-x3/issues#248]
An AsyncFile opened for reading and paused in the endHandler will call the endHandler again when the ReadStream is resumed.

Tested behaviour detected in 3.3.3 and 3.4.1

reproducer:
https://github.com/bckfnn/vertx-file-stream-test

**Comment by vietj** [comment]
https://github.com/eclipse/vert.x/issues/1890
