### ISSUE TITLE
HttpClient timeout exceptions if there is delay in response handler

### ISSUE THREAD

**Issue by ghost** [vert-x3/issues#249]
```
package vx.app.test;

import io.vertx.core.*;
import io.vertx.core.eventbus.Message;
import io.vertx.core.http.*;

import java.util.concurrent.atomic.AtomicInteger;

public class RequestHandler extends AbstractVerticle {
    private HttpClient httpClient;
    private AtomicInteger successCount = new AtomicInteger(0);
    private AtomicInteger failureCount = new AtomicInteger(0);

    @Override
    public void start() throws Exception {
        HttpClientOptions options = new HttpClientOptions();
        options.setMaxWaitQueueSize(1000);
        options.setKeepAlive(true);
        options.setMaxPoolSize(500);
        httpClient = vertx.createHttpClient(options);
        vertx.eventBus().consumer("request", (Message<Integer> message) -> {
            sendData(response -> {
//                System.out.println(Thread.currentThread().getName());
                if (response.succeeded()) {
                    successCount.incrementAndGet();
                } else {
                    failureCount.incrementAndGet();
                }
                if ((successCount.intValue() + failureCount.intValue()) % 20 == 0) {
                    int totalResponses = successCount.intValue() + failureCount.intValue();
                    System.out.println("total = " + totalResponses + " (success = " + successCount.intValue() + ", failure = " + failureCount.intValue() + ")");

                    if (totalResponses == 200) {
                        System.out.println("done");
                        vertx.eventBus().send("shutdown", "");
                    }
                }
                delay(20);
            });
        });
    }

    private void sendData(Handler<AsyncResult<String>> handler) {
        HttpClientRequest request = httpClient.postAbs("http://localhost:7777", response -> {
            response.bodyHandler(buffer -> {
                handler.handle(Future.succeededFuture(buffer.toString()));
            });
        });
        request.exceptionHandler(e -> {
            handler.handle(Future.failedFuture(e));
        });
        request.setTimeout(2000);

        String data = "data";
        request.putHeader(HttpHeaders.CONTENT_LENGTH, Integer.toString(data.length()));
        request.putHeader(HttpHeaders.CONTENT_TYPE, "text/plain");
        request.write(data).end();
    }

    private void delay(long time) {
        try {
            Thread.sleep(time);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}

class Main {
    private Vertx vertx;
    private HttpServer httpServer;

    public Main() {
        vertx = Vertx.vertx();
        startWebServer();
        vertx.deployVerticle(RequestHandler.class.getName(), new DeploymentOptions().setWorker(true), future -> {
            if (future.succeeded()) {
                for (int i = 0; i < 200; i++) {
                    vertx.eventBus().send("request", 1);
                }
            }
        });

        vertx.eventBus().consumer("shutdown", e -> {
            httpServer.close();
            vertx.close();
        });
    }

    public static void main(String[] args) {
        new Main();
    }

    private void startWebServer() {
        String webServiceResponse = "<response><hello></hello></response>";
        HttpServerOptions options = new HttpServerOptions();
        httpServer = vertx.createHttpServer(options).requestHandler(request -> {
            vertx.setTimer(1000, event -> {
                request.response().headers().set(HttpHeaders.CONTENT_LENGTH, String.valueOf(webServiceResponse.length()));
                request.response().headers().set(HttpHeaders.CONTENT_TYPE, "application/xml");
                request.response().end(webServiceResponse);
            });
        }).listen(7777);
    }
}
```
If there is some delay in httpclient's(pool) response handler then it starts getting timeout exceptions. I am not blocking event loop i am handling responses on worker threads. Here is output

total = 20 (success = 20, failure = 0)
total = 40 (success = 40, failure = 0)
total = 60 (success = 60, failure = 0)
total = 80 (success = 80, failure = 0)
total = 100 (success = 100, failure = 0)
total = 120 (success = 120, failure = 0)
total = 140 (success = 140, failure = 0)
total = 160 (success = 160, failure = 0)
total = 180 (success = 180, failure = 0)
total = 200 (success = 200, failure = 0)
done
total = 220 (success = 200, failure = 20)
total = 240 (success = 200, failure = 40)
total = 260 (success = 200, failure = 60)
total = 280 (success = 200, failure = 80)
total = 300 (success = 200, failure = 100)
total = 320 (success = 200, failure = 120)
total = 340 (success = 200, failure = 140)
total = 360 (success = 200, failure = 160)

I am using HttpClient with connection pool of 500 Vertx version 3.4.0, Java 8
I am sending 200 requests and i get all 200 success responses and then after that i start getting timeout exceptions, program should stop after **done** but keep getting timeout exceptions. Please run program 2 or 3 times if you won't get any timeout exceptions.
What i am doing wrong here? If i create new thread to handle response in response handler then i will not get any timeout exceptions.

**Comment by vietj** [comment]
this happens because you are using worker and Thread.sleep in your verticle.

In such situations timers can introduce race conditions specially when combined with IO.

you should probably avoid to use Thread.sleep(20) and use instead also a timer.

that being said, the HttpClientRequest should not fire a timeout exception after the response has been received, so I consider this as a bug, although you should also fix your code to avoid thread sleeping

**Comment by ghost** [comment]
Thanks for the response bro, in real application i am not using Thread.sleep but there is time consuming work i am doing in response handler still getting timeouts. I used sleep to reproduce this issue. It appears that request timer get cancels after response handler finishes its work not before.

**Comment by vietj** [comment]
yes this happens because how the timer is handled for workers, I'm contributing a fix

**Comment by vietj** [comment]
meanwhile you should use something like a io.vertx.core.Future with tryComplete / tryFail operation and have a single callback on the future.setHandler to make sure only one operation is executed

**Comment by vietj** [comment]
I've created this PR : https://github.com/eclipse/vert.x/pull/1900

**Comment by ghost** [comment]
Am i doing it right the fix you propose?
```
    private void sendData(Handler<AsyncResult<String>> handler) {
        Future<String> future = Future.future();
        future.setHandler(handler);

        HttpClientRequest request = httpClient.postAbs("http://localhost:7777", response -> {
            response.bodyHandler(buffer -> {
                future.tryComplete(buffer.toString());
            });
        });
        request.exceptionHandler(e -> {
            future.tryFail(e);
        });
        request.setTimeout(2000);

        String data = "data";
        request.putHeader(HttpHeaders.CONTENT_LENGTH, Integer.toString(data.length()));
        request.putHeader(HttpHeaders.CONTENT_TYPE, "text/plain");
        request.write(data).end();
    }
```

**Comment by vietj** [comment]
yes, or better use the new Vert.x Web Client http://vertx.io/docs/vertx-web-client/java/ it has a Future built-in to guarantee a single callback

**Comment by ghost** [comment]
Thanks bro i will check it

**Comment by ghost** [comment]
Hi bro i ran in to another problem. If i do some time consuming work before sending http requests i start getting timeout exceptions. Here is output

**total = 10 (success = 0, failure = 10)
total = 20 (success = 0, failure = 20)
total = 30 (success = 0, failure = 30)
total = 40 (success = 0, failure = 40)
total = 50 (success = 0, failure = 50)
total = 60 (success = 0, failure = 60)
total = 70 (success = 0, failure = 70)
total = 80 (success = 7, failure = 73)
total = 90 (success = 17, failure = 73)
total = 100 (success = 27, failure = 73)
done**

Just before sendData if there is time consuming work i start getting timeouts in real app i am not using sleep. Please help
```
package vx.app.test;

import io.vertx.core.*;
import io.vertx.core.eventbus.Message;
import io.vertx.core.http.*;

import java.util.concurrent.atomic.AtomicInteger;

public class RequestTimeoutVerticle extends AbstractVerticle {
    private HttpClient httpClient;
    private AtomicInteger successCount = new AtomicInteger(0);
    private AtomicInteger failureCount = new AtomicInteger(0);

    @Override
    public void start() throws Exception {
        HttpClientOptions options = new HttpClientOptions();
        options.setMaxWaitQueueSize(1000);
        options.setKeepAlive(true);
        options.setMaxPoolSize(1000);
        httpClient = vertx.createHttpClient(options);
        vertx.eventBus().consumer("request", (Message<Integer> message) -> {
            vertx.setTimer(10, event -> {
                delay(30);
                sendData(response -> {
//                System.out.println(Thread.currentThread().getName());
                    if (response.succeeded()) {
                        successCount.incrementAndGet();
                    } else {
                        failureCount.incrementAndGet();
                    }
                    if ((successCount.intValue() + failureCount.intValue()) % 10 == 0) {
                        int totalResponses = successCount.intValue() + failureCount.intValue();
                        System.out.println("total = " + totalResponses + " (success = " + successCount.intValue() + ", failure = " + failureCount.intValue() + ")");

                        if (totalResponses == 100) {
                            System.out.println("done");
                            vertx.eventBus().send("shutdown", "");
                        }
                    }
                });
            });
        });

    }

    private void sendData(Handler<AsyncResult<String>> handler) {
        Future<String> future = Future.future();
        future.setHandler(handler);

        HttpClientRequest request = httpClient.postAbs("http://localhost:7777", response -> {
            response.bodyHandler(buffer -> {
                future.tryComplete(buffer.toString());
            });
        });
        request.exceptionHandler(future::tryFail);
        request.setTimeout(2000);

        String data = "data";
        request.putHeader(HttpHeaders.CONTENT_LENGTH, Integer.toString(data.length()));
        request.putHeader(HttpHeaders.CONTENT_TYPE, "text/plain");
        request.write(data).end();
    }

    private void delay(long time) {
        try {
            Thread.sleep(time);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    private static Vertx vertx;
    private static HttpServer httpServer;

    private static void startWebServer() {
        String webServiceResponse = "<response><hello></hello></response>";
        HttpServerOptions options = new HttpServerOptions();
        httpServer = vertx.createHttpServer(options).requestHandler(request -> {
            vertx.setTimer(1000, event -> {
                request.response().headers().set(HttpHeaders.CONTENT_LENGTH, String.valueOf(webServiceResponse.length()));
                request.response().headers().set(HttpHeaders.CONTENT_TYPE, "application/xml");
                request.response().end(webServiceResponse);
            });
        }).listen(7777);
    }

    public static void main(String[] args) {
        vertx = Vertx.vertx();
        startWebServer();
        vertx.deployVerticle(RequestTimeoutVerticle.class.getName(), new DeploymentOptions().setWorker(true), future -> {
            if (future.succeeded()) {
                for (int i = 0; i < 100; i++) {
                    vertx.eventBus().send("request", 1);
                }
            }
        });

        vertx.eventBus().consumer("shutdown", e -> {
            httpServer.close();
            vertx.close();
        });
    }
}
```

**Comment by ghost** [comment]
because of these timeout issues i moved to retrofit library. I just saw your library retrofit-vertx
http://www.julienviet.com/retrofit-vertx/guide/java/index.html
this is what i needed only problem is that i can't set request timeout. I don't have access to HttpClientRequest how can i add request timeout using your library?

**Comment by vietj** [comment]
I think we should add this as an option of the `VertxCallFactory` that's quite easy to add, if you do a PR on the project I would review it and make a new release

**Comment by vietj** [comment]
@farrukh-obaid note you can call setTimeout again on HttpClientRequest to re-set the timer to a new value.

**Comment by vietj** [comment]
I'm fixing this issue as the corresponding core issue in vertx core has been merged.

**Comment by ghost** [comment]
where should i add new setTimeout? I added setTimeout in response handler like this 

`response.request().setTimeout(10000);`

still same problem

**Comment by vietj** [comment]
I think that you should separate your HTTP client activities from your worker blocking interaction activities using the EventBus:

- all your HTTP operations encapsulated in an event loop verticle listening on the EventBus, perhaps using a Vert.x Service Proxy
- all your worker activities using workers and then do HTTP operations using the EventBus to communicate

**Comment by ghost** [comment]
Hi bro i created Vert.x Service Proxy as you suggested to handle http and i am handling http response in another WorkerExecutor pool to avoid vertx workers blocking. But there is problem in WorkerExecutor pool it creates only one thread if i call executeBlocking method with ordered=false i reported issue here #250 
Is this a bug or i am doing it wrong?

**Comment by vietj** [comment]
this bug has been fixed indeed : https://github.com/eclipse/vert.x/issues/1887

instead use Context#executeBlocking without using a WorkerExecutor

**Comment by ghost** [comment]
Hi I want to avoid running code inside vertx workers threads i need another thread pool is there any way to create another Context thread pool?

**Comment by vietj** [comment]
I think then indeed you need to wait for Vert.x 3.4.2.

In the meantime you can use your own thread pool (as you don't need ordered) and use runOnContext to piggy back the result.

**Comment by ghost** [comment]
yes i am planning to use rxjava to handle this. When will 3.4.2 is releasing?

**Comment by vietj** [comment]
we are aiming around May
