### ISSUE TITLE
Add support for array column type in PostgreSQL client (Scala collection types)

### ISSUE THREAD

**Issue by jvz** [vert-x3/issues#251]
If I have a table like this:

```
CREATE TABLE example (
  id UUID PRIMARY KEY,
  tags TEXT[]
);
```

Then when I query for rows, `Json.checkAndCopy()` throws an IllegalStateException because it doesn't know how to handle the class `scala.collection.mutable.ArrayBuffer`. Now I'm not super experienced with Scala at all, but it seems like this can be supported by adding generic support for `scala.collection.Seq[T]`, however, it might be nicer to support `Traversable[T]` since that seems to be one of the most generic collection classes in Scala.

**Comment by EmadAlblueshi** [comment]
Kindly take a look https://github.com/vert-x3/vertx-sql-common/issues/17

**Comment by jvz** [comment]
I don't recall having a problem inserting the data (I inserted as a `List` instance using `queryWithParams`), but I had issues retrieving it since the JsonObject/JsonArray classes were unaware of how to convert a Scala collection into an appropriate type.

**Comment by pmlopes** [comment]
Issue moved to [vert-x3/vertx-mysql-postgresql-client #73](https://github.com/vert-x3/vertx-mysql-postgresql-client/issues/73) via [**ZenHub**](https://www.zenhub.com/)
