### ISSUE TITLE
How to pass a groovy closure where a handler is expected

### ISSUE THREAD

**Issue by jgarcia241** [vert-x3/issues#252]
Hi,

Migrating from vertx 2 I found the following issue:

We have some places where when sending messages to the eventBus, we pass a closure as a handler. For example:

`eventBus.send(sqlAddress, json, closure )` (where `closure` is defined before, or in our passed passed as parameter)

This worked fine on vertx2. On vertx 3.4.1 this no longer works and I'm getting an error like:

`groovy.lang.MissingMethodException: No signature of method: <myclass>$_XXX_closure1.doCall() is applicable for argument types: (io.vertx.core.impl.FutureImpl) values: [io.vertx.core.impl.FutureImpl@690594ce]`

however, if I do:
`eventBus.send(sqlAddress, json, {some code} )` it will work. 

I read in [google groups](https://groups.google.com/forum/#!topic/vertx/jIvsoHKavyQ) that a posible solution would be to use:

`eventBus.send(sqlAddress, json, closure.&call )`

However, this is not working for me either. Not sure if it has to do with the changes done for groovy in 3.4.0

Any idea on how we can convert the closure so it can be called back?

Kind regards

Note: the idea of using `{closure()}` is  I'd like to avoid

**Comment by pentagon** [comment]
@underkin hi, any luck on this issue?

**Comment by jgarcia241** [comment]
It is working for me with;

```
vertx.eventBus().send(address, payload, opts,{AsyncResult<Message> ar->
			if (ar.failed()){
				//do X)
			}else{
				//do Y
			}

		})
```

and with:

```
Handler handler = { AsyncResult<ArrayList> ar ->
if (ar.failed()){
				//do X)
			}else{
				//do Y
			}

}
vertx.eventBus().send(address, payload, opts,handler)
```

**Comment by pentagon** [comment]
@underkin thank you very much, hopefully this solution gets its reflection in vertx docs :)
