### ISSUE TITLE
References of a handler can't be parameterized in a scala manner

### ISSUE THREAD

**Issue by sascha10000** [vert-x3/issues#258]
When defining a handler-function like

```
val handler = (rc:RoutingContext) => {
 rc.request.end("Hallo")
}
```

You can't pass it to the route handler
```
router.route("/some/path").handle(handler)
```

caused by non matching types.
A workaround would be a nested call but this wouldn't be "Scala-Style".

An example is provided here (uncomment the line with the error and everything works fine):
https://gist.github.com/sascha10000/811159d48057a0e63cc5317afc1a6193#file-verticletest-scala

By providing an implicit you could use it in a scala manner.
Provide a class e.g.:
https://gist.github.com/sascha10000/d9dd792f8d2d6e9defab8fb99d9eed79#file-rchandler

Now it's possible to add
```
import RCHandler._
```
at top and one is able to pass the handler as a function value.
The issue here is that basic scala things aren't working because of typing which could be easily omitted.

**Comment by vietj** [comment]
ping @codepitbull

**Comment by Narigo** [comment]
Could this be a workaround, @sascha10000?

```scala
val handler: RoutingContext => Unit = rc => {
  rc.request.end("Hallo")
}
```

@codepitbull could a definition of handler functions like `RoutingContext => _` instead of `RoutingContext => Unit` work in this case?

**Comment by codepitbull** [comment]
I will try it tonight.

**Comment by sascha10000** [comment]
@Narigo I did try it that way in another place, didn't work. But that is not the thing here, because the interfered type is each way (RoutingContext) => Unit. Therefore explicit typing doesn't help...

**Comment by codepitbull** [comment]
The problem is that Handler is a functional interface. A Function needs to be adapted to be usable in place of a functional interface.

You have to give Scala a hint what you want to do with the Function. In this case you have to specify the type explicitly and Scala will take care of it.

```scala
val handler:Handler[RoutingContext] = (rc:RoutingContext) => {
      rc.response().end("Hallo")
}

router.get("/hu").handler(handler)
```

**Comment by sascha10000** [comment]
Yes that's what I didn't see right away. I know about the functional interface... Okay so I will use a type for that purpose. Thanks.
