### ISSUE TITLE
vertx Pressure fault 

### ISSUE THREAD

**Issue by wpxdong** [vert-x3/issues#259]
version:3.41
pressure tool:wrk(https://github.com/wg/wrk)
------------------------------------------------
java code:
  public class Micro extends AbstractVerticle {
	public static void main(String[] args) {
	   Runner.runExample(Micro.class);
	  }
	@Override
	public void start() throws Exception {
		vertx.createHttpServer().requestHandler(req -> {
			req.response().putHeader("content-type", "text/plain").end("Hello world!");
		}).listen(8081);
	}
}
----------------------------------------------------------
script:   
  wrk -t1 -c5 -d10s http://localhost:8081/
--------------------------------------------------------
error log:

 io.vertx.core.net.impl.ConnectionBase
 java.io.IOException: Connection reset by peer

**Comment by pmlopes** [comment]
You see that message when`wrk` finishes and abruptly kills the connection. It is a notification that your peer (the client) just closed the connection before the server sent any data.

**Comment by wpxdong** [comment]
@pmlopes 

5 connections into the 1, then no error
wrk -t1 -c1 -d10s http://localhost:8081/
