### ISSUE TITLE
Add Zookeeper Cluster Manager to the vert.x stack

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/issues#26]
Github Project: https://github.com/vert-x3/vertx-zookeeper

**Comment by cescoffier** [comment]
Be aware that it's not currently possible to get several cluster manager in the classpath (it would take the first one appearing on classpath).

**Comment by kuujo** [comment]
Got it

**Comment by pmlopes** [comment]
This is already added to the stack: https://github.com/vert-x3/vertx-stack/blob/master/stack-depchain/pom.xml

And present in the official documentation
