### ISSUE TITLE
EventBus.LocalSender

### ISSUE THREAD

**Issue by LisiLisenok** [vert-x3/issues#260]
EventBus allows to register consumer which listens only local messages. What about producer which sends or publishes only to local consumers?

**Comment by vietj** [comment]
it is not supported, you need to agree on an address that will be for local delivery only.

**Comment by LisiLisenok** [comment]
@vietj that was enhancement idea for the next versions.

**Comment by vietj** [comment]
please open an issue in the https://github.com/vert-x3/issues/issues repo with a tag whishlist

I thought it was a question, there are so many persons opening issues for asking questions...
