### ISSUE TITLE
Add sql connection reference into the operation result.

### ISSUE THREAD

**Issue by chengenzhao** [vert-x3/issues#262]
Hi there: 

I would like to see some enhancements for sql connection since sql connection is a little bit different from other async api
it requires closing the connection  manually, so it makes fluent coding style messy when you compose some futures

e.g.

```java
Future.<SQLConnection>future(future ->{
    client.getConnection(future);
}).<UpdateResult>compose(connection ->
    Future.future(future -> connection.update("update table_1 set name = a where id = 001", future))
).setHandler(updateResult ->{
    if(updateResult.succeeded()){
        
    }else{

    }
    //is there any way to add updateResult.getConnection(); here?
    //thus we could use updateResult.getConnection().close();
});
```

as we could see here, the 1st step is to get connection from the pool, then do some operations then close the connection, which means return the connection to the pool, however currently we may not be able to do that since most of sql connection apis does not return the reference for the sql connection then the connection is lost when you chain the futures

I would suggest to add sql connection reference to the result then we should be able to close the connection at the end of the fluent future chain.

**Comment by pmlopes** [comment]
Issue moved to [vert-x3/vertx-sql-common #47](https://github.com/vert-x3/vertx-sql-common/issues/47) via [**ZenHub**](https://www.zenhub.com/)
