### ISSUE TITLE
JDBC Connection

### ISSUE THREAD

**Issue by SELLAM** [vert-x3/issues#263]
Hello,

i'm using vertx 3.4.1, i have a problem with JDBC Connection when the username or password of the data base is wrong, vertx try to reconnect every many time and that cause blocking the user compte by the data base.

can you help me please? Thanks

**Comment by pmlopes** [comment]
when you call `getConnection()` I believe you should check if the result was an error, it should state what error it was (Bad Credentials for example) and you should handle it from there or stop your application.

**Comment by SELLAM** [comment]
this is my function getConnection:

```
public void getConnection(Handler<AsyncResult<SQLConnectionOracle>> resultHandler){
        if(this.client == null){
            logger.error(Error.BD_CLIENT_NOT_FOUND);
            resultHandler.handle(Future.failedFuture(Error.BD_CLIENT_NOT_FOUND.toString()));
        }else {
            this.client.getConnection(connection -> {
                if (connection.succeeded()) {
                    resultHandler.handle(Future.succeededFuture(connection.result()));
                } else {
                    logger.error(connection.cause().getMessage());
                    resultHandler.handle(Future.failedFuture(Error.ER_DB_CONX.toString()));
                }
            });
        }
    }
```
i juste calling the getConnection of the vertex jdbc client.

in my case the information to connect to database comming when the user authentificate, the user using the database to connecte and the name/password of database.

so when the username or password wrong, JDBC essaye to connecting each many time.

**Comment by tsegismont** [comment]
It is very unusual for each app user to get its own account in the
database. I would revisit this design, if possible.

If not possible, then I'd create a JDBC client for each request, with
maxPoolSize=1 and close the client after the request is processed (you
can't use true pooled connections if the underlying user changes all the
time).

2017-05-15 17:58 GMT+02:00 SELLAM <notifications@github.com>:

**Comment by SELLAM** [comment]
i think i will not create a JDBC client for each request but for each session, when the user sign out that moment i will close the client.
