### ISSUE TITLE
DNS Resolution fail

### ISSUE THREAD

**Issue by CarstenLeue** [vert-x3/issues#264]
Using Vertx 3.4.1

I am experiencing the problem, that the DNS lookup to some domain names fails when using the built-in DNS resolver. 

Testcode (using VertxInternal to produce the simplest possible test, the problem actually occurs when doing an HTTP request):

```java
VertxInternal intern = (VertxInternal) certx.getVertx();
intern.resolveAddress("dx-marathon.rtp.raleigh.ibm.com", res -> System.out.println("err: " + res.cause() + ", result: " + res.result());
```

This produces the error message:
java.net.UnknownHostException: failed to resolve 'dx-marathon.rtp.raleigh.ibm.com'. Exceeded max queries per resolve 4 

When running the same with "-Dvertx.disableDnsResolver=true", i.e. bypassing the internal DNS resolver I get the correct resolution:
dx-marathon.rtp.raleigh.ibm.com/9.37.244.153

In the logs for the failing case I see:
DatagramDnsResponse(from: /9.152.120.241:53, to: /0.0.0.0:59736, 4548, QUERY(0), Refused(5), RD)
	DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com. IN A)

As if the request was refused. But why?

This is the log for the failing case:
log4j: Trying to find [log4j.xml] using context classloader sun.misc.Launcher$AppClassLoader@a265b0bb.
log4j: Using URL [file:/C:/d/ContentHub/prod-publishing-manager-scheduler/queues/bin/log4j.xml] for automatic log4j configuration.
log4j: Preferred configurator class: org.apache.log4j.xml.DOMConfigurator
log4j: System property is :null
log4j: Standard DocumentBuilderFactory search succeded.
log4j: DocumentBuilderFactory is: org.apache.xerces.jaxp.DocumentBuilderFactoryImpl
log4j: debug attribute= "null".
log4j: Ignoring debug attribute.
log4j: reset attribute= "false".
log4j: Threshold ="null".
log4j: Level value for root is  [debug].
log4j: root level set to DEBUG
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Setting property [target] to [System.out].
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%-5p %c{1} - %m%n].
log4j: Adding appender named [console] to category [root].
DEBUG InternalLoggerFactory - Using SLF4J as the default logging framework
DEBUG ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
DEBUG ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
DEBUG MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
DEBUG PlatformDependent - -Dio.netty.noUnsafe: false
DEBUG PlatformDependent0 - java.nio.Buffer.address: available
DEBUG PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
DEBUG PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
DEBUG PlatformDependent0 - direct buffer constructor: available
DEBUG PlatformDependent0 - java.nio.Bits.unaligned: available, true
DEBUG PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
DEBUG Cleaner0 - java.nio.ByteBuffer.cleaner(): available
DEBUG PlatformDependent - Platform: Windows
DEBUG PlatformDependent - Java version: 8
DEBUG PlatformDependent - sun.misc.Unsafe: available
DEBUG PlatformDependent - -Dio.netty.noJavassist: false
DEBUG PlatformDependent - Javassist: unavailable
DEBUG PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
DEBUG PlatformDependent - -Dio.netty.tmpdir: C:\Users\IBM_AD~1\AppData\Local\Temp (java.io.tmpdir)
DEBUG PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
DEBUG PlatformDependent - -Dio.netty.noPreferDirect: false
DEBUG PlatformDependent - io.netty.maxDirectMemory: 67108864 bytes
DEBUG NioEventLoop - -Dio.netty.noKeySetOptimization: false
DEBUG NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
DEBUG PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
DEBUG DnsServerAddresses - Default DNS servers: [/9.152.120.241:53, /9.152.64.172:53, /9.0.136.50:53, /9.0.138.50:53, /192.168.2.1:53] (sun.net.dns.ResolverConfiguration)
DEBUG NetUtil - -Djava.net.preferIPv4Stack: false
DEBUG NetUtil - -Djava.net.preferIPv6Addresses: false
DEBUG NetUtil - Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
DEBUG NetUtil - \proc\sys\net\core\somaxconn: 200 (non-existent)
DEBUG DefaultChannelId - -Dio.netty.processId: 16740 (auto-detected)
DEBUG DefaultChannelId - -Dio.netty.machineId: 00:00:00:00:00:00:00:e0 (auto-detected)
DEBUG ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0x9cd3f5179c86b969
DEBUG PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 5
DEBUG PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 0
DEBUG PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
DEBUG PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
DEBUG PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
DEBUG PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
DEBUG PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
DEBUG PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
DEBUG PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
DEBUG PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
DEBUG PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
DEBUG ByteBufUtil - -Dio.netty.allocator.type: pooled
DEBUG ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
DEBUG ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
DEBUG ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@dc71a56b
DEBUG DnsQueryContext - [id: 0xdfa9baef] WRITE: [4548: /9.152.120.241:53], DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com. IN A)
DEBUG Recycler - -Dio.netty.recycler.maxCapacityPerThread: 32768
DEBUG Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
DEBUG Recycler - -Dio.netty.recycler.linkCapacity: 16
DEBUG Recycler - -Dio.netty.recycler.ratio: 8
DEBUG DnsQueryContext - [id: 0xdfa9baef] WRITE: [1360: /9.152.120.241:53], DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com. IN AAAA)
DEBUG AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
DEBUG ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@88dd2261
DEBUG DnsNameResolver - [id: 0xdfa9baef] RECEIVED: [4548: /9.152.120.241:53], **DatagramDnsResponse(from: /9.152.120.241:53, to: /0.0.0.0:59736, 4548, QUERY(0), Refused(5), RD)
	DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com. IN A)**
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
DEBUG DnsQueryContext - [id: 0xdfa9baef] WRITE: [35583: /9.152.64.172:53], DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com. IN A)
DEBUG DnsNameResolver - [id: 0xdfa9baef] RECEIVED: [1360: /9.152.120.241:53], DatagramDnsResponse(from: /9.152.120.241:53, to: /0.0.0.0:59736, 1360, QUERY(0), Refused(5), RD)
	DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com. IN AAAA)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
DEBUG DnsQueryContext - [id: 0xdfa9baef] WRITE: [6446: /9.0.136.50:53], DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com. IN AAAA)
DEBUG DnsNameResolver - [id: 0xdfa9baef] RECEIVED: [35583: /9.152.64.172:53], DatagramDnsResponse(from: /9.152.64.172:53, to: /0.0.0.0:59736, 35583, QUERY(0), Refused(5), RD)
	DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com. IN A)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
DEBUG DnsNameResolver - [id: 0xdfa9baef] RECEIVED: [6446: /9.0.136.50:53], DatagramDnsResponse(from: /9.0.136.50:53, to: /0.0.0.0:59736, 6446, QUERY(0), NoError(0), RD RA)
	DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com. IN AAAA)
	DefaultDnsRawRecord(dx-marathon.rtp.raleigh.ibm.com. 11788 IN CNAME 16B)
	DefaultDnsRawRecord(rtp.raleigh.ibm.com. 900 IN SOA 52B)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
DEBUG DnsQueryContext - [id: 0xdfa9baef] WRITE: [1070: /9.152.120.241:53], DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.ibm.com. IN A)
DEBUG DnsQueryContext - [id: 0xdfa9baef] WRITE: [44153: /9.152.120.241:53], DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.ibm.com. IN AAAA)
DEBUG DnsNameResolver - [id: 0xdfa9baef] RECEIVED: [1070: /9.152.120.241:53], DatagramDnsResponse(from: /9.152.120.241:53, to: /0.0.0.0:59736, 1070, QUERY(0), Refused(5), RD)
	DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.ibm.com. IN A)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
DEBUG DnsQueryContext - [id: 0xdfa9baef] WRITE: [43763: /9.152.64.172:53], DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.ibm.com. IN A)
DEBUG DnsNameResolver - [id: 0xdfa9baef] RECEIVED: [44153: /9.152.120.241:53], DatagramDnsResponse(from: /9.152.120.241:53, to: /0.0.0.0:59736, 44153, QUERY(0), Refused(5), RD)
	DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.ibm.com. IN AAAA)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
DEBUG DnsQueryContext - [id: 0xdfa9baef] WRITE: [44923: /9.0.136.50:53], DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.ibm.com. IN AAAA)
DEBUG DnsNameResolver - [id: 0xdfa9baef] RECEIVED: [44923: /9.0.136.50:53], DatagramDnsResponse(from: /9.0.136.50:53, to: /0.0.0.0:59736, 44923, QUERY(0), NXDomain(3), RD AA RA)
	DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.ibm.com. IN AAAA)
	DefaultDnsRawRecord(ibm.com. 900 IN SOA 54B)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
DEBUG DnsNameResolver - [id: 0xdfa9baef] RECEIVED: [43763: /9.152.64.172:53], DatagramDnsResponse(from: /9.152.64.172:53, to: /0.0.0.0:59736, 43763, QUERY(0), Refused(5), RD)
	DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.ibm.com. IN A)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
DEBUG DnsQueryContext - [id: 0xdfa9baef] WRITE: [49899: /9.152.120.241:53], DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.speedport.ip. IN A)
DEBUG DnsQueryContext - [id: 0xdfa9baef] WRITE: [45790: /9.152.120.241:53], DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.speedport.ip. IN AAAA)
DEBUG DnsNameResolver - [id: 0xdfa9baef] RECEIVED: [49899: /9.152.120.241:53], DatagramDnsResponse(from: /9.152.120.241:53, to: /0.0.0.0:59736, 49899, QUERY(0), Refused(5), RD)
	DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.speedport.ip. IN A)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
DEBUG DnsQueryContext - [id: 0xdfa9baef] WRITE: [32678: /9.152.64.172:53], DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.speedport.ip. IN A)
DEBUG DnsNameResolver - [id: 0xdfa9baef] RECEIVED: [45790: /9.152.120.241:53], DatagramDnsResponse(from: /9.152.120.241:53, to: /0.0.0.0:59736, 45790, QUERY(0), Refused(5), RD)
	DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.speedport.ip. IN AAAA)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
DEBUG DnsQueryContext - [id: 0xdfa9baef] WRITE: [26064: /9.0.136.50:53], DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.speedport.ip. IN AAAA)
DEBUG DnsNameResolver - [id: 0xdfa9baef] RECEIVED: [26064: /9.0.136.50:53], DatagramDnsResponse(from: /9.0.136.50:53, to: /0.0.0.0:59736, 26064, QUERY(0), NXDomain(3), RD RA)
	DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.speedport.ip. IN AAAA)
	DefaultDnsRawRecord(. 8188 IN SOA 64B)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
DEBUG DnsNameResolver - [id: 0xdfa9baef] RECEIVED: [32678: /9.152.64.172:53], DatagramDnsResponse(from: /9.152.64.172:53, to: /0.0.0.0:59736, 32678, QUERY(0), Refused(5), RD)
	DefaultDnsQuestion(dx-marathon.rtp.raleigh.ibm.com.speedport.ip. IN A)
	DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)

And this for the succeeding case:
log4j: Trying to find [log4j.xml] using context classloader sun.misc.Launcher$AppClassLoader@426f26d3.
log4j: Using URL [file:/C:/d/ContentHub/prod-publishing-manager-scheduler/queues/bin/log4j.xml] for automatic log4j configuration.
log4j: Preferred configurator class: org.apache.log4j.xml.DOMConfigurator
log4j: System property is :null
log4j: Standard DocumentBuilderFactory search succeded.
log4j: DocumentBuilderFactory is: org.apache.xerces.jaxp.DocumentBuilderFactoryImpl
log4j: debug attribute= "null".
log4j: Ignoring debug attribute.
log4j: reset attribute= "false".
log4j: Threshold ="null".
log4j: Level value for root is  [debug].
log4j: root level set to DEBUG
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Setting property [target] to [System.out].
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%-5p %c{1} - %m%n].
log4j: Adding appender named [console] to category [root].
DEBUG InternalLoggerFactory - Using SLF4J as the default logging framework
DEBUG ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
DEBUG ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
DEBUG MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
DEBUG PlatformDependent - -Dio.netty.noUnsafe: false
DEBUG PlatformDependent0 - java.nio.Buffer.address: available
DEBUG PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
DEBUG PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
DEBUG PlatformDependent0 - direct buffer constructor: available
DEBUG PlatformDependent0 - java.nio.Bits.unaligned: available, true
DEBUG PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
DEBUG Cleaner0 - java.nio.ByteBuffer.cleaner(): available
DEBUG PlatformDependent - Platform: Windows
DEBUG PlatformDependent - Java version: 8
DEBUG PlatformDependent - sun.misc.Unsafe: available
DEBUG PlatformDependent - -Dio.netty.noJavassist: false
DEBUG PlatformDependent - Javassist: unavailable
DEBUG PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
DEBUG PlatformDependent - -Dio.netty.tmpdir: C:\Users\IBM_AD~1\AppData\Local\Temp (java.io.tmpdir)
DEBUG PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
DEBUG PlatformDependent - -Dio.netty.noPreferDirect: false
DEBUG PlatformDependent - io.netty.maxDirectMemory: 67108864 bytes
DEBUG NioEventLoop - -Dio.netty.noKeySetOptimization: false
DEBUG NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
DEBUG PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available

**Comment by vietj** [comment]
can you check with latest 3.5.1-SNAPSHOT and reopen if necessary ?
