### ISSUE TITLE
Missing blank after colon in thrown exception message

### ISSUE THREAD

**Issue by adamdickmeiss** [vert-x3/issues#267]
Seems like in most places there is a separator/blank after colon when messages are generated.. But not for 2 of them:
```
adam@nugget:~/folio/vert.x$ find . -name '*.java' -print|xargs grep throw|grep getMessage
...
./src/main/java/io/vertx/core/json/Json.java:      throw new DecodeException("Failed to decode:" + e.getMessage());
./src/main/java/io/vertx/core/json/Json.java:      throw new DecodeException("Failed to decode:" + e.getMessage(), e);
```

**Comment by tsegismont** [comment]
Can you please open a PR in the corresponding project? Thanks

2017-05-11 15:19 GMT+02:00 Adam Dickmeiss <notifications@github.com>:

**Comment by cescoffier** [comment]
I've the file opened in my IDE, gonna fix it.
