### ISSUE TITLE
Resource not found

### ISSUE THREAD

**Issue by pavanshetty05** [vert-x3/issues#269]
Hi Team 
        I am using below code and URL to hit . But it works some time and other time it thrown an error in UI as **Resource not found** . Will you please let me know what is missing ?
    Below is the URL which i am using. Validated that we are using below port 8080 only for this . 
    localhost:8080/api/query/

public class WebEPICVerticle extends AbstractVerticle {

/** The logger. */
private static transient Logger logger = LoggerFactory
		.getLogger(WebEPICVerticle.class);

/*
 * (non-Javadoc)
 * 
 * @see io.vertx.core.AbstractVerticle#start(io.vertx.core.Future)
 */
@Override
public void start(Future<Void> startFuture) {
	logger.info("WebVerticle started!");

	HttpServer server = vertx.createHttpServer();

	Router router = Router.router(vertx);

	router.route("/api/query/").handler(routingContext -> {

			
		HttpServerRequest request = routingContext.request();

		// Business logic is commented  

			response.end(jsonObject.toString());
		});
	server.requestHandler(router::accept).listen(8080);
}

}

**Comment by tsegismont** [comment]
Hi,

It seems my previous comment was misleading. Please use the Vert.x forum
for questions (https://groups.google.com/forum/?fromgroups#!forum/vertx)
The community uses GH issues for actual problems.

Thanks

2017-05-16 10:33 GMT+02:00 pavanshetty05 <notifications@github.com>:

**Comment by cescoffier** [comment]
Marking issue as invalid because it's a question.
