### ISSUE TITLE
io.vertx.scala.ext.web.client.HttpResponse.statusCode always returns 0 via io.vertx.scala.ext.web.client.WebClient

### ISSUE THREAD

**Issue by oysterpack** [vert-x3/issues#270]
HttpResponse.statusCode always returns 0, but the status message reflects the correct status.
    
    scenario("GET / - check HTTP response status using WebClient") { implicit app =>
      assert(app.running)
      runApplicationTest(
        implicit injector => {
          val vertx = inject[Vertx]
          val options = WebClientOptions().setDefaultHost("localhost").setDefaultPort(ServerPort.HTTP.value)
          val client = WebClient.create(vertx, options)
          Await.result(Task.fromFuture(client.get("/").sendFuture()).materialize.runAsync, Duration.Inf) match {
            case Success(response) =>
              log.info(s"response status = ${response.statusCode()} - ${response.statusMessage()}")
              // TODO: there is a bug in the client - it is always returning 0, instead of proper status code (200 in this case)
              // assert(response.statusCode() == HttpStatus.SC_OK)
              assert(response.statusMessage() == "OK")
            case Failure(ex) => fail(ex)
          }
        }
      )
    }
        
The bug lies within the WebClient. When the HttpClient is used directly, then the correct status code is returned.

    scenario("GET / - check HTTP response status using HttpClient") { implicit app =>
      assert(app.running)
      runApplicationTest(
        implicit injector => {
          val vertx = inject[Vertx]
          val options = HttpClientOptions().setDefaultHost("localhost").setDefaultPort(ServerPort.HTTP.value)
          val client = vertx.createHttpClient(options)
          val task = Task.create[(Int, String)] { case (scheduler, callback) =>
            client.getNow("/", response => {
              callback.onSuccess((response.statusCode(), response.statusMessage()))
            })
            Cancelable.empty
          }
          val (statusCode,statusMessage) = Await.result(task.runAsync,Duration.Inf)
          log.info(s"response status : ($statusCode,$statusMessage) ")
          assert(statusCode == HttpStatus.SC_OK)
          assert(statusMessage == "OK")
        }
      )
    }

**Comment by tsegismont** [comment]
Duplicates vert-x3/vertx-lang-scala#35

**Comment by tsegismont** [comment]
@oysterpack this is fixed in master and will be released in 3.4.2

**Comment by oysterpack** [comment]
Thank you for the quick response.
