### ISSUE TITLE
Non blocking JSON parsing support

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/issues#278]
Jackson will soon get support for "non-blocking" parsing, see FasterXML/jackson-core#57

It would be nice to have at least a blog post to explain how to use it with Vert.x Web.

For simple case like JSON arrays it should be possible to provide a `ReadStream` of `JsonObject` from the HTTP request

This would be useful to data intensive apps.

**Comment by vietj** [comment]
good idea! I think it could be handled in core, in a similar fashion than `RecordParser` as it does not require any new external dependency

**Comment by codepitbull** [comment]
This would also solve vert-x3/vertx-lang-scala#25

**Comment by michel-kraemer** [comment]
Just for your interest, I created a non-blocking JSON parser some time ago:
https://github.com/michel-kraemer/actson/

I also included an example for Vert.x:
https://github.com/michel-kraemer/actson/blob/master/examples/src/main/java/vertx/VertxExample.java

Anyway, I suppose if Jackson supports asynchronous parsing this will be the way to go for Vert.x. I just wanted to mention Actson in the hope it is useful for some people. Maybe the Vert.x example can at least be a starting point for the implementation of the support for asynchronous Jackson.

**Comment by vietj** [comment]
@michel-kraemer why don't you blog about it on vertx.io/blog ?

**Comment by michel-kraemer** [comment]
@vietj Isn't this feature already included in Vert.x 3.5.0? I think the issue can be closed, right?

**Comment by vietj** [comment]
indeed!!
