### ISSUE TITLE
hi,I find issues in the Class vertx.SharedData.LocalMap

### ISSUE THREAD

**Issue by king588** [vert-x3/issues#279]
The Method put(K key, V value) ,I think  if had put in Map Value ,so can not change it outside,  so example, 
JsonObject jsonInfo=new JsonObject();
jsonInfo.put("name","myname");
localMap.put("info",jsonInfo);
After,
I change jsonInfo: jsonInfo.put("name","otherName");
So, I think the LocalMap jsonInfo was chaged, 
i want you explain for me, thank you

**Comment by tsegismont** [comment]
This is the contract of LocalMap: only immutable keys/values or certain objects which can be copied (like JsonObject).

**Comment by tsegismont** [comment]
Please use the Vert.x forum for user questions (see vertx.io/community)

**Comment by king588** [comment]
Yes，i know，but in sources code，there no copy operate at  put method ，at get method i see  the copy ，so  i  think  put  method should copy the  object  value
