### ISSUE TITLE
JUnit 5 support

### ISSUE THREAD

**Issue by rodolfodpk** [vert-x3/issues#281]
http://junit.org/junit5/ is almost done and there are many new features and improvements. Vert.x tests should leverage it.

**Comment by jponge** [comment]
I have started investigations on this front. I will share a prototype soon.

**Comment by jponge** [comment]
I have made solid progress here.

I will share a prototype at worst by next week, sooner hopefully :-)

**Comment by blandger** [comment]
@jponge It there any progress on this? Is there any sources available somewhere?
I would be good to have ability to initialize Spring dependencies wired to Vertx instance from Spring context. It's really helpful to wire up all in one test.
Have ability use Mockito in bundle also very desirable.

**Comment by jponge** [comment]
Tonight or tomorrow, the code is ready :-)

**Comment by jponge** [comment]
https://github.com/jponge/vertx-junit5

**Comment by blandger** [comment]
@jponge Seems very promising, I will check it this days.

I see error in unit test.
/vertx-junit5/src/test/java/io/vertx/ext/junit5/IntegrationTest.java
void start_and_request_http_server_with_checkpoints()
It fails because port = 8080  is busy by other started server.
If I change it to 8081 it works fine.

**Comment by blandger** [comment]
@jponge I was able to do some checks.

I was able to run Vertx junit5 test with SpringExtention (for Spring 4.x) + VertxExtention together.
It wires up Spring beans ok and makes VertxTestContext available in test methods. The VertxTestContext interface has changed from previous junit4 version.

So all looks quite good. I suppose wiring up some stubs with MockitoExtention should work too.

**Comment by jponge** [comment]
Awesome, thanks for your feedback!

**Comment by jponge** [comment]
Marking this issue as resolved, although I'll do some Vert.x stack integration work next week.
