### ISSUE TITLE
Caffeine cache support

### ISSUE THREAD

**Issue by rodolfodpk** [vert-x3/issues#282]
http://vertx.io/docs/apidocs/io/vertx/rxjava/core/shareddata/LocalMap.html is great for local cache but it misses a lot of manageability that https://github.com/ben-manes/caffeine already has. It would be nice to have a Caffeine / Vertx integration in order to work with the cache within the event loop.

**Comment by rodolfodpk** [comment]
I noticed there is a way to  work with cache from event loop: http://vertx.io/docs/vertx-hazelcast/java/#_using_hazelcast_async_methods.

**Comment by laurentvaills** [comment]
Hi @rodolfodpk , 
I am also interested into using Caffeine and Vertx together. But I don't understand why you closed the issue. How did you solve it ? 

Regards,
Laurent

**Comment by rodolfodpk** [comment]
Hey @laurentvaills 
The main requirements I had when I opened it:
1) Local cache (not distributed)
2) Lazy entry loading (to implicitly load elements not in cache)
3) Expiration policies (to evict older cache entries and save RAM)
4) to fit well the Vertx async api

So far, I decided to wrap the cache operations within a vertx executeBlocking and using https://github.com/jhalterman/expiringmap instead of Caffeine. Caffeine seems more advanced but I don't need all that features. Expiringmap is fine for my requirements: https://github.com/crabzilla/crabzilla/blob/master/crabzilla-core/src/main/java/io/github/crabzilla/vertx/verticles/CommandVerticle.kt

But I still need to try the Hazelcast async api I mentioned above. Hazelcast has lazy load data from db (http://docs.hazelcast.org/docs/3.10.3/manual/html-single/index.html#loading-and-storing-persistent-data) and also has some expiration policies. 

Any read or write cache operation can block. I guess it would be easier to integrate Vertx with a cache library designed to be async since its conception.
 
Regards,
Rodolfo

**Comment by laurentvaills** [comment]
Thanks for your details. 

Actually Caffeine has both synchronous and asynchronous cache implementation: https://github.com/ben-manes/caffeine/wiki/Population#asynchronously-loading

Hazelcast is mostly interesting if you need a distributed cache. I've played a bit with it few years ago and that was really simple to use. 

Regards,
Laurent

**Comment by javenwang** [comment]
Hi @laurentvaills, should we use `buildAsync()` with `AsyncCacheLoader` instead of `CacheLoader`? The latter calls `asyncLoad()` method with default Executor, `ForkJoinPool`, which may break Vert.x's threading model.

**Comment by tsegismont** [comment]
When configure Caffeine, you could provide an `Executor` that invoke the async loader on the verticle context.

Would you like to contribute a post about the trick on the Vert.x blog?

**Comment by rodolfodpk** [comment]
@tsegismont What if the loading computation involves a blocking IO operation (pure jdbc, etc) ?

**Comment by tsegismont** [comment]
@rodolfodpk the code will be invoked on a Vert.x context so you can invoke
executeBlocking and complete the async loader eventually

**Comment by javenwang** [comment]
hi @tsegismont , I don't know if I do it in the right way, and here is [my solution](https://stackoverflow.com/questions/55270732/how-do-i-correctly-launch-kotlin-coroutines-to-implement-a-caffeine-asyncloading/56471133#56471133):

Define an extension function of `CoroutineVerticle`

```kotlin
fun <K, V> CoroutineVerticle.buildCache(configurator: Caffeine<Any, Any>.() -> Unit = {}, loader: suspend CoroutineScope.(K) -> V) = Caffeine.newBuilder().apply(configurator).buildAsync { key: K, _ ->
    // do not use cache's executor
    future {
        loader(key)
    }
}
```

Create our cache within `CoroutineVerticle`

```kotlin
val cache : AsyncLoadingCache<String, String> = buildCache({
  maximumSize(10_000)
  expireAfterWrite(10, TimeUnit.MINUTES)
}) { key ->
    // load data and return it
    delay(1000)
    "data for key: $key"
}
```

Use the cache

```kotlin
suspend fun doSomething() {
    val data = cache.get('key').await()

    val future = cache.get('key2')
    val data2 = future.await()
}
```

I always avoid to use `executeBlocking()`, because the ThreadPool will dry up quickly if QPS is high.

**Comment by rodolfodpk** [comment]
@tsegismont Do you mean something like this? (it works) 

```java
package com.mylab;

import com.github.benmanes.caffeine.cache.AsyncLoadingCache;
import com.github.benmanes.caffeine.cache.Caffeine;
import io.vertx.core.Vertx;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import me.escoffier.vertx.completablefuture.VertxCompletableFuture;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executor;
import java.util.concurrent.TimeUnit;
import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(VertxExtension.class)
class VertxCaffeineAsyncTest {
  @Test
  void asyncTest(VertxTestContext tc, Vertx vertx) {
    AsyncLoadingCache<String, Integer> cache = Caffeine.newBuilder()
      .executor(vertx.nettyEventLoopGroup())
      .maximumSize(10_000)
      .expireAfterWrite(10, TimeUnit.MINUTES)
      .buildAsync((key, executor) -> buildIntegerFromKey(vertx, key, executor));
    System.out.println("test thread: " + Thread.currentThread());
    // Lookup and asynchronously compute an entry if absent
    CompletableFuture<Integer> val1 = cache.get("1");
    tc.verify(() -> assertThat(val1.get()).isEqualTo(1));
    CompletableFuture<Integer> val2 = cache.get("2");
    tc.verify(() -> assertThat(val2.get()).isEqualTo(2));
    tc.completeNow();
  }

  private CompletableFuture<Integer> buildIntegerFromKey(Vertx vertx, String key, Executor executor) {
    final CompletableFuture<Integer> future = new VertxCompletableFuture<>(vertx);
    executor.execute(() -> vertx.<Integer>executeBlocking(event -> {
      System.out.println("async load thread #1: " + Thread.currentThread());
      try { // just simulating some blocking IO
        Thread.sleep(1000);
        event.complete(new Integer(key));
      } catch (InterruptedException e) {
        e.printStackTrace();
        event.fail(e);
      }
    }, event2 -> {
      System.out.println("async load thread #2: " + Thread.currentThread());
      if (event2.succeeded()) {
        future.complete(event2.result());
      } else {
        future.completeExceptionally(event2.cause());
      }
    }));
    return future;
  }
}
```

When I ran it, it passed and printed: 

```
test thread: Thread[main,5,main]
async load thread #1: Thread[vert.x-worker-thread-0,5,main]
async load thread #2: Thread[vert.x-eventloop-thread-2,5,main]
async load thread #1: Thread[vert.x-worker-thread-1,5,main]
async load thread #2: Thread[vert.x-eventloop-thread-6,5,main]
```

**Comment by tsegismont** [comment]
Your test passes, but I wouldn't use the Netty EL group as executor, because when you're implementing a verticle, you want to have async cache loading executing on the verticle context.

I used Caffeine in a benchmark for GraphQL. Here's how the cache is created:

https://github.com/tsegismont/graphql-server-benchmark/blob/master/Java/vertx-graphql-java/src/main/java/com/github/graphql/server/benchmark/vertx/ServerVerticle.java#L209-L211

And the contextExecutor:

https://github.com/tsegismont/graphql-server-benchmark/blob/master/Java/vertx-graphql-java/src/main/java/com/github/graphql/server/benchmark/vertx/ServerVerticle.java#L67-L68

**Comment by domherro** [comment]
@tsegismont Hi. 

Maybe i misunderstood something. If the executor is the eventloop-thread (based on the code in your last reply) for the async caffeine support buildAsync method, what´s the difference with the non-async cache build method? I mean, that portion of code will be executed in the eventloop thread for non-async caffeine cache. If caffeine is fast when perform operations, the performance impact will not be affected in the thread, but i´m not sure about that. 

Is this correct? Thnx!

**Comment by tsegismont** [comment]
@domherro you need the async build method if loading the value involves an async method call (for example sending a query to a dabase). If loading the value is a matter of simple computation, then indeed the async build is not needed.
