### ISSUE TITLE
Vertx 3.4.2: receive a file using netSocket

### ISSUE THREAD

**Issue by SELLAM** [vert-x3/issues#286]
i'm trying to receive un file from a netSocketClient in vetrx 3.4.2, this is my code:

> 
> NetServerOptions options = new NetServerOptions().setPort(10000);
> NetServer netserver = vertx.createNetServer(options);
> netserver.connectHandler(sock -> {
> 
>     System.out.println("Incoming connection!");
>     sock.handler(buffer-> {
>        String dd = buffer.getString(0,buffer.length());
>        System.out.println("new Buffer: "+dd);
>        sock.write("From serveur: "+buffer.getString(0, buffer.length()));
>     });
> 
>     sock.closeHandler(v -> {
>        System.out.println("The socket has been closed");
>     });
> }).listen();

but i receive a decoped buffer.

my question is how i can get the end buffer of the file in a single buffer?

can someone help me please?

**Comment by SELLAM** [comment]
I try this and it's working:

> StringBuffer buff = new StringBuffer();
> sock.handler(buffer-> {
>         String dd = buffer.getString(0,buffer.length());
>         if(dd.contains("EOT")){
>                dd = dd.replace("EOT", "");
>                buff.append(dd);
>         }else{
>                buff.append(dd);
>         }
> });

**Comment by vietj** [comment]
you can try this:

```
Buffer b = Buffer.buffer();
sock.handler(b::append);
```

however keep in mind you can get OOM using this.
