### ISSUE TITLE
Getting java.lang.NoClassDefFoundError: io/vertx/core/file/FileSystemException

### ISSUE THREAD

**Issue by michaelpog** [vert-x3/issues#288]
Hi I wrote a simple http server in Groovy.
However I am having some unexpected behavior when  running the server with maven, and without.

This is the repo to reproduce everything I'm going to describe https://github.com/michaelpog/vertx-http-server-groovy (https://github.com/michaelpog/vertx-http-server-groovy.git)
First of all when I run the HTTP server using a maven plugin, I'm getting this stack trace in the end:
mvn clean install
```
Exception in thread "Thread-13" java.lang.NoClassDefFoundError: io/vertx/core/file/FileSystemException
	at io.vertx.core.file.impl.FileSystemImpl.deleteInternal(FileSystemImpl.java:585)
	at io.vertx.core.file.impl.FileSystemImpl.deleteRecursive(FileSystemImpl.java:212)
	at io.vertx.core.impl.FileResolver.deleteCacheDir(FileResolver.java:315)
	at io.vertx.core.impl.FileResolver.lambda$setupCacheDir$1(FileResolver.java:304)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.vertx.core.file.FileSystemException
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more
```
The plugin simply runs the http server Groovy script.
Looking at the exception it looks like it is trying to access the file system and it's failing. I don't want to / need to use the file system.

I looked through the documentation http://vertx.io/docs/vertx-web/java/#_disabling_file_caching_on_disk and tried everything
I started by simply running the http server directly in my IDE, and I see that after every time I exit the application I see a new folder created in my src directly under .vertx/ the name is something like file-cache-xxxxxxx... 
I looked at this part of the documentation:
"To disable file caching you can provide your vert.x options the property fileResolverCachingEnabled to true"
And was completely confused, setting "fileResolverCachingEnabled" to true is supposed to disable? or enabled? I tried both:
```
def options = new VertxOptions();
options.setFileResolverCachingEnabled(false/true);
def vertx = Vertx.vertx(options)
``` 
Nothing really changed, every time I run the server in the IDE, and exit I get a new cache directory. And in maven I get the same stack trace dump.

After having a discussion about it here:
https://groups.google.com/forum/?fromgroups=#!topic/vertx/golo_ZibZts

Thomas suggested to use this flag -DdisableFileCPResolving (I'm guessing it's a system property for java), I tried that, and tried -DdisableFileCPResolving = true, nothing changed.
In fact I could not even find that documented anywhere, but I saw another flag documented:
"For backwards compatibility it will also default that value to the system property vertx.disableFileCaching"

Tried that and also nothing worked, regardless I need some programatic solution because the maven plugin I'm using is running the Groovy script directly from maven and doesn't pass any JVM properties.

Can you please help us  with all the above issues I'm having?
Thanks in advance

**Comment by michaelpog** [comment]
Has anyone had a chance to look into it?

**Comment by vietj** [comment]
can someone provide a reproducer ? I would be happy fixing this :-)

**Comment by vietj** [comment]
ah there is one linked :-)

**Comment by vietj** [comment]
I will have a look

**Comment by vietj** [comment]
this issue happens when the script ends when the JVM exits.

if you add a pause at the end of your script, it runs, for instance I've added:

```
    server.requestHandler(router.&accept).listen(8888)
    // Prevent the JVM to exit
    System.in.read()
```

it seems there is a classloading issue that prevents the shutdown hook to cleanup the cache dir. You can disable the cache dir with the _vertx.disableFileCPResolving_ property.

**Comment by vietj** [comment]
The classloading issue may be related to the fact that it happens when the JVM shutdowns, perhaps that the ClassRealm class refuses to load some classes at this moment. If I set a reference to this class in the script it works ok.

**Comment by vietj** [comment]
Also you can try close the Vert.x instance in a try/finally block of your script, that will eagerly delete the directory without the shutdown hook.

**Comment by michaelpog** [comment]
@vietj thanks for looking into it, I'm trying to understand the suggestions that you provided:
1) vertx.disableFileCPResolving I am not sure where it's documented and how to use it. Thomas suggested -DdisableFileCPResolving you suggest  vertx.disableFileCPResolving, I just tried running with -Dvertx.disableFileCPResolving, doesn't seeem to make any difference. And I don't know how to even pass that to the maven groovy plugin. 

2) I tried wrapping with try finally, it doesn't make any difference, neither when I run the server directly, nor when I run it from maven.

**Comment by vietj** [comment]
have you set a pause in your script ?

**Comment by michaelpog** [comment]
Yes I did, and It doesn't make any difference.
```
server.requestHandler(router.&accept).listen(8888)
System.in.read()
```
So now when I run mvn install, it stops and then when I press any key, mvn continues and I see this
```
Exception in thread "Thread-2" java.lang.NoClassDefFoundError: io/vertx/core/file/FileSystemException
	at io.vertx.core.file.impl.FileSystemImpl.deleteInternal(FileSystemImpl.java:585)
	at io.vertx.core.file.impl.FileSystemImpl.deleteRecursive(FileSystemImpl.java:212)
	at io.vertx.core.impl.FileResolver.deleteCacheDir(FileResolver.java:315)
	at io.vertx.core.impl.FileResolver.lambda$setupCacheDir$1(FileResolver.java:304)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.vertx.core.file.FileSystemException
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 5 more```

I'm also not sure how it was supposed to solve the problem that there's no way to disable vertx from writing to file system. as I mentioned before, none of the options actually worked.

**Comment by vietj** [comment]
what I mean is this happen when the JVM exits and if you don't have a pause your server will be shutdown.

have you tried to close the created Vertx instance in a finally block ?

**Comment by michaelpog** [comment]
Ok that made some difference.
```
server.requestHandler(router.&accept).listen(8888)
    System.in.read()
}finally {
    server.close()
    vertx.close()
}
```
Now It works fine I don't see anything created  in the .vertx directory (not using any additional flags and maven doesn't dump that stack trace.
That's good progress however it's a solution since I need that System.in.read() to prevent from calling the finally and close the server right away, and mvn plugin is run by a Continuous Integration server and there's no human to press any key to move to the finally part. 
Even not in the maven context, it is very unusual for a server application to block the thread with a  System.in.read() to prevent incorrect shutdown.

**Comment by vietj** [comment]
the `System.in` pause seems necessary because of the maven plugin. For instance if you look at this netty example you can see it blocks as well https://github.com/netty/netty/blob/4.0/example/src/main/java/io/netty/example/echo/EchoServer.java

**Comment by michaelpog** [comment]
@vietj Thanks again for helping out with this.
I'm not sure I understand how we are expected to send anything into the standard input of an application ran by maven on a Continuous Integration server in an automated build context. And I also believe that we are not addressing the problem here.  Netty doesn't write anything to the Filesystem that the devs need to deal with. 
Vert.x Does.

The problem/bug that we need to address here is the fact that there's no way to turn off Vert.x writing to filesystem. 
The solution should be a working configuration that I can set to VertxOptions that will prevent Vertx from accessing filesystem. 
In fact it seems like this http://vertx.io/docs/apidocs/io/vertx/core/VertxOptions.html#setFileResolverCachingEnabled-boolean- is supposed to do exactly that, but it's not working. 
This is the bug, this should be solved.
Adding delays in code is not the solution.

Can any of the Vert.x Developers please fix this bug?
Thanks in advance

**Comment by vietj** [comment]
@michaelpog I think there is confusion here.

I am just saying that if you don't add a pause, then your server will just not be launched because the groovy script will exit before the http server is started, making your integration test fail.

I said to use `System.in.read()` as pause but probably that in your case it should be a different pause (for instance until an event occurs), that prevents the script to exit until your test has finished to use the script.

does it make sense ?

**Comment by vietj** [comment]
besides in your case, you should close the vertx instance in a finally block which will properly close the file system, because the JVM exit hook set by Vert.x seems to fail to execute properly due to what I suspect the shutdown procedure of the maven plugin / classloading.

that being said I have not said that there is no bug related to filesystem caching.

**Comment by vietj** [comment]
the `enableCaching` flag does not control wether the `.vertx` directory is created or not. It control wether or not caching is using during file resolving.

the `.vertx` directory is used by the file cache and the classpath resolver (in `.vertx/file-cache-$UUID`). So to be sure that the `.vertx` dir is not created you should disable both caching and CP resolving

**Comment by michaelpog** [comment]
Ok thank you @vietj I understand what you mean, and if I do want to use caching then I will have to figure out a way to shut down the server in the finally. And I am sure there's a bug because even when I'm not using maven, and I run the vertx server in the IDE and then shut it down, I see the .vertx directory still remains. I have it in production, and in all my verx git repos in the .gitignore because it's created an stays everywhere which is really annoying

```
So to be sure that the .vertx dir is not created you should disable both caching and CP resolving
```
So to my original question: How do I do that?
How do I disable caching and CP resolving?
How do I do it in code so that I can run the http server from maven, and I will be guaranteed that filesystem will not be accessed?
Nothing I've tried actually succeeded, and the documentation on this is lacking unfortunately.

**Comment by vietj** [comment]
@michaelpog you should set the system property of the JVM : `vertx.disableFileCPResolving=true` and `vertx.disableFileCaching=true`, the later can also be set on the VertxOptions with `fileCachingEnabled=false`. Probably we should have something similar for the former.

Some other vertx projects uses the `.vertx` directory (like the http service factory).

I'm thinking that this directory should be retrieved from `VertxInternal` in a unified way and could also be a directory in the `/tmp` dir instead.

**Comment by michaelpog** [comment]
@vietj that worked. It would be great if this could be documented somewhere in your official documentation, and also it would be helpful if both could be set programatically.
Thank you for your help

**Comment by vietj** [comment]
@michaelpog will address this
