### ISSUE TITLE
Vertx websocket client doest not automatically send pong reply to server when ping is received

### ISSUE THREAD

**Issue by dgoetsch** [vert-x3/issues#290]
I have been trying to use the vertx websocket client for a distributed load test against a websocket application.  I have configured my server to send Ping messages, and expect a response pong.  When I connect with a glassfish tyrus client, the ping/pong works, but not so with vert.x websocket client As far as I understand, the client should automatically respond with a PONG, but it doesn't not respond to ping messages, and I cannot figure out how to do so manually, and I can't even see them from the client side with the vertx client.  The client is closed by the server because it did not receive the pong from the ping, and the client close handle is invoked.

client configuration:

```
vertx.createHttpClient(HttpClientOptions().setSsl(appConfig.useSsl).setTcpKeepAlive(true).setKeepAlive(true).setIdleTimeout(5000)) //I tried this with and without the keepAlives or idleTimeout
```

websocket code:

```
client.websocket(
                requestOptions,
                MultiMap.caseInsensitiveMultiMap().add(HttpHeaders.ORIGIN, appConfig.origin),
                { webSocket: WebSocket ->

                    webSocket.exceptionHandler { error ->
                        LOG.error("[$name] caught error from active socket: $error")
                        LOG.debug(error.stackTrace.joinToString("\n\t\t"))
                    }

                    webSocket.closeHandler {
                        LOG.info("[$name] webSocket has been closed")
                    }

                    webSocket.frameHandler {
                        LOG.info("[$name] received frame: $it")
                    }

                    webSocket.binaryMessageHandler {
                        LOG.info("[$name] received binary message: $it")
                    }

                    webSocket.textMessageHandler { textMessage: String ->
                        LOG.info("[$name] received binary message: $it")   
                    }
                },
                { failure: Throwable ->
                    LOG.error("[$name] caught error when opening connection: $failure")
                    LOG.debug(failure.stackTrace.joinToString("\n\t\t"))
                })
```
I can't find instructions on how to do thisfrom the client in the documentation, but I have seen instructions on how to do this on the server.  The code for HTTPClientImpl does not reference ping or pong, but the server does.  Is this a defect, or am I missing something important?

**Comment by dgoetsch** [comment]
I found int he ClientHandler, where it receives the ping, but the call to 

`chctx.writeAndFlush(new WebSocketFrameImpl(FrameType.PONG, frame.getBinaryData()))`

doest not appear to actually write the data out to the server.

**Comment by vietj** [comment]
can you provide a reproducer test ?

**Comment by dgoetsch** [comment]
I will, but I won't be able to get to it until at least mid next week.

**Comment by dgoetsch** [comment]
I made a little exemplar project to express the problem I've been running into: https://github.com/dgoetsch/vertx-web-socket-test

I recently ran into a problem where sustained web client sessions would stop working.  Somehow, the server and client had a brief network interruption that severed communications, and when the server would attempt to send a message to the client, it would block that thread and be unable to clean it up because it couldn't tell the connection had died. (Byzantine General's Problem...)  I can't offer any details about the client or the problem domain, beyond websocket server with a large number of sustained websocket clients.  

Here is a simplified version of the solution I came up with (we currently have to use tyrus for session management due to business reasons.. and oracle): https://github.com/dgoetsch/vertx-web-socket-test/blob/master/web-socket-server/src/main/kotlin/dev/yn/playground/web/socket/server/tyrus/EchoWebSocketEndPoint.kt;  This example implements a keep alive by sending a ping every 1 second and expecting a pong back within 2 seconds; this is done to keep connections alive even if some arbitrary timeout is reached, and allows the server to detect if a connection has been lost or not. This implementation allows one to fully separate network health from application logic, and allows the application to clean up system resources effectively without wasting resources on dead connections.

The connection should stay alive as long as the client responds to ping messages with a pong, and will be killed as long as commmunications cease.  I was able to use the application properly with a javascript client and a tyrus client, but the vertx client I used for load testing would not sustain a connection with the tyrus server because the server never received a pong.  From the vertx api I have no access into the ping/pong mechanism, though I've altered the code locally to have it Log a message when it replies with a pong, and the client does hit the appropriate line in `io.vertx.core.http.impl.ClientHandler:115`, but the server never receives the pong. Moreover, when I use a vertx server rather than the glassfish server, the server never initiates the ping/pong.

Where do we go next?  I think we need a formal test case, however without ping/pong being accessible from the API, I'm not sure how we could write a unit tests.  There are unit tests that currently validate the ping/pong functionality, but that functionality does not work when run as part of an actual application.  Can you provide some thoughts or guidance? I really like the vertx websocket api, and I want to use it on my project, but I won't be able to unless I can solve this issue.

**Comment by zella** [comment]
I tired investigate issue and found that `WebSocketClientProtocolHandler` never instantiated in netty. But I may be wrong

Also I put breakpoint at `WebSocketProtocolHandler::decode` and it never breaks

**Comment by dgoetsch** [comment]
I've created an MR, I'll have to figure out how to get rights and finish the MR.. for now I've fixed the client:
https://github.com/eclipse/vert.x/pull/2107

**Comment by dgoetsch** [comment]
I believe I have fully resolved the issue in https://github.com/eclipse/vert.x/pull/2107
