### ISSUE TITLE
Duplicate Eventbus message received on v3.3.3 in non clustered mode

### ISSUE THREAD

**Issue by neal-eiger** [vert-x3/issues#292]
I have observed what appears to be a duplicate message received by the eventbus MessageConsumer.handler method.  Our logs show only one message was sent but it was received and handled twice.  We will upgrade now to version 3.4.2, but has this been reported before?

**Comment by tsegismont** [comment]
Did you use send or publish? How many receiver verticle instances do you
have?

**Comment by neal-eiger** [comment]
Hi there!  Thank you, you are right, we published.  But as we normally have only a single receiver we have never seen this before.  It is possible there was mistakenly a second handler deployed.  I'll close this as it could well be our issue there.  Many thanks.
