### ISSUE TITLE
Invalid Handling of MaxHeaderListSize lead to ignore configuration value

### ISSUE THREAD

**Issue by ylemoigne** [vert-x3/issues#293]
Hi,

On vertx 3.4.2
Using the configuration :
```
HttpServerOptions options = new HttpServerOptions()
            .setInitialSettings(new Http2Settings().setMaxHeaderListSize(Integer.MAX_VALUE))
            .setUseAlpn(true)
            .setSsl(true)
            .setKeyStoreOptions(new JksOptions()
                .setPath(ServerConfig.CONFIG_KEYSTORE)
                .setPassword(ServerConfig.CONFIG_KEYSTORE_PASSWORD))
            .setJdkSslEngineOptions(new JdkSSLEngineOptions())
            .setPort(Integer.parseInt(ServerConfig.getInstance().getPort()));
```

If headers exceed limit `10240`, then vertx fail :
```
Sep 05, 2017 2:53:53 PM io.vertx.core.net.impl.ConnectionBase
SEVERE: io.netty.handler.codec.http2.Http2Exception: Header size exceeded max allowed size (10240)
```

After some investigation, it seem to come from `io.vertx.core.http.Http2Settings` where :
```
public static final int DEFAULT_MAX_HEADER_LIST_SIZE = Integer.MAX_VALUE;
```

When this value is read by : `io.vertx.core.http.impl.HttpUtils`
```
public static void fromVertxInitialSettings(boolean server, io.vertx.core.http.Http2Settings vertxSettings, Http2Settings nettySettings) {
    if (vertxSettings != null) {
      [...]
      if (vertxSettings.getMaxHeaderListSize() != DEFAULT_MAX_HEADER_LIST_SIZE) {
        nettySettings.maxHeaderListSize(vertxSettings.getMaxHeaderListSize());
      }
      [...]
    }
  }
```

They do not differ, so it's not updated. But by default, netty use `8192` as seen from `io.netty.handler.codec.http2.Http2CodecUtil`:
```
public static final long DEFAULT_HEADER_LIST_SIZE = 8192;
```

This value is used in `io.netty.handler.codec.http2.AbstractHttp2ConnectionHandlerBuilder`

Workaround :
```
HttpServerOptions options = new HttpServerOptions()
            .setInitialSettings(new Http2Settings().setMaxHeaderListSize(Integer.MAX_VALUE-1))
```

I think the fix should be to change `io.vertx.core.http.Http2Settings. DEFAULT_MAX_HEADER_LIST_SIZE` value to either `8192` or `io.netty.handler.codec.http2.Http2CodecUtil. DEFAULT_HEADER_LIST_SIZE`.

**Comment by vietj** [comment]
can you contribte a test and fix for this ?

**Comment by ylemoigne** [comment]
I can try.

**Comment by vietj** [comment]
thanks

**Comment by ylemoigne** [comment]
Done : https://github.com/eclipse/vert.x/pull/2114
It's seems there is an agreement to sign, and the commit have to be signed.... :(
If you can send me a link on the procedure to follow (if really needed)

**Comment by vietj** [comment]
reopen with a new PR that fixes it with ECA valid

**Comment by laurentvaills** [comment]
Hi guys. 
Any news on this problem? 
@vietj I was not able to find that new PR that you were talking about.

We ran into that issue recently.

**Comment by vietj** [comment]
this https://github.com/eclipse-vertx/vert.x/pull/2114

**Comment by vietj** [comment]
I'll have a look myself today

**Comment by laurentvaills** [comment]
> this [eclipse-vertx/vert.x#2114](https://github.com/eclipse-vertx/vert.x/pull/2114)

Ok then that's the one I found, I thought there was another one. 
Thanks to have a look Julien.

**Comment by vietj** [comment]
- https://github.com/eclipse-vertx/vert.x/pull/4212
- https://github.com/eclipse-vertx/vert.x/pull/4213
- https://github.com/eclipse-vertx/vert.x/pull/4214
