### ISSUE TITLE
ProxyHelper.createProxy call delay 

### ISSUE THREAD

**Issue by xiaoxianqian** [vert-x3/issues#296]
when i do pressure test, i get a delay problem of "ProxyHelper.createProxy ":

`DevServ serv = ProxyHelper.createProxy(DevServ.class, gVertx, MsgAddr.makeDevAddr(ccid));
serv.sendCmd(cmd, params, resultHandler);  // this line delay`

with hawtio to monitor vertx, workpoolsize should be enough. I set workpoolsize = 4000, and it has 3500 handlers more or less.

is the delay caused by event bus delay?  or some other problem?

dose event bus have priority?

dose the parameter topLevel of function registerService has some advantage?
`MessageConsumer<JsonObject> registerService(Class<T> clazz, Vertx vertx, T service, String address, boolean topLevel, long timeoutSeconds)`

**Comment by vietj** [comment]
what is workpoolsize ?

**Comment by xiaoxianqian** [comment]
new VertxOptions().setWorkerPoolSize(workerPoolSize)

**Comment by xiaoxianqian** [comment]
I find the problem: I broken The Golden Rule - Don’t Block the Event Loop...

**Comment by vietj** [comment]
3000 is a very huge size for the worker pool. The handlers on the event bus are by default handled by the event loop, if they are workers, then worker thread are shared from the pool between the handlers
