### ISSUE TITLE
The close of Websocket returns a status code of 1005 instead of 1000

### ISSUE THREAD

**Issue by WangHansen** [vert-x3/issues#297]
From MDN docs, status code 1005 or 1006 should be used when the websocket abnormally closed (ref: https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent)

But calling the close method from the client results in a status code of 1005

Here is the client function: 
```javascript
  close () { 
    let self = this 
      if (this.socket !== null) { 
        self.socket.close() 
      } 
    } 
  } 
```

And the server side function:
```java
  websocket.closeHandler(data -> {
    System.out.println("Websocket closed!");
  });
```

**Comment by Sparcks** [comment]
Hi @WangHansen , seems that nobody answered your question. You may probably have found the reason (or not), but I do wanted to reply as I had the same "issue".

If you close the socket without a parameter, it will automatically use code 1005. this means: 'No Status Received'. You can find all codes here: https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent#Status_codes

So you have to give the code yourself if you know you are doing a normal close. Info about that can be found here: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close#Parameters 

Hope this helps someone.

**Comment by vietj** [comment]
thanks for helping @Sparcks I'll close the issue

**Comment by pipoupiwam** [comment]
Thanks @Sparcks ! 

A list of status codes for websockets : https://github.com/Luka967/websocket-close-codes
