### ISSUE TITLE
Add support for Stomp

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/issues#30]
Stomp: https://stomp.github.io/

**Comment by pmlopes** [comment]
FYI: i've written a stomp frame parser and client for vert.x2 code is here:

https://github.com/pmlopes/mod-stomp-io

reusing the frame parser in vert.x3 is trivial in case you want it...

**Comment by cescoffier** [comment]
Just a comment to track progress:

- [ ] Server connection
- [ ] Implement frame parser
- [ ] Subscription management
- [ ] Ack policy in subscription
- [ ] Transaction management
- [ ] Ack policy in transactions
- [ ] Encoding / Decoding of headers
- [ ] Content-Length computation (option)
- [ ] Receipt support
- [ ] Implement size limits (options)
- [ ] Support CONNECT and STOMP frames
- [ ] Support CONNECTED frames
- [ ] Support SSL (client and server)
- [ ] Implement security mechanism
- [ ] Implement heartbeat (client and server)
- [ ] Implement protocol negotiation
- [ ] Support SEND frames and MESSAGE frames
- [ ] Manage SUBSCRIBE / UNSUBSCRIBE 
- [ ] Add transaction operation on client
- [ ] Cleanup on connection close (server and client)
- [ ] Support DISCONNECT 
- [ ] Support the 'message' header in ERROR
- [ ] Implement an event bus bridge (same options as sockJS)
- [ ] Tests against ActiveMQ
- [ ] Tests against Artemis
- [ ] Tests against RabbitMQ

**Comment by cescoffier** [comment]
I will need a new repository (vertx-stomp).

**Comment by cescoffier** [comment]
Work done here: https://github.com/vert-x3/vertx-stomp/tree/initial-work

**Comment by cescoffier** [comment]
The last item will be tracked in another issue: https://github.com/vert-x3/vertx-stomp/issues/1

the vert.x ecosystem has several bridges (TCP, SockJS), configuration should be similar, and actually, only the transport layer is different. So, it should all be based on the same structure.

**Comment by cescoffier** [comment]
The current implement is ready to be reviewed.

**Comment by cescoffier** [comment]
Work to do after first code review:

- [ ] Add author tags
- [ ] Remove useless property in `pom.xml` file
- [ ] Replace `AcknowledgementHandler` by `Handler<Acknowledgement>`
- [ ] Move default handlers to the main package
- [ ] Use a local shared map to manage subscriptions
- [ ] Replace the client and server frame handlers by simple handlers
- [ ] Use vertx-auth to manage authentication
- [ ] Replace frame handler by a simple handler
- [ ] Replace `Frames` by something using VertxGen
- [ ] Rename `getOptions` by `options()`
- [ ] Rename `begin` by `beginTX`
- [ ] Add a `disconnect` method taking a `Frame` as parameter
- [ ] Remove `ack(Frame)` and `nack(Frame)`
- [ ] Hide transaction and subscription methods from `StompServerHandler`
- [ ] move transaction and subscription to `impl`
- [ ] Implement transaction size limit
- [ ] Replay transaction by chunk (option - 1000 by default)
- [ ] Remove ack / nack timeout
- [ ] Check that when a connection is closed, the subscription is removed
- [ ] Limit the number of subscription a client can create
- [ ] Use `String.charAt(pos)` in the encoder / decoder
- [ ] Execute the `close` handler asynchronously 
- [ ] Use nanoTime
- [ ] Use a single periodic timer for the heartbeat (is this possible)
- [ ] Remote the ` vertx.runOnContext` in `connect`
- [ ] find a way to support queue and bridge destination
- [ ] check the cumulative ACK in `client` mode
- [ ] use queue peek and poll in `ack` (SuscriptionImpl`
