### ISSUE TITLE
TemplateEngine.render() is discarding first char of templateFileName parameter

### ISSUE THREAD

**Issue by ralleal** [vert-x3/issues#300]
[Version 3.4.2]

Hi, I was using the depcretated TemplateEngine.render (HandlebarsTemplateEngine), so I changed to the other one with separated template folder and template name, like this:

            engine.render(ctx, "templates", "app.hbs", res -> {
                if (res.succeeded()) {
                    ctx.response().end(res.result());
                } else {
                    ctx.fail(res.cause());
                }
            });

But then I started getting the error:
 io.vertx.core.file.FileSystemException: java.nio.file.NoSuchFileException: templates/pp.hbs

The "a" in "app.hbs" is being ignored, so I had to include an extra char (a space) when calling the function, like this:  engine.render(ctx, "templates", " app.hbs", res -> { ...

Most certainly a bug in Vert-X, so I decided to file a bug.

**Comment by tsegismont** [comment]
The TemplateEngine#render method says:

    NOTE if you call method directly (i.e. not using
io.vertx.ext.web.handler.TemplateHandler) make sure that templateFileName
is sanitized via io.vertx.ext.web.impl.Utils.normalizePath(String)

So in your case, the leading slash is missing. Try with:

    engine.render(ctx, "templates", "/app.hbs", res -> {

2017-10-09 15:24 GMT+02:00 ralleal <notifications@github.com>:

**Comment by ralleal** [comment]
I haven't noticed the NOTE in TemplateEngine#render, and yes, I guess it works if I use a "/", but also with any other character (a space, "i", etc). I don't think it's the best behavior, but it it's not really seen as a bug, the issue may be ignored.

**Comment by wesbiggs** [comment]
I agree with @ralleal; this behavior is confusing and could be easily addressed by only removing the first character if it is a '/'.

It also seems impossible to specify a template that's not in a subdirectory. I've tried using "" (the empty string), ".", and "/" for the templateDirectory argument, all to no avail. Arguably, having templates at the root level is unwise, but it broke our code when upgrading from 3.4.1 to 3.5.2.
