### ISSUE TITLE
During the redeploy period , the http server not working

### ISSUE THREAD

**Issue by ghost** [vert-x3/issues#301]
During the redeploy period,, the server can not be access. 
```
Starting vert.x application...
77544b32-4662-41f6-a250-d7d976d2fb96-redeploy
Oct 11, 2017 1:40:11 PM io.vertx.core.impl.launcher.commands.Watcher
INFO: Redeployment done in 2622 ms.
``
Is it possible to redeploy smothly like PHP? not break the running server

**Comment by vietj** [comment]
no it is not possible to achieve it with the redeployer.

can could achieve it by adding a proxy in front of the server or by moving your logic in a verticle accessed by the event bus and only re-deploying this verticle.

**Comment by ghost** [comment]
Thanks. I am looking for smooth redeploy solution.
Currently seems playframework can do smoth redeploy

**Comment by vietj** [comment]
Can you open an issue about supporting this in this repo (label it with whishlist ), so we can discuss its feasability ?
