### ISSUE TITLE
JWT decode issue

### ISSUE THREAD

**Issue by neterium-dev** [vert-x3/issues#304]
Hi !

I'm using the vertx JWT auth provider, but I'm behind an API gateway which does all the signature checks etc.... for me already. So I basically use the provider to further (re)check the token expiration and to receive my User which will then be used for the authorization (role checks).

I noticed in the JWT.class code that the decode could be 'secure' or 'unsecure'; well that's fine, I'm unsecure in my case, but still got an exception, which should not be raised in my opinion:

`List<Crypto> cryptos = cryptoMap.get(alg);

    if (cryptos == null || cryptos.size() == 0) {
      throw new RuntimeException("Algorithm not supported");
    }

    // if we only allow secure alg, then none is not a valid option
    if (!unsecure && "none".equals(alg)) {
      throw new RuntimeException("Algorithm \"none\" not allowed");
    }`

In my case, 'cryptos' is null and I get that "Algorithm not supported" exception... But if in "unsecure" mode, 'cryptos' is not used anywhere and the JWT should just be decoded, checked and returned.

Thanks,

**Comment by pmlopes** [comment]
Issue moved to [vert-x3/vertx-auth #168](https://github.com/vert-x3/vertx-auth/issues/168) via [**ZenHub**](https://www.zenhub.com/)
