### ISSUE TITLE
Native memory leak

### ISSUE THREAD

**Issue by yanivpl5** [vert-x3/issues#306]
We are using Vertx 4.4.2 that uses netty 4.1.8
We experienced native memory leaks in Vertx that cause the process memory footprint to grow to several giga bytes beyond the usual.
After long investigation we found that netty is allocation native memory buffer which cause the leak.
The only way to limit netty is by adding -XX:MaxDirectMemorySize argument to the application startup script.
This worked for sometime but when using Vertx API vertx.fileSystem().readFile() which create Vertx Buffer we got null buffer.
Vertx Buffer is a wrapper around netty ByteBuf which probably means that netty was unable to allocate buffer.
I would be gratefully if anyone can help with that.
Maybe the new Vertx version (3.5) can solve this but didn't try it yet.

**Comment by tsegismont** [comment]
@yanivpl5 Have you tried with Vert.x 3.5? Could you provide a reproducer?

**Comment by yanivpl5** [comment]
A little more info that I collected regarding the problem:

1. It happends on Linux servers (CentOS) and does not happen in Windows.
2. It leads to Netty consuming sometimes several Giga bytes of ram.
3. The scenario that cause this: is many client downloading large file from the server (about 24Mbyte).
4. The client issue https requests (the server uses open SSL) for the file download.
5. The server send Buffer object and sends it in the rsponse body.
6. In Vert.x 3.5 it happends too.

I will try to create reproducer, not sure it will be simple.

**Comment by vietj** [comment]
@yanivpl5 any news about this ?

**Comment by yanivpl5** [comment]
We understood that we need to limit the number of concurrent client that receive large data.
We implement throttling mechanism based on counter of the active clients being handled.
This was a tricky one and we understood that when the response committed using the response end() method, Netty is handling the sending of the response to the client asynchronously and we have no idea when Netty completed sending the response.
This caused several hundreds of open connections concurrently consuming several giga bytes eventually leading to heap OutOfMemory.
The solution was to use AsyncInputStream from [Vertx Wizdom Engine](https://github.com/wisdom-framework/wisdom/tree/master/core/wisdom-vertx-engine) and Pump see example 16 [here](https://www.programcreek.com/java-api-examples/index.php?api=io.vertx.core.streams.Pump)
This way we have control of the rate of clients being handled.
We also use -XX:MaxDirectMemorySize to limit memory size.
Maybe we were flooding Netty with too many active connections handling large data consuming too much native memory. The key was to understand that Netty is working in the background after the response is committed.

**Comment by vietj** [comment]
it's not clear wether you are consuming too much memory or if you have an effective leak, i.e memory which is not released after usage, can you clarify ?

**Comment by yanivpl5** [comment]
I found that our throttling mechanism that was supposed to limit the number of concurrent clients was buggy. There for we reached hundreds of clients downloading 12MByte file. This lead to Netty consuming large amount of memory eventually crashing the application. I don't think that we had memory leak we just didn't analzed the situation correctly.

**Comment by vietj** [comment]
I'm assuming we can close this issue
