### ISSUE TITLE
A new project created with "sbt new" does not run out-of-the-box

### ISSUE THREAD

**Issue by dimitardi** [vert-x3/issues#307]
How to reproduce:
1. execute `sbt new vert-x3/vertx-scala.g8` and answer the questions (name, package)
2. open the new project in intelliJ by "File > New > Project from existing sources... > SBT"
3. execute in Terminal `sbt clean compile run`

Output:
```
 [3] → sbt compile run
...
[info] Loading project definition from ...
[info] Set current project to ...
[success] Total time: 0 s, completed Nov 3, 2017 12:34:46 PM
java.lang.RuntimeException: No main class detected.
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) No main class detected.
[error] Total time: 0 s, completed Nov 3, 2017 12:34:46 PM
```

**Comment by codepitbull** [comment]
Sorry, this is currently not supported.
I will take a look to see how/if I can make this work but right now you can use:
- The sbt-built-in Scala-console
- the Fat-jar
- the Docker image

Take a look at the README, there you will find the examples.

**Comment by codepitbull** [comment]
I opened a new issue in the appropriate project (https://github.com/vert-x3/vertx-scala.g8/issues/2)
Closing this and working on the other one.
