### ISSUE TITLE
Vertx zookeeper error

### ISSUE THREAD

**Issue by mscofy** [vert-x3/issues#308]
I am using vertx with zookeeper as my cluster manager. Suddenly I started getting this excpetion in my logs:

   ERROR io.vertx.spi.cluster.zookeeper.ZookeeperClusterManager - Failed to handle memberRemoved
io.vertx.core.VertxException: java.io.InvalidClassException: io.vertx.spi.cluster.zookeeper.impl.ZKSyncMap$KeyValue; local class incompatible: stream classdesc serialVersionUID = -472487054773491211, local class serialVersionUID = -6066652933022630380
    at io.vertx.spi.cluster.zookeeper.impl.ZKSyncMap.get(ZKSyncMap.java:95)
How can I fix it?

Regards, Ido

**Comment by cescoffier** [comment]
Can you open your issue on https://github.com/vert-x3/vertx-zookeeper
