### ISSUE TITLE
DNS client is not working

### ISSUE THREAD

**Issue by michaelpog** [vert-x3/issues#312]
Hi I have created a reproducer:
https://github.com/michaelpog/vertx-dns-resolver/blob/master/src/main/java/Main.java

All I'm getting is 
{code}
io.vertx.core.VertxException: DNS query timeout for vertx.io
{code}
I've tried localhost instead of "10.0.0.1"
I've tried every possible hostname, I'm getting the same exception.
As I mentioned here https://groups.google.com/forum/?fromgroups#!topic/vertx/aezJMoxESpQ

I've also tried to downgrade the version of Vertx core to 3.4.2. When I do that, I never ever even get into the callback.
I've also tried all lookupX and resolveX methods.
Please advice.
(Running on MacOs Sierra)

**Comment by vietj** [comment]
will have a try

**Comment by vietj** [comment]
what is `10.0.0.1` ? your DNS resolver ?

**Comment by vietj** [comment]
it sounds like a bug indeed, the datagram sent does not have the recursion desired flag set to true which leads to no answer

**Comment by vietj** [comment]
can you open this issue in eclipse/vert-x repository instead ?

**Comment by vietj** [comment]
fixed here https://github.com/eclipse/vert.x/issues/2232

**Comment by vietj** [comment]
can you give a try ? and you should use a DNS server in your example (i.e not `10.0.0.1` which is a example), for instance `8.8.8.8` (Google's DNS server)

**Comment by michaelpog** [comment]
Yes, I will give it a try.

**Comment by michaelpog** [comment]
@vietj I'm not able to get the 3.5.1 dependency using maven and I don't see it in the releases

**Comment by alexlehm** [comment]
@michaelpog its a snapshot version, you have to add the sonatype snapshot repo to the maven project

**Comment by michaelpog** [comment]
Thanks @alexlehm.
@vietj  that worked with Google's DNS server (8.8.8.8:53)
When do you think the 3.5.1 will be out?

Also on a completely separate note.
I'm not very familiar with DNS.
What address should I use for the DnsClient to behave exactly like the internal DnsResolver the the HttpClient is using ( I believe it's netty's implementation)
As I described I'm using this DnsClient explicitly in my code to implement a cache that would store the addresses and if there's an issue with the Dns Resolution I have the addresses cached.

**Comment by vietj** [comment]
we aim for 3.5.1 early 2017.

the `DnsClient` will behave differently than the `DnsResolver` because the resolver does more (it's a resolver with a different logic) than the client. You can use the `DnsResolver` directly you can use the internal API by casting `Vertx` to `VertxInternal` and use the `AddressResolver` provided. It's internal but given the logic is simple, it will not impact much your application if we change the API.

**Comment by michaelpog** [comment]
Ok if you think it's safe to use the VertxInternal AddressResolver then I will actually prefer to use that.
Is it possible to simply make the vertx.addressResolver part of the public API instead? 
I don't want update to a future version of Vertx and end up breaking my code because that was a private API that I used.

Thank you!

**Comment by alexlehm** [comment]
If you are sure your dns resolves everything you need, you do not need to use address resolver, this supports resolving from /etc/hosts, dns suffixes and some other stuff.
You have to figure out your dns ip from resolv.conf (and failover) though.

**Comment by vietj** [comment]
@michaelpog thing is that it's more correct than just using a DNS client that will not perform resolution. I prefer keep it internal instead for the moment and think what is the best way to expose it.

**Comment by michaelpog** [comment]
That's my point, to use DnsClient I need to explicitly figure out the dns ip address. which kind of ties my code to a particular infrastructure, but the implementation of the AddressResolver doesn't require you to know anything ( I haven't looked at the code to know how it does that).
It seems like it would be a good idea to have that functionality in the DnsClient that is exposed to the user rather than me having to get a reference to an internal object.

**Comment by vietj** [comment]
I think we can safely expose the address of the DNS server used by the internal DNS resolver.

is that what you mean ? for instance : createDNSClient() without the server address that uses the resolver server address.

**Comment by michaelpog** [comment]
Correct.

**Comment by vietj** [comment]
that's something easily doable and that makes sense to me

**Comment by vietj** [comment]
https://github.com/eclipse/vert.x/issues/2239
