### ISSUE TITLE
LocalMap computeIfPresent incorrect behaviour

### ISSUE THREAD

**Issue by vkhomytskyi** [vert-x3/issues#313]
LocalMap's implementation of `io.vertx.core.shareddata.LocalMap#computeIfPresent` doesn't make it possible to remove entry by returning null in `remappingFunction` because of `io.vertx.core.shareddata.impl.Checker#checkType` that is being applied to check type of returning value

**Comment by vietj** [comment]
have you checked if that behavior applies to other methods ?

**Comment by vkhomytskyi** [comment]
The same applies to all methods with `remappingFunction`, like `computeIfAbsent`, `compute`, `merge`, etc.

**Comment by vietj** [comment]
@Sammers21 interested by this issue ?

**Comment by Sammers21** [comment]
@vietj, sure, I will work on it.

**Comment by vietj** [comment]
thanks for the contribution @Sammers21
