### ISSUE TITLE
io.vertx.core.http.HttpClient#websocketStream claims to be fluent, but is not

### ISSUE THREAD

**Issue by wu-lee** [vert-x3/issues#319]
I've noticed the javadoc for this family of functions all say:

> Returns: a reference to this, so the API can be used fluently

Whereas they all return a `ReadStream<WebSocket>`.

Presumably this is a mistake in the documentation?

**Comment by tsegismont** [comment]
@wu-lee nice catch. Yes probably a copy/paste... Would you mind to fix it?

**Comment by wu-lee** [comment]
I'll have to track down which repository to check out, etc., but I might try.  Perhaps you could encourage me by giving me some information on the use case for method and its return value of `ReadStream<WebSocket>`? It is puzzling me. (I am a vertx newbie.)

**Comment by tsegismont** [comment]
The repo is https://github.com/eclipse/vert.x

Just update the `io.vertx.core.http.HttpClient` Javadoc broken `@return` tags. The methods return a stream emitting a `WebSocket` event when the client connection has been upgraded to a websocket.

**Comment by vietj** [comment]
should have been merged
