### ISSUE TITLE
Provide a link to documentation for older versions of Vert.x

### ISSUE THREAD

**Issue by InfoSec812** [vert-x3/issues#325]
I am working in Red Hat OpenShift Application Runtimes and thus limited to using certain APIs in version 3.4.2 and earlier. There does not appear to be a simple way to view the older versions of the Documentation from the Vert.x web site. It would be awesome if we could view documentation from older versions of Vert.x easily.

**Comment by cescoffier** [comment]
This is plan. I'm going to work on a first attempt next week.

**Comment by InfoSec812** [comment]
PING - Is there anything I can do to help here? I have some cycles over the next 3 weeks.

**Comment by vietj** [comment]
you can download them from Bintray in the meantime.

**Comment by InfoSec812** [comment]
@vietj How do I find that... I searched bintray.com and only found the Maven artifacts

**Comment by vietj** [comment]
https://bintray.com/vertx/downloads/distribution

**Comment by cescoffier** [comment]
It has been fixed in the website, but seem broken since 3.5.0
https://github.com/vert-x3/vert-x3.github.io/tree/master/docs.

The latest released didn't update the website correctly. Will fix it Today.

**Comment by cescoffier** [comment]
Fixed, the documentation of previous versions is available on:

https://vertx.io/docs/$version

For instance:

* https://vertx.io/docs/3.5.1
* https://vertx.io/docs/3.5.2
