### ISSUE TITLE
WebClient response always executed in the main thread? (question)

### ISSUE THREAD

**Issue by dasantos** [vert-x3/issues#331]
While testing in a really slow device, I got a **thread blocked warning** (using the default 2000 ms) when processing the response.

This code raises warnings and then io.vertx.core.VertxException: Thread blocked

    Future<Void> future = Future.future();
    vertx.executeBlocking(status -> {

        // mock
        final String endpoint = "endpoint";
        final short timeout = 30000;

        WebClient client = WebClient.create(vertx);

        client.getAbs(endpoint).timeout(timeout).send(ar -> {
            if (ar.succeeded()) {

                // Obtain response
                HttpResponse<Buffer> response = ar.result();

                // do stuff with the response
                // ...
                // --> WARNING and then io.vertx.core.VertxException: Thread blocked
                
                future.complete();

            } else {
                status.fail("message");
            }
        });

    }, res -> {
        if (res.failed()) {
            future.fail(res.cause());
        } else {
            future.complete();
        }
    });
    return future;

but this code works as expected:

    Future<Void> future = Future.future();

    vertx.executeBlocking(status -> {

        // mock
        final String endpoint = "endpoint";
        final short timeout = 30000;

        WebClient client = WebClient.create(vertx);

        client.getAbs(endpoint).timeout(timeout).send(ar -> {
            if (ar.succeeded()) {

                // parse succeeded response in an executeBlocking call
                vertx.executeBlocking(hanleResp -> {
                    // Obtain response
                    HttpResponse<Buffer> response = ar.result();

                    // do stuff with the response
                    // ...
                    // No warnings, everything OK
                    
                    hanleResp.complete();

                }, res -> {
                    if (res.failed()) {
                        status.fail(res.cause());
                    } else {
                        status.complete();
                    }
                });

            } else {
                status.fail("message");
            }
        });

    }, res -> {
        if (res.failed()) {
            future.fail(res.cause());
        } else {
            future.complete();
        }
    });
    return future;

I'm quite new to vertx. Am I doing something wrong? It seems that response is being executed in the main thread. Shouldn't the (async) response be handled the same way as is the code inside vertx.executeBlocking(...) method?

Thank you.

**Comment by vietj** [comment]
can you show the stack trace to give more context ?

**Comment by dasantos** [comment]
Stacktrace:

Feb 20 17:14:31 xxx YYY[6797]: Feb 20, 2018 5:14:31 PM io.vertx.core.impl.BlockedThreadChecker
Feb 20 17:14:31 xxx YYY[6797]: WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2057 ms, time limit is 2000
Feb 20 17:14:32 xxx YYY[6797]: Feb 20, 2018 5:14:32 PM io.vertx.core.impl.BlockedThreadChecker
Feb 20 17:14:32 xxx YYY[6797]: WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3058 ms, time limit is 2000
Feb 20 17:14:33 xxx YYY[6797]: Feb 20, 2018 5:14:33 PM io.vertx.core.impl.BlockedThreadChecker
Feb 20 17:14:33 xxx YYY[6797]: WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4057 ms, time limit is 2000
Feb 20 17:14:34 xxx YYY[6797]: Feb 20, 2018 5:14:34 PM io.vertx.core.impl.BlockedThreadChecker
Feb 20 17:14:34 xxx YYY[6797]: WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5058 ms, time limit is 2000
Feb 20 17:14:34 xxx YYY[6797]: io.vertx.core.VertxException: Thread blocked
Feb 20 17:14:34 xxx YYY[6797]: at java.lang.System.nanoTime(Native Method)
Feb 20 17:14:34 xxx YYY[6797]: at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
Feb 20 17:14:34 xxx YYY[6797]: at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
Feb 20 17:14:34 xxx YYY[6797]: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
Feb 20 17:14:34 xxx YYY[6797]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._property(POJOPropertiesCollector.java:1046)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:445)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:308)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:287)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:170)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:164)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:239)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:329)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:313)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:252)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:245)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:168)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4179)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3997)
Feb 20 17:14:34 xxx YYY[6797]: at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
Feb 20 17:14:34 xxx YYY[6797]: at io.vertx.core.json.Json.decodeValue(Json.java:122)
Feb 20 17:14:34 xxx YYY[6797]: at com.company.project.provision.ProvisioningServiceVerticle.lambda$getProvisioningStatus$4(ProvisioningServiceVerticle.java:255)
Feb 20 17:14:34 xxx YYY[6797]: at com.company.project.provision.ProvisioningServiceVerticle$$Lambda$104/31084266.handle(Unknown Source)
Feb 20 17:14:34 xxx YYY[6797]: at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
Feb 20 17:14:34 xxx YYY[6797]: at io.vertx.ext.web.client.impl.HttpContext$$Lambda$135/18497326.handle(Unknown Source)
Feb 20 17:14:34 xxx YYY[6797]: at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
Feb 20 17:14:34 xxx YYY[6797]: at io.vertx.core.impl.ContextImpl$$Lambda$28/18679878.run(Unknown Source)
Feb 20 17:14:34 xxx YYY[6797]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
Feb 20 17:14:34 xxx YYY[6797]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
Feb 20 17:14:34 xxx YYY[6797]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
Feb 20 17:14:34 xxx YYY[6797]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
Feb 20 17:14:34 xxx YYY[6797]: at java.lang.Thread.run(Thread.java:748)
Feb 20 17:14:35 xxx YYY[6797]: Feb 20, 2018 5:14:35 PM io.vertx.core.impl.BlockedThreadChecker
Feb 20 17:14:35 xxx YYY[6797]: WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 6058 ms, time limit is 2000
Feb 20 17:14:35 xxx YYY[6797]: io.vertx.core.VertxException: Thread blocked
Feb 20 17:14:35 xxx YYY[6797]: at java.lang.ClassLoader.findBootstrapClass(Native Method)
Feb 20 17:14:35 xxx YYY[6797]: at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1015)
Feb 20 17:14:35 xxx YYY[6797]: at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
Feb 20 17:14:35 xxx YYY[6797]: at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
Feb 20 17:14:35 xxx YYY[6797]: at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
Feb 20 17:14:35 xxx YYY[6797]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder._findRequired(POJOPropertyBuilder.java:652)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getMetadata(POJOPropertyBuilder.java:220)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.SettableBeanProperty.<init>(SettableBeanProperty.java:136)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.impl.FieldProperty.<init>(FieldProperty.java:46)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.constructSettableProperty(BeanDeserializerFactory.java:829)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:553)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:258)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:168)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4179)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3997)
Feb 20 17:14:35 xxx YYY[6797]: at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
Feb 20 17:14:35 xxx YYY[6797]: at io.vertx.core.json.Json.decodeValue(Json.java:122)
Feb 20 17:14:35 xxx YYY[6797]: at com.company.project.provision.ProvisioningServiceVerticle.lambda$getProvisioningStatus$4(ProvisioningServiceVerticle.java:255)
Feb 20 17:14:35 xxx YYY[6797]: at com.company.project.provision.ProvisioningServiceVerticle$$Lambda$104/31084266.handle(Unknown Source)
Feb 20 17:14:35 xxx YYY[6797]: at io.vertx.ext.web.client.impl.HttpContext.lambda$null$0(HttpContext.java:125)
Feb 20 17:14:35 xxx YYY[6797]: at io.vertx.ext.web.client.impl.HttpContext$$Lambda$135/18497326.handle(Unknown Source)
Feb 20 17:14:35 xxx YYY[6797]: at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
Feb 20 17:14:35 xxx YYY[6797]: at io.vertx.core.impl.ContextImpl$$Lambda$28/18679878.run(Unknown Source)
Feb 20 17:14:35 xxx YYY[6797]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
Feb 20 17:14:35 xxx YYY[6797]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
Feb 20 17:14:35 xxx YYY[6797]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
Feb 20 17:14:35 xxx YYY[6797]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
Feb 20 17:14:35 xxx YYY[6797]: at java.lang.Thread.run(Thread.java:748)
