### ISSUE TITLE
io.vertx.ext.web.client.HttpRequest does not have any getters for testing

### ISSUE THREAD

**Issue by michaelpog** [vert-x3/issues#340]
The interface of io.vertx.ext.web.client.HttpRequest  does not have any getters that correspond to the setters it has.
So for example it would be very nice if for
```
  @Fluent
  HttpRequest<T> method(HttpMethod value);
```
it would also have a 
```
HttpMethod getMethod()
```

For   
```
HttpRequest<T> ssl(boolean value);
```
if would also have
``` 
boolean isSsl()
```

It is very useful for unit test purposes where you have a method that sets those parameters and returns an HttpRequest
and we can assert on every value that was set in HttpRequest using getters.

Thank you

**Comment by vietj** [comment]
feel free to make a PR

**Comment by michaelpog** [comment]
Will do

**Comment by michaelpog** [comment]
@vietj I created a branch with those additions.
I'm trying to push the branch and I'm getting a 
```
iphone:vertx-web-client mpogrebinsky$ git push origin feature/340
remote: Permission to vert-x3/vertx-web.git denied to michaelpog.
fatal: unable to access 'https://github.com/vert-x3/vertx-web.git/': The requested URL returned error: 403
```
Do I need to get permissions to push the feature branch to submit a pr?

**Comment by vietj** [comment]
only vertx committers can push to these repo, you just need to make a  PR from your own fork

**Comment by michaelpog** [comment]
Thank you @vietj here is the pr https://github.com/vert-x3/vertx-web/pull/867

**Comment by michaelpog** [comment]
I think we can close this one? @vietj
