### ISSUE TITLE
Better documentation combining service proxies and RX-ification

### ISSUE THREAD

**Issue by jponge** [vert-x3/issues#341]
Service proxies provide a compelling way to define and consume functional units in a service.

It is also possible to use code generation to provide language-specific variants around the callback-based proxies. It is especially appealing to provide a _Reactive eXtension_ variant of a service proxy interface.

This is already present in the [Vert.x examples](https://github.com/vert-x3/vertx-examples/blob/1938513e237ac7daa30fa9fbf3efe6e112e2b7e9/service-proxy-examples/service-provider/pom.xml#L90), but the overall Vert.x documentation can be improved to explicitly explain how to combine service proxies and their _Rx-ification_.

It would also be worth expanding the example to Gradle builds.

**Comment by tsegismont** [comment]
@jponge can you elaborate about where you thought the doc should be improved?

**Comment by jponge** [comment]
We can close this one :-)
