### ISSUE TITLE
Osgi descriptor update

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#342]
motivation: the vertx polyglot support in the vertx stack has changed since Vert.x 3.5.1 with a new layout on the stack artifacts. Osgi descriptor are likely not up to date anymore.
change: osgi descriptors needs to be updated to reflect this new status.

**Comment by cescoffier** [comment]
As an example, I've provided the OSGi metadata for the Vert.x Circuit Breaker a few days ago.

This task should also cover the OSGi metadata of the polyglot task themselves (and this is going to be the hardest part)

**Comment by vietj** [comment]
@cescoffier ping

**Comment by cescoffier** [comment]
I know @vietj  but no time for now.

**Comment by cescoffier** [comment]
Most of them have been provided, we can close this issue and open issue specifically in each repository.
