### ISSUE TITLE
The HTTP client pool should manage per host connections with a configurable LIFO or FIFO strategy

### ISSUE THREAD

**Issue by michaelpog** [vert-x3/issues#350]
I'm using Vert.x 3.5.0 (Vertx Core 3)

Assuming I have a connection pool size of 2, I have noticed an undesirable behavior of how the connections are managed by the ConnectionManager.

Assuming two connections are already created in the connection pool (TCP stream 0 and TCP stream 1)
What I noticed is the following scenario:
My application sends a request to host:port on TCP stream 0 at time T
Then a response from host:port comes back at T+1
Then I send another request to host:port, and instead of reusing stream 0, it's actually picking steam 1 at time T+2

I have a screen shot I took with Wireshark that follows the two TCP streams:
![screen shot 2018-04-09 at 12 07 43 pm](https://user-images.githubusercontent.com/7913776/38523728-4b3fa062-3c01-11e8-9be5-09163eaa61c3.png)
![screen shot 2018-04-09 at 12 11 08 pm](https://user-images.githubusercontent.com/7913776/38523729-4b588820-3c01-11e8-862a-1842610ade83.png)

As you can see at time 0.0000 a request is sent on stream 0 from 10.31.32.203 (my app)
and the response comes back at time 0.030363 (event #3)
So that stream is available for the next request, but at time 0.409870 (event 5) the next request is actually sent on steam 1.
So it looks like it's doing round robin.

after that another request is sent at 17.211581 (event 84) on steam 1, and the response comes back at 17.245042 (event 85) and instead of sending the next request on steam 1, it's actually go to stream 0 again at time 28.02570 (event #119)

Looking at this sequence of events, only one TCP stream could be used for all the requests and the other could stay idle and be closed.

Looking at the class that is responsible for that io.vertx.core.http.impl.Http1xPool
 (which is gone in the current master)
I see that the availableConnections is a Queue (ArrayDeque)
connections are taken from the front of the queue
```
 @Override
  public ClientConnection pollConnection() {
    return availableConnections.poll();
  }
```

But are recycled to the end of the queue
```
public void recycle(ClientConnection conn) {
    synchronized (queue) {
      Waiter waiter = queue.getNextWaiter();
      if (waiter != null) {
        queue.deliverStream(conn, waiter);
      } else if (conn.getOutstandingRequestCount() == 0) {
        // Return to set of available from here to not return it several times
        availableConnections.add(conn);
      }
    }
  }
```
I think what makes more sense, is not a queue but a stack
So assuming 2 connection on the stack.
You pick the top one, and if you're done with it ,you put it back on the stack, next time the same connection would be reused and the bottom connection stays idle and eventually would expire and disappear.
That would be more efficient, in terms of number of connections that stay open. (which is critical in our case since we are opening a lot of connections to our downstream partners, and they have limitations on the number of connections we can open to them.

I see that that Http1xPool was replaced with a more complex class 
https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/pool/Pool.java
which I don't understand its logic 100%. But what I see is 
```
private final Deque<Holder<C>> available;                         // Available connections
```
And acquireConnection(..) is still taking the connection from the front:
```
private boolean acquireConnection(Waiter<C> waiter) {
    if (available.size() > 0) {
      Holder<C> conn = available.peek();
      if (--conn.capacity == 0) {
        available.poll();
      }
...
```
and  recycleConnection(..) still adds the connection to the end:
```
 private void recycleConnection(Holder<C> conn, int c, boolean closeable) {
    long newCapacity = conn.capacity + c;
    if (newCapacity > conn.concurrency) {
      log.debug("Attempt to recycle a connection more than permitted");
      return;
    }
    if (closeable && newCapacity == conn.concurrency && waitersQueue.isEmpty()) {
      available.remove(conn);
      conn.capacity = 0;
      connector.close(conn.connection);
    } else {
      if (conn.capacity == 0) {
        available.add(conn);
      }
      conn.capacity = newCapacity;
    }
  }
```
which should be 
```
available.addFirst(conn)
```
instead 

What do you think @vietj ?
Would you like me to submit a PR to fix that?

**Comment by vietj** [comment]
@michaelpog I think we could make that configurable (AsyncHttpClient has a `PoolLeaseStrategy` with LIFO and FIFO values), but this would be done in master with the new pool.

**Comment by vietj** [comment]
I've renamed the issue to reflect more the issue we want to address

**Comment by michaelpog** [comment]
Yes @vietj that would be fantastic!
And it makes perfect sense to have that configurable. Different users may have different preferences.
And I appreciate you giving this ticket a much better title

**Comment by michaelpog** [comment]
@vietj please see my pull request https://github.com/eclipse/vert.x/pull/2383
I struggled with adding unit tests for that, the way ConnectionPoolTest is written, I could not find a good way to test it, but the change looks pretty straightforward
