### ISSUE TITLE
vert-x with api gateway

### ISSUE THREAD

**Issue by ryrun168** [vert-x3/issues#351]
Hi Team,

I have started using vert-x, does the vert-x can acting as reverse proxy (zuuls or Spring Cloud Gateway)?

Regards

**Comment by vietj** [comment]
you can use Vert.x has a very scalable api gateway but you need to do it yourself with Vert.x Web and Vert.x Web Client

**Comment by brasseld** [comment]
@ryrun168 if you don't want to implement it by yourself, there is already an API Gateway based on Vert.x: https://github.com/gravitee-io/gravitee-gateway

**Comment by ryrun168** [comment]
@brasseld thanks for share.
