### ISSUE TITLE
Typo in keys for shiro ldap provider documentation.

### ISSUE THREAD

**Issue by Anuj-Chauhan** [vert-x3/issues#355]
[https://vertx.io/docs/vertx-auth-shiro/java/](url)

The keys have **hyphens** instead of **underscores** in documentation. 
Example: ldap-user-dn-template instead of ldap_user_dn_template.

Source LDAPProviderConstants.java in vertx-auth-shiro:3.5.1.

![image](https://user-images.githubusercontent.com/8949980/38912819-289dbb16-42f5-11e8-8302-c9a333dc66c5.png)

![image](https://user-images.githubusercontent.com/8949980/38912828-329240a6-42f5-11e8-8da3-4243aa0448e1.png)

**Comment by vietj** [comment]
make a PR here https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-shiro/src/main/asciidoc/index.adoc

**Comment by Anuj-Chauhan** [comment]
Thanks!
I see it is already fixed in the the above link only the official website [https://vertx.io/docs/vertx-auth-shiro/java/](url) is to be updated. :)
