### ISSUE TITLE
Allocate the body handler buffer with the body size when the content-length header is set

### ISSUE THREAD

**Issue by michaelpog** [vert-x3/issues#362]
Hi, It is not a bug but really a good optimization that I think needs to be put in place.
In  ```io.vertx.ext.web.handler.impl. BodyHandlerImpl``` a new BHandler is created for every incoming HTTP request.
However in that BHandler a new body buffer https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java#L113 is created with a size of 1024 bytes.

At the point of the creation of BHandler here https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/BodyHandlerImpl.java#L70 
the headers are already available, including the Content-Length header, which tells us exactly how much memory to allocated for the body buffer in BHandler.
This can reduce the resizing and copying of the body buffer for big HTTP requests.

In some cases the content-length may not be present so we may have a default of 1024.
@vietj, would you like me to create a pull request for that?

**Comment by vietj** [comment]
yes @michaelpog that's a good contribution I think, keep in mind you need to check the initial size does not exceed bodyLimit, also I think that we could fail fast in case the initial size exceeds the bodyLimit instead of waiting the buffers are received.

**Comment by vietj** [comment]
I hope this is tested in the current tests otherwise it should be added.

**Comment by vietj** [comment]
see line 181 : if we forget that it measn that vertx-web body handler is sensitive to attacks, so you need to come up with a test that sends an content-length with an insane size (like 10 gigas)

**Comment by michaelpog** [comment]
Ok @vietj I will look into this

**Comment by michaelpog** [comment]
https://github.com/vert-x3/vertx-web/pull/918
