### ISSUE TITLE
TrustOptions should either implement Cloneable or remove clone() method

### ISSUE THREAD

**Issue by testn** [vert-x3/issues#363]
clone() method implies Cloneable interface but it does not implement Cloneable interface. This seems like a potential security issue as reported by findbugs.

**Comment by vietj** [comment]
can you elaborate why it's a security issue ?

**Comment by testn** [comment]
https://sourceforge.net/p/findbugs/bugs/511/

**Comment by vietj** [comment]
I think then we should rather rename the clone operation to "copy" instead.

that's what we use in other places like JsonObject and JsonArray

**Comment by testn** [comment]
+1 and they should probably be a default method ?

**Comment by vietj** [comment]
no, this interface is not intended to be implemented by users, it's more a conveniency for copying.

let's scope this issue for Vert.x 4 and rename the title to rename the clone method to copy
