### ISSUE TITLE
HikariCP connection pool, Connections is not closed???

### ISSUE THREAD

**Issue by laudylcp** [vert-x3/issues#365]
### Version

* vert.x core: 3.5.0
* vert.x jdbc-client: 3.5.0
* jdbc driver:
![default](https://user-images.githubusercontent.com/23287431/39686104-b8c1b860-51f9-11e8-95d6-71c9b02bbbba.png)

* RDBMS: Mysql 5.7

### General info

* What is your jdbc driver
![default](https://user-images.githubusercontent.com/23287431/39686108-c41c64e4-51f9-11e8-8897-087b68a72ca5.png)

* What is your RDBMS server
Mysql 5.7

* What is your connection string (no user/passwords please!)
![connstr](https://user-images.githubusercontent.com/23287431/39686241-79bf1c74-51fa-11e8-898a-c05db5ff6edb.png)

### Extra
![default](https://user-images.githubusercontent.com/23287431/39686080-84f0b64e-51f9-11e8-9f51-860bc61be940.png)

Why??
It looks like connections is not be closed???

My code is below:
![default](https://user-images.githubusercontent.com/23287431/39686326-0088cd9a-51fb-11e8-89fc-39eb7c7c96a8.png)

but log is:
![default](https://user-images.githubusercontent.com/23287431/39686404-644cb724-51fb-11e8-9dc4-d5399c048753.png)

if success, the log is:
![default](https://user-images.githubusercontent.com/23287431/39686442-932cdf38-51fb-11e8-8f96-be2b51bb1d09.png)

Please give me help, Thanks very much!!

**Comment by tsegismont** [comment]
The `autoReconnect=true`and `autoReconnectForPools=true` url params look suspicious to me.

Anyway, could you put together a small reproducer on GH to show the problem? Code in screenshots is impossible to work with. Thank you

**Comment by laudylcp** [comment]
@tsegismont Occasionally this happens, and sometimes it doesn't take a whole day to run.

DeviceVehicleServiceImpl.java:

public class DeviceVehicleServiceImpl implements IDeviceVehicleService {

    private static final Logger logger = LoggerFactory.getLogger(DeviceVehicleServiceImpl.class);

    private static Vertx vertx;

    private RedisDeviceVehicleRepositoryImpl redisDeviceVehicleRepository;

    private MysqlDeviceVehicleRepositoryImpl mysqlDeviceVehicleRepository;

    public DeviceVehicleServiceImpl(Vertx vertx){
        this.vertx = vertx;
        this.redisDeviceVehicleRepository = new RedisDeviceVehicleRepositoryImpl(vertx);
        this.mysqlDeviceVehicleRepository = new MysqlDeviceVehicleRepositoryImpl(vertx);
    }

    @Override
    public Future<Boolean> insert(DeviceVehicleEntity deviceVehicleEntity) {
        Future<Boolean> result = Future.future();

        Future<Boolean> redisFut = redisDeviceVehicleRepository.insert(deviceVehicleEntity);

        Future<Boolean> mysqlFut = mysqlDeviceVehicleRepository.insert(deviceVehicleEntity);

        CompositeFuture.all(redisFut, mysqlFut).setHandler(res -> {
            if(res.succeeded()){
                logger.trace("insert device vehicle entity to redis and mysql successfully.");
                result.complete(true);
            }
            else {
                logger.error("Failed insert device vehicle entity to redis or mysql.", res.cause());
                result.fail(res.cause());
            }
        });

        return result;
    }
}

AbstractMysqlRepository.java:

public abstract class AbstractMysqlRepository {

    private static final Logger logger = LoggerFactory.getLogger(AbstractMysqlRepository.class);

    private final static JsonObject mysqlConfig = Vertx.currentContext().config().getJsonObject("mysql");
    private final static String ip = mysqlConfig.getString("ip", "127.0.0.1");
    private final static String user = mysqlConfig.getString("user", "root");
    private final static String password = mysqlConfig.getString("password", "123456");
    private final static String dbName = mysqlConfig.getString("dbname", "obd");
    private final static int port = mysqlConfig.getInteger("port", 3306);
    private final static int poolSize = mysqlConfig.getInteger("max_pool_size", 80);
    private final static boolean useSSL = mysqlConfig.getBoolean("usessl", false);

    private final static String jdbcUrl = "jdbc:mysql://" + ip + ":" + port + "/" + dbName
                                        + "?useSSL=" + useSSL
                                        + "&serverTimezone=Asia/Shanghai"
                                        + "&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true"
                                        + "&useUnicode=true&characterEncoding=utf8";

    private final static JsonObject hikaricp_config = new JsonObject()
            .put("provider_class", "io.vertx.ext.jdbc.spi.impl.HikariCPDataSourceProvider")
            .put("jdbcUrl", jdbcUrl)
            .put("driverClassName", "com.mysql.cj.jdbc.Driver")
            .put("minimumIdle", 40)
            .put("maximumPoolSize", poolSize)
            .put("cachePrepStmts", true)
            .put("prepStmtCacheSize", 250)
            .put("prepStmtCacheSqlLimit", 2048)
            .put("useServerPrepStmts", true)
            .put("useLocalSessionState", true)
            .put("useLocalTransactionState", true)
            .put("rewriteBatchedStatements", true)
            .put("cacheResultSetMetadata", true)
            .put("cacheServerConfiguration", true)
            .put("elideSetAutoCommits", true)
            .put("maintainTimeStats", false)
            .put("idleTimeout", 60000)
            .put("connectionTimeout", 60000)
            .put("maxLifetime", 300000)
            .put("validationTimeout", 3000)
            .put("leakDetectionThreshold", 5000)
            .put("username", user)
            .put("password", password);

    JDBCClient jdbcClient;

    AbstractMysqlRepository(Vertx vertx){
        jdbcClient = JDBCClient.createShared(vertx, hikaricp_config);
    }

    Handler<AsyncResult<SQLConnection>> connHandler(Future future, Handler<SQLConnection> handler) {
        return conn -> {
            if (conn.succeeded()) {
                final SQLConnection connection = conn.result();
                handler.handle(connection);
            } else {
                logger.error("Failed get mysql connection.", conn.cause());
                future.fail(conn.cause());
            }
        };
    }
}

MysqlDeviceVehicleRepositoryImpl.java:

public class MysqlDeviceVehicleRepositoryImpl extends AbstractMysqlRepository {

	private static final Logger logger = LoggerFactory.getLogger(MysqlDeviceVehicleRepositoryImpl.class);

	private static final String SQL_INSERT = "INSERT INTO `device_vehicle` " +
			"(`Imei`,`Vin`,`LinkedTime`) VALUES (?,?,?) ON DUPLICATE KEY UPDATE Vin=VALUES(Vin), LinkedTime=VALUES(LinkedTime)";

	private static final String SQL_QUERY = "SELECT count(*) As cnt FROM device_vehicle WHERE Imei = ? and Vin=?";

	public MysqlDeviceVehicleRepositoryImpl(Vertx vertx){
		super(vertx);
	}

	public Future<Boolean> insert(DeviceVehicleEntity deviceVehicleEntity) {
		Future<Boolean> result = Future.future();

		SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		final String linkedTime = format.format(deviceVehicleEntity.getLinkedTime());

		jdbcClient.getConnection(connHandler(result, connection -> {
			connection.updateWithParams(SQL_INSERT, new JsonArray()
					.add(deviceVehicleEntity.getImei())
					.add(deviceVehicleEntity.getVin())
					.add(linkedTime),r -> {
				if (r.succeeded()) {
					logger.trace("insert or update vehicle Vin successfully.");
					result.complete(true);
				} else {
					logger.error("failed insert or update vehicle Vin. Imei: " + deviceVehicleEntity.getImei(), r.cause());
					result.fail(r.cause());
				}
				connection.close();
			});
		}));

		return result;
	}
}

if success, the log is:
2018-05-07 18:11:26.268 [vert.x-worker-thread-14] TRACE com.gzfns.obdpps.repository.mysql.MysqlDeviceVehicleRepositoryImpl - insert or update vehicle Vin successfully.

2018-05-07 18:11:26.269 [vert.x-worker-thread-3] TRACE com.gzfns.obdpps.service.DeviceVehicleServiceImpl - insert device vehicle entity to redis and mysql successfully.

else, the log is:

2018-05-07 18:13:44.204 [vertx-jdbc-service-get-connection-thread] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Timeout failure stats (total=100, active=100, idle=0, waiting=0)
2018-05-07 18:13:44.204 [vert.x-worker-thread-13] ERROR com.gzfns.obdpps.repository.mysql.AbstractMysqlRepository - Failed get mysql connection.
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 60000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676) ~[obdpps-0.0.1-fat.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190) ~[obdpps-0.0.1-fat.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155) ~[obdpps-0.0.1-fat.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[obdpps-0.0.1-fat.jar:?]
	at io.vertx.ext.jdbc.impl.JDBCClientImpl.lambda$getConnection$3(JDBCClientImpl.java:186) ~[obdpps-0.0.1-fat.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
2018-05-07 18:13:44.205 [vert.x-worker-thread-13] ERROR com.gzfns.obdpps.service.DeviceVehicleServiceImpl - Failed insert device vehicle entity to redis or mysql.
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 60000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676) ~[obdpps-0.0.1-fat.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190) ~[obdpps-0.0.1-fat.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155) ~[obdpps-0.0.1-fat.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[obdpps-0.0.1-fat.jar:?]
	at io.vertx.ext.jdbc.impl.JDBCClientImpl.lambda$getConnection$3(JDBCClientImpl.java:186) ~[obdpps-0.0.1-fat.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

Thanks for your help! Thanks for your comments!

**Comment by laudylcp** [comment]
@tsegismont I find connection leak log, but I don't know how to solve the problem, please give me some help, thanks a lot!
The log is below:
2018-05-08 15:38:09.861 [HikariPool-1 housekeeper] WARN  com.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl@333b50f9 on thread vertx-jdbc-service-get-connection-thread, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[obdpps-0.0.1-fat.jar:?]
	at io.vertx.ext.jdbc.impl.JDBCClientImpl.lambda$getConnection$3(JDBCClientImpl.java:186) ~[obdpps-0.0.1-fat.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

Thanks for your comment.

**Comment by tsegismont** [comment]
As commented previously, the reconnect parameters in the JDBC url look
suspicious to me. Have you tried without them?

And when I talked about a reproducer, I was thinking about a small,
simplified project on GitHub which we can fork and run locally.

**Comment by laudylcp** [comment]
@tsegismont There is no problem with local debugging, and the problem will occur in a few hours.

the reconnect parameters in the JDBC url had deleted, I have tried without them.

**Comment by laudylcp** [comment]
/*
        This can block until a connection is free.
        We don't want to do that while running on a worker as we can enter a deadlock situation as the worker
        might have obtained a connection, and won't release it until it is run again
        There is a general principle here:
        *User code* should be executed on a worker and can potentially block, it's up to the *user* to deal with
        deadlocks that might occur there.
        If the *service code* internally blocks waiting for a resource that might be obtained by *user code*, then
        this can cause deadlock, so the service should ensure it never does this, by executing such code
        (e.g. getConnection) on a different thread to the worker pool.
        We don't want to use the vert.x internal pool for this as the threads might end up all blocked preventing
        other important operations from occurring (e.g. async file access)
        */

@tsegismont What does this note mean?

connection leak seems to be happening here???

**Comment by tsegismont** [comment]
We really need a small reproducer. It doesn't matter if the reproducer takes time to fail. The purpose is to reproduce. Without a reproducer it is hard to help as we can only do wild guessing.

**Comment by laudylcp** [comment]
@tsegismont I have upload all code to github, please git clone from:

https://github.com/laudylcp/obdgateway.git

Thanks for your help!

**Comment by tsegismont** [comment]
@laudylcp the repository contains a lot of code, no instructions to setup the database, ... etc. Please provide a reproducer (small piece of code with, ideally, an automated test, at least instructions to reproduce manually).

**Comment by laudylcp** [comment]
@tsegismont Thanks, I had changed Data Access Layer to mybatis, The problem had resolved. thanks for your reply!
