### ISSUE TITLE
Vert.x 3.5.2-SNAPSHOT ERROR Unhandled exception java.lang.IllegalStateException: Response is closed

### ISSUE THREAD

**Issue by michaelpog** [vert-x3/issues#369]
I'm testing Vert.x 3.5.2-SNAPSHOT I see a lot of unhandled exceptions in the logs that look like this:
```
java.lang.IllegalStateException: Response is closed
	at io.vertx.core.http.impl.HttpServerResponseImpl.checkValid(HttpServerResponseImpl.java:548)
	at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:189)
	at XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	at io.vertx.core.impl.CompositeFutureImpl.lambda$all$1(CompositeFutureImpl.java:49)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:121)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:128)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:90)
	XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
I've marked our internal classes which are irrelevant with XXXXXX 

I understand that this exception is happening if an attempt to send a response is happening when the connection was already closed by the upstream client.
But:
Why is this exception unhandled? 
It is a normal behavior for us to not respond in time to our upstream client from time to time (ideally it would not happen, but it does) so right now in addition to not meeting our upstream client's SLA we are also flooding our logs with stacktraces of IllegalStateExceptions.
Is there a way to avoid this exception to be thrown (with an expensive stack-trace capturing, and logging involved)? 
Is there a way for us to check if the connection is still open, and if it is closed avoid this error entirely?

Thanks

**Comment by manish-panwar** [comment]
> httpServerRequest.exceptionHandler(ex -> {
            if (context.response().closed() || context.response().ended()) {
                LOGGER.warn("Connection with upstream client is closed or ended.");
            } else {
                // Handle the crazy error.
            }
        });

Just so you know, in older version of Vertx, it used to quietly suppress these errors, but now anymore - and definitely it makes sense for it to not do it quietly.

**Comment by vietj** [comment]
you can use `HttpServerResponse#ended()` to determine wether or not you can write the response

**Comment by manish-panwar** [comment]
@vietj - I think #ended may never be set to true if you haven't called the response#end() method yet. I noticed that #ended is explicitly set to true if upstream connection is closed unexpectedly - thus making it more reliable to use???

**Comment by vietj** [comment]
@manish-panwar good point it should be `!ended() && !closed()`

**Comment by michaelpog** [comment]
Thank you @vietj  and @manish-panwar so just to clarify.
When I want to send a response I can simply check if 
```
httpServerResponse.ended() || httpServerResponse.closed() 
```
and if it's true then I don't do anything? 
I just want to make sure I don't leave the httpServerResponse in some undefined hanging state

**Comment by manish-panwar** [comment]
Yes - as long as you are executing this on request exception only - see above my sample code.

**Comment by michaelpog** [comment]
Oh I see I missed that part. I thought I could just check if ```httpServerResponse.ended() || httpServerResponse.closed() `` is false first and then send the response.

It's a bit of a bummer that the Handler passed to the exceptionHandler takes a Throwable and not some object that would contain the httpServerResponse.
The way it is right now, it's forcing you to write it as a closure.
If I want to do something like this:
```
 httpServerResponse.exceptionHandler(HttpServerResponseUtils::sendResponseExceptionHandler);

 private static void sendResponseExceptionHandler(HttpServerResponse response,  Throwable throwable) {
        
}
````

It would not work:(

**Comment by michaelpog** [comment]
Actually @manish-panwar I'm not sure I am following how this exception handler is related.
looking here https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/HttpServerResponseImpl.java#L198
And my stacktrace
Looks like this 
```
if(!httpServerResponse.ended() && !httpServerResponse.closed()) {
    httpServerResponse.setStatusCode(httpStatusCode)
                          .putHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                          .end(responseBodySupplier.get());

}
else {
}
```
Is what I need as I'm trying to avoid throwing the IllegalStateException to begin with, not not catch it

My question is should I put something in the else. Should I put httpServerResponse.close()  for example?

Why do I need the exception handler at all then?

**Comment by manish-panwar** [comment]
I meant to say, in case you have a generic exception handler:

> router.route().failureHandler(context -> {
            // At this point you don't know what happened.
Throwable throwable = context.getDelegate().failure();
        });

v/s 

> httpServerRequest.exceptionHandler(ex -> {
// Here we knows that error indeed happened in handling of request. 
});

Vertx documentation isn't clear enough on what are mandatory things to do in connection/request errors, but so far I have seen no problem in doing nothing in **ELSE** block than just logging the WARNING. I specifically prefer to handle request level error in a separate error handler - just my preference, no additional advantage though over catch-all error handler. 

I think it's like a chicken-egg problem problem if you try to call #end() or #close() method in your error handler because calling these methods may result into error again. Given below is what you can do in your ELSE block to avoid recursive error due to calling #end(), but not sure if it's really needed.

> if (context.get(END_ON_ERROR_CALLED) == null) {
            context.put(END_ON_ERROR_CALLED, true);
            context.response().end();
        }

**Comment by vietj** [comment]
actually only `httpServerResponse.closed()` should be ok, because `ended()` will return a boolean that is set only with `end()`, since you are calling this method you don't need to test it.

**Comment by michaelpog** [comment]
Thanks you guys.
@vietj anything you may add about whether I need to do any additional steps if the ```httpServerResponse.closed()``` returns true?

**Comment by vietj** [comment]
I  think it should be fine with closed() (try it), I'm still thinking the best way to mitigate this in the future

**Comment by michaelpog** [comment]
Sorry @vietj let me clarify my question:
```
if(!httpServerResponse.closed()) {
    httpServerResponse.setStatusCode(httpStatusCode)
                          .putHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                          .end(responseBodySupplier.get());

}
else {
}
```
Do I need to add anything in the else section to do additional clean up? Or nothing is fine?
I may have misunderstood your answer.

**Comment by vietj** [comment]
I think it depends on your app but if you just received a buffer then there is nothing to do

**Comment by michaelpog** [comment]
Ok I've tested it and it looks like I don't see this stack trace anymore.
I'll run for longer, but so far the solution looks promising

**Comment by michaelpog** [comment]
Ok I don't see any of this in our logs any more.
@vietj we can close this
