### ISSUE TITLE
Write a testing guide

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/issues#373]
This guide will explain the different approach to develop (and execute):

* unit tests (junit + await, vertx-unit, vertx-junit 5)
* integration tests
* ...

**Comment by tejavenkatlanka** [comment]
jponge  can you guid me i will work on it

**Comment by jponge** [comment]
@tejavenkatlanka The only suggestion I may have is to adopt a structure similar to that of the Vert.x guide for Java developers, where you have code and text in sub-project `README` files.

Good luck!

**Comment by tejavenkatlanka** [comment]
Thanks for your response @jponge  should i write test case for vertx-guide-for-java-devs or other vert module

**Comment by jponge** [comment]
I suggest you start something from scratch in your own repository, with samples that make sense rather than taking those from the Java guide.
