### ISSUE TITLE
FailedFuture uses NoStackTraceThrowable when created with simple error message

### ISSUE THREAD

**Issue by morganmcc** [vert-x3/issues#377]
The FailedFuture implementation creates a failed future with a NoStackTraceThrowable error when created with a simple string message. I think this is bad practice, because Throwables should only be used for egregious non-recoverable errors.

I ran into this because I was using the awaitResult construct in a Kotlin co-routine to make a call to connect to a Stomp server. The implementation of awaitResult looks for a failed future and then throws any error. On line 192 the StompClientImpl creates a failed future with an error message if the CONNECTED frame was not received from the server in time. This results in the above exception being thrown.

The consequences of this were that my code using awaitResult which was using a try/catch block with Exception failed to catch the error.

First, a connection error like that should result in a normal exception and not a Throwable. Also, it seems like bad practice to make users of the awaitResult function catch all Throwables or catch both the NoStackTraceThrowable along with other exceptions.

**Comment by vietj** [comment]
@morganmcc creating a throwable with a stack trace is very expensive (and also it messes with the JVM JIT) and that's the main reason why creating an future with a message does not capture the stack trace. I think instead the Stomp server should create a failed future with its own stack trace instead and you should open an issue there.

**Comment by morganmcc** [comment]
Fair enough. Thanks. I'll open against the Stomp client.
