### ISSUE TITLE
MessageCodec for NetServer

### ISSUE THREAD

**Issue by JuKu** [vert-x3/issues#379]
Currently, MessageCodec is only available for eventbus.
Is there an alternative to use for NetSocket?

**Comment by vietj** [comment]
@JuKu what do you want to achieve ?

**Comment by JuKu** [comment]
@vietj I try to implement a own network protocol and want to use layers.
But my real problem is another: TCP Fragmenting
Because of TCP Fragments i receive incomplete packages and have to merge them / split them up and wait for the rest of the expected message. And so i search for a solution to do this in a nice way.

**Comment by vietj** [comment]
@JuKu I see

it is possible to use Netty codec with Vert.x NetServer and NetClient, they provide support for ByteToMessageCodec that takes care of this task.

it is an internal feature (stable, used by other parts of Vert.x) but it is very convenient if you know to use Netty.

**Comment by JuKu** [comment]
@vietj Thanks for your fast answer!
I have found another solution in your examples:
https://github.com/vert-x3/vertx-examples/blob/master/core-examples/src/main/java/io/vertx/example/core/net/stream/BatchStream.java

Class `RecordParser` does already what i wanted to do.

**Comment by vietj** [comment]
oh right indeed!!!! you mentionned "codec" which lead me to the wrong track
