### ISSUE TITLE
Add support for cache-control immutable

### ISSUE THREAD

**Issue by leolux** [vert-x3/issues#382]
It would be nice if we could add **cache-control immutable** to the StaticHandler. This is a relative new feature and increases the performance of media rich websites. 

It seems to be supported in major browsers already: https://stackoverflow.com/questions/41936772/which-browsers-support-cache-control-immutable

**Comment by pmlopes** [comment]
This should be a flag as it can affect the case where changes at the file system level cause an invalidation

**Comment by leolux** [comment]
I don't understand what you mean by "flag" in this context. What does it mean?

**Comment by pmlopes** [comment]
I mean that users could either enable or disable it.

**Comment by leolux** [comment]
Ok, thanks!

Assuming the flag would be called `immutable` then this flag should only take effect when the base flag `cachingEnabled` is enabled. If `immutable` is enabled it should be combined in the header with `maxAgeSeconds` to produce something like `Cache-Control: max-age=365000000, immutable` . As far as I can remember the combination of multiple HTTP response header values is managed by the HTTP response handler automatically.

**Comment by pmlopes** [comment]
You can also concatenate the header when it is generated

**Comment by leolux** [comment]
We could or should also add flags for `must-revalidate` and `proxy-revalidate`.

**Comment by pmlopes** [comment]
or instead just have a configurable initial cache header value

**Comment by pmlopes** [comment]
Setting headers before the handler will be respected, which voids this request.
