### ISSUE TITLE
Vertx webclient unable to resolve host

### ISSUE THREAD

**Issue by beginner** [vert-x3/issues#383]
i am getting UnknownHostException in webclient, but i do not think its a host problem as I can resolve it fine via terminal.

Future{cause=failed to resolve 'myhost.com'. Exceeded max queries per resolve 4 }

I'm using vertx-web

3.5.0

 

Here is my code :

```
private void callMe(RoutingContext routingContext) {
        final IncomingObject incomingObject = Json.decodeValue(routingContext.getBodyAsString(),
            IncomingObject.class);

        OutGoingRequest outGoingRequest = new OutGoingRequest();

        WebClientOptions optionsWeb = new WebClientOptions().setLogActivity(true);
        optionsWeb.setConnectTimeout(10);
        optionsWeb.setIdleTimeout(10);
        optionsWeb.setSsl(true);
        optionsWeb.setTrustAll(true);

        webClient = WebClient.create(vertx, optionsWeb);


        List<OutGoingRequest> outGoingRequests = new ArrayList<>();

        List<Future> futures = new ArrayList<>();
        for(Item item : incomingObject.getItems()) {
          
            Future<JsonObject> future = Future.future(fut -> {
                if(fut.failed()) {
                    System.out.println("failed");
                } else {
                    System.out.println("succeeded");

                }
            });

            futures.add(future);
           
            webClient.postAbs("https://myhost.com")
                .addQueryParam("myName", "true")
                .putHeader("Content-Type", "application/json")
                .putHeader("Accept", "application/json")
                .timeout(10000)
                .sendJsonObject(new JsonObject(Json.encode(item)), handler1 -> {

                    int code = handler1.result().statusCode();
                    if (code == 200) {
                        future.complete(handler1.result().bodyAsJsonObject());
                    }
                });


        }


        CompositeFuture.all(futures).setHandler(h -> {
            if(h.failed()) {
                System.out.println("all failed");
            } else {
                System.out.println("all succeeded");
            }
        });


    }
```

**Comment by vietj** [comment]
use `http://myhost.com` instead

**Comment by beginner** [comment]
Why shall I use http when the remote server is https?

**Comment by nitish24p** [comment]
I am getting the same issue..
in the the webClientOptions i havent done setSSl to true, but my abs url is an https one. I still get the same error..

**Comment by tsegismont** [comment]
@nitish24p can you try to run the JVM with the ` -Dvertx.disableDnsResolver=true` sysprop?

**Comment by nitish24p** [comment]
Yea it works with that but that's not the root cause of the problem. I did a tcp dump of the dns via wireshark, and the vertx client was making a call to some weird dns server ip, which was causing the not resolved exception. The browser was hitting the correct dns servers as configured by my ISP but the vertx client was calling some random dns server ip.. Don't know why though

**Comment by tsegismont** [comment]
Can you take a look at https://vertx.io/docs/vertx-core/java/#_host_name_resolution ?

Vert.x by default uses an async DNS resolver. DNS servers should be the system list of servers. I suspect these were not found and Vert.x fallbacks to Google DNS servers (`8.8.8.8` and `9.9.9.9`).

Can you tell me which DNS server IP you saw?
What is your operating system?
