### ISSUE TITLE
when log4j2.xml has custom plugin config in vertx root-fat.jar, log4j2 do not work

### ISSUE THREAD

**Issue by loginin** [vert-x3/issues#385]
I write one vertx project and use log4j2 as my log framework.
and I use custom log4j2 plugin to configure my custom property in log4j2.xml
it run ok when I run the project in idea, but failed when I package the code into root-fat.jar.

xml config file:
![image](https://user-images.githubusercontent.com/16422345/41904744-c5311f8e-796b-11e8-8d53-cbf8912cd4ab.png)
and the plugin code:
![image](https://user-images.githubusercontent.com/16422345/41904878-1f51b618-796c-11e8-85e5-46400dec7178.png)
use log4j2 in vertx and all-asynchronzied logger
![image](https://user-images.githubusercontent.com/16422345/41906776-61dc28ec-7971-11e8-9fe7-71f38610d17a.png)
the command in terminal
![image](https://user-images.githubusercontent.com/16422345/41906735-3b14df88-7971-11e8-963d-7493df6a2785.png)
and the fail message
![image](https://user-images.githubusercontent.com/16422345/41904789-de44b2b0-796b-11e8-944f-0a055958e1d8.png)

**Comment by loginin** [comment]
the dependency:
<project.log4j2.version>2.11.0</project.log4j2.version>
<project.slf4j.version>1.7.2</project.slf4j.version>
<project.logback-classic.version>1.1.5</project.logback-classic.version>
<project.vertx.version>3.5.1</project.vertx.version>

**Comment by tsegismont** [comment]
Can you please ask your question the Vert.x user forum? This does not look like a Vert.x issue, rather a packaging issue. Not everyone in the community subscribes to GitHub.

See https://vertx.io/community
