### ISSUE TITLE
Handling sub domain routing

### ISSUE THREAD

**Issue by bnlambert** [vert-x3/issues#386]
I wish to know if vert-x3 supports subdomain routing and how it handles it.
For example sub1.domain.com, how do I obtain sub1 from such a request made to vert-x3 app?

**Comment by tsegismont** [comment]
Can you explain what you mean with subdomain routing?

**Comment by bnlambert** [comment]
For example, given a that a request is coming from admin.domain.com, can vert-x3 provide 'admin' as one of it params?
Or 
If the domain of incoming request is of the format `*.domain.com`, how can I determine if '*' is set and what is the value if it exist in vert-x3?
thanks

**Comment by tsegismont** [comment]
There is no builtin param, but you could use a `VirtualHostHandler` and put the info in the `RoutingContext`:

```java
router.route().handler(VirtualHostHandler.create("admin.domain.com", routingContext -> {
  routingContext.put("virtualHost", "admin");
}));
```

Add this at the top of your router definitions and then later in your route handlers:

```java
router.get("/somepath").handler(routingContext -> {
  String virtualHost = routingContext.put("virtualHost");
  // Check virtual host and handle request
});
```

**Comment by bnlambert** [comment]
Wow thanks. Just to confirm. Can it also be used like this

```
router.route().handler(VirtualHostHandler.create("*.domain.com", routingContext -> {
routingContext.put("virtualHost", "*");
}));
```

Add this at the top of your router definitions and then later in your route handlers:

r```
outer.get("/somepath").handler(routingContext -> {
String virtualHost = routingContext.put("virtualHost");
// Check virtual host and handle request
}));

```
?

I wish there were example online showing how virtualHost works. Your example is more elaborate and comprehensive than what I see in the doc/manual about this subject.
Thanks

**Comment by tsegismont** [comment]
Yes, you can use wildcards when creating a `VirtualHostHandler`.

**Comment by tsegismont** [comment]
Closing at it seems your questions are answered. If you need more info please follow up on the Vert.x user forum. See https://vertx.io/community
