### ISSUE TITLE
Vertx 3.5.2 HttpServer response pending

### ISSUE THREAD

**Issue by ghost** [vert-x3/issues#389]
If i access ```request.netSocket().writeHandlerID()``` before sending http response, browser waits and waits for response it never comes if i remove this line everything works. Is this expected behavior? here is sample code

```java
public class TestVerticle extends AbstractVerticle {
    @Override
    public void start() throws Exception {
        vertx.createHttpServer().requestHandler(request -> {
            String id = request.netSocket().writeHandlerID();
            request.response().end("Hello World");
            System.out.println(id);
        }).listen(8080);
    }

    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        vertx.deployVerticle(TestVerticle.class.getName());
    }
}
```

**Comment by vietj** [comment]
why are you doing this ?

**Comment by vietj** [comment]
you should send the response before getting the NetSocket.

when you get the NetSocket, this removes the HTTP handlers from the pipeline and so the only way you can get this to work is to send a response manually in the NetSocket

**Comment by ghost** [comment]
I am using `writeHandlerID` as unique request id to put request in HashMap and later on when i will get DB response will use that `writeHandlerID` to get request from HashMap. I used this in my TCP server but in HTTP Server it was creating pending issue. I will use UUID 
Thanks

**Comment by vietj** [comment]
yes you should use your own UUID, getting the NetSocket from a request means that you will exclusively use the NetSocket for further network interactions.
