### ISSUE TITLE
HttpClient must use the http scheme for non SSL connections

### ISSUE THREAD

**Issue by michaelpog** [vert-x3/issues#390]
When upgrading to Vert.x 3.5.3.CR1 and enabling HTTP_2 in HTTP client. The request scheme in the HTTP server is HTTPs even when the request from the HTTP client to HTTP server is HTTP.

Reproducer https://github.com/michaelpog/http2reproducer
1. Run HTTP server
2. Run HTTP client.
Observe HTTP server output:
```
Starting HTTP server on port 8881
REQUEST: hi from client - 1
Request Scheme : https
REQUEST: hi from client - 2
Request Scheme : https
```
3. Change line :
```
 HttpClientOptions options = new HttpClientOptions().setProtocolVersion(HttpVersion.HTTP_2);
```
in HTTP client  to
```
  HttpClientOptions options = new HttpClientOptions().setProtocolVersion(HttpVersion.HTTP_1_1);
```
4. Rerun HTTP client
5. Observe correct HTTP request scheme
```
REQUEST: hi from client - 1
Request Scheme : http
REQUEST: hi from client - 2
Request Scheme : http
```

**Comment by vietj** [comment]
it's actually a client problem and not a server problem

**Comment by vietj** [comment]
fixed by https://github.com/eclipse/vert.x/issues/2533

**Comment by michaelpog** [comment]
Awesome, thanks!
