### ISSUE TITLE
Websocket client with ssl:true -> NotSslRecordException

### ISSUE THREAD

**Issue by injecteer** [vert-x3/issues#396]
The code in vert.x 3.5.3

```
import groovy.util.logging.Log4j
import io.vertx.core.AbstractVerticle
import io.vertx.core.http.HttpClientOptions
import io.vertx.core.http.WebSocket

@Log4j
class GatewayVerticle extends AbstractVerticle {
 
  @Override
  void start() throws Exception {
    HttpClientOptions o = new HttpClientOptions( defaultHost:'remy-ws.glitch.me', ssl:true )
    log.info "creating client with $o.properties"
    WebSocket socket
    vertx.createHttpClient( o ).websocket( '' ){ WebSocket ws ->
      socket = ws
      log.info "connected to $socket"
      ws.handler{ log.info "<< $it "}
      ws.closeHandler{ log.warn "closing << $socket" }
      ws.exceptionHandler{ log.error 'oops', it }
    }
  }

}
```
produces 

> 12:04:10.658 [vert.x-eventloop-thread-2] INFO i.m.gateway.http.GatewayVerticle - creating client with [http2KeepAliveTimeout:60, crlValues:[], pemTrustOptions:null, defaultHost:remy-ws.glitch.me, http2ClearTextUpgrade:true, maxRedirects:16, pfxKeyCertOptions:null, jdkSslEngineOptions:null, usePooledBuffers:false, verifyHost:true, openSslEngineOptions:null, defaultPort:80, crlPaths:[], maxWebsocketFrameSize:65536, logActivity:false, metricsName:, keepAliveTimeout:60, pipelining:false, maxWaitQueueSize:-1, maxPoolSize:5, tcpNoDelay:true, keepAlive:true, pipeliningLimit:10, pfxTrustOptions:null, trustOptions:null, tcpCork:false, localAddress:null, maxInitialLineLength:4096, poolCleanerPeriod:1000, sslEngineOptions:null, forceSni:false, sendBufferSize:-1, connectTimeout:60000, maxWebsocketMessageSize:262144, enabledSecureTransportProtocols:[TLSv1, TLSv1.1, TLSv1.2], trustAll:false, sendUnmaskedFrames:false, tcpFastOpen:false, http2MaxPoolSize:1, protocolVersion:HTTP_1_1, maxHeaderSize:8192, http2MultiplexingLimit:-1, trustStoreOptions:null, reuseAddress:true, reusePort:false, class:class io.vertx.core.http.HttpClientOptions, tcpKeepAlive:false, trafficClass:-1, idleTimeout:0, receiveBufferSize:-1, http2ConnectionWindowSize:-1, decoderInitialBufferSize:128, keyStoreOptions:null, enabledCipherSuites:[], useAlpn:false, tryUseCompression:false, proxyOptions:null, pemKeyCertOptions:null, soLinger:-1, alpnVersions:[], tcpQuickAck:false, ssl:true, keyCertOptions:null, maxChunkSize:8192, initialSettings:{"headerTableSize":4096,"initialWindowSize":65535,"maxConcurrentStreams":4294967295,"maxFrameSize":16384,"maxHeaderListSize":2147483647,"pushEnabled":true}]

> 12:04:11.135 [vert.x-eventloop-thread-2] WARN i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
> io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 485454502f312e31203430302042616420526571756573740d0a5365727665723a20617773656c622f322e300d0a446174653a204672692c2032342041756720323031382031303a30343a313120474d540d0a436f6e74656e742d547970653a20746578742f68746d6c0d0a436f6e74656e742d4c656e6774683a203133380d0a436f6e6e656374696f6e3a20636c6f73650d0a0d0a3c68746d6c3e0d0a3c686561643e3c7469746c653e3430302042616420526571756573743c2f7469746c653e3c2f686561643e0d0a3c626f6479206267636f6c6f723d227768697465223e0d0a3c63656e7465723e3c68313e3430302042616420526571756573743c2f68313e3c2f63656e7465723e0d0a3c2f626f64793e0d0a3c2f68746d6c3e0d0a
> 
>     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
>     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)

If ssl is set to false, the websocket is created normally.

See https://groups.google.com/d/msg/vertx/PK-OcoEEZYU/UpkJEjWFDwAJ for further info

**Comment by vietj** [comment]
it seems your server does not support SSL, can you provide a reproducer ?

**Comment by vietj** [comment]
this is because you are missing the default 443 port, your client options should have a "defaultPort: 443" declaration.
