### ISSUE TITLE
Stack osgi upgrade for major modules

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#404]
- [x] vertx-core
- [x] vertx-web
    - [x] vertx-web
    - [x] vertx-web-client
    - [x] openapi
    - [x] handlebar template engine
    - [x] freemarker template engine
- [x] vertx-sql-common
- [x] vertx-jdbc-client
         - with Hikari connection pool
- [x] vertx-auth
     - [x] vertx-auth-common
     - [x] vertx-auth-htdigest
     - [x] vertx-auth-htpasswd
     - [x] vertx-auth-jdbc
     - [x] vertx-auth-jwt
     - [x] vertx-auth-mongo
     - [x] vertx-auth-oauth2
     - [x] vertx-auth-shiro
     - [x] vertx-jwt
- [x] vertx-mongo-client
- [x] vertx-dropwizard-metrics
- [x] vertx-micrometer-metrics
- [x] vertx-mail-client

**Comment by cescoffier** [comment]
OSGi metadata have been pushed to the listed projects.
