### ISSUE TITLE
How to get vertx mqttClient info?

### ISSUE THREAD

**Issue by wwhai** [vert-x3/issues#412]
I want to design a mqtt server with vertx MqttServer,Now I have complated a demo,This demo contains
 some simple function for remote mqtt client to connect.
I have a question, how to get client info which have already connected?
I can not found a API to get this info, please help me.
this is core code:
`  
 MqttServer mqttServer = MqttServer.create(vertx); 

 List clientList =mqttServer.getClientList();
`
such this API

**Comment by vietj** [comment]
it seems like a missing feature, WDYT @ppatierno ?

**Comment by ppatierno** [comment]
Yeah it seems a new feature. @wwhai what kind of information would you like to see for a client? All the ones provided by the `MqttEndpoint` interface?

**Comment by wwhai** [comment]
> Yeah it seems a new feature. @wwhai what kind of information would you like to see for a client? All the ones provided by the `MqttEndpoint` interface?

Such as the number of the online mqtt client or more detail, such of client's current state, etc;
All of those are provided in Activemq,In Activemq we can sub a special topic to get current clients.
I hope vertx-mqtt also provide the same interface,It can help us to monitor the client number in realtime.

**Comment by wwhai** [comment]
> Yeah it seems a new feature. @wwhai what kind of information would you like to see for a client? All the ones provided by the `MqttEndpoint` interface?

I hope next version MqttEndpoint interface or MqttServer can provider a method such this:
List <Client>list=server/endpoint.getAllClient();
for(list)......
Though this interface we can get detail info what are realtime needs.

**Comment by ppatierno** [comment]
I could think about providing the list of clients even because connection/endpoint(s) objects are already taken in memory but in any case, consider that ActiveMQ is a broker. The MQTT server is not a broker so it's out of its scope providing too much.

**Comment by ppatierno** [comment]
FYI I have just opened this one https://github.com/vert-x3/vertx-mqtt/issues/107

**Comment by vietj** [comment]
thanks @ppatierno let's close this issue in favor of the new one
