### ISSUE TITLE
Network issues and Timed out waiting for group information to appear

### ISSUE THREAD

**Issue by apanasevich** [vert-x3/issues#414]
Hi there.

I've created a simple [example](https://github.com/apanasevich/vertx-cluster-test/tree/master) to play with cluster mode. I run two nodes in the cluster with manual deployment of verticles. After a successful start I turn off the network from one node for five minues and turn it on after that. The cluster seems to be created again, but [LoggingVerticle](https://github.com/apanasevich/vertx-cluster-test/blob/master/src/main/java/ru/mail/vertx/LoggingVerticle.java) at the node that was suffered from the network problems doesn't consumes messages anymore. These messages are created with [HttpControllerVerticle](https://github.com/apanasevich/vertx-cluster-test/blob/master/src/main/java/ru/mail/vertx/HttpControllerVerticle.java).

Also, I see a warning in the log file:

`io.vertx.core.impl.HAManager WARNING: Timed out waiting for group information to appear`

I've attached the log file from the node that was disconnected.
[vertx-test-log-39.log](https://github.com/vert-x3/issues/files/2506501/vertx-test-log-39.log)

What does the warning mean? I want to get the cluster worked again, but the problem is that I don't know where to start fixing the problem.

**Comment by tsegismont** [comment]
Seems related to https://github.com/vert-x3/vertx-hazelcast/issues/90. Upgrade to 3.5.4 and it should fix your issue.

**Comment by apanasevich** [comment]
Thank you for advice, I confirm that the problem is fixed.
