### ISSUE TITLE
how to use this API?

### ISSUE THREAD

**Issue by wwhai** [vert-x3/issues#415]
@Fluent
    MqttEndpoint subscribeAcknowledge(int var1, List<MqttQoS> var2);

    @Fluent
    MqttEndpoint unsubscribeAcknowledge(int var1);

**Comment by tsegismont** [comment]
@wwhai take a look at [Handling client subscription/unsubscription request](https://vertx.io/docs/vertx-mqtt/java/#_handling_client_subscription_unsubscription_request)
