### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by wwhai** [vert-x3/issues#417]
I have learned vert-Mqtt Server long time.but at recently I found some problem,because too many so I can't list here.
Hope one can help me who are the mqttServer's author or developer.
Very thanks.

**Comment by wwhai** [comment]
I am a Chinese developer ,my Email is 751957846@qq.com,if who can help me please send e-mail to this address.

**Comment by Sammers21** [comment]
@wwhai, I think the best way to solve these problems is to create an issue for each of them in the related repository.

**Comment by wwhai** [comment]
> @wwhai, I think the best way to solve these problems is to create an issue for each of them in the related repository.

Thank you,last night I read the document of vertx-mqtt by careful,I found this vert-mqttServer dosn't for my design,It isn't a standard mqtt broker,so it can't suit a broker's function ,or maybe I should consider other mqtt broker such Activemq or HiveMq,etc.

**Comment by tsegismont** [comment]
@wwhai right, this module is for building your own broker, not a ready to use one.
