### ISSUE TITLE
JsonObject doesn't deserialize after being sent through eventbus

### ISSUE THREAD

**Issue by lfmunoz** [vert-x3/issues#418]
```

data class Workflow(
    var key: String,
    var script: String,

    var created: Instant = Instant.now(),
    var udpated: Instant = Instant.now(),
    var group: Array<String> = arrayOf()
) {}


// Test code that works
val obj = JsonObject.mapFrom(workflow)
println(obj)
val result  = obj.mapTo(Workflow::class.java)
println(result)

// Output:
{"key":"myScript","script":"out.println(\"Hello World\")","created":1541788054.411000000,"udpated":1541788054.411000000,"group":[]}
Workflow(key=myScript, script=out.println("Hello World"), created=2018-11-09T18:27:34.411Z, udpated=2018-11-09T18:27:34.411Z, group=[])

```

This works but when I do the exact samething but pass it through the event bus it doesn't work

```
// Send object 
val obj = JsonObject.mapFrom(workflow)
eb.send("/test", obj, ...)

// Receive object
vertx.eventBus().consumer<JsonObject>("/test")  {
   val result  = it.body().mapTo(Workflow::class.java) // Throws error

}

//The exception:

   java.lang.IllegalStateException: Illegal type in JsonObject: class java.math.BigDecimal
	at io.vertx.core.json.Json.checkAndCopy(Json.java:211)
	at io.vertx.core.json.JsonObject.copy(JsonObject.java:796)
	at io.vertx.core.eventbus.impl.codecs.JsonObjectMessageCodec.transform(JsonObjectMessageCodec.java:39)
}

```

Looks like a bug, why doesn't this work. Any work arounds?

**Comment by tsegismont** [comment]
@lfmunoz can you provide a reproducer? I'm curious how it works in the first snippet. With the Vert.x mapper config, `Instant` should be serialized as an ISO string.

That being said, @pmlopes I'm not sure why we have a serializer config for Instant but no deserializer config. Same goes for byte array. Is there a reason why you didn't add it in https://github.com/eclipse-vertx/vert.x/commit/3ac6c840029b9bd8767a596aa289fd8ba7055b6b ?

**Comment by pmlopes** [comment]
@tsegismont that is because of the RFC only defines serialization not the otherwayaround as the encoded value is a string so it is hard to tell for non typed languages what kind of data it should be. We could add it as we're on java.

**Comment by pmlopes** [comment]
@lfmunoz the lack of `BigDecimal` comes from `jackson`. If we enable BigDecimal then all floating point values will be of type `BigDecimal` you can do this now by accessing the `mapper` in the `Json` class and setting:

```java
Json.mapper.enable(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS);
```

Then it will work **BUT** will break everything you expected to have as `float` or `double`

**Comment by tsegismont** [comment]
@pmlopes well the deserializer applies only when you use `mapTo` so if the user tries to set a string to an Instant field, I think we're fine.

**Comment by tsegismont** [comment]
@pmlopes I'll go ahead and try to push a PR

**Comment by tsegismont** [comment]
@pmlopes here's the PR https://github.com/eclipse-vertx/vert.x/pull/2754

**Comment by GustavoGramajo** [comment]
@pmlopes i tried setting Json.mapper.enable(DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS) but it keeps failing to deserialize the message from the bus (i have a BigDecimal in the message). I'm using Quarkus 1.13.0, which seems to use Vertx 3.9.5; if necessary i could provide a reproducer. Thanks for your time!
