### ISSUE TITLE
io.vertx.core.streams improvements

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#42]
1/ add an `end()` method to WriteStream<T> (this was agreed for 3.0 but not done)

2/ find a way to have read/write stream that do not support back pressures, for instance:

```
interface ReadStream<T> {
   ReadStream<T> exceptionHandler(Handler<Throwable> handler);
   ReadStream<T> handler(Handler<T> handler);
   ReadStream<T> endHandler(Handler<Void> endHandler);
}

interace ReactiveReadStream<T> extends ReadStream<T> {
   ReadStream<T> pause();
   ReadStream<T> resume();
}
```

Same for write stream.

this is a fictional design just to show what I do have in mind. Then we should refactor our stream usage to use reactive / non reactive streams, for instance MessageConsumer<T> would extend the non reactive stream version as we don't support and the reactive ones (HttpServerRequest, AsyncFile, etc...).

This would help the integration with RxJava (and perhaps reactive-streams spec) and avoid confusion about Pump usage that one may have with non reactive streams.

**Comment by testn** [comment]
Let's prioritize this a bit. If there is no good way to introduce it without breaking changes. I would prefer a new interface like Closeable/Endable{Read/WriteStream}

**Comment by vietj** [comment]
Note: in RxJava 2.0 there is concept of `Observable` that is not back-pressured and `Flowable` that is back-pressured. This would map to the concept we are trying to develop here.
