### ISSUE TITLE
Need to add polyglot support for io.vertx.ext.web.api 

### ISSUE THREAD

**Issue by artemiokost** [vert-x3/issues#421]
### Version

* vert.x web: 3.6.0.CR1

### Context

Need to add reactivex support for io.vertx.ext.web.api, kotlin, etc....

**Comment by slinkydeveloper** [comment]
Pull requests:
- [x] https://github.com/vert-x3/vertx-rx/pull/166 (docs override in https://github.com/vert-x3/vertx-web/pull/1076)
- [x] https://github.com/vert-x3/vertx-lang-kotlin/pull/95
- [x] https://github.com/vert-x3/vertx-lang-js/pull/82
- [x] https://github.com/vert-x3/vertx-lang-groovy/pull/65
- [x] https://github.com/vert-x3/vertx-lang-ruby/pull/36
