### ISSUE TITLE
forEach method in io.vertx.reactivex.core.MultiMap

### ISSUE THREAD

**Issue by artemiokost** [vert-x3/issues#422]
Maybe it makes sense to implement the forEach method in MultiMap. After context.request().headers() need to invoke .getDelegate() method.

**Comment by tsegismont** [comment]
Thanks for reporting.

I'm closing as duplicate of https://github.com/vert-x3/vertx-rx/issues/61

There is an issue tracking the larger problem (interfaces implemented by non Rx objects) planned for 3.6: https://github.com/vert-x3/vertx-rx/issues/132
