### ISSUE TITLE
Restructure CLI to ease vertx shell integration

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/issues#43]
In order to let vertx-shell reuse the model and parser, the current CLI need to be restructure. This will be done in https://github.com/eclipse/vert.x/pull/1110

**Comment by cescoffier** [comment]
For tracking purpose:

- [ ] CLI model and annotations
- [ ] Option and Argument parser
- [ ] Usage / Help generation
- [ ] Command SPI
- [ ] Run command
- [ ] Bare command
- [ ] Version command
- [ ] Launcher class
- [ ] Classpath handling (classloader)

**Comment by cescoffier** [comment]
@vietj have checked the integration in vert.x shell. It looks ok (can you confirm)

**Comment by vietj** [comment]
yes it improves usability in vertx-shell proto

**Comment by cescoffier** [comment]
Related PR is https://github.com/eclipse/vert.x/pull/1135
