### ISSUE TITLE
Why eventbus can't use consul to service registration and discovery

### ISSUE THREAD

**Issue by wamshawn** [vert-x3/issues#432]
In this [page](https://vertx.io/docs/vertx-service-discovery/java/#_additional_bridges) .
Wrote ‘’Only http-endpoint is supported for now.‘’
But when without consul bridge,  supported?
That means only supported in Hazelcast Cluster, IS IT？
I know it is a long connection, NOT A HTTP. 
But using a connection pool will be much graceful. # #

**Comment by tsegismont** [comment]
@cescoffier any idea?

**Comment by cescoffier** [comment]
The documentation just means that right now only services with the type "http.endpoint" are imported. 
So, if in your Consul you have a service, it will be imported. If it detects it as an HTTP endpoint, it will compute the right set of metadata (SSL, location...).

**Comment by wamshawn** [comment]
got it, it is a bridge.
So I can register a Vertx HTTP endpoint into consul services, instead of using discovery service to publish a record.
the consul bridge will import the http endpoint into Hazelcast.
is that doable? let me try it.
cause, i want to use golang to make a http gateway server with consul.
