### ISSUE TITLE
Vert.x higher when 3.6.0 (3.6.1 and 3.6.2) is not generate reactivex service

### ISSUE THREAD

**Issue by artemiokost** [vert-x3/issues#440]
Maybe I missed something, but after update from 3.6.0 to 3.6.2 reactivex proxy service is not generated. This feature was very helpfull. When I switch only vertx-rx-java2 module version to 3.6.0 all good.

**Comment by vietj** [comment]
this feature is still supported but I think you need to annotate the service with `@VertxGen` in addition of `@ServiceProxy`

**Comment by artemiokost** [comment]
Oh thanks for quick reply), but I have always used this annotation like:
```
@ProxyGen
@VertxGen
public interface UserService{
    @Fluent
    UserService getUserSummary(int userId, Handler<AsyncResult<JsonObject>> handler);
}
```
But today I have update my project to 3.6.2 and after annotation processing all reactrivex/service folders in each project where lost. And like I said, when I roll back to 3.6.0 all generates again.

**Comment by vietj** [comment]
ok, it looks like a regression

**Comment by vietj** [comment]
can you add the dependency to vertx-rx-java2-gen artifact ?

**Comment by vietj** [comment]
I think you must be missing this one actually

**Comment by vietj** [comment]
I think we should properly document how to generate rxjava services with proxy

**Comment by HugoCrd** [comment]
Hi @vietj !
We also experience this issue on our side.
I just tried adding `vertx-rx-java2-gen` (as below) and it doesn't change anything.

```
<dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-rx-java2-gen</artifactId>
            <version>3.6.2</version>
</dependency>
```

What would you need from us to help finding the issue?
Best!

**Comment by vietj** [comment]
I think that a PR in vertx-examples to update the service-proxy-examples/service-consumer to add rx support would be a good thing, so we can use it as integration test

**Comment by HugoCrd** [comment]
My bad, we do use rxJava 1 so we had to include 

```
<dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-rx-java-gen</artifactId>
            <version>3.6.2</version>
</dependency>
```

Everything's fine now.
Something changed as we didn't have to include this dependency before. But it's definitely documented in https://vertx.io/docs/vertx-service-proxy/java/ :
> To generate the proxies in different languages, you will need to add the language dependency such as vertx-lang-groovy for Groovy.

I think adding a little more about it here would definitely help

**Comment by artemiokost** [comment]
Thanks alot @vietj ! Now after adding `vertx-rx-java2-gen` all works perfect!

**Comment by vietj** [comment]
ah thanks for reporting, I'll update the xample anyway as this use case is more often used than we thought initially
