### ISSUE TITLE
ServiceVertxProxyHandler do not manage Enum symmetrically if toString() is overwritten

### ISSUE THREAD

**Issue by ruget** [vert-x3/issues#445]
Hello,

`ServiceVertxProxyHandler` generated from service proxy module handle Enum with:
- `.valueOf()` to marshall from json msg
- `.toString()` to  unmarshall to json msg

If `.toString()` is overwritten, we are losing the symmetry.

Should we have `.name()` instead to unmarshall Enum?

This ticket might be related to https://github.com/vert-x3/vertx-codegen/issues/174

Thanks

**Comment by vietj** [comment]
yes with a test thanks!

**Comment by ruget** [comment]
Here a test: https://github.com/ruget/vertx-445-reproducer

**Comment by ruget** [comment]
I've tried to propose something here https://github.com/vert-x3/vertx-service-proxy/pull/84
