### ISSUE TITLE
io.vertx.core.VertxException: Thread blocked spam

### ISSUE THREAD

**Issue by DemianTinkiel** [vert-x3/issues#450]
Hi,

I'm trying to debug my tests and every time I stop at a break-point I get

```
Mar 27, 2019 1:19:42 PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 70580 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked

at....
```

I know this is a normal part of vertx and I have tried using 
`-Dvertx.options.blockedThreadCheckInterval=999999
-Dvertx.options.maxEventLoopExecuteTime=9999999
`
as well as adding `<logger name="io.vertx.core.impl.BlockedThreadChecker" level="OFF" />` to my logback configuration but nothing seems to stop vertx from spamming my console. This makes it really hard to see my own debug messages.

Running JUNIT 4.X tests from IntelliJ. Tests started from intellij (same problem if tests started maven-surefire-plugin, also with above options)

**Comment by Jofairden** [comment]
Hey, you can do something like this for debugging:
```Vertx.vertx (VertxOptions().setBlockedThreadCheckInterval(1000 * 60 * 60))```

**Comment by DemianTinkiel** [comment]
Isn't that the same as using
 -Dvertx.options.blockedThreadCheckInterval=999999

**Comment by Jofairden** [comment]
Maybe, but codewise has worked for me.
