### ISSUE TITLE
A fatal error has been detected

### ISSUE THREAD

**Issue by b3lowster** [vert-x3/issues#451]
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe5b5f64361, pid=18470, tid=0x00007fe526ded700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 6014 C2 io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(Ljava/lang/Void;)V (55 bytes) @ 0x00007fe5b5f64361 [0x00007fe5b5f64220+0x141]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/vtsukanov/java_projects/demo_day/reactive_microservices/reactive_vertex/gateway/hs_err_pid18470.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
```
[hs_err_pid18470.log](https://github.com/vert-x3/issues/files/3027142/hs_err_pid18470.log)
[hs_err_pid14782.log](https://github.com/vert-x3/issues/files/3027143/hs_err_pid14782.log)

**Comment by tsegismont** [comment]
A small reproducer would help

**Comment by b3lowster** [comment]
@tsegismont Would you like to have access to my project ?

**Comment by tsegismont** [comment]
Not the whole project. Just a small reproducer.

**Comment by b3lowster** [comment]
[reactive_vertx.zip](https://github.com/vert-x3/issues/files/3028371/reactive_vertx.zip)
I guess to reproduce you need to have a whole project. There are three project the issue was happened in gateway part

**Comment by tsegismont** [comment]
It's going to be difficult to run the whole project.

Configure your system to enable coredumps and then
https://www.oracle.com/technetwork/java/javase/crashes-137240.html#gdywn
