### ISSUE TITLE
context.request().remoteAddress().host() May appear NullPointException.

### ISSUE THREAD

**Issue by CreazySlider** [vert-x3/issues#454]
context.request().remoteAddress().host(); This code may appear NullPointException.But I don't know which one of the apis is this exception.

**Comment by vietj** [comment]
is that your code or code in vertx ?

**Comment by CreazySlider** [comment]
> is that your code or code in vertx ?

"context.request().remoteAddress().host();"  --this is vertx's apis."context" is "Routingcontext".

**Comment by CreazySlider** [comment]
> is that your code or code in vertx ?

NullPointException occurred when I wanted to use this code to get the browser's ip address.

**Comment by vietj** [comment]
if that's you code you should separate this into multiple statements so you know where these is an NPE appearing

**Comment by CreazySlider** [comment]
> if that's you code you should separate this into multiple statements so you know where these is an NPE appearing

yes,I have already done the idea you said.Is NPE occurring because vertx's api is unstable?

**Comment by vietj** [comment]
no I want to undestand which part of the expression raise the NPE

**Comment by CreazySlider** [comment]
> no I want to undestand which part of the expression raise the NPE
This is what I want to know.I have split this expression apart.And Npe has only appeared 5 times so far.

**Comment by CreazySlider** [comment]
> no I want to undestand which part of the expression raise the NPE

I already know which expression raise the NPE.--context.request().remoteAddress()

When I split the code into multiple statements, I found that the NPE occurred by remoteAddress().

**Comment by vietj** [comment]
so the request is null ?

**Comment by CreazySlider** [comment]
> so the request is null ?

request.remoteAddress() is null.
