### ISSUE TITLE
vertx3.7 Redis connection is broken

### ISSUE THREAD

**Issue by 13779983327** [vert-x3/issues#457]
RedisOptions options = new RedisOptions();
		options.setEndpoint(SocketAddress.inetSocketAddress(6379, "127.0.0.1"));
		options.setPassword("123");
		Redis.createClient(vertx, options).connect(onConnect -> {
			if (onConnect.succeeded()) {
				System.out.println("redis connect success"); 
                         else {
				System.out.println("redis connect fail");
			}
               });

The IP, port, and password are all correct
When I call this code [options.setPassword("123");], the connection returns a prompt:
io.vertx.core.impl.NoStackTraceThrowable: Redis connection is broken.
redis connect fail

**Comment by 13779983327** [comment]
If redis does not set a password and does not call this code [options.setPassword("123");], the connection is fine

**Comment by 13779983327** [comment]
I found a bug:
io.vertx.redis.client.impl.RedisClient.connect,In this method,If the select method is not completed,connected is false,but authenticate method call client.send,Would be an error.

  if (!connected) {
      // this avoids entering the socket exception handler as it is well known
      // that the transport is broken.
      handler.handle(Future.failedFuture("Redis connection is broken."));
      return this;
    }

**Comment by reisandbeans** [comment]
This might be related to https://github.com/vert-x3/vertx-redis-client/issues/152

**Comment by 13779983327** [comment]
> This might be related to [vert-x3/vertx-redis-client#152](https://github.com/vert-x3/vertx-redis-client/issues/152)
OK,Thank you!
