### ISSUE TITLE
EventBus send() does not have a way to know that a send failed

### ISSUE THREAD

**Issue by apatrida** [vert-x3/issues#46]
When we had multiple nodes in the vertx cluster with invalid public published ports, so when send of a message got to the subs to send a message, and it fails, it silently eats the message.  Sending failing earlier in the call sometimes logs a failure, but again doesn't let the caller know.

So there is no way for a caller to know send() had a failure (has subscription, wants to send, but can't)

**Comment by purplefox** [comment]
You can set a timeout when sending and you will receive a failure exception if the message has not been replied to by then.

**Comment by apatrida** [comment]
We have a case where there were bad nodes in the cluster, replaced by good nodes.  So we are having send failures on the bad nodes (we think, feels like that supposedly-fixed hazelcast bug with the sub map not evicting nodes from the maps).  Therefore if 1 out of 3 nodes is down, and we put a timeout on each send, then we have a lag 1 out of 3 times which would be bad and make the system perform badly after node outages.

By "replied" you mean ACK'd internally, or an actual reply using a reply on the other end (currently we are not expecting a reply)

We are looking to try and figure out if it is hazel cast or us manually configuring hazel cast that is the issue.  (We create the cluster.xml basically in memory by loading the default value, then disabling multi-cast, then doing EC2 + docker discovery to figure out what the tcp-ip addresses should be, setting those we then start the cluster which appears to work fine until a node is down or replaced)

**Comment by purplefox** [comment]
Without sending a reply I don't see how you will know if the message has been received or not.

**Comment by apatrida** [comment]
A few cases would be nice to be built-in:

- connection was never established to send (would think there was a connection refused at some point given our case of node down, but still in 'subs' collection)
- A light-weight ACK for receipt would be useful so we do not have to put a reply on every receiver and handle that on every sender for a case of "did the protocol succeed in transferring the data"

Then for cases where you need to confirm action completed, a reply would be useful for our application code.

If not, the API is a bit RAW and the extra effort takes it closer to the edge of asking "why are we not using XxxxMq system?" ...  

And since there are probably plans for a bit more message guarantees, and worker queue module, those can cover some of the other cases without the application needing to send a reply as well.

But still have this odd problem that messages vanish into dead nodes and don't seem to notice nor heal the 'subs' collection.

**Comment by apatrida** [comment]
(related, and not related:  any way to print out the 'subs' map easily or changes to it from vertx so we can see what is hanging around after nodes die?)

**Comment by apatrida** [comment]
The node hanging around problem:  if we had a problem connecting to the cluster port at the start, but the nodes were added in hazelcast and alive, then when we drop the node it stays in the hazelcast subs list.    So when we fixed the private/public port and host issues with our nodes so they could connect correctly, we no longer have dropped nodes staying around.  Therefore, there is some logic error somewhere; but not a horrible case because once the cluster is healthy, we don't see the issue.

(maybe on failure to connect on the cluster port causes a listener to not be added, or something that would see it go away?)

**Comment by purplefox** [comment]
I am not aware of any remaining cluster issues, but if you have a reproducer for one please open a separate issue and we will investigate.

Regarding your suggestions, it's a good idea to always provide a result handler when doing a send.

In any distributed system it's always going to be possible that your message doesn't get delivered, for example:

1. At time of send the subscription existed but by the time it got to the target node the target had been unsubscribed
2. The target node was taken down
3. The target node crashed
4. Probably other cases

If you care about message delivery then you need to handle the failure case and take appropriate action, e.g. store message, retry message or log an error.

So closing this issue.
