### ISSUE TITLE
FileResolver resolve the wrong file path 

### ISSUE THREAD

**Issue by ddean2009** [vert-x3/issues#47]
in eclipse I import the vertx-examples-master maven project. 

then I try to run src/main/java/io/vertx/example/core/http/https/Server.java under module core-examples.  

it failed to load server-keystore.jks  . 

saying: 
Caused by: java.nio.file.NoSuchFileException: D:\work\eclipse_workspaces\mars\vertx-examples-master\core-examples\core-examples\src\main\java\io\vertx\example\core\http\https\server-keystore.jks

if you check the exception , the issue is there are two "core-examples"  in the path. 

in further debug ,  I find the issue is in FileResolver 

  public FileResolver(Vertx vertx) {
    this.vertx = vertx;
    String cwdOverride = System.getProperty("vertx.cwd");
    if (cwdOverride != null) {
      cwd = new File(cwdOverride).getAbsoluteFile();
    } else {
      cwd = null;
    }
    setupCacheDir();
  }

here the cwdOverride is : core-examples/src/main/java/io/vertx/example/core/http/https

after it got the absoluteFile , the file path is changed to : D:\work\eclipse_workspaces\mars\vertx-examples-master\core-examples\core-examples\src\main\java\io\vertx\example\core\http\https

and it adds the extra core-examples to it .

**Comment by purplefox** [comment]
How are you running the example?

**Comment by ddean2009** [comment]
In eclipse , select the Server.java ,  Run As --> Java Application

**Comment by ddean2009** [comment]
hi purplefox , any idea for this issue ?

**Comment by purplefox** [comment]
When run in the IDE the examples assume the current working directory is set to the project root directory, this is the default in IntelliJ.

In your case your project root seems to be set to the root of your module, not the project root. Maybe there is a setting in Eclipse to tell it to use project root for cwd?

**Comment by ddean2009** [comment]
sorry , can not find the setting in Eclipse ... 
![image](https://cloud.githubusercontent.com/assets/13955545/9516671/c162b9da-4cdc-11e5-88f5-176603545185.png)

these are the projects after I import vertx-examples-master

every module is treated as a project .

**Comment by purplefox** [comment]
Sorry, I don't use Eclipse, but a simple google turned up this:

http://stackoverflow.com/questions/329129/set-the-execution-directory-in-eclipse

**Comment by ddean2009** [comment]
after changed the working directory , it works . thanks.
