### ISSUE TITLE
Json Serializer timeout in vert.x 3.6.+ and 3.7.+

### ISSUE THREAD

**Issue by argaha** [vert-x3/issues#475]
Json serialer is not terminating.

reproducing: 
[vertxProject.zip](https://github.com/vert-x3/issues/files/3378131/vertxProject.zip)

**Comment by argaha** [comment]
Hi @vietj ,

vert.x 3.8.0 has been released already but issue is still not fixed. Any updates on when we can expect this to be fixed?

**Comment by dawinter** [comment]
Hi

this issue blocks the upgrade to a newer vert.x versions that become a security risk. 
Looks like argaha provided sample code to be able to recreate it.
Is there anything missing that we could provide? 

@vietj Do you have any idea who can work or when the issue can be fixed?
Thanks.

**Comment by vietj** [comment]
it's not clear what the issue is by the description, there is a reproducer though

**Comment by dawinter** [comment]
@argaha See update from Julien, Can you update the issue description and and describe the issue more in detail, error condition, expected good condition, may steps to reproduce / how to use the attacted reproduce package. 

Thanks

**Comment by vietj** [comment]
I found the issue in the `JsonParser`, there will be a patch likely tomorrow

**Comment by vietj** [comment]
fixed by https://github.com/eclipse-vertx/vert.x/issues/3076

**Comment by dawinter** [comment]
@vietj Great, thanks for your immediate help.
