### ISSUE TITLE
GraphQL Subscriptions generate an 'Internal Server Error'

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vert-x3/issues#479]
I am trying to get a GraphQL subscription working with Java/Vert.x and to have the results shown in GraphiQL. I see all the System.out.println statements in the console, but GraphiQL is not displaying any results because the server is generating an 'Internal Server Error' message. I am using vert.x 3.8.0 jars

Schema:

    type Subscription {
        test: String
    }

Vert.x Verticle

    private RuntimeWiring getRuntimeWiring() {
      return new RuntimeWiring()
        .type("Subscription", builder -> builder
          .dataFetcher("test", getTestDataFetcher()))
        .build();
    }

    private VertxDataFetcher<Publisher<String>> getTestDataFetcher() {
      return new VertxDataFetcher<>((env, future) -> future.complete(doTest()));
    }

    private Publisher<String> doTest() {
      AtomicReference<Subscription> ar = new AtomicReference<>();
      Observable<String> obs = Observable.just("Hello");
      Publisher<String> pub = obs.toFlowable(BackpressureStrategy.BUFFER);
      pub.subscribe(new Subscriber<String>() {
        @Override  
        public void onSubscribe(Subscription s) {
          System.out.println("SUBSCRIBE");
          ar.set(s);
          s.request(1);
        }
        @Override  
        public void onNext(String s) {
          System.out.println("NEXT="+s);
          ar.get().request(1);
        }
        @Override  
        public void onError(Throwable t) {
          System.out.println("ERROR");
        }
        @Override  
        public void onComplete(){
          System.out.println("COMPLETE");
        }
      }
      return pub;
    }

If I run the subscription using GraphiQL and look on my vert.x servers console, the output on the console is:

    SUBSCRIBE
    NEXT=Hello
    COMPLETE

The GraphiQL output window says "Internal Server Error" and is sent a 500 error code from the server  

If I modify the DataFetcher to exactly what is shown at the bottom of the first link, I also receive "Internal Server Error".  

    private DataFetcher<Publisher<String>> getTestDataFetcher() {
      return env -> doTest();
    }

I do not see any stack traces for the 500 error in the vertx console.  So maybe this is a bug?

Sidenote  - If I try using a CompletionStage as shown below (based off the bottom of the 2nd link) I get an error message saying 'You data fetcher must return a publisher of events when using graphql subscriptions'

    private DataFetcher<CompletionStage<String>> getTestDataFetcher() {
      Single<String> single = Single.create(emitter -> { 
        new Thread(()-> {
          try {
            emitter.onSuccess("Hello");
          } catch(Exception e) {
            emitter.onError(e);
          }
        }).start();
      )};
      return environment -> single.to(SingleInterop.get());
    }

I have used the following sources as references to get this far:

  - https://www.graphql-java.com/documentation/v9/subscriptions/
  - https://vertx.io/docs/vertx-web-graphql/java/

**Comment by tsegismont** [comment]
Duplicates https://github.com/vert-x3/vertx-web/issues/1334
