### ISSUE TITLE
[Task] Clean up deprecated code that is older than 3 releases

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/issues#484]
Deprecated code older than 3 releases (older or equal to 3.6.0) shall be removed from the master branches as agreed by the project governance. To simplify the task all `@Deprecated` introduced before `2018-11-28 21:54` shall be removed.

* [ ] [https://github.com/vert-x3/vertx-web/issues/1351](vertx-web)

**Comment by vietj** [comment]
Should never be fixed
