### ISSUE TITLE
Future<T> future() problem

### ISSUE THREAD

**Issue by zhaozhou11** [vert-x3/issues#487]
My case is:

Future future = Future.future();
future.setHandler(res ->{
    System.out.println("currThreadId4=" + Thread.currentThread().getId());
    System.out.println("result:" + ((Future)res).succeeded());
});
Future.<String>future(f -> exceptionFuture(f)).compose(res -> {
    System.out.println("res=" + res);
    throw new NullPointerException("TTTT");
},future)

when function "exceptionFuture()" occur exception, "future.setHandler()" will never call, then we don't know whether result is successd or failed!

i recommand it need got some change of interface Future,just like this:

static <T> Future<T> future(Handler<Future<T>> handler) {
        Future<T> fut = Future.future();
        try {
            handler.handle(fut);
        }catch (Exception e){
            fut.tryFail(e);
        }
        return fut;
    }

then "future.setHandler()" will be called, and we know the result.

**Comment by thced** [comment]
@pmlopes This seems to be already solved by [d14f8328](https://github.com/eclipse-vertx/vert.x/commit/d14f832823c4e08dd692f9b70fc91a2ac03ebc13)
Close?

**Comment by tsegismont** [comment]
@thced this is outdated. Thanks
