### ISSUE TITLE
AsyncResult handlers of type Void are problematic

### ISSUE THREAD

**Issue by apatrida** [vert-x3/issues#49]
Some of the Async Handlers have type Void as the result type, but that isn't an instantiate-able type, so they instead return null.  Other languages on the JVM treat Void as not nullable because when a void method returns it always returns as void.  But in the case of vert.x it is always null.  

Seems to be a misuse of Void, but I'm not sure.  Nor sure what to do about it.

Kotlin for example, has an issue with this.  If I weren't using promises I could probably try calling it a `Void?` but that type isn't allowed in a promise.

**Comment by vietj** [comment]
Currently integrated languages in Vert.x 3 are using codegen to create an API. Perhaps you should consider doing the same for Kotlin, it would allow to map Handler<AsyncResult> the way you want.

**Comment by vietj** [comment]
Changing this design in Vert.x would definitely break the API, so I'm afraid we cannot change this on our side for the moment.

**Comment by vietj** [comment]
any comment on this ?

**Comment by pmlopes** [comment]
We have now kotlin bindings so this is not an issue.
