### ISSUE TITLE
JsonParser in combination with Flowable does not return Parsing exception in error case

### ISSUE THREAD

**Issue by dawinter** [vert-x3/issues#495]
Hello,
we use the JSONParser in combination with Flowable in the request flow.
The user sends JSON documents and it is processed by the JSONParser.
If the user sends corrupt JSON, the process usually got an exception via onError and could sends a 400 error to client. After updating to Vertx3.8.1, the onError never triggered and the request goes into a timeout.

We investigated the issue and could recreate it in a simple example (see attachment)
The package contains a Unit Testcase that loads a JsonFile as ReadStream and process it with JSONParser.
Can you please check out and let us know if we need to change the usage the vertx code need to change?

Steps to recreate:
1.	Download and extract project
2.	configure dependency vertx 3.5.4 or vertx 3.8.1
3.	Excecute parserDemo.ParserTest

Expected Result: Test throws parsing exception
Actual Result (3.8.1): Test run in timout

Non-Affected version (tried): 3.5.4
Affected version (tried): 3.8.1, 3.8.2

[recreateFile.zip](https://github.com/vert-x3/issues/files/3691313/recreateFile.zip)

We analyzed the issue further and found that the usual error processing is happen in the JSONParser and is pushed to the RX stream exception handler FlowableReadStream. The exception handler processes the release method and null the handler of the JSONParser. Afterwards the release method triggers the fetch again and when the JSONParser continue to process, the exception handler is null and so the JSONParser throw the exception directly. Our assumption is that the nulling of the Parser and trigger the processing crashs the complete flow and prevent to trigger the OnError event. An idea is may to instead of null the handler, just set a NOOPHandler as exception handler in Flowable scenario.

Let me know if you need any further information. Thanks. @vietj

**Comment by vietj** [comment]
thanks for the reproducer, having a look.

**Comment by vietj** [comment]
thanks for the explanation too

**Comment by vietj** [comment]
I think we need to look at two things:

- the stream resume failure should be caught in vertx-rx
- in JsonParser since we are already parsing, the `checkPending()` should not trigger parsing in a reentrant way

**Comment by vietj** [comment]
I will do a fix for the vertx-rx and hopefully it will solve the solution, the second point might take more time to study.

Also likley the handle method should not throw an exception and the error should always be done on the exception handler whatsoever.

**Comment by vietj** [comment]
see https://github.com/vert-x3/vertx-rx/issues/212

**Comment by vietj** [comment]
see also https://github.com/eclipse-vertx/vert.x/issues/3149

**Comment by vietj** [comment]
thanks for the reproducer and thorough analysis.
