### ISSUE TITLE
Typo in the redis docs

### ISSUE THREAD

**Issue by AnthonyRuffinoDH** [vert-x3/issues#496]
On this page of the documentation: https://vertx.io/docs/vertx-redis-client/java/

The following text appears:

"The automatic reconnect is not part of the redis client has it will force a behaviour that might not match the user expectations, for example:"

It should read: 

"The automatic reconnect is not part of the redis client as it will force a behaviour that might not match the user expectations, for example:"

**Comment by pmlopes** [comment]
Thanks!  Fixed on master
