### ISSUE TITLE
vertx-circuit-breaker java CircuitBreaker interface has breaking change 3.8.1 > 3.8.2

### ISSUE THREAD

**Issue by dawinter** [vert-x3/issues#498]
The method signature from of the io.vertx.reactivex.circuitbreaker.CircuitBreaker execute method changed from 

public <T> io.vertx.reactivex.core.Future<T> execute(Handler<io.vertx.reactivex.core.Promise<T>> command)
to 
public <T> void execute(Handler<io.vertx.reactivex.core.Promise<T>> command, Handler<AsyncResult<T>> handler)

But the 3.8.2 breaking changes list https://github.com/vert-x3/wiki/wiki/3.8.2-Deprecations-and-breaking-changes does not show it and the documentation also describe the original interface:
https://vertx.io/docs/vertx-circuit-breaker/java/

Can you please make it consistent. Thanks.

**Comment by vietj** [comment]
the method:

```
  <T> Future<T> execute(Handler<Promise<T>> command);
```

still exist in 3.8.2

**Comment by dawinter** [comment]
Are you sure that `io.vertx.reactivex.circuitbreaker.CircuitBreaker` has a method with  `<T> Future<T> execute(Handler<Promise<T>> command)`? The version I can download has only `public <T> void execute(Handler<io.vertx.reactivex.core.Promise<T>> command, Handler<AsyncResult<T>> handler)`

**Comment by dawinter** [comment]
But I see what you mean. The doc describes the non reactive version. Unfortunately the reactive version had a breaking change that is not in the breaking changes list :)

**Comment by vietj** [comment]
oh right indeed, this is because we need to use `@GenIgnore` to ignore the method and thus there is no RX generation. I'll update the wiki page thanks.
