### ISSUE TITLE
Heroku buildpack

### ISSUE THREAD

**Issue by mthenw** [vert-x3/issues#5]
Hi,

I'm owner of https://github.com/mthenw/heroku-buildpack-vertx. Are you interested in hosting it as a official buildpack? Of course some work is required to update packages to latest version. I'm also not sure if that kind of buildpack is required, maybe the one handling maven (or gradle) is enough for developers using vertx.

**Comment by purplefox** [comment]
Hi Maciej,
Could you explain a bit about what hosting as an official buildpack would involve?

**Comment by mthenw** [comment]
Buildpack is a set of three shell scripts (`detect`, `compile`, `release`). When you want to deploy application, heroku runs `detect` script from every buildpack. If it returns true, that means that this buildpack should take care of compilation and release. The only thing that is required for making buildpack usable is bumping versions of vert.x (https://github.com/mthenw/heroku-buildpack-vertx/blob/master/bin/compile#L8) and sometimes Java.

When I was using vert.x for my on purpose I was bumping version quite often. Now I'm not sure if anyone is using my buildpack (but based on number of forks, looks like it's useful). Making it official probably should cause that it would be more popular I could spend more time on it. 

One thing to figure out is how buildpack should decide that some application is compatible with it. I was assuming that repository has `server.js` and `mod.json`. Of course it's not good solution as it doesn't support other languages (e.g. nodejs buildpack checks if there is `package.json`).

One more thing, when I wrote "hosting" I only meant making a repository under vert-x organization. Noting more is required.

**Comment by purplefox** [comment]
I would be happy for this to become official. I assume this is only for vert.x 2 at the moment?
It would be good to get something working for the imminent Vert.x 3.
The vert-x organisation in GitHub is for Vert.x 2, the vert-x3 org is for Vert.x 3.

**Comment by mthenw** [comment]
Great. I will prepare working buildpack for version 3.

**Comment by mthenw** [comment]
I've updated 2.x buildpack to Java 1.8 and Vert.x 2.1.5. I've also prepared one for v3-milestone3 but looks like it's not working (https://github.com/mthenw/heroku-buildpack-vertx/issues/1). I will try to fix that later today or tomorrow.

BTW, you would rather there be one repo for that (one branch for v2, one for v3) or two separate repositories?

**Comment by purplefox** [comment]
Hi Maciej - I think it would be better to have a separate repo for V3

**Comment by mthenw** [comment]
Well, as Heroku started supporting docker images and vert.x has official docker images buildpack is no longer needed.
