### ISSUE TITLE
commit: c3b8d9ed702e9fad506e53aa3104a86c741f93f2

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/issues#50]
breaks vert.x web - we are getting mixed status responses. I would guess that since we are reusing connections some state was not reseted in netty.

**Comment by purplefox** [comment]
Paulo, can you provide a link? It's not clear which repository this refers to.

**Comment by pmlopes** [comment]
https://github.com/eclipse/vert.x/commit/c3b8d9ed702e9fad506e53aa3104a86c741f93f2

**Comment by pmlopes** [comment]
i now get status code 999 while runing the vertx-web tests which is kind of strange i i revert that single commit in core and rebuild and run web tests everything is fine...

**Comment by purplefox** [comment]
Ok, will take a look :)

**Comment by purplefox** [comment]
This seems to be happening because Netty doesn't like the statusMessage that is set by the test, e.g. "/2933f122-47e7-49f8-8466-f5c37d1f0cda" and then sets the status code to the value "999".

**Comment by pmlopes** [comment]
that is not a typical message but perfectly legal, it does not contain invalid chars and if that commit is not applied then netty accepts it...

**Comment by purplefox** [comment]
I think for some reason that Netty thinks the HTTP protocol is broken, and then uses this status code, you'll also notice that the status message on the client side is "Unknown". This is done in the client side protocol parsing.

So maybe something in that commit, broke the HTTP protocol in some way? We need to debug it some more. I'll give it a go tomorrow as I'm going to be in meetings the rest of the day.

**Comment by pmlopes** [comment]
Ok, so after some more investigation, the issue is not related to the server component but to the Client and that makes sense since the commit relates to `ClientConnection`.

Looking to curl requests using the same code as the test i can assert that the status codes are correctly sent by the server, however the HttpClient gets messed up.

**Comment by purplefox** [comment]
Should be fixed now in vertx-web
