### ISSUE TITLE
[Vert.x/Gradle/Java/Help] How to build specific verticle

### ISSUE THREAD

**Issue by tuhuynh27** [vert-x3/issues#503]
I'm using Vert.x with Gradle and Java, how to build multiple verticles (each verticle to a .jar file) in the same code base:

I also use the Gradle starter with this default config:

```
shadowJar {
  classifier = 'fat'
  manifest {
    attributes 'Main-Verticle': mainVerticleName
  }
  mergeServiceFiles {
    include 'META-INF/services/io.vertx.core.spi.VerticleFactory'
  }
}
```

Thank you.

**Comment by jponge** [comment]
In this case you'd better use sub-projects

**Comment by tuhuynh27** [comment]
> In this case you'd better use sub-projects

Do you know an example sub-projects repository example with Gradle or a tutorial for doing this, I only see the sub-project with Maven 😃
