### ISSUE TITLE
Vertx - Codegen Service Proxy flow

### ISSUE THREAD

**Issue by tuhuynh27** [vert-x3/issues#505]
I'm using Codegen & Service Proxy to create service call between two verticle in a cluster (via the service proxy - event bus).

But, if serverA want to call serviceB, then service A must include the `serviceBInterface` in the serviceA's source code, so I have to include the serviceB project this in gradle `compile project(':b-service')` which lead to a **circular dependency exception**.

How can I handle that. Thanks. :smiley:

**Comment by tuhuynh27** [comment]
Hi, any body help :(

**Comment by BornToRain** [comment]
u can create api and impl 2 module.api module only define interface,impl module  to imple the interface.
u only need  **compile(":api")**  in build.gradle

**Comment by tsegismont** [comment]
Closing as this is not a Vert.x issue
