### ISSUE TITLE
Optional

### ISSUE THREAD

**Issue by bailly-idmgroup-com** [vert-x3/issues#506]
Hi everyone,

I was wondering if there is a vertx equivalent for java.util.Optional which could be used over service proxy, json communication.
For example a service could provide that sort of mapping:
- fetchOne(String sql, JsonArray params, Handler<AsyncResult<Optional<JsonObject>>> resultHandler)
- fetchOne(String sql, JsonArray params, Handler<AsyncResult<Optional<MyDataObject>>> resultHandler)

so we can have clean and maybe avoid easierly null pointer exception in the handler

fetchOne(..., ..., hr -> {
if(hr.succeeded()){
  if(hr.result().isPresent())
// succeed and found
else
// succeed but not found
} else
// failed to query maybe retry ?
}
})

as a side note I was wondering why @DataObject was an annotation and not an interface.
It would then be easy create the vertx Optional.

**Comment by jotak** [comment]
I was thinking about something quite similar too: some way to decompose the handler into one handler for success and one for error (a bit similar to the `runCatching` of kotlin). This is quite a common pattern. So that when the success handler is called we're guaranteed to have a result.

But I don't know, if it adds yet another way of doing the things, that might be counter-productive for a clean API? I'm not sure.

**Comment by vietj** [comment]
that exist if you use the RxJava2 version of the API that will return Maybe<T> instead of Single<T> . We are not planning adding a similar type in Vert.x

**Comment by vietj** [comment]
e.g https://vertx.io/docs/apidocs/io/vertx/reactivex/ext/mongo/MongoClient.html#rxFindOne-java.lang.String-io.vertx.core.json.JsonObject-io.vertx.core.json.JsonObject-

**Comment by bailly-idmgroup-com** [comment]
Then do you think it is possible to have an interface equivalent to @DataObject so it's easy to implement independantly an Optional class ? Obviously I can create one wrapping jsonObject only which might cover lot of case, but I think it's plan for @DataObject to enlarge the type of data it can cover

**Comment by vietj** [comment]
I don't understand what you mean @bailly-idmgroup-com , can you give an example ?

**Comment by bailly-idmgroup-com** [comment]
Sure
Currently I should be able to do something like it
`
package com.idmgroup.ao.web.utils;

import io.vertx.codegen.annotations.DataObject;
import io.vertx.core.json.JsonObject;

@DataObject(generateConverter = true)
public class Optional {

    private JsonObject value = null;

    public Optional() {
        super();
    }

    public Optional(JsonObject json) {
        OptionalConverter.fromJson(json, this);
    }

    public JsonObject toJson() {
        JsonObject json = new JsonObject();
        OptionalConverter.toJson(this, json);
        return json;
    }

    public JsonObject getValue() {
        return value;
    }

    public void setValue(JsonObject value) {
        this.value = value;
    }

    public boolean isPresent() {
        return this.value != null;
    }

    public static Optional of(JsonObject value) {
        Optional optional = new Optional();
        optional.value = value;
        return optional;
    }

    public static Optional empty() {
        return new Optional();
    }

}
`

but with a DataObject interface, I could do something like that

`public class Optional<D extends DataObject> implements DataObject {

    private D value = null;

    public Optional() {
        super();
    }

    public Optional(JsonObject json) {
        OptionalConverter.fromJson(json, this);
    }

    public JsonObject toJson() {
        JsonObject json = new JsonObject();
        OptionalConverter.toJson(this, json);
        return json;
    }

    public D getValue() {
        return value;
    }

    public void setValue(D value) {
        this.value = value;
    }

    public boolean isPresent() {
        return this.value != null;
    }

    public static <D extends DataObject> Optional<D> of(D value) {
        Optional<D> optional = new Optional<>();
        optional.value = value;
        return optional;
    }

    public static <D extends DataObject> Optional<D> empty() {
        return new Optional<D>();
    }
}`

I hope it's clearer

**Comment by vietj** [comment]
what would the `DataObject` interface do ?

**Comment by bailly-idmgroup-com** [comment]
hum there is something wrong with the code tag the second class header should be :
public class Optional\<D extends DataObject\> implements DataObject
the interface would just be interpreted like the @DataObject. enabling for generic interpretation.
All the wonderful black magic done in codegen ...

This could be useful also for a dao for example:
`package com.idmgroup.ao.web.utils.test;

import java.util.List;
import java.util.function.Function;
import java.util.stream.Collectors;

import io.vertx.core.AsyncResult;
import io.vertx.core.Future;
import io.vertx.core.Handler;
import io.vertx.core.json.JsonObject;
import io.vertx.ext.sql.SQLClient;

public class Dao\<D extends DataObject\> {
	
	private Function<JsonObject, D> converter;

    protected SQLClient dbClient;

	public Dao(SQLClient dbClient, Function<JsonObject, D> converter) {
		super();
		this.converter = converter;
        this.dbClient = dbClient;
	}
	
    protected void fetchAll(String sql, Handler<AsyncResult<List<D>>> resultHandler) {
        this.dbClient.query(sql, rh -> {
            if (rh.succeeded()) {
            	List<D> results = rh.result().getRows().stream().map(this.converter).collect(Collectors.toList());
                resultHandler.handle(Future.succeededFuture(results));
            } else {
                resultHandler.handle(Future.failedFuture(rh.cause()));
            }
        });
    }
}`
