### ISSUE TITLE
vertx-guice don't support vert.x 3.8.x

### ISSUE THREAD

**Issue by Kirik0u** [vert-x3/issues#509]
Hi,

i'm here because i noticed that vertx-guice 2.3 don't support vertx 3.8 and precisly the using of Promise in verticle start and stop methods.

My project just works fine when i'm using a version of vertx below 3.8 (with Future) but since i made my changes to use promises, my verticle doesn't start anymore.

When i test to remove the use of vertx-guice, it works, but i need it, so this is not a solution

Did someone noticed the same thing ? and how can i fix it ?

**Comment by vietj** [comment]
can you report this to the vertx-guice project ?

**Comment by Kirik0u** [comment]
i would like to but i can't find it

**Comment by vietj** [comment]
what are the maven coordinates of the project you are using ?

**Comment by Kirik0u** [comment]
maven coordinates ?? I don't know what it means ... sorry

But I find out that vertx-guice instanciate his own verticle but use Future instead of Promise. And then call the super verticle start methods with Future.

It means that vertx needs to update this dependancy.

**Comment by tsegismont** [comment]
@Kirik0u please report to https://github.com/ef-labs/vertx-guice

Vert.x Guice is a community effort not supported by the core team.
