### ISSUE TITLE
io.vertx.core.file.impl.FileResolver.resolveFile() has a bug

### ISSUE THREAD

**Issue by yn-tadpole** [vert-x3/issues#515]
### Questions

io.vertx.core.file.impl.FileResolver.resolveFile(fileName) use a ClassLoader to resolve resource. It always return null when getResource() has been called. Because the fileName which send to resolveFile alway starts with '/'.

The resolveFile method will been used in StaticHandler and HttpServerResponse. 

It will cause an error when sending the file to the client, the first time it is called, and the subsequent time it will not see an error because it reads from the cache and did not execute getResource 
This leads to program instability.

### Version

3.8.5

### Context

```
resolveFile:143, FileResolver (io.vertx.core.file.impl)
resolveFile:805, VertxImpl (io.vertx.core.impl)
<init>:933, FileSystemImpl$20 (io.vertx.core.file.impl)
existsInternal:932, FileSystemImpl (io.vertx.core.file.impl)
exists:340, FileSystemImpl (io.vertx.core.file.impl)
lambda$isFileExisting$2:283, StaticHandlerImpl (io.vertx.ext.web.handler.impl)
call:-1, 1512148561 (io.vertx.ext.web.handler.impl.StaticHandlerImpl$$Lambda$234)
wrapInTCCLSwitch:266, StaticHandlerImpl (io.vertx.ext.web.handler.impl)
isFileExisting:283, StaticHandlerImpl (io.vertx.ext.web.handler.impl)
sendStatic:192, StaticHandlerImpl (io.vertx.ext.web.handler.impl)
handle:145, StaticHandlerImpl (io.vertx.ext.web.handler.impl)
handle:51, StaticHandlerImpl (io.vertx.ext.web.handler.impl)
```

### Do you have a reproducer?

See the source code, everything is there.

### Extra

OS: Windows 10
JVM: OpenJDK 12

**Comment by vietj** [comment]
your issue description is not clear enough, according to your saying, you say that the classloader returns null but this null value is checked the line after.

I spent some time trying to figure out what possible issue could happen here and I did not find.

can you post a stack trace or a more accurate description of the issue (_it causes an error_ which error ?) ?
