### ISSUE TITLE
vertx 3.8.5 fat jar

### ISSUE THREAD

**Issue by DaveO-Home** [vert-x3/issues#519]
This may not be a fat jar problem - looks like a 3.8.5 problem.
I get the same results when executing `build/scripts/dodex-vertx`

Note: gradlew run - works

executing `java -jar build/libs/dodex-vertx-3.8.5-all.jar` produces `[SEVERE] Failed to deploy verticle dmo.fs.vertx.Server io.vertx.core.impl.launcher.commands.RunCommand`

executing `java -jar build/libs/dodex-vertx-3.8.5-all.jar start`  produces
`Starting vert.x application... 26523e7b-9ba1-4cea-9f03-2109eb2daacf`
No vertical is actually started.
`java -jar build/libs/dodex-vertx-3.8.5-all.jar list
Listing vert.x applications...
No vert.x application found.`

gradle config:
`id 'com.github.johnrengelman.shadow' version '5.2.0'

mergeServiceFiles {
    include "META-INF/services/io.vertx.core.spi.VerticleFactory"
  }

  manifest{
    attributes 'Main-Verticle': mainVerticleName
  }`

works with 3.8.4.

**Comment by tsegismont** [comment]
Can you compare your config with
https://github.com/vert-x3/vertx-gradle-starter

**Comment by DaveO-Home** [comment]
My project is on npmjs - dodex-vertx. You can install or view on github.  I run on Fedora  31, it was working as of 1+ weeks ago.  I'm thinking maybe it's the Java VM - 
`openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)`
I've tried Vertx 3.8.4 and  down-graded gradle to 5.4.6 with the same results.
However, I also ran with Oracle java13 with same results.

**Comment by DaveO-Home** [comment]
I ran the starter kit as is and it worked. Old versions of vertx and shadow plugin.
Upgraded starter kit to vertx 3.8.5 and plugin to 5.2.0 and failed with same results above.
And gradlew run worked just fine....

**Comment by DaveO-Home** [comment]
Solved - with my previous tests/development I had an enviroment variable set.  In my Server class I was assuming it was set;  
`private static String development = System.getenv("VERTXWEB_ENVIRONMENT") .toLowerCase();`
It was failing on null pointer but not reporting it!

**Comment by tsegismont** [comment]
Thanks for letting us know
