### ISSUE TITLE
JSON object properties ordering is not preserved when sent over EventBus

### ISSUE THREAD

**Issue by zdila** [vert-x3/issues#52]
JsonObject stores properties in LinkedHashMap that ensures the property order. Unfortunately this order gets lost when sending the JsonObject as meessage via EventBus.

**Comment by pmlopes** [comment]
> JsonObject stores properties in LinkedHashMap that ensures the property order.

That is a false assumption!

JSON spec does not require that the order of properties is guaranteed.

See: http://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%203rd%20edition,%20December%201999.pdf

Specifically:

> 4.3.3 Object
> An object is a member of the type Object. It is an unordered collection of properties each of which contains a primitive value, object, or function. A function stored in a property of an object is called a method.

If you need to preserve the order you must use an JsonArray where it is guaranteed that the order is preserved.

**Comment by zdila** [comment]
OK. Then I am wondering why JsonObject uses LinkedHashMap and not just HasMap.

**Comment by pmlopes** [comment]
That is an implementation detail but some benchmarks will tell you that usually the cost of iteration or access to a hash bucket on a `LinkedHashMap` is cheaper than on a traditional `HashMap`.

**Comment by zdila** [comment]
Thanks for the explanation.

**Comment by purplefox** [comment]
+1 If you want ordering you can use a JsonArray
