### ISSUE TITLE
BlockedThreadChecker.log not work in 4.0.0-SNAPSHOT, but 3 is work ok.

### ISSUE THREAD

**Issue by takeseem** [vert-x3/issues#522]
### Questions

I'm build a new framework with Vert.X 4, but I fond it's look not stable.
although I love 4.x, but now I must be back to 3.x .
**What's the 4.x release time?** that time I will back to try 4.x.

- bug1: `BlockedThreadChecker.log` not work in 4, but 3 is work ok.
log4j2 2.13.1,  includeLocation="true"
in eclipse debug: [StackLocator.calcLocation(StackLocator.java:79)](https://github.com/apache/logging-log4j2/blob/log4j-2.13.1/log4j-api/src/main/java/org/apache/logging/log4j/util/StackLocator.java#L79), but I found in fact it's [logging-log4j2-java9 StackLocator.java:79](https://github.com/apache/logging-log4j2/blob/log4j-2.13.1/log4j-api-java9/src/main/java/org/apache/logging/log4j/util/StackLocator.java#L79), but in my classpath I can't found the log4j-api-java9.jar?
```
Exception in thread "vertx-blocked-thread-checker" java.lang.NullPointerException
	at org.apache.logging.log4j.util.StackLocator.calcLocation(StackLocator.java:79)
	at org.apache.logging.log4j.util.StackLocatorUtil.calcLocation(StackLocatorUtil.java:78)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:153)
	at org.apache.logging.slf4j.Log4jLogger.log(Log4jLogger.java:376)
	at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:188)
	at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:160)
	at io.vertx.core.logging.SLF4JLogDelegate.log(SLF4JLogDelegate.java:156)
	at io.vertx.core.logging.SLF4JLogDelegate.warn(SLF4JLogDelegate.java:86)
	at io.vertx.core.impl.logging.LoggerAdapter.warn(LoggerAdapter.java:79)
	at io.vertx.core.impl.BlockedThreadChecker$1.run(BlockedThreadChecker.java:59)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```
- bug2：thead death block use SpringVerticleFactory in Spring IoC, but 3.9 is work ok.
SpringBoot SpringApplication.run() : main thead
```
VerticlesManager {
  @PostConstruct
  public void init() {
    Promise<String> p = Promise.promise();
    vertx.deployVerticle(name, new DeploymentOptions(), p);
    Future<String> f = p.future();
    // use CompletableFuture to await future
    UtilVertx.await(f);
    logger.info("deploy verticle: {}", f.result());
  }
}
````
vert.x-eventloop-thread-0 
```
SpringVerticleFactory {
  createVerticle {
     // it will wait the main thead, because spring application context not ready.
     (Verticle) spring.getBean(classLoader.loadClass(name));
  }
}
```
in 3.9.0, it's the same thead[main] so it's work ok.

I think maybe not bug, it is reasonable use eventloop to deploy Verticle. (I use SmartLifecycle to fix it)

the stack is
```
Thread [main] (Suspended (breakpoint at line 63 in SpringVerticleFactory))	
	DeploymentManager.createVerticles(VerticleFactory, String, int, ClassLoader) line: 243	
	DeploymentManager.lambda$doDeployVerticle$2(String, DeploymentOptions, Handler, VerticleFactory, ClassLoader, ContextInternal, ContextInternal, Iterator, AsyncResult) line: 216	
	1752894940.handle(Object) line: not available	
	FutureImpl<T>.dispatch(Handler<AsyncResult<T>>) line: 105	
	FutureImpl<T>.onComplete(Handler<AsyncResult<T>>) line: 83	
	DeploymentManager.doDeployVerticle(Iterator<VerticleFactory>, Throwable, String, DeploymentOptions, ContextInternal, ContextInternal, ClassLoader, Handler<AsyncResult<String>>) line: 183	
	DeploymentManager.doDeployVerticle(String, DeploymentOptions, ContextInternal, ContextInternal, ClassLoader, Handler<AsyncResult<String>>) line: 156	
	DeploymentManager.deployVerticle(String, DeploymentOptions, Handler<AsyncResult<String>>) line: 145	
	VertxImpl.deployVerticle(String, DeploymentOptions, Handler<AsyncResult<String>>) line: 683	
	VerticlesManager.deployVerticle(VerticleDeployProperties) line: 65	
```

### Version

4.0.0-SNAPSHOT

### Extra
* Ubuntu 18.04.4 LTS
* OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

**Comment by vietj** [comment]
Vert.x 4 is still a work in progress, you can use instead published milestones which have been reported quite stable and avoid snapshots. If you report issues we will fix them of course. We believe to start stable beta within a couple of months but we cannot give precise estimations it might go faster or slower, given at the same time we need to work also on Vert.x 4 new web site.

**Comment by vietj** [comment]
Can you provide a reproducer project for the bugs, it will be easier to figure out.

**Comment by vietj** [comment]
resolved as a bug in lo4j.
