### ISSUE TITLE
HTTP2 request does not return if `Http2ServerResponse#trailers()` called and response is handled inside an `Executor` or `runOnContext`.

### ISSUE THREAD

**Issue by wmorrison365fr** [vert-x3/issues#528]
### Questions

N/A

### Version
3.9.0

### Context
I encountered an exception which looks suspicious while ...

handling a request within the context of an `Executor` (which is also demonstrable running within `Vertx#runOnContext` within an `Executor`). In short, the client does not fully receive the response and it does not return.

The issue is demonstrated with an HTTP2 `curl` request. Superficially, when we execute `curl`, it will log that the headers and data are actually returned but the process overall does not return.

The reproducer server is very simple
1. It accepts the request and returns a response. In preparing the response, we explicitly call `response#trailers()` (even though we have no trailers to return) as this seems to be core to the problem arising.
1. I've provided three example `#handleResponse...` implementations:
   1. Basic `#handleResponse` - which works fine and returns the response immediately.
   1. `#handleResponseViaExecutor` - handles the response in the same way but is executed via an `Executor`.
   1. `#handleResponseViaExecutorRunOnContext`- as (2) but runs the code with an `Executor` and `runOnContext`. This is closest to how we'd expect to use it in our product.

1. With the call to `response#trailers()` commented, all of the versions of the `#handleResponse...` methods return successfully.
1. With the call to `response#trailers()` in place, we see the following:
   1. the call to `#handleResponse` succeeds
   1. with any of the other `#handleResponse...` methods uncommented, the client does not return
      1. `#handleResponseViaExecutor` does not return on first call. For some reason, if that's ^C'd, then subsequent calls work! (Though I've not yet checked to see what trailers we might get).
      1. `#handleResponseViaExecutorRunOnContext` does not return on any call

When the response is not completed, the `curl` client reveals that the headers and data are received ok but does not return. From the logs, it's not clear why that is but further investigation reveals that the problem is on trying to write the trailers. Here's some sample `curl --trace -` output:

```
17:20:38 69 $ curl --trace - --http2-prior-knowledge http://localhost:9090/test
== Info:   Trying 127.0.0.1...
== Info: TCP_NODELAY set
== Info: Connected to localhost (127.0.0.1) port 9090 (#0)
== Info: Using HTTP2, server supports multi-use
== Info: Connection state changed (HTTP/2 confirmed)
== Info: Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
== Info: Using Stream ID: 1 (easy handle 0x7fdd89009200)
=> Send header, 80 bytes (0x50)
0000: 47 45 54 20 2f 74 65 73 74 20 48 54 54 50 2f 32 GET /test HTTP/2
0010: 0d 0a 48 6f 73 74 3a 20 6c 6f 63 61 6c 68 6f 73 ..Host: localhos
0020: 74 3a 39 30 39 30 0d 0a 55 73 65 72 2d 41 67 65 t:9090..User-Age
0030: 6e 74 3a 20 63 75 72 6c 2f 37 2e 36 34 2e 31 0d nt: curl/7.64.1.
0040: 0a 41 63 63 65 70 74 3a 20 2a 2f 2a 0d 0a 0d 0a .Accept: */*....
== Info: Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
<= Recv header, 13 bytes (0xd)
0000: 48 54 54 50 2f 32 20 32 30 30 20 0d 0a          HTTP/2 200 ..
<= Recv header, 33 bytes (0x21)
0000: 78 2d 63 6f 6e 74 65 6e 74 2d 74 79 70 65 2d 6f x-content-type-o
0010: 70 74 69 6f 6e 73 3a 20 6e 6f 73 6e 69 66 66 0d ptions: nosniff.
0020: 0a                                              .
<= Recv header, 47 bytes (0x2f)
0000: 63 6f 6e 74 65 6e 74 2d 74 79 70 65 3a 20 61 70 content-type: ap
0010: 70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 3b 20 plication/json;
0020: 63 68 61 72 73 65 74 3d 55 54 46 2d 38 0d 0a    charset=UTF-8..
<= Recv header, 25 bytes (0x19)
0000: 63 61 63 68 65 2d 63 6f 6e 74 72 6f 6c 3a 20 6e cache-control: n
0010: 6f 2d 63 61 63 68 65 0d 0a                      o-cache..
<= Recv header, 2 bytes (0x2)
0000: 0d 0a                                           ..
<= Recv data, 14 bytes (0xe)
0000: 7b 22 72 65 73 75 6c 74 22 3a 20 2d 31 7d       {"result": -1}

^C
17:21:02 70 $
```

#### More specific findings:
Flushing the stream:
1. As indicated, this problem is only present if we make a call to `response#trailers()`, which has the side effect of creating a default object if the `trailers` field is null.
1. Doing so causes the `Http2ServerResponseImpl#write` method (as called from the `Http2ServerResponseImpl#end` methods) to try to write the trailers.
1. Of note here, when this method writes the response headers, it does so via a call to `#checkSendHeaders` which performs a `ctx.flush()` before delegating (ultimately) to `#writeHeaders`.
1. When it then writes the data `stream.writeData`, it also flushes `ChannelContext` (at the layer of `VertxHttp2ConnectionHandler._writeData`).
1. However, when the trailers are written - directly with `stream#writeHeaders()` (line 502) - similar to when the headers are written - the `ChannelContext` is not flushed. Inserting a breakpoint after this line and calling `ctx.flush()` does remedy the situation. Unfortunately this is not a practical solution as there's no clear way to force the flush as a client of a `Http2ServerResponse`.

Where does it actually hang?
1. Also notable, the location where the code seems to hang is as below.
   1. `DefaultHttp2ConnectionEncoder` writes the headers, passing the `promise` which is exchanged for a `ChannelFuture` (where the promise is then composed in a `SimpleChannelPromiseAggregator` with two new dependent promises handling writing the data [added in `DefaultHttp2FrameWriter` lines 525 and 528]). These two promises never seem to complete:
`        return promiseAggregator.doneAllocatingPromises();`
   1. This is located here (`DefaultHttp2ConnectionEncoder`:233):
```
                ChannelFuture future = sendHeaders(frameWriter, ctx, streamId, headers, hasPriority, streamDependency,
                        weight, exclusive, padding, endOfStream, promise);
```
   1. The code gets a bit confusing here but it looks like there is not listener registered on that `future`. I'm not sure if the flush completes these promises.

### Do you have a reproducer?
Sample server [Http2ApiServer.java.zip](https://github.com/vert-x3/issues/files/4629783/Http2ApiServer.java.zip).

I've supplied a sample class for now but will endeavour to upload the mini-project on github. `Http2ApiServer` is a plain `AbstractVerticle` that when run just sits on port 9090 and requests to `/test` will demonstrate the problem.

As indicated above, a request to the above server should leave `curl` hanging waiting for the response to complete. The `curl` request is:
```
$ curl --trace - --http2-prior-knowledge http://localhost:9090/test
```

### Steps to reproduce

1. Launch `HttpApiServer` - starts on port 9090 and has endpoint `/test`
   1. Note that `#handleResponseViaExecutor` is uncommented by default
2. Access with `curl`: 
```
$ curl --trace - --http2-prior-knowledge http://localhost:9090/test
```
3. Note the`curl` request receives the headers and JSON response data - `"{"result": -1}"` but does not return.
4. Replace `#handleResponseViaExecutor`  with the other `#handleResponse...` methods:
   1. `#handleResponse` works ok
   1. `#handleResponseViaExecutorRunOnContext` also does not complete (`curl` does not return)

### Extra

* MacOS 10.15.4
* JVM:
```
16:38:56 1 $ java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

Any help welcome or suggestions on an alternative means of doing this. 
[Http2ApiServer.java.zip](https://github.com/vert-x3/issues/files/4629783/Http2ApiServer.java.zip)

**Comment by vietj** [comment]
@wmorrison365fr this seems to be a flush issue

when the response is sent asynchronously then the stream will end the stream with an HEADER frame because of the trailers (even if it's empty) and writing a trailer frame async does not have a flush operation which will not flush the frame to the encoder and thus hang.

we will try fixing that soon.

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vert.x/issues/3414

**Comment by wmorrison365fr** [comment]
Thanks a lot for the feedback and explanation @vietj. Looking forward to 3.9.2 then.

**Comment by vietj** [comment]
that will actually be 3.9.1, the change was small enough to fit in this release
