### ISSUE TITLE
Improve the VerticleFactory#createVerticle blocking call

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#53]
Sometimes makes a warning for VerticleFactory that take some time (like MavenVerticleFactory or Ruby).

- we should wrap the createVerticle method with an executeBlocking call
- or uses an Handler<AsyncResult> pattern and the underlying factory can use executeBlocking if it wants

**Comment by purplefox** [comment]
I think we should introduce a method on VerticleFactory:

boolean isBlockingCreate()

This should return true if the createVerticle implementation blocks (is slow)

default should be false (e.g. for fast Java verticles)

If true then the deployment manager should run using executeblocking

**Comment by vietj** [comment]
yes.

**Comment by purplefox** [comment]
Ok, I'll take a look at this today :)

**Comment by cescoffier** [comment]
Isn't this one fixed (so should be 3.1.0, and not 3.2.0) ? I've seen related code in the JRubyVerticleFactory and in the core.

**Comment by purplefox** [comment]
Yep, it's fixed :)
