### ISSUE TITLE
Vert.x 3.9.1 verticle deployment error due to io.vertx.core.impl.logging.LoggerFactory

### ISSUE THREAD

**Issue by khteh** [vert-x3/issues#533]
I am using Vert.x 3.9.1 and when I run `java --add-opens java.base/jdk.internal.misc=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true -jar target/restapi-1.0-fat.jar`, it fails to deploy the verticle with the following error:
```
08:55:25.634 [vert.x-eventloop-thread-0] ERROR com.restapi.vertx.Launcher - Failed to launch com.restapi.vertx.verticles.BookVerticle Future{cause=io/vertx/core/impl/logging/LoggerFactory}
```

**Comment by tsegismont** [comment]
Can you please share a small reproducer? Thank you

**Comment by khteh** [comment]
https://github.com/khteh/RestAPIDocker.Vertx

**Comment by tsegismont** [comment]
Can you please provide instructions to run the project?

Le mer. 1 juil. 2020 à 11:29, Teh Kok How <notifications@github.com> a
écrit :

**Comment by khteh** [comment]
It's in the first post: `java --add-opens java.base/jdk.internal.misc=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true -jar target/restapi-1.0-fat.jar`

**Comment by khteh** [comment]
Running `mvn test` bumps into the same exception:
```
java.lang.AssertionError: java.lang.NoClassDefFoundError: io/vertx/core/impl/logging/LoggerFactory
Caused by: java.lang.NoClassDefFoundError: io/vertx/core/impl/logging/LoggerFactory
Caused by: java.lang.ClassNotFoundException: io.vertx.core.impl.logging.LoggerFactory
```

**Comment by tsegismont** [comment]
You have set the `vertx-jdbc-client` version to `4.0.0-milestone5` in your POM, whereas the rest of the Vert.x modules (in particular `vertx-core`) are set version `3.9.1`.

These versions are incompatible. Change the vertx-jdbc-client version to `3.9.1` and the issue will go away.
