### ISSUE TITLE
Can not get request parameter 

### ISSUE THREAD

**Issue by vinhio** [vert-x3/issues#542]
I create a post/route with request path /login. But at server-side can not get  request parameter. Please see the image

![2020-08-08_19-58](https://user-images.githubusercontent.com/7539391/89711032-e4d7ad00-d9b1-11ea-9d89-bf2517c80817.png)

**Comment by tsegismont** [comment]
Can you share some code and shell commands so that we can try to spot the issue? Screenshots in general are useless.

**Comment by parit** [comment]
so this is for 3.7.1 I think it is same for future versions but you need to use
BodyHandler.create().setMergeFormAttributes(true) as a handler for your post requests first and then you can use request.params()

**Comment by pmlopes** [comment]
Yes, you're missing the `BodyHandler.create()`, the merge form attributes is `true` by default, so in this case it has no effect.
