### ISSUE TITLE
Jruby deployment options not setting for worker verticles

### ISSUE THREAD

**Issue by amiracam** [vert-x3/issues#543]
I have setup a simple verticle which I'm configuring as a standard verticle but from which I will use a blockingHandler which is supposed to use a worker thread pool instead of the event loop. It actually does indeed use a thread pool , however I can't seem to change its default pool size.

This is the setup:

options = {'workerPoolName' => 'DEFAULT', 'workerPoolSize'=> 5}

$vertx.deploy_verticle "service.rb", options  

said verticle instantiates a http server 

I have setup a debug statement on the blockingHandler equipped route,  where I print out the name of the current thread.

When I execute said route, it clearly goes beyond the 5 specified but it as well will definitely limit itself to 20 and start again round robin on thread 0.

I have tested this against 3.8.4 which is what my project currently uses but also went ahead and tested with 3.9.2

I've reviewed the documentation several times and I can't figure out what I'm missing , so I'm reporting it as a bug.

thanks

**Comment by tsegismont** [comment]
Can you please provide the snippets and commands to reproduce? Thank you

**Comment by amiracam** [comment]
hi, in coding up a simplistic version of the project that I could share , I realized what the issue is , I was inadvertently creating two instances of vertx, i.e. the verticle responsible for the http service was not being set with the worker options but rather the verticle doing the deployment of the http service verticle

**Comment by tsegismont** [comment]
Thanks for letting us know
