### ISSUE TITLE
RedisAPI.zadd fail to add the secondray score &member

### ISSUE THREAD

**Issue by yxder** [vert-x3/issues#548]
### Steps
redisAPI.zadd(Arrays.asList("anykey", "1598248800", "member1", "1598248700", "member2"), r->{})

result: only "1598248800", "member1" added to zset

**Comment by pmlopes** [comment]
The issue doesn't happen on 4.0.0

**Comment by pmlopes** [comment]
Please see the added test, the issue is not reproducible
