### ISSUE TITLE
MultiMap is overriding my entries

### ISSUE THREAD

**Issue by TatianaBuica** [vert-x3/issues#549]
The fact that the index is calculated like this (in `CaseInsensitiveHeaders`), it overrides my entries.
```
private static int index(int hash) {
        return hash % 17;
}
```

It is intended to not allow you to have more than 17 entries and override them?
If so, could you please let me know what can I use instead?

**Comment by vietj** [comment]
@TatianaBuica did you find a bug ? do you have a reproducer ?

**Comment by TatianaBuica** [comment]
When I am trying to make the following insert into a `MultiMap`, keys _doorsUser_ and _encryptionAlgorithm_ are always fighting for index 4.
```
MultiMap form = MultiMap.caseInsensitiveMultiMap();
form.add("doorsUser", "aa");
form.add("encryptionAlgorithm", "");
```

The fact that the index is calculated as I mentioned above, it is a bit confusing and I am not sure if this is a bug.

**Comment by vietj** [comment]
is there a bug ? i.e is data overwritten when you use the `MultiMap` ?

it's expected to have collision inside the implementation, that's how hash tables work https://en.wikipedia.org/wiki/Hash_table#Collision_resolution

**Comment by vietj** [comment]
I ran the code you provided:

```java
  public static void main(String[] args) {
    MultiMap form = MultiMap.caseInsensitiveMultiMap();
    form.add("doorsUser", "aa");
    form.add("encryptionAlgorithm", "");
    for (Object o : form) {
      System.out.println("o = " + o);
    }
    System.out.println("doorsUser=" + form.get("doorsUser"));
    System.out.println("encryptionAlgorithm=" + form.get("encryptionAlgorithm"));
  }
```

and I got

```
o = doorsUser=aa
o = encryptionAlgorithm=
doorsUser=aa
encryptionAlgorithm=
```
