### ISSUE TITLE
 Failed to send eventbus message.

### ISSUE THREAD

**Issue by frank9527889** [vert-x3/issues#556]
### Questions
 Failed to send eventbus message.

### Version
all

### Context
  Connecting to server ef468d8c-fbd8-44cb-9b5d-01d692e02f69 failed io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.16.0.173:34003

 When the connection fails, the nodeinfo information is not cleared, resulting in obtaining the unavailable node information. Failed to send an eventbus message

**Comment by tsegismont** [comment]
Please reopen this bug in the repository corresponding to the cluster that you use. Would be helpful if you could add some snippets/reproduction instructions. Thank you
