### ISSUE TITLE
Release simplification

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#561]
Release process simplification for Vert.x 4 line (https://github.com/vert-x3/wiki/wiki/Release-Process)

- custom [home-brew third party repository](https://docs.brew.sh/Taps)
- https://github.com/vert-x3/vertx-bus-bower decouple from stack release (using a different version based on the protocol instead of the version implementing the protocol) that is deployed to NPM and WebJars
- un-necessary Bintray usage, the same artifacts are deployed in Maven Central

**Comment by jponge** [comment]
LGTM

**Comment by pmlopes** [comment]
Bower has deprecated itself more than 3 years ago:

https://bower.io/blog/2017/how-to-migrate-away-from-bower/

Maybe it's time we also stop releasing it with 4.0.0

With the current tools, npm, yarn, webpack, parcel, etc... https://github.com/vert-x3/vertx-stack/tree/master/stack-npm/src/main/npm/client is enough. Same for webjars. Webjars can refer to npm packages if needed.

So I'm proposing to drop it with a note on the release notes/docs.

**Comment by pmlopes** [comment]
For the npm part we can also stop the min and full distributions. They are broken for Windows users due to the way npm handles scripts.

**Comment by vietj** [comment]
@pmlopes what is the use case distributing vertx with NPM ? is it related to vertx-lang-js ?

**Comment by vietj** [comment]
or perhaps it's the only way to get a vertx distribution on windows ?

**Comment by pmlopes** [comment]
No, it was yet another option to distribute the "distribution" just like home brew.
