### ISSUE TITLE
Vert.x 4 GH actions CI

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#563]
- [x] workflow template that can be reused within the organizations
  - [x] vert-x3
  - [x] eclipse-vert
  - [x] custom SVG icon
- [ ] build requiring customizations
   - [x] vertx-core
      - [x] CI deployed
      - [x] Windows test
   - [x] vertx-sql-client
   - [x] vertx-hazelcast
   - [x] vertx-grpc
   - [x] vertx-web
   - [x] vertx-zookeeper
   - [x] vertx-auth
   - [x] vertx-redis-client
   - [x] vertx-stack
   - [x] vertx-eventbus-bridge-clients
   - [ ] vertx-lang-scala
   - ...
- [x] vanilla builds
   - [x] vertx-codegen
   - [x] vertx-json-schema
   - [x] vertx-tracing
   - [x] vertx-unit
   - [x] vertx-junit5
   - [x] vertx-proton
   - [x] vertx-mongo-client
   - [x] vertx-stomp
   - [x] vertx-service-proxy
   - [x] vertx-dropwizard-metrics
   - [x] vertx-cassandra-client
   - [x] vertx-health-check
   - [x] vertx-rx
   - [x] vertx-consul-client
   - [x] vertx-bridge-common
   - [x] vertx-tcp-eventbus-bridge
   - [x] vertx-amqp-client
   - [x] vertx-camel-bridge
   - [x] vertx-config
   - [x] vertx-kafka-client
   - [x] vertx-rabbitmq-client
   - [x] vertx-mail-client
   - [x] vertx-jdbc-client
   - [x] vertx-mqtt
   - [x] vertx-service-discovery
   - [x] vertx-sockjs-service-proxy
   - [x] vertx-http-service-factory
   - [x] vertx-maven-service-factory
   - [x] vertx-service-factory
   - [x] vertx-circuit-breaker
   - [x] vertx-sync
   - [x] vertx-shell
   - [x] vertx-micrometer-metrics
   - [x] vertx-reactive-streams
   - [x] vertx-lang-kotlin
   - [x] vertx-lang-groovy
   - [x] vertx-codetrans
   - [x] vertx-infinispan
   - [x] vertx-ignite
   - ...
- [x] cleanup files (`.travis.yml` and `.travis.deploy.artifacts.sh`)
- [x] add badge to README
- [x] dashboard
- [x] don't cache `io/vertx` dir in Maven repo

## Differences with Travis CI

- each repository has a cron execution of the repository CI action at 4am UTC (previously only vertx-core)
- the entire CI job is executed for PR, previously only the JDK 8 build. This might create contention so it might be changed if it impacts the project development
- builds can run on Windows / MacOS

## Dashboard

Project | Status
------- | ------
[vertx-codegen](https://github.com/vert-x3/vertx-codegen) | [![vertx-codegen](https://github.com/vert-x3/vertx-codegen/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-codegen/actions)
[vertx-core](https://github.com/eclipse-vertx/vert.x) | [![vertx-core](https://github.com/eclipse-vertx/vert.x/workflows/CI/badge.svg?branch=master)](https://github.com/eclipse-vertx/vert.x/actions)
[vertx-sql-client](https://github.com/eclipse-vertx/vertx-sql-client) | [![vertx-sql-client](https://github.com/eclipse-vertx/vertx-sql-client/workflows/CI/badge.svg?branch=master)](https://github.com/eclipse-vertx/vertx-sql-client/actions)
[vertx-json-schema](https://github.com/eclipse-vertx/vertx-json-schema) | [![vertx-json-schema](https://github.com/eclipse-vertx/vertx-json-schema/workflows/CI/badge.svg?branch=master)](https://github.com/eclipse-vertx/vertx-json-schema/actions)
[vertx-tracing](https://github.com/eclipse-vertx/vertx-tracing) | [![vertx-tracing](https://github.com/eclipse-vertx/vertx-tracing/workflows/CI/badge.svg?branch=master)](https://github.com/eclipse-vertx/vertx-tracing/actions)
[vertx-junit5](https://github.com/vert-x3/vertx-junit5) | [![vertx-junit5](https://github.com/vert-x3/vertx-junit5/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-junit5/actions)
[vertx-unit](https://github.com/vert-x3/vertx-unit) | [![vertx-unit](https://github.com/vert-x3/vertx-unit/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-unit/actions)
[vertx-web](https://github.com/vert-x3/vertx-web) | [![vertx-web](https://github.com/vert-x3/vertx-web/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-web/actions)
[vertx-hazelcast](https://github.com/vert-x3/vertx-hazelcast) | [![vertx-hazelcast](https://github.com/vert-x3/vertx-hazelcast/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-hazelcast/actions)
[vertx-grpc](https://github.com/vert-x3/vertx-grpc) | [![vertx-grpc](https://github.com/vert-x3/vertx-grpc/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-grpc/actions)
[vertx-proton](https://github.com/vert-x3/vertx-proton) | [![vertx-proton](https://github.com/vert-x3/vertx-proton/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-proton/actions)
[vertx-mongo-client](https://github.com/vert-x3/vertx-mongo-client) | [![vertx-mongo-client](https://github.com/vert-x3/vertx-mongo-client/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-mongo-client/actions)
[vertx-stomp](https://github.com/vert-x3/vertx-stomp) | [![vertx-stomp](https://github.com/vert-x3/vertx-stomp/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-stomp/actions)
[vertx-service-proxy](https://github.com/vert-x3/vertx-service-proxy) | [![vertx-service-proxy](https://github.com/vert-x3/vertx-service-proxy/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-service-proxy/actions)
[vertx-dropwizard-metrics](https://github.com/vert-x3/vertx-dropwizard-metrics) | [![vertx-dropwizard-metrics](https://github.com/vert-x3/vertx-dropwizard-metrics/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-service-proxy/actions)
[vertx-cassandra-client](https://github.com/vert-x3/vertx-cassandra-client) | [![vertx-cassandra-client](https://github.com/vert-x3/vertx-cassandra-client/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-cassandra-client/actions)
[vertx-health-check](https://github.com/vert-x3/vertx-health-check) | [![vertx-health-check](https://github.com/vert-x3/vertx-health-check/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-cassandra-client/actions)
[vertx-rx](https://github.com/vert-x3/vertx-rx) | [![vertx-rx](https://github.com/vert-x3/vertx-rx/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-rx/actions)
[vertx-consul-client](https://github.com/vert-x3/vertx-consul-client) | [![vertx-consul-client](https://github.com/vert-x3/vertx-consul-client/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-consul-client/actions)
[vertx-bridge-common](https://github.com/vert-x3/vertx-bridge-common) | [![vertx-bridge-common](https://github.com/vert-x3/vertx-bridge-common/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-bridge-common/actions)
[vertx-tcp-eventbus-bridge](https://github.com/vert-x3/vertx-tcp-eventbus-bridge) | [![vertx-eventbus-bridge](https://github.com/vert-x3/vertx-tcp-eventbus-bridge/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-eventbus-bridge/actions)
[vertx-amqp-client](https://github.com/vert-x3/vertx-amqp-client) | [![vertx-amqp-client](https://github.com/vert-x3/vertx-amqp-client/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-amqp-client/actions)
[vertx-camel-bridge](https://github.com/vert-x3/vertx-camel-bridge) | [![vertx-camel-bridge](https://github.com/vert-x3/vertx-camel-bridge/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-camel-bridge/actions)
[vertx-config](https://github.com/vert-x3/vertx-config) | [![vertx-config](https://github.com/vert-x3/vertx-config/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-config/actions)
[vertx-kafka-client](https://github.com/vert-x3/vertx-kafka-client) | [![vertx-kafka-client](https://github.com/vert-x3/vertx-kafka-client/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-kafka-client/actions)
[vertx-rabbitmq-client](https://github.com/vert-x3/vertx-rabbitmq-client) | [![vertx-rabbitmq-client](https://github.com/vert-x3/vertx-rabbitmq-client/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-rabbitmq-client/actions)
[vertx-mail-client](https://github.com/vert-x3/vertx-mail-client) | [![vertx-mail-client](https://github.com/vert-x3/vertx-mail-client/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-mail-client/actions)
[vertx-jdbc-client](https://github.com/vert-x3/vertx-jdbc-client) | [![vertx-jdbc-client](https://github.com/vert-x3/vertx-jdbc-client/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-jdbc-client/actions)
[vertx-mqtt](https://github.com/vert-x3/vertx-mqtt) | [![vertx-mqtt](https://github.com/vert-x3/vertx-mqtt/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-mqtt/actions)
[vertx-service-discovery](https://github.com/vert-x3/vertx-service-discovery) | [![vertx-service-discovery](https://github.com/vert-x3/vertx-service-discovery/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-service-proxy/actions)
[vertx-sockjs-service-proxy](https://github.com/vert-x3/vertx-sockjs-service-proxy) | [![vertx-sockjs-service-proxy](https://github.com/vert-x3/vertx-sockjs-service-proxy/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-sockjs-service-proxy/actions)
[vertx-http-service-factory](https://github.com/vert-x3/vertx-http-service-factory) | [![vertx-http-service-factory](https://github.com/vert-x3/vertx-http-service-factory/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-http-service-factory/actions)
[vertx-maven-service-factory](https://github.com/vert-x3/vertx-maven-service-factory) | [![vertx-maven-service-factory](https://github.com/vert-x3/vertx-maven-service-factory/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-maven-service-factory/actions)
[vertx-service-factory](https://github.com/vert-x3/vertx-service-factory) | [![vertx-service-factory](https://github.com/vert-x3/vertx-service-factory/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-service-factory/actions)
[vertx-circuit-breaker](https://github.com/vert-x3/vertx-circuit-breaker) | [![vertx-circuit-breaker](https://github.com/vert-x3/vertx-circuit-breaker/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-circuit-breaker/actions)
[vertx-sync](https://github.com/vert-x3/vertx-sync) | [![vertx-sync](https://github.com/vert-x3/vertx-sync/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-sync/actions)
[vertx-shell](https://github.com/vert-x3/vertx-shell) | [![vertx-shell](https://github.com/vert-x3/vertx-shell/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-shell/actions)
[vertx-reactive-streams](https://github.com/vert-x3/vertx-reactive-streams) | [![vertx-reactive-streams](https://github.com/vert-x3/vertx-reactive-streams/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-reactive-streams/actions)
[vertx-micrometer-metrics](https://github.com/vert-x3/vertx-micrometer-metrics) | [![vertx-micrometer-metrics](https://github.com/vert-x3/vertx-micrometer-metrics/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-micrometer-metrics/actions)
[vertx-lang-kotlin](https://github.com/vert-x3/vertx-lang-kotlin) | [![vertx-lang-kotlin](https://github.com/vert-x3/vertx-lang-kotlin/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-lang-kotlin/actions)
[vertx-lang-groovy](https://github.com/vert-x3/vertx-lang-groovy) | [![vertx-lang-groovy](https://github.com/vert-x3/vertx-lang-groovy/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-lang-groovy/actions)
[vertx-codetrans](https://github.com/vert-x3/vertx-codetrans) | [![vertx-codetrans](https://github.com/vert-x3/vertx-codetrans/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-codetrans/actions)
[vertx-auth](https://github.com/vert-x3/vertx-auth) | [![vertx-auth](https://github.com/vert-x3/vertx-auth/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-auth/actions)
[vertx-infinispan](https://github.com/vert-x3/vertx-infinispan) | [![vertx-infinispan](https://github.com/vert-x3/vertx-infinispan/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-infinispan/actions)
[vertx-ignite](https://github.com/vert-x3/vertx-ignite) | [![vertx-ignite](https://github.com/vert-x3/vertx-ignite/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-ignite/actions)
[vertx-redis-client](https://github.com/vert-x3/vertx-redis-client) | [![vertx-redis-client](https://github.com/vert-x3/vertx-redis-client/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-redis-client/actions)
[vertx-zookeeper](https://github.com/vert-x3/vertx-zookeeper) | [![vertx-stack](https://github.com/vert-x3/vertx-zookeeper/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-zookeeper/actions)
[vertx-stack](https://github.com/vert-x3/vertx-stack) | [![vertx-stack](https://github.com/vert-x3/vertx-stack/workflows/CI/badge.svg?branch=master)](https://github.com/vert-x3/vertx-stack/actions)

**Comment by tsegismont** [comment]
On GH Actions, I've noticed we cache the whole repository. On Travis we used to exclude what's in `{repo}/io/vertx`

This might be the reason we had a failure on GraphQL Apollo tests last week after updating `BodyHandler` in `vertx-web`

Perhaps we should do this:

```
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/io/vertx
```
