### ISSUE TITLE
Vert.x 4 RC1 HttpContext null clientRequest bug

### ISSUE THREAD

**Issue by elfogre** [vert-x3/issues#564]
Hello!

I'm upgrading a working project from vert.x3 to vert.x4 to use your new tracing capabilities and I found a bug in web client.

We have a handler to store cache responses during DISPATCH_RESPONSE Phase. We get some info from HttpContext.clientRequest in vert.x3 without problem, but now in vert.x4 our HttpContext.clientResponse is null in DISPATCH_RESPONSE. Doc says it should be non null: only available during ClientPhase#SEND_REQUEST **and after**

![context](https://user-images.githubusercontent.com/13524391/99678278-ee75b400-2a7a-11eb-9c29-593bfc38f0e6.png)

Is there a condition that could set this object as null?

**Comment by elfogre** [comment]
Also in SEND_REQUEST phase is null.

**Comment by vietj** [comment]
could you provide a reproducer project ?

**Comment by vietj** [comment]
please provide a reproducer

**Comment by vietj** [comment]
no reproducer provided
