### ISSUE TITLE
Reactive MySQL Client ,column type json ,use the rowset to tabke column vvalue is mistaken code 

### ISSUE THREAD

**Issue by dangerLT** [vert-x3/issues#565]
### Questions
Reactive MySQL Client ,column type json ,  when the column value contains chinese , use the rowset to tabke column vvalue is mistaken code 
row.getString()'value is 
my db charset is utf-8  mysqlPool'option charset is utf-8 too.
### Version
mysql version is 8.0.22 
vertx'dependencies is 3.94
os = windows10
jdk  is  graalvm-ce-java11-windows-amd64-20.3.0

**Comment by BillyYccc** [comment]
I think it has been fixed in https://github.com/eclipse-vertx/vertx-sql-client/issues/790 recently, can you try `3.9.5-SNAPSHOT` to see if it works for you?

**Comment by dangerLT** [comment]
I  try 4.0 milestone 5 , the column value contains the chinese word , the client'result still is mistaken code

**Comment by BillyYccc** [comment]
The changes are not included in the milestone5 release, you can try 4.0.0.CR2 instead.

**Comment by dangerLT** [comment]
yes be fixed in 4.0.0 CR2 , THANKS!!!!
