### ISSUE TITLE
Improve Infinispan clustering docs by adding details around requirements for firewalls, mDNS, etc...

### ISSUE THREAD

**Issue by InfoSec812** [vert-x3/issues#569]
#### Describe the feature

Per discussions with @tsegismont -

This is a documentation improvement based on experiences I have had with Vert.x users and clients. Many get frustrated that examples of Infinispan clustering do not work on their computers when running MacOS or Windows. This is often caused by the built-in or company mandated firewalls and security software.

#### Use cases

- When a developer is programming on Windows and Windows Defender is preventing local discovery
- When a developer is programming on a Mac and the built-in firewall is blocking local discovery
- When a developer is programming on any OS where a 3rd-party firewall has been installed and mDNS discovery is not working

#### Contribution

I will be working on a submission to add more details about the required networking in order to support mDNS local discovery. In all cases, I will attempt to keep specific details out of the Vert.x docs and just link to external references for things like Windows Defender and MacOS Firewall.

**Comment by tsegismont** [comment]
There's already some info in the doc https://github.com/vert-x3/vertx-infinispan/blob/121d7069a842a7ac524924bf4b74025457b2dad6/vertx-infinispan/src/main/asciidoc/index.adoc#multicast-not-enabled-on-the-machine
