### ISSUE TITLE
Cluster wide async maps not so useful for intended "things like storing session state"

### ISSUE THREAD

**Issue by apatrida** [vert-x3/issues#57]
The docs for vert-x core state that cluster-wide async maps:

"This makes them really useful for things like storing session state "

But really, if you cannot expire objects from these caches at the same time a session expires, they will continue to build up items in the maps.  There is no `TTL` for cleaning up values.

And if you wanted session state, you would just put it in the clustered session manager.  

So then putting much into these maps is dangerous because there is no eviction policy.  You cannot list all items to write your own TTL / eviction handling.  You can only put/remove if you know the item exists.

Add `TTL` or other eviction policies like Guava caches have, then this seems useful.  Until then, is a big memory leaker.

**Comment by apatrida** [comment]
Is the expected use of these maps that you would go and add Hazelcast configuration parameters to the map by name, setting the eviction policy there?  If so,  are the map name mangled in any way, or if I ask for async map "Franky" do I get "Franky" or "vertxFranky1234"?

**Comment by apatrida** [comment]
Ok, looks like no name mangling.  So configure map evection inside hazelcast config used by vertx when loading `HazelCastClusterManager` and let that do its job.

**Comment by purplefox** [comment]
Hi Jayson,

You can set ttl for an entry (that's the timeout parameter on put). The javadoc is currently wrong for that param and should be corrected.

BTW, clustered sessions in vertx-web use this functionality to make sessions available across the cluster.

**Comment by apatrida** [comment]
Ah great, I saw `timeout` and cried when it wasn't `TTL` but now I am happy to find out it is indeed `TTL`
