### ISSUE TITLE
Add asBoolean() to AsyncResult make use in Groovy more consise

### ISSUE THREAD

**Issue by injecteer** [vert-x3/issues#576]
Now to check the AsyncResult instances for success the following code is used:

```
if( asyncRes.succeeded() ){
  println asyncRes.result()
}else{
  log.error 'Error!', asyncRes.cause()
}
```
I would be good to add a default method to AsyncResult interface to mirror succeeded():

```
default boolean asBoolean() {
  return succeeded();
} 
```
according to [Groovy Truth](https://groovy-lang.org/semantics.html#Groovy-Truth) to make Groovy code look simpler to read:

```
if( asyncRes ){
  println asyncRes.result()
}else{
  log.error 'Error!', asyncRes.cause()
}
```

**Comment by vietj** [comment]
can that be done with an extension method in groovy ?

**Comment by injecteer** [comment]
You mean with global AST transformation? Yes, sure 

The amount of code is going to be relatively big comparing to default interface method though

**Comment by vietj** [comment]
I think the best would be to cnotribute this as an extension method  in
vertx-lang-groovy in Vert.x 4

we already have extension methods there for Groovy:

https://github.com/vert-x3/vertx-lang-groovy/blob/master/src/main/java/io/vertx/lang/groovy/VertxExtensionModule.java

**Comment by injecteer** [comment]
https://gist.github.com/injecteer/945af9faf519f65a4801a13f2cad2d93

**Comment by injecteer** [comment]
I tried shortly the method in Gist and it works like a charm

**Comment by vietj** [comment]
Do you mind doing a PR ?

**Comment by injecteer** [comment]
Have a look please.
