### ISSUE TITLE
Support unstable APIs in stable packages

### ISSUE THREAD

**Issue by slinkydeveloper** [vert-x3/issues#579]
#### Describe the feature

Define a way to support in Vert.x unstable APIs.

#### Use cases

Plenty of times, while developing new Vert.x APIs in stable packages, I've found myself requiring to create some api as unstable, in order to let the community try it and gather feedback.

I propose to add an annotation like `@Unstable`, just for documentation purpose, to tag the new APIs that still needs some refinements and might break anytime in the next releases.

An unstable API should both be annotated with the unstable annotation, and should both contain the warning in the javadoc:

```
/**
 * WARNING: this method is unstable and might break anytime, use with caution
**/
@Unstable
void myUnstableApi()
```

**Comment by vietj** [comment]
I do support this, in addition we should have an optional message in the API to give more context.

The API should handle also other level like package or class/interface

**Comment by pmlopes** [comment]
Yes I'd prefer to see:

```java
@Unstable("this method is unstable and might break anytime, use with caution")
void myUnstableApi()
```

Plus codegen should be able to extract this information to the `MethodInfo` type so extensions could use this information too.

**Comment by vietj** [comment]
right.

"this method is unstable and might break anytime, use with caution"


could be the default message :-)

**Comment by tsegismont** [comment]
We discussed this with @vietj today. We agreed to do something simple: adding the `@interface` annotated with `@Documented` so that the information is conveyed to the Vert.x API docs.
