### ISSUE TITLE
Documentation for Reactive programming

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/issues#580]
In various docs we have a section for Reactive programming with RxJava 2.

For example:

- https://vertx.io/docs/vertx-cassandra-client/java/#_rxjava_2_api
- https://vertx.io/docs/vertx-pg-client/java/#_rxjava_2_api

Given RxJava 2 is no longer maintained, I think we should update those to RxJava 3.

In most cases it consists in changing titles/wording, not examples themselves.

- [x] vertx-rx https://github.com/vert-x3/vertx-rx/pull/264
- [x] vertx-cassandra-client https://github.com/vert-x3/vertx-cassandra-client/pull/73
- [x] vertx-kafka-client https://github.com/vert-x3/vertx-kafka-client/pull/204
- [x] vertx-mongo-client https://github.com/vert-x3/vertx-mongo-client/pull/258
- [x] vertx-pg-client, vertx-sql-common https://github.com/eclipse-vertx/vertx-sql-client/pull/973
- [x] vertx-web-api-contract, vertx-web-client, vertx-web-graphql https://github.com/vert-x3/vertx-web/pull/1967
- [x] vertx-junit5 https://github.com/vert-x3/vertx-junit5/pull/105
- [x] vertx-lang-kotlin-coroutines https://github.com/vert-x3/vertx-lang-kotlin/pull/201
- [x] vertx-service-discovery https://github.com/vert-x3/vertx-service-discovery/pull/150

**Comment by tsegismont** [comment]
@vietj I built `vertx-stack/stack-docs` and checked the changes. Tell me if you want to review the PRs or if I shall go ahead and merge.

**Comment by vietj** [comment]
LGTM
