### ISSUE TITLE
Support custom deserialization in OpenAPI support

### ISSUE THREAD

**Issue by rhino-harley** [vert-x3/issues#586]
Currently the OpenAPI support provided by vert.x converts an OpenAPI JSON payload into a JsonObject. When an application then wants to map this to some POJOs for internal representation, then they must call json.mapTo(POJO.class). This is inefficient, as the object must be mapped once from JSON to JsonObject and then once from JsonObject to POJO. It would be nice if API supported body.getObject(Class) and did this directly.

**Comment by InfoSec812** [comment]
@rhino-harley I'm pretty sure there would be no gain in efficiency as the underlying operations would remain the same. Jackon's ObjectMapper would still be doing the same steps/operations. Unless @pmlopes or @vietj or @jponge or @tsegismont have a different perspective, I believe that `ctx.getBody().mapTo(POJO.class)` makes the most sense.

**Comment by rhino-harley** [comment]
@InfoSec812 Using plain old jackson, if I register a custom deserializer, I can interpret the JsonToken tree directly without have to create either JsonNode or JsonObject objects. Using your suggestion we would be first parsing into a JsonObject tree and then having to map it separately which is less efficient. I was thinking something more like `ctx.getBody(POJO.class)`. Thoughts?

**Comment by InfoSec812** [comment]
OK, I tried to implement what it is you are asking for and it would require adding a hard dependency on some new libraries to `vertx-web`. Specifically, we would need to add Jackson Databind. Something you might consider trying instead might be:

```java
MyPojo decoded = JacksonFactory.INSTANCE.codec().fromBuffer(ctx.getBody(), MyPojo.class);
```

That will bypass the intermediate Json/JsonObject/JsonArray objects.

**Comment by InfoSec812** [comment]
I tried implementing this and writing some tests around it, but I am getting a strange error from the traditional method:

When I call:

```java
ctx.getBodyAsJson().mapTo(TestPojoA.class)
```

I get a `DecodeException` with the message:

```
io.vertx.core.json.DecodeException: Mapping io.vertx.ext.web.impl.RoutingContextImplTest$TestPojoA  is not available without Jackson Databind on the classpath
```

Branch can be found here: https://github.com/InfoSec812/vertx-web/tree/Issue-586-_-Custom_body_deserialization_from_Buffer

**Comment by InfoSec812** [comment]
OK, that branch and the associated unit tests work now. That said, based on discussions on Discord the dependency on jackson-databind was explicitly removed from `vertx-web` and is not likely to be added back for a feature which can be implemented by a developer in a single line. @rhino-harley I suggest you use the solution mentioned above which bypasses the intermediate Json object.

```java
JacksonFactory.INSTANCE.codec().fromBuffer(ctx.getBody(), MyPojo.class);
```

**Comment by InfoSec812** [comment]
I just finished some microbenchmarking as well. The results were pretty clear. The performance difference between `JacksonFactory.INSTANCE.codec().fromBuffer(ctx.getBody(), TestPojoA.class)` and `ctx.getBodyAsJson().mapTo(TestPojoA.class)` is pretty much negligible. Slight memory increase which is only noticeable on my machine after 10000 iterations.

**Comment by rhino-harley** [comment]
Thanks for trying this out so quickly. Interesting that there isn't much difference in there benchmark. How big were the messages that you benchmarked with? In my line of work (payments) we often have messages that are deeply nested with thousands of fields.

**Comment by InfoSec812** [comment]
I used a pretty simple object. The size of the JSON that you're using definitely could impact things. That said, the solution you can use to avoid the intermediate state is via `JacksonFactory` and it's a one-liner.

**Comment by InfoSec812** [comment]
@pmlopes or @tsegismont or @vietj - I believe you can safely close this issue
