### ISSUE TITLE
Expose underlying implementations

### ISSUE THREAD

**Issue by purplefox** [vert-x3/issues#6]
In a break from how we did things in Vert.x 2 I think we should expose a handle to the underlying implementation in various places in Vert.x e.g:

* The Netty Event Loop Group
* The Jackson ObjectMapper
* The Hazelcast instance
* Dropwizard metrics instance
*etc

**Comment by kuujo** [comment]
+1

It seems to have been a pretty common pattern in Vert.x 2 (no thanks to me for recommending this) for people to get the Hazelcast instance via Hazelcast.getAllHazelcastInstances().iterator().next() which is not ideal as it assumes there's only one Hazelcast instance.

**Comment by vietj** [comment]
+1 too, better having something we support than having ppl hacking stuff
