### ISSUE TITLE
PgConnectOptions.fromUri drops extra parameters passed in the URI

### ISSUE THREAD

**Issue by InfoSec812** [vert-x3/issues#602]
### Version

4.2.7

### Context

This was noticed when using the Reactive PostgreSQL client with a Quarkus application

### Do you have a reproducer?

We have shared a reproducer with @vietj interally at Red Hat and I have created a unit test which demonstrates the error and will post the link below in the comments

### Steps to reproduce

1. Use PgConnectOptions.fromUri with a URI which contains a non-standard option like `postgresql://dbserver:5432/dbname?nonstandardvertxoption=foo`
2. Dump the added properties from the created `PgConnectOptions`
3. Note that the non-standard property is not retained

### Extra

* Anything that can be relevant such as OS version, JVM version
OS: Linux
JVM: OpenJDK 11.0.15

**Comment by InfoSec812** [comment]
Unit test which succinctly demonstrates the error: https://github.com/InfoSec812/vertx-sql-client/blob/vertx-issue-602-pgconnectoptions-fromuri-extra-params/vertx-pg-client/src/test/java/io/vertx/pgclient/PgConnectOptionsTest.java#L192

**Comment by Sanne** [comment]
@vietj see also : https://github.com/quarkusio/quarkus/issues/25914#issuecomment-1144096024
HTH

**Comment by vietj** [comment]
fixed by https://github.com/eclipse-vertx/vertx-sql-client/issues/1197
