### ISSUE TITLE
Stack wide async result callback deprecation

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#612]
Deprecate callbacks of the Vert.x API.

This uses a slight [modification](https://github.com/eclipse-vertx/vertx-codegen/actions/runs/4321302640) of codegen to detect callback methods

* [x] [vertx-core](https://github.com/eclipse-vertx/vert.x/pull/4641/files)
* [x] [vertx-uri-template](https://github.com/eclipse-vertx/vertx-uri-template/pull/4)
* [x] [vertx-stomp](https://github.com/vert-x3/vertx-stomp/pull/80)
* [x] [vertx-tracing](https://github.com/eclipse-vertx/vertx-tracing/pull/54)
* [x] [vertx-shell](https://github.com/vert-x3/vertx-shell/pull/52)
* [x] [vertx-amqp-client](https://github.com/vert-x3/vertx-amqp-client/pull/82)
* [x] [vertx-json-schema](https://github.com/eclipse-vertx/vertx-json-schema/pull/92)
* [x] [vertx-redis-client](https://github.com/vert-x3/vertx-redis-client/pull/366)
* [x] [vertx-sql-client](https://github.com/eclipse-vertx/vertx-sql-client/pull/1282)
* [x] [vertx-auth](https://github.com/eclipse-vertx/vertx-auth/pull/622)
* [x] [vertx-mongo-client](https://github.com/vert-x3/vertx-mongo-client/pull/300)
* [x] [vertx-kafka-client](https://github.com/vert-x3/vertx-kafka-client/pull/231)
* [x] [vertx-micrometer-metrics](https://github.com/vert-x3/vertx-micrometer-metrics/pull/172)
* [x] [vertx-mail-client](https://github.com/vert-x3/vertx-mail-client/pull/205)
* [x] [vertx-mqtt](https://github.com/vert-x3/vertx-mqtt/pull/237)
* [x] [vertx-dropwizard-metrics](https://github.com/vert-x3/vertx-dropwizard-metrics/pull/111)
* [x] ~~vertx-reactive-streams~~ nothing to do, no vertxgen
* [x] [vertx-health-check](https://github.com/vert-x3/vertx-health-check/pull/53)
* [x] [vertx-circuit-breaker](https://github.com/vert-x3/vertx-circuit-breaker/pull/67)
* [x] [vertx-service-discovery](https://github.com/vert-x3/vertx-service-discovery/pull/166)
* [x] [vertx-hazelcast](https://github.com/vert-x3/vertx-hazelcast/pull/171)
* [x] [vertx-infinispan](https://github.com/vert-x3/vertx-infinispan/pull/120)
* [x] ~~vertx-zookeeper~~ nothing to do, no vertxgen
* [x] [vertx-cassandra-client](https://github.com/vert-x3/vertx-cassandra-client/pull/81)
* [x] [vertx-config](https://github.com/vert-x3/vertx-config/pull/158)
* [x] [vertx-web](https://github.com/vert-x3/vertx-web/pull/2381)
* [x] [vertx-camel-bridge](https://github.com/vert-x3/vertx-camel-bridge/commits/master)
* [x] [vertx-tcp-event-bus-bridge](https://github.com/vert-x3/vertx-tcp-eventbus-bridge/commit/e9361d9416796e03edb24d63785308abd2675238)
* [x] [vertx-bridge-common](https://github.com/vert-x3/vertx-bridge-common/commit/b81e346f982e45f544041d595d7e16040d6941c3)
* [x] [vertx-consul-client](https://github.com/vert-x3/vertx-consul-client/pull/92)
* [x] [vertx-rabbitmq-client](https://github.com/vert-x3/vertx-rabbitmq-client/commit/aee44b84eb328fb9d2c3e3fa796268ab71954c60)
* [x] [vertx-jdbc-client](https://github.com/vert-x3/vertx-jdbc-client/commits/master)
* [x] [vertx-ignite](https://github.com/vert-x3/vertx-ignite/commits/master)
* [x] [vertx-grpc](https://github.com/vert-x3/vertx-grpc/commit/e17cf5caff18ddeb89064774f3b9882631dbb429)
* [x] [vertx-service-proxy](https://github.com/vert-x3/vertx-service-proxy/commit/c826b5e7f81e4db2d321c2393ba91e2311b879a6)

Anyone can help and contribute with a PR, just leave a comment on this issue.

**Comment by bfreuden** [comment]
https://github.com/vert-x3/vertx-mongo-client/pull/300

**Comment by vietj** [comment]
I'm on Kafka Client

**Comment by vietj** [comment]
handling MQTT

**Comment by vietj** [comment]
handling vertx-web
