### ISSUE TITLE
Callback usage removal

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#616]
Remove the usage of deprecated callbacks

- docs and examples, it must be back-ported to 4.x
- implementation of vertx
- tests

* [x] [vertx-core](https://github.com/eclipse-vertx/vert.x/pull/4645)
* [x] vertx-web
* [x] [vertx-sql-client](https://github.com/eclipse-vertx/vertx-sql-client/pull/1286)
* [x] vertx-uri-template
* [x] [vertx-stomp](https://github.com/vert-x3/vertx-stomp/pull/83)
* [x] [vertx-tracing](https://github.com/eclipse-vertx/vertx-tracing/pull/58)
* [x] [vertx-shell](https://github.com/vert-x3/vertx-shell/pull/54)
* [x] [vertx-proton](https://github.com/vert-x3/vertx-proton)
* [x] [vertx-amqp-client](https://github.com/vert-x3/vertx-amqp-client/pull/83)
* [x] [vertx-json-schema](https://github.com/eclipse-vertx/vertx-json-schema/pull/99)
* [x] [vertx-redis-client](https://github.com/vert-x3/vertx-redis-client/pull/369)
* [x] vertx-auth
* [x] [vertx-mongo-client](https://github.com/vert-x3/vertx-mongo-client/pull/301)
* [x] [vertx-kafka-client](https://github.com/vert-x3/vertx-kafka-client/pull/232)
* [x] [vertx-micrometer-metrics](https://github.com/vert-x3/vertx-micrometer-metrics/pull/176)
* [x] [vertx-mail-client](https://github.com/vert-x3/vertx-mail-client/pull/207)
* [x] [vertx-mqtt](https://github.com/vert-x3/vertx-mqtt/pull/238)
* [x] [vertx-dropwizard-metrics](https://github.com/vert-x3/vertx-dropwizard-metrics/commit/6a69baa367edf8c86c6517e8c2e9000635896fc7)
* [x] vertx-reactive-streams
* [x] [vertx-health-check](https://github.com/vert-x3/vertx-health-check/pull/55)
* [x] [vertx-circuit-breaker](https://github.com/vert-x3/vertx-circuit-breaker/pull/69)
* [x] [vertx-service-discovery](https://github.com/vert-x3/vertx-service-discovery/pull/167)
* [x] [vertx-hazelcast](https://github.com/vert-x3/vertx-hazelcast/pull/172)
* [x] [vertx-infinispan](https://github.com/vert-x3/vertx-infinispan/pull/121)
* [x] [vertx-zookeeper](https://github.com/vert-x3/vertx-zookeeper/pull/137)
* [x] [vertx-cassandra-client](https://github.com/vert-x3/vertx-cassandra-client/pull/82)
* [x] [vertx-config](https://github.com/vert-x3/vertx-config/pull/160)
* [x] [vertx-camel-bridge](https://github.com/vert-x3/vertx-camel-bridge/pull/49)
* [x] [vertx-tcp-event-bus-bridge](https://github.com/vert-x3/vertx-tcp-eventbus-bridge/pull/74)
* [x] vertx-bridge-common
* [x] [vertx-consul-client](https://github.com/vert-x3/vertx-consul-client/pull/93)
* [x] [vertx-rabbitmq-client](https://github.com/vert-x3/vertx-rabbitmq-client/pull/187)
* [x] [vertx-jdbc-client](https://github.com/vert-x3/vertx-jdbc-client/pull/300)
* [x] [vertx-ignite](https://github.com/vert-x3/vertx-ignite/pull/132)
* [x] [eclipse-vertx/vertx-grpc](https://github.com/eclipse-vertx/vertx-grpc/commit/9d8353354388d113fdc3367bd9cb2b6637fe2bfd)
* [x] [vert-x3/vertx-grpc](https://github.com/vert-x3/vertx-grpc/commit/a43f4450e2896cdd5df209b5c8266ea0ae9dc900)
* [x] vertx-service-proxy

**Comment by tsegismont** [comment]
Please do not update the issue's description for a moment. I'm going to update the list using the list we've built in the callback deprecation issue.

**Comment by tsegismont** [comment]
Done

**Comment by vietj** [comment]
thanks @tsegismont , I'm on SQL client

**Comment by vietj** [comment]
there is a linked PR

**Comment by vietj** [comment]
I'll take care of both vertx-grpc
