### ISSUE TITLE
[https://vertx.io/doc] Wrong summary for Web API Service module

### ISSUE THREAD

**Issue by dprincethg** [vert-x3/issues#618]
From the "docs" page of the  [Vertx public website ](https://vertx.io/docs/), the summary of the **Web API Service** module is wrong:

`Directly connect your OpenAPI 3 web routers to event-bus services.`

This text is about another module "**Web Open API**" that, by the way, has been removed without notice :(

(replaced by a new "Vert.x OpenAPI Router" but in "Technical Preview" state)

**Comment by tsegismont** [comment]
@pmlopes @pk-work can you take care of this one? Thank you

**Comment by pk-work** [comment]
@tsegismont can you have a look and merge the PR in the website if it is okay?
