### ISSUE TITLE
vertx3-eventbus-client 3.1.0 and browserify

### ISSUE THREAD

**Issue by slackeast** [vert-x3/issues#63]
I need help and I don't know where else to post this question.   Maybe someone here could help quickly?  I'm tyring to set up vertx3-eventbus-client and browserify.  Here is my client code:

require('../../node_modules/vertx3-eventbus-client/vertx-eventbus');

$(function() {
    var eb = new EventBus('http://localhost:8080/eventbus');

    eb.onopen = function() {
    
      // set a handler to receive a message
      eb.registerHandler('some-address', function(message) {
        console.log('received a message: ' + JSON.stringify(message));
      });
    
      // send a message
      eb.send('createAccount', {name: 'tim', age: 587});
    
    }
    
});

The javascript console gives me this error:  Uncaught ReferenceError: EventBus is not defined

The above code works fine if I don't use browserify and use a standard script tag in the index.html.

**Comment by cescoffier** [comment]
Try with:
```
var EventBus = require('../../node_modules/vertx3-eventbus-client/vertx-eventbus');
```

**Comment by pmlopes** [comment]
```
require('../../node_modules/vertx3-eventbus-client/vertx-eventbus');
```

In the old code we were polluting the global namespace which is both a *bad practice* and a *bug* so you need to get the reference to the constructor from the require as @cescoffier just noted.
