### ISSUE TITLE
Remove pump from Javadocs and examples

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/issues#642]
Remove pump mentions from the Javadoc and vertx-examples (or replace with `pipeTo` when relevant).

- [x] https://github.com/vert-x3/vertx-examples/commit/b6194db5b5e7eac3173f8c968c9ecac8e4a567f9
- [x] https://github.com/eclipse-vertx/vert.x/pull/5027
- [x] https://github.com/eclipse-vertx/vert.x/pull/5028
- [x] [Remove pump usage in documentation](https://github.com/vert-x3/vertx-reactive-streams/commit/aac950f2f40db018da00cba3dcd034d45c06246c)
- [x] [Remove pump usage in documentation](https://github.com/vert-x3/vertx-rx/commit/03448ad5e1ba4a1c4cc73740bf3cf0eea2cf8115)
- [x] [Remove pump usage in documentation](https://github.com/vert-x3/vertx-reactive-streams/commit/81468fe8866453f80c74c10b0206a05b7ba54764)
- [x] [Remove pump usage in documentation](https://github.com/vert-x3/vertx-rx/commit/2d53465da1820e56ed36a0d77ae6cf791d40f87f)

**Comment by vietj** [comment]
https://github.com/vert-x3/vertx-examples/commit/b6194db5b5e7eac3173f8c968c9ecac8e4a567f9
