### ISSUE TITLE
Using HTTP verbs not defined on the Enum will cause request to stall and not close the connection

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/issues#71]
See: https://github.com/vert-x3/vertx-web/issues/225

We need to surround with try-catch and properly terminate the request in case of exception.

**Comment by pmlopes** [comment]
Fixing this will probably bring a API breaking change since the value for the method is not required to be on the enum. While the example uses the method DEBUG which is not specified and therefore "wrong".

However a use case that can make sense is a client connecting to a `webdav` server, where basically we should "speak" HTTP but using a whole different set of verbs such as:

* COPY
* DELETE
* MKCOL
* etc...

**Comment by cescoffier** [comment]
Also related to #255.

**Comment by cescoffier** [comment]
We should keep the enum as it is but improve the checking if the method is not part of the valid values.

**Comment by cescoffier** [comment]
Fixed in https://bugs.eclipse.org/bugs/show_bug.cgi?id=482207.
