### ISSUE TITLE
.vertx/file-cache* files not being removed when echo is run as an embedded Java example

### ISSUE THREAD

**Issue by cxbrooks** [vert-x3/issues#72]
If I compile and run the echo Client/Server example, then the .vertx/file-cache* files are not removed.

To replicate:
1. Download the vert.x-3.1.0-full.tar.gz and uncompress it.
2. Download the vertx-examples git repo
3. Compile the example:
    cd src/vertx-examples/core-examples/src/main/java/
    javac -classpath '.:/Users/cxh/src/vert.x-3.1.0/lib/*' io/vertx/example/core/net/echo/*.java
4. In one window, remove the .vertx directory and run the server:
    rm -rf .vertx
    java -classpath '.:/Users/cxh/src/vert.x-3.1.0/lib/*' io.vertx.example.core.net.echo.Server
5. In another window, run the server
    cd src/vertx-examples/core-examples/src/main/java/
    java -classpath '.:/Users/cxh/src/vert.x-3.1.0/lib/*' io.vertx.example.core.net.echo.Client
6. Put the client in the background and note that .vertx/ contains two files.
    bash-3.2$ ls -l .vertx
    total 0
    drwxr-xr-x  2 cxh  staff  68 Nov  5 14:13 file-cache-8b08f94d-85a8-4fed-bf0e-fad3a2b0f3b0
    drwxr-xr-x  2 cxh  staff  68 Nov  5 14:14 file-cache-cfbaaf05-e1b1-46de-8f55-05b10b88b56a
7. Kill both processes and the files remain in the .vertx/ directory.  I would expect that the .vertx/ directory would be empty.

If I run these client and server with 

    cd src/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo
    vertx run Client.java

and

    cd src/vertx-examples/core-examples/src/main/java/io/vertx/example/core/net/echo
    vertx run Server.java

Then the subdirectories in .vertx are removed.

One possible solution is that modifying FileResolver.deleteCacheDir() so that it calls

 vertx.fileSystem().deleteRecursiveBlocking(cacheDir.getAbsolutePath(), true);
instead of
 vertx.fileSystem().deleteRecursive(cacheDir.getAbsolutePath(), true, handler);
seems to fix the problem.

What I think is happening is that FileResolver is calling deleteCacheDir() in a shutdown hook.  My guess is that there is not enough left running to invoke the non-blocking methods.

I'm new to Vert.x and shutdown hooks, but http://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#addShutdownHook-java.lang.Thread- says

"Shutdown hooks should also finish their work quickly. When a program invokes exit the expectation is that the virtual machine will promptly shut down and exit. When the virtual machine is terminated due to user logoff or system shutdown the underlying operating system may only allow a fixed amount of time in which to shut down and exit. It is therefore inadvisable to attempt any user interaction or to perform a long-running computation in a shutdown hook. "

A feature request is that it would be nice if the code that deleted the last subdirectory in .vertx/ also removed the now empty .vertx/ directory.  The problem is that when I run Java examples, even if the subdirectories are removed, my tree gets littered with .vertx/ directories.  These directories need to be excluded by version control etc.

My workaround is to set the vertx.cacheDirBase property to user.home/.vertx.

However, without the fix to FileResolver, the directory will get lots of subdirectories created in it.

**Comment by purplefox** [comment]
Thanks,

Looks like a bug - the non blocking delete doesn't have time to finish before the JVM exits, using deleteBlockingRecursive should work as you suggest.

If you're using git you should be able to add .vertx to your .gitignore file, then you won't be troubled by them again :)

**Comment by purplefox** [comment]
Should be fixed in this commit https://github.com/eclipse/vert.x/commit/a9db9646106d24e5f04a72aa0f4a17b4ba13c2f6 - can you verify?

**Comment by cxbrooks** [comment]
Thanks, that fixes the problem.  The file-cache directories are now deleted.

To run the Server, I used:

java -classpath '.:/Users/cxh/src/vert.x/target/vertx-core-3.2.0-SNAPSHOT.jar:/Users/cxh/src/vertx-codegen/target/vertx-codegen-3.2.0-SNAPSHOT.jar:/Users/cxh/src/vert.x-3.1.0/lib/*' io.vertx.example.core.net.echo.Server

To run the client, I used:

java -classpath '.:/Users/cxh/src/vert.x/target/vertx-core-3.2.0-SNAPSHOT.jar:/Users/cxh/src/vertx-codegen/target/vertx-codegen-3.2.0-SNAPSHOT.jar:/Users/cxh/src/vert.x-3.1.0/lib/*' io.vertx.example.core.net.echo.Client
