### ISSUE TITLE
SocketAddress params are "resolved" when Metrics callback are invoked 

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/issues#73]
Currently, when Metrics SPI callbacks are invoked, the `io.vertx.core.net.SocketAddress#host` values are "resolved".

For example, if you connect a `NetClient` to `www.google.com`, `io.vertx.core.spi.metrics.TCPMetrics#connected` is invoked with host `216.58.208.36`. This is because `io.vertx.core.net.impl.NetClientImpl#connected` creates the SocketAddress object from the result of invoking `#remoteAddress` on the Netty `Channel`:
```java
private void connected(ContextImpl context, Channel ch, Handler<AsyncResult<NetSocket>> connectHandler) {
  // Need to set context before constructor is called as writehandler registration needs this
  ContextImpl.setContext(context);
  NetSocketImpl sock = new NetSocketImpl(vertx, ch, context, sslHelper, true, metrics, null);
  socketMap.put(ch, sock);
  context.executeFromIO(() -> {
    sock.setMetric(metrics.connected(sock.remoteAddress()));
    connectHandler.handle(Future.succeededFuture(sock));
  });
}
```
This is just an example and applies to HTTP clients, servers, ... etc.

This process has the following issues:
- it's not possible for the user to enable metrics on a remote host basis, because he would have to know remote IP addresses in advance
- if, over time, hosts get resolved to different IP addresses, then Metrics SPI implementations will create counters for each remote address even if, from the user perspective, `www.google.com` is a single destination

**Comment by vietj** [comment]
can you review @tsegismont https://github.com/eclipse/vert.x/tree/metrics-remote-name ?

**Comment by vietj** [comment]
https://github.com/eclipse/vert.x/pull/1199

**Comment by vietj** [comment]
so it is not necessary to do that for datagram socket as the remote host is the bare value without any resolution.

**Comment by vietj** [comment]
so are we good ?
