### ISSUE TITLE
Messages sent by worker on cluster are sent after the current worker task

### ISSUE THREAD

**Issue by vietj** [vert-x3/issues#75]
A worker Verticle is sending a message with clustered eventbus in a section with blocking code (and actually before) : the message is delayed until the blocking section.

The cluster eventbus manager uses the AsyncMap to obtain the list of subs that uses an executeBlocking section to lookup the server address and then send the message when it has the lookup result. Note that this also happen for a local message because it’s not related to transport but rather to obtain the server info in the subs AsyncMap.
- it could remain this way and people should be aware of that case
- the hazelcast implementation could uses the current thread when it is a worker thread (doing a check on the current context and use execute blocking only when on event loop thread, quite tedious)
- the worker Context implementation of executeBlocking could use the current thread to execute the blocking section

**Comment by tetv** [comment]
Another option could be having a private `WorkerExecutor` just for doing that.
Related also to https://github.com/vert-x3/vertx-hazelcast/issues/43

**Comment by vietj** [comment]
Note : this happens either with worker verticles or `executeBlocking` but not for the same reason:
- in a worker Verticle the `subs` lookup callback is scheduled on the actual worker thread
- in an `executeBlocking` the `subs` lookup is ordered after the current block

So a solution to have Hazelcast uses ordered = false will fix only one case
