### ISSUE TITLE
vertx.bat is broken in 3.2.0

### ISSUE THREAD

**Issue by Petikoch** [vert-x3/issues#76]
Hi,

The vertx.bat is broken in version 3.2.0. (https://github.com/vert-x3/vertx-stack/blob/master/stack-manager/src/main/packaging/bin/vertx.bat)
Fix: Lines 101 and 102 should be together on one line.

Is this the right place to report this? Or is Eclipse Bugzilla the "right place"? You have kind of two issue trackers... ;-)

Best regards,
Peti

**Comment by cescoffier** [comment]
So Bugzilla is not used anymore.

In the case of this issue, it should have been in vertx-stack. But don't worry, here is good too (and then we do the triage, and see the impacted project).

I've created https://github.com/vert-x3/vertx-stack/issues/36 (and fixed it).

**Comment by Petikoch** [comment]
@cescoffier thanks for the fast feedback.

Maybe it's a good idea to update the issue section in http://vertx.io/community/ and remove the eclipse Bugzilla there?

Best regards,
Peti

**Comment by cescoffier** [comment]
Yes definitely ! Thanks for reporting, will do that right now.

**Comment by cescoffier** [comment]
Web site updated.

**Comment by Petikoch** [comment]
Amazing, how fast you guys are!
