### ISSUE TITLE
Adding headers to bridge events does not work (in javascript and in groovy on 3.2)

### ISSUE THREAD

**Issue by cinterloper** [vert-x3/issues#77]
(moved from vert-x3/lang-js)
here is my example repo:
https://github.com/cinterloper/vertx-tinkering

according to this documentation:
http://vertx.io/docs/vertx-web/js/#_sockjs_event_bus_bridge

i should be able to add 'headers' (username, etc) to a message coming across the sockjs bridge

sockJSHandler.bridge(options, function (be) {
  if (be.type() === 'PUBLISH' || be.type() === 'SEND') {
    // Add some headers
    var headers = {
      "header1" : "val",
      "header2" : "val2"
    };
    be.rawMessage().headers = headers;
  }
  be.complete(true);
}
however, when receiving the message (in the same vertical or in other verticals) i am unable to retrieve the headers

**Comment by cinterloper** [comment]
Hey guys, i have updated the repo above
unless im doing something wrong, this also appears to be broken in Groovy - is there a unit test for headers?

**Comment by cescoffier** [comment]
What do you mean by "broken in groovy" ? Do you have header working in a JS verticle and not in a Groovy verticle ?

**Comment by cinterloper** [comment]
[grant@silverbullet groovy]$ vertx run server.groovy 
Succeeded in deploying verticle 
this is v2 here running 
##########groovy: after headers added, as rm: null
##########groovy: after headers added, as rm: [type:register, address:chat.to.client, headers:[:]]
##########groovy: after headers added, as rm: [type:publish, address:chat.to.server, headers:{"thisheader":"kibble","thatheader":"skooba"}, body:message]
#### groovy headers on message after headers added666: [] //there should be headers here
##########groovy: after headers added, as rm: [type:rec, address:chat.to.client, body:1/8/16 12:24:40 AM: message]
V2: got this message: "message" with headers: {}  // there should be headers here


I do not think the feature, adding headers in the bridge event handler/lambda, works as described, in either js or groovy, according to vertx.io/docs

https://github.com/cinterloper/vertx-tinkering/blob/master/groovy/server.groovy

https://github.com/cinterloper/vertx-tinkering/blob/master/js/server.js

**Comment by vietj** [comment]
it is due to the fact that rawMessage() makes a copy of the original JsonObject. To solve it we need to have a setRawMessage(JsonObject) and add in the doc that a modified message should be set.

**Comment by purplefox** [comment]
This is the case in the JS API, although in the Java API a reference to the uncopied object is returned.

**Comment by cescoffier** [comment]
Fixed in the related project.
