### ISSUE TITLE
Please fix the Vert.bat file 

### ISSUE THREAD

**Issue by mogaembo** [vert-x3/issues#78]
@rem Execute vertx
"%JAVA_EXE%" %JVM_OPTS% %JMX_OPTS% %JAVA_OPTS% %VERTX_SYNC_AGENT% %VERTX_OPTS% %VERTX_MODULE_OPTS% -Dvertx.cli.usage.prefix=vertx -Djava.util.logging.config.file="%VERTX_JUL_CONFIG%" -Dvertx.home="%VERTX_HOME%" -Dvertx.clusterManagerFactory="%VERTX_CLUSTERMANAGERFACTORY%" -classpath "%CLASSPATH%"
io.vertx.core.Launcher %CMD_LINE_ARGS%

New line at the end of "%CLASSPATH%" causes vertx.bat to break.

**Comment by cescoffier** [comment]
It has been fixed in https://github.com/vert-x3/vertx-stack/issues/36.
