### ISSUE TITLE
Connection is closed when sending a file causes NullPointerException

### ISSUE THREAD

**Issue by gjroylance** [vert-x3/issues#80]
NullPointerException
io.vertx.core.http.impl.HttpServerResponseImpl in doSendFile at line 483
io.vertx.core.http.impl.HttpServerResponseImpl in sendFile at line 339
io.vertx.core.http.HttpServerResponse in sendFile at line 316
io.vertx.core.http.HttpServerResponse in sendFile at line 302
io.vertx.rxjava.core.http.HttpServerResponse in sendFile at line 334

**Comment by RuchiraKulathunga** [comment]
There is this security vulnerability and I am working on this issue..

**Comment by woollybah** [comment]
I'm also seeing this in 3.3.2

```
java.lang.NullPointerException
    at io.vertx.core.http.impl.HttpServerResponseImpl.doSendFile(HttpServerResponseImpl.java:491)
    at io.vertx.core.http.impl.HttpServerResponseImpl.sendFile(HttpServerResponseImpl.java:342)
    at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:317)
    at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:303)
```

**Comment by vietj** [comment]
@woollybah could you provide a reproducer ?

**Comment by woollybah** [comment]
After further testing, I have found that my particular problem concerns this "double-tap" issue in chrome ( https://bugs.chromium.org/p/chromium/issues/detail?id=587709 ), which relates to chrome sending two requests to the server for a PDF.

It appears that one of the channels is closed by chrome before completion, and it is this that vertx doesn't handle very well, resulting in ServerConnection writeToChannel() returning null on one of two the requests.
The other request succeeds, and file retrieval is completed.

**Comment by pmlopes** [comment]
@woollybah if the client closes the connection then an exception is expected on the server side right. So what you would like to see is that the exception is thrown from writeToChannel instead of a NPE?

**Comment by woollybah** [comment]
Well, what I'm not expecting is for HttpServerResponse sendFile() to throw a NullPointerException.
It would be nice if the exception (whatever you decide it to be) was contained within the resultHandler, so I can handle it normally.
Thanks!

**Comment by vietj** [comment]
+1 @woollybah however we would like to have a clear reproducer of the problem that would help a lot :-)

**Comment by woollybah** [comment]
Here's something that demonstrates the issue...

https://github.com/woollybah/sendfile-npe-reproducer

Open the page in Chrome, and then you can basically just hold-down ctrl-R to refresh the page lots.
I get the exception almost immediately here.
