### ISSUE TITLE
Vertical stop working after error

### ISSUE THREAD

**Issue by dlaberge** [vert-x3/issues#81]
When an Exception is thrown (classcast exception, null pointer ...) the vertical stop working. Our setup is a single server so the -ha option doesn't work. Is there an auto-restart that could restart the vertical on automatically?

Working on vertx 3.0.0 with the JAVA API

**Comment by manish-panwar** [comment]
What do you mean by "vertical stop working" ? Are you registering a handler in this verticle which doesn't handle the message on event-bus anymore?

e.g. given below is the handler registered on event bus.

vertx.eventBus().consumer("handlerName").toObservable()
                .subscribe(message -> {
                    // Do my stuff
                }, ex -> {
                    // Handle error
                });

After you got error, any message sent on "handlerName" doesn't get served ?

**Comment by dlaberge** [comment]
Thanks , I forgot the onError part.
