### ISSUE TITLE
Thread metrics

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/issues#83]
(as we are collecting metrics requirements I was thinking about this one often asked)

We should provide metrics about the event loop and worker thread pool such as ManagedThread metrics.

**Comment by tsegismont** [comment]
+1, great idea

2016-01-15 8:12 GMT+01:00 Clement Escoffier <notifications@github.com>:

**Comment by poiuytrez** [comment]
A great improvement would be to get the number of execute blocking code waiting for a worker thread to be available: 
https://github.com/eclipse/vert.x/issues/1333
