### ISSUE TITLE
Format of Mongo Client Java seems to be broken

### ISSUE THREAD

**Issue by coolcfxp** [vert-x3/issues#86]
http://vertx.io/docs/vertx-mongo-client/java/

The content after "Finding Documents" seems not to be correctly formatted?

I am using latest Chrome on Mac

![image](https://cloud.githubusercontent.com/assets/3876456/12376036/eb077fc4-bd1a-11e5-9b23-6d2929a4ef5a.png)

**Comment by cescoffier** [comment]
Fixed in https://github.com/vert-x3/vertx-mongo-client/commit/b273ba4007785241f6036d2a66aadb75aded1bdb
