### ISSUE TITLE
SLF4JLogDelegate calls wrong methods of org.slf4j.Logger

### ISSUE THREAD

**Issue by riemenschneider** [vert-x3/issues#90]
The method log(int level, Object message, Throwable t, Object... params) in SLF4JLogDelegate has several issues:
1. When the underlying logger is an instance of LocationAwareLogger, the parameter array is not passed to it since its log method is called with null instead of the parameter array.
2. Otherwise the SLF4JLogDelegate tries to transfer message, params, and t to the underlying SLF4J Logger by calling its according log method with message, t and params, e.g., logger.error(message, t, params) for ERROR level. Unfortunately, SLF4J Logger does not provide log methods accepting a message with parameters AND a Throwable. Therefore SLF4JLogDelegate calls SLF4J Logger's log method with a message and two parameters (t is the first parameter and the Object array params the second one) which breaks the parameter substitution.

**Comment by cescoffier** [comment]
Hello,

These issues are fixed in https://github.com/eclipse/vert.x/pull/1282.
