### ISSUE TITLE
Asynchronous Hazelcast integration

### ISSUE THREAD

**Issue by gregl01** [vert-x3/issues#92]
I would like to use Hazelcast as session cache in my Vert.x application, however, I am not a fan of the separate thread pool in the current Hazelcast Vert.x client.

For example, the current code contains calls to vertx.executeBlocking (https://github.com/vert-x3/vertx-hazelcast/blob/master/src/main/java/io/vertx/spi/cluster/hazelcast/impl/HazelcastAsyncMap.java#L53)

Alternatively the Redis client is completely asynchronous (uses netclient etc...). https://github.com/vert-x3/vertx-redis-client/blob/master/src/main/java/io/vertx/redis/impl/RedisConnection.java

**Comment by vietj** [comment]
what's the status on this @tsegismont ?

**Comment by tsegismont** [comment]
It's possible to use Hazelecast's async APIs. It's documented here: http://vertx.io/docs/vertx-hazelcast/java/#_using_hazelcast_async_methods
