### ISSUE TITLE
Eventbus bridge with Vert.x 2

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/issues#96]
To ease the migration from Vert.x 2 to Vert.x 3, we should provide a bidirectional event bus bridge. 

So, Vert.x 2 application could migrate to Vert.x 3 step by step.

**Comment by meggarr** [comment]
Hi @cescoffier ,

Is there a early preview of this feature? I'd like to see how this works, and we have a Vert.X2 system, and one Vert.X 3 newly developed server, I hope with this bridge, the Event from Vertx2 can be broadcasted to Vert.x 3

Thanks!

**Comment by cescoffier** [comment]
@meggarr Yes, @pmlopes has developed the bridge. It's there: https://github.com/vert-x/mod-eventbus3-bridge-client/tree/initial-work

(and I just realized that it needs a code reviews to be merge)

**Comment by meggarr** [comment]
Thanks!
