### ISSUE TITLE
Ping is ignored in WebSocket Ping/Pong mechanism

### ISSUE THREAD

**Issue by gerbenk** [vert-x3/issues#99]
The WebSocket Ping/Pong mechanism is used to check whether the other party is still online. This works fine if the client initiates the ping but when the server initiates the ping, the pong is (intensionally) ignored. This means that the behaviour is the same regardless the connection. 

Possible solution: when no pong is received before a certain timeout, close the connection.

**Comment by purplefox** [comment]
I'm not sure I understand the issue here. What would you do with the pong on the server side?

**Comment by gerbenk** [comment]
I would know for sure that the client is still alive. At this moment, when I ping the client, the result is the same whether a pong comes back or not. It now can take a long time before the server senses the client went offline (of lost the connection for any other reason).

**Comment by purplefox** [comment]
The purpose of ping/pong is to close the connection if pong is not received.

When the server receives a pong from the client it keeps the connection open.

The idea is that this is used in connection with the connection timeout functionality of Vert.x. If a pong is not received from the client the connection will be closed.

I can't see how you could really do anything meaningful above and beyond this by handling it yourself.

**Comment by purplefox** [comment]
I.e. just set this:

http://vertx.io/docs/apidocs/io/vertx/core/net/TCPSSLOptions.html#setIdleTimeout-int-

Then send your ping to the client. If client does not respond with pong within timeout the connection will be closed automatically.

**Comment by gerbenk** [comment]
Thanks. I though I tried everything but I guess I did not.
